### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20355: ordinal not in range(128)

### ISSUE THREAD

**Issue by yarikoptic** [pandas-dev/pandas#10312]
While building a fresh package (out of snapshot of master at bc7d48f, since the last release had way too many failures) for Debian I am running into

```
======================================================================
ERROR: test_file_like (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/test_html.py", line 284, in test_file_like
    df1 = self.read_html(f, '.*Water.*')
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/test_html.py", line 92, in read_html
    return read_html(*args, **kwargs)
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/html.py", line 865, in read_html
    parse_dates, tupleize_cols, thousands, attrs, encoding)
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/html.py", line 728, in _parse
    raise_with_traceback(retained)
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/compat/__init__.py", line 708, in raise_with_traceback
    raise exc.with_traceback(traceback)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20355: ordinal not in range(128)

======================================================================
ERROR: test_string (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/test_html.py", line 275, in test_string
    data = f.read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20355: ordinal not in range(128)

======================================================================
ERROR: test_string_io (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/pandas-0.16.1+git97-gbc7d48f/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/test_html.py", line 264, in test_string_io
    data1 = StringIO(f.read())
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20355: ordinal not in range(128)
```

when building with Python 3.4.3+ .  Locale is set to C while running tests

**Comment by jreback** [comment]
show ``pd.get_option('display.encoding')``

**Comment by jreback** [comment]
Try this out: https://github.com/jreback/pandas/commit/2b934123be707333f1b8c5bcf8b3edb8c98de067

**Comment by jreback** [comment]
@cpcloud ping

**Comment by yarikoptic** [comment]
```
(Pdb) import pandas as pd
(Pdb) print(pd.get_option('display.encoding'))
ANSI_X3.4-1968
```

**Comment by yarikoptic** [comment]
I think I have patched it alright with the suggested patch but the same result

**Comment by teh** [comment]
Running into the same issue with pandas 0.16.1 but at a different byte offset:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)
```

```
export | grep LANG
LANG="en_GB.UTF-8"
```

```
>>> pd.__version__
'0.16.1'
>>> pd.get_option('display.encoding')
'UTF-8'
```

**Comment by adnelson** [comment]
I also encountered this in the unit tests for pandas 0.17.1. For me, what fixed it was to replace the calls to `open(self.spam_data)` to `open(self.spam_data, encoding='utf-8')`. Hopefully this works for others.

**Comment by jreback** [comment]
@adnelson hmm, that might work for the last 3 erros above (as the test comparison was not decoded properly). I think the first one might need an encoding arg in the ``.read_html(...)``. Want to take a crack at this to make it fail on Travis? we already have some alt locale builds (look for ``LOCALE_OVERRIDE`` env var in the ``.travis.yml``, but its possible they are skipping these tests.

**Comment by mroeschke** [comment]
We don't support 3.4.3 anymore, so these errors should not be relevant anymore. Closing
