### ISSUE TITLE
Params not properly supported for pymssql

### ISSUE THREAD

**Issue by litchfield** [pandas-dev/pandas#11683]
Pandas read SQL functions internally convert params to a list in pandas.io.sql._convert_params().

However on pymssql, params must be a tuple or dictionary. Stacktrace below. 

```
Traceback (most recent call last):
  File "/Users/simon/.virtualenvs/rfcapital/lib/python3.4/site-packages/pandas/io/sql.py", line 1539, in execute
    cur.execute(*args)
  File "pymssql.pyx", line 447, in pymssql.Cursor.execute (pymssql.c:6274)
  File "_mssql.pyx", line 998, in _mssql.MSSQLConnection.execute_query (_mssql.c:10085)
  File "_mssql.pyx", line 1029, in _mssql.MSSQLConnection.execute_query (_mssql.c:9964)
  File "_mssql.pyx", line 1146, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:11010)
  File "_mssql.pyx", line 1168, in _mssql.MSSQLConnection.format_sql_command (_mssql.c:11219)
  File "_mssql.pyx", line 1799, in _mssql._substitute_params (_mssql.c:18045)
ValueError: 'params' arg (<class 'list'>) can be only a tuple or a dictionary.
```

**Comment by litchfield** [comment]
I realise pandas doesn't officially support pymssql but it is DBAPI2 and "almost" works. I wonder if anyone else is keen to see better support?

**Comment by jorisvandenbossche** [comment]
@litchfield it does work correctly when using an sqlalchemy engine together with pymssql?

The thing is that we do not want to add special cases for certain database flavors (once we start doing that, that becomes a rabbit hole, and that is also the reason that we are using sqlalchemy for lots of this abstraction). 
But, I think it would be possible to solve this in a neutral way. As the DBAPI2 says, the `parameters` should be a sequence: https://www.python.org/dev/peps/pep-0249/#id15. So it would be possible to relax the current conversion to a list, and eg only make it a list if it is not yet a sequence.

Would you be interested in contributing a patch for this?

**Comment by jbrockmendel** [comment]
@rhshadrach i think you expressed an opinion on not wanting to special-case for some interfaces?

**Comment by rhshadrach** [comment]
As far as I can tell this now works as expected; we are no longer converting to a list. Could add a test like the one below. Marking it as such, but I'd have no objection if we wanted to close this without it.

```python
@pytest.mark.parametrize("params", [(1,), [1], {"x": 1}])
def test_dbapi_params_passed_through_unchanged(params):
    # GH#11683 - pandas shouldn't coerce the user's params
    received = []

    class Cursor:
        description = [("a",)]

        def execute(self, sql, *args):
            received.extend(args)

        def fetchall(self):
            return [(1,)]

        def close(self):
            pass

    class Con:
        def cursor(self):
            return Cursor()

        def commit(self):
            pass

        def rollback(self):
            pass

    with tm.assert_produces_warning(UserWarning, match="Other DBAPI2 objects"):
        sql.read_sql("select 1", Con(), params=params)
    assert len(received) == 1
    assert received[0] is params
```
