### ISSUE TITLE
BUG: test_clipboard fails

### ISSUE THREAD

**Issue by BastiaanBergman** [pandas-dev/pandas#12807]
nosetests pandas/io/tests/test_clipboard.py
fails on Windows 7 Professional SP1
### Code Sample

`nosetests pandas/io/tests/test_clipboard.py`
### Output

```
.EE.
======================================================================
ERROR: test_round_trip_frame (pandas.io.tests.test_clipboard.TestClipboard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\...\pandas\io\tests\test_clipboard.py", line 81, in test_rou
nd_trip_frame
    self.check_round_trip_frame(dt)
  File "C:\...\pandas\io\tests\test_clipboard.py", line 68, in check_ro
und_trip_frame
    result = read_clipboard()
  File "C:\...\pandas\io\clipboard.py", line 36, in read_clipboard
    lines = text[:10000].split('\n')[:-1][:10]
TypeError: 'NoneType' object has no attribute '__getitem__'

======================================================================
ERROR: test_round_trip_frame_sep (pandas.io.tests.test_clipboard.TestClipboard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\...\pandas\io\tests\test_clipboard.py", line 73, in test_rou
nd_trip_frame_sep
    self.check_round_trip_frame(dt, sep=',')
  File "C:\...\pandas\io\tests\test_clipboard.py", line 69, in check_ro
und_trip_frame
    tm.assert_frame_equal(data, result, check_dtype=False)
  File "C:\...\pandas\util\testing.py", line 1164, in assert_frame_equa
l
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "C:\...\pandas\util\testing.py", line 1047, in assert_series_equ
al
    check_less_precise, obj='{0}'.format(obj))
  File "pandas\src\testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas\src\testing.c:3809)
    cpdef assert_almost_equal(a, b, bint check_less_precise=False,
  File "pandas\src\testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas\src\testing.c:2685)
    raise_assert_detail(obj, msg, lobj, robj)
  File "C:\...\pandas\util\testing.py", line 912, in raise_assert_detai
l
    [right]: {3}""".format(obj, message, left, right)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 9: ordinal not in range(128)
----------------------------------------------------------------------
Ran 4 tests in 0.132s
FAILED (errors=2)
```
### output of `pd.show_versions()`

```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: 6f246d5022dec8c9d85e4103ec8dc89f8d981502
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0+80.g6f246d5
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: None
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
>>>
```

**Comment by jreback** [comment]
yeah, we can't repro on Travis though. But I get 1 of these failures locally (on macosx)
