### ISSUE TITLE
iterrows: when upcasting to object, values are converted to python types

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#13468]
I know `iterrows` is not the most recommended function, but I noticed a strange behaviour (triggered by a problem of a geopandas user: https://github.com/geopandas/geopandas/issues/348). When using `iterrows` on a df with mixed dtypes (so the resulting series is of object dtype), the numeric values are converted to python types, while with `loc/iloc` the numpy types are preserved:

```
In [254]: df = pd.DataFrame({'int':[0,1], 'float':[0.1,0.2], 'str':['a','b']})

In [255]: df
Out[255]:
   float  int str
0    0.1    0   a
1    0.2    1   b

In [256]: row1 = df.iloc[0]

In [257]: i, row2 = next(df.iterrows())

In [258]: row3= next(df.itertuples())

In [260]: type(row1['float'])
Out[260]: numpy.float64

In [261]: type(row2['float'])
Out[261]: float

In [269]: type(row3.float)
Out[269]: numpy.float64
```

Is this intentional? (it's a consequence of using `self.values` in the implementation, and numpy does this conversion to python types in an object array) And if so, is this worth documenting?

(note it was actually the numpy types in an object dtyped series that caused an issue for the geopandas user, because fiona couldn't handle those numpy scalars in an object dtyped column, but that's not an issue to blame pandas)

**Comment by jreback** [comment]
see discussion https://github.com/pydata/pandas/issues/13236

should be the same (eg Python types)

**Comment by jreback** [comment]
so after #17491 
[269] is also float.

I think we could actually fix [260], but that's another item.

**Comment by jorisvandenbossche** [comment]
Yes, I think this can actually be closed now, apart from a doc update to iterrows / itertuples to make it clear that it boxes to python / custom pandas types.

**Comment by jreback** [comment]
i think ok to keep open for now

I want to fix the scalar getting as well (will reirose for that)

**Comment by mitar** [comment]
To fix `[260]` you can call `item` on the underlying numpy arrays the same as I am doing in #20796. So this seems to do the same thing as `tolist` does on whole array. So you could call `item` for each cell in a row, when constructing the result for `df.iloc[0]`.

**Comment by mitar** [comment]
There is something strange going on here. Taking an example [from documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iterrows.html):

```
>>> df = pd.DataFrame([[1, 1.5]], columns=['int', 'float'])
>>> row = next(df.iterrows())[1]
>>> row
int      1.0
float    1.5
Name: 0, dtype: float64
>>> print(row['int'].dtype)
float64
```

But:

```
>>> df = pd.DataFrame([[1, 1.5, 'a']], columns=['int', 'float', 'str'])
>>> row = next(df.iterrows())[1]
>>> row
int        1
float    1.5
str        a
Name: 0, dtype: object
>>> print(row['int'].dtype)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'dtype'
```

So it seems conversion to Python types happens only if there is some `object` dtype present. Otherwise we get (and keep) numpy types, only upcast to a common dtype.

**Comment by TomAugspurger** [comment]
@jorisvandenbossche is the only remaining issue here documenting the behavior?

**Comment by MarioProjects** [comment]
> There is something strange going on here. Taking an example [from documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iterrows.html):
> 
> ```
> >>> df = pd.DataFrame([[1, 1.5]], columns=['int', 'float'])
> >>> row = next(df.iterrows())[1]
> >>> row
> int      1.0
> float    1.5
> Name: 0, dtype: float64
> >>> print(row['int'].dtype)
> float64
> ```
> 
> But:
> 
> ```
> >>> df = pd.DataFrame([[1, 1.5, 'a']], columns=['int', 'float', 'str'])
> >>> row = next(df.iterrows())[1]
> >>> row
> int        1
> float    1.5
> str        a
> Name: 0, dtype: object
> >>> print(row['int'].dtype)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'int' object has no attribute 'dtype'
> ```
> 
> So it seems conversion to Python types happens only if there is some `object` dtype present. Otherwise we get (and keep) numpy types, only upcast to a common dtype.

I found the same problem printing a dataframe. When printing an int column as [1992, 1993, 1994], prints [1992.0, 1993.0, 1994.0]. I tried 
```
wm["Year"] = wm["Year"].astype(int)
wm.astype(int)
```
and nothing
