### ISSUE TITLE
TST: failing tests at pandas-wheels

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#14183]
A bunch of tests are failing in the wheel-building repo (https://github.com/MacPython/pandas-wheels): https://travis-ci.org/MacPython/pandas-wheels/builds/158414872

It are mainly issues with 32 bit linux (see eg https://travis-ci.org/MacPython/pandas-wheels/jobs/158414875), but also some tests are failing for 64bit:

On 2.7:

```
======================================================================
FAIL: test_abs (pandas.tests.test_panel4d.TestPanel4d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/test_panel4d.py", line 303, in test_abs
    assert_frame_equal(result, expected)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 2538, in assert_produces_warning
    % extra_warnings)
AssertionError: Caused unexpected warning(s): ['RuntimeWarning', 'RuntimeWarning', 'RuntimeWarning'].
```

On 3.5:

```
======================================================================
FAIL: test_pi_ops_errors (pandas.tseries.tests.test_period.TestPeriodIndexSeriesMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/pandas/tseries/tests/test_period.py", line 4184, in test_pi_ops_errors
    np.add(ng, obj)
  File "/venv/lib/python3.5/site-packages/pandas/util/testing.py", line 2450, in __exit__
    raise AssertionError("{0} not raised.".format(name))
AssertionError: TypeError not raised.
======================================================================

FAIL: test_pi_sub_period (pandas.tseries.tests.test_period.TestPeriodIndexSeriesMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/pandas/tseries/tests/test_period.py", line 4299, in test_pi_sub_period
    tm.assert_index_equal(result, exp)
  File "/venv/lib/python3.5/site-packages/pandas/util/testing.py", line 756, in assert_index_equal
    assertIsInstance(left, Index, '[index] ')
  File "/venv/lib/python3.5/site-packages/pandas/util/testing.py", line 947, in assertIsInstance
    raise AssertionError(err_msg.format(msg, cls, type(obj)))
AssertionError: [index] Expected type <class 'pandas.indexes.base.Index'>, found <class 'NotImplementedType'> instead
```

I can't directly reproduce, but that last one is possibly an issue with the numpy version

**Comment by jreback** [comment]
ok so now we are building daily wheels, hosted at ``wheels.scipy.org``

most builds working, but 32-bit still has issues.

https://travis-ci.org/MacPython/pandas-wheels/jobs/212206134

**Comment by jreback** [comment]
ok our daily builds are now running; hosted here (I put a link on the wiki as well): http://8b8c47f30575e674b56d-47bd50c35cd79bd838daf386af554a83.r59.cf2.rackcdn.com/

32-bit builds failing though.

**Comment by jorisvandenbossche** [comment]
@jreback Great! 
Would you like to send a notice to the mailing list about this? (and maybe a pointer how to use them when you want to test against pandas master)

**Comment by jreback** [comment]
@jorisvandenbossche sure (soon). trying to see if I can fix up some of these.......

**Comment by jreback** [comment]
done!

**Comment by jorisvandenbossche** [comment]
@jreback Thanks!

**Comment by jreback** [comment]
https://travis-ci.org/MacPython/pandas-wheels/jobs/213622891

down to 2!

**Comment by jreback** [comment]
@gfyoung any idea why this is failing on 32-bit (only). see the above link. unfort no easy way to debug this (unless you happen to have a 32-bit machine!)

```
self = <pandas.tests.test_algos.TestValueCounts testMethod=test_value_counts_uint64>
    def test_value_counts_uint64(self):
        arr = np.array([2**63], dtype=np.uint64)
        expected = Series([1], index=[2**63])
        result = algos.value_counts(arr)
    
        tm.assert_series_equal(result, expected)
    
        arr = np.array([-1, 2**63], dtype=object)
        expected = Series([1, 1], index=[-1, 2**63])
        result = algos.value_counts(arr)
    
>       tm.assert_series_equal(result, expected)
/venv/lib/python3.6/site-packages/pandas/tests/test_algos.py:651: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/venv/lib/python3.6/site-packages/pandas/util/testing.py:1185: in assert_series_equal
    obj='{0}.index'.format(obj))
/venv/lib/python3.6/site-packages/pandas/util/testing.py:840: in assert_index_equal
    obj=obj, lobj=left, robj=right)
as/pandas/util/testing.pyx:59: in pandas.util.libtesting.assert_almost_equal (pandas/util/testing.c:4156)
    ???
as/pandas/util/testing.pyx:173: in pandas.util.libtesting.assert_almost_equal (pandas/util/testing.c:3274)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
obj = 'Series.index', message = 'Series.index values are different (100.0 %)'
left = Index([9223372036854775808, -1], dtype='object')
right = Index([-1, 9223372036854775808], dtype='object'), diff = None
    def raise_assert_detail(obj, message, left, right, diff=None):
        if isinstance(left, np.ndarray):
            left = pprint_thing(left)
        if isinstance(right, np.ndarray):
            right = pprint_thing(right)
    
        msg = """{0} are different
    
    {1}
    [left]:  {2}
    [right]: {3}""".format(obj, message, left, right)
    
        if diff is not None:
            msg = msg + "\n[diff]: {diff}".format(diff=diff)
    
>       raise AssertionError(msg)
E       AssertionError: Series.index are different
E       
E       Series.index values are different (100.0 %)
E       [left]:  Index([9223372036854775808, -1], dtype='object')
E       [right]: Index([-1, 9223372036854775808], dtype='object')
/venv/lib/python3.6/site-packages/pandas/util/testing.py:1053: AssertionError
```
