### ISSUE TITLE
test_panel4d: on ubuntu 14.04 (amd64 only) -- AssertionError: Did not see expected warning of class 'FutureWarning'

### ISSUE THREAD

**Issue by yarikoptic** [pandas-dev/pandas#14289]
#### Code Sample, a copy-pastable example if possible

```
 % grep -2 '^\(FAIL\|ERROR\|[^ ]*Error:\)' pandas_0.18.1+git25-ga7469cf-1~nd14.04+1_amd64.build | head -20

======================================================================
FAIL: test_table_mixed_dtypes (pandas.io.tests.test_pytables.TestHDFStore)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python3/dist-packages/pandas/util/testing.py", line 2536, in assert_produces_warning
    % expected_warning.__name__)
AssertionError: Did not see expected warning of class 'FutureWarning'.

======================================================================
FAIL: test_panel4d_concat (pandas.tools.tests.test_concat.TestConcatenate)
----------------------------------------------------------------------
Traceback (most recent call last):
--
  File "/build/pandas-0.18.1+git25-ga7469cf/debian/tmp/usr/lib/python3/dist-packages/pandas/util/testing.py", line 2536, in assert_produces_warning
    % expected_warning.__name__)
AssertionError: Did not see expected warning of class 'FutureWarning'.

======================================================================
```

full buildlog with all the versions etc at http://neuro.debian.net/_files/_buildlogs/pandas/0.18.1+git25-ga7469cf/pandas_0.18.1+git25-ga7469cf-1~nd14.04+1_amd64.build

**Comment by jreback** [comment]
closing as panel is obsolete
