### ISSUE TITLE
IndexError when indexing into a Series containing a UTC datetime by name

### ISSUE THREAD

**Issue by bshanks** [pandas-dev/pandas#14557]
#### A small, complete example of the issue

```python
import pandas; import pytz; import datetime; pandas.Series([pytz.UTC.localize(datetime.datetime(2000,1,1))], index=['idx1'])['idx1']

/usr/lib/python2.7/dist-packages/pandas/tseries/base.py:100: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = getitem(key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 557, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/index.py", line 1780, in get_value
    return s[key]
  File "/usr/lib/python2.7/dist-packages/pandas/tseries/base.py", line 100, in __getitem__
    val = getitem(key)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

#### Expected Output
datetime.datetime(2000, 1, 1, 0, 0, tzinfo=<UTC>)

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C

pandas: 0.17.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
IPython: 2.4.1
sphinx: None
patsy: 0.4.1
dateutil: 2.4.2
pytz: 2014.10
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.3
matplotlib: 1.5.1
openpyxl: 2.3.0
xlrd: 0.9.4
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
Jinja2: None
</details>

**Comment by bshanks** [comment]
Fixed by Pandas 0.19.0
