### ISSUE TITLE
Unable to pass additional arguments to resample().apply()

### ISSUE THREAD

**Issue by sivieri** [pandas-dev/pandas#14615]
```python
import pandas as pd
import numpy as np

def stuff(vals, th):
    return np.mean(vals)

df_modules = pd.read_csv("somefile.csv", sep = ";", index_col = 0, parse_dates = [0])
df_res = df_modules.resample("D").apply(stuff, 10)

```

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Darwin
OS-release: 16.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.0
pip: 9.0.0
setuptools: 28.7.1
Cython: 0.20.2
numpy: 1.11.2
scipy: 0.13.2
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.8
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
<details>
In this version, it seems to be impossible to apply a function with an additional argument (which is not used in the example above): checking the Pandas 0.19.1 code, what happens is that the grouped argument of the function _groupby_and_aggregate gets the first value of the *args argument passed from the function aggregate, which is clearly wrong.

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    df_res = df_modules.resample("D").apply(stuff, 10)
  File "/usr/local/lib/python2.7/site-packages/pandas/tseries/resample.py", line 324, in aggregate
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/tseries/resample.py", line 405, in _groupby_and_aggregate
    result = grouped.apply(how, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 694, in apply
    return self._python_apply_general(f)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 697, in _python_apply_general
    keys, values, mutated = self.grouper.apply(f, self._selected_obj,
AttributeError: 'int' object has no attribute 'apply'
</details>

**Comment by jreback** [comment]
hmm thought we had an issue for this already - yep looks like a bug
if you'd like to submit a PR to fix would be great

**Comment by jythonic** [comment]
I will look at this today if no one else working on it?
