### ISSUE TITLE
Cython not found

### ISSUE THREAD

**Issue by lemioneta** [pandas-dev/pandas#14648]
I pip instlaled pandas, and did `setup.py build_ext --inplace --force` but when I import pandas from python I get this message

```python
running build_ext
Traceback (most recent call last):
  File "setup.py", line 685, in <module>
    **setuptools_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "setup.py", line 374, in build_extensions
    self.check_cython_extensions(self.extensions)
  File "setup.py", line 371, in check_cython_extensions
    """ % src)
Exception: Cython-generated file 'pandas/index.c' not found.
                Cython is required to compile pandas from a development branch.
                Please install Cython or download a release package of pandas.

```

#### Expected Output

How can I fix this? Thank you!

**Comment by jreback** [comment]
if you are installing a dev version
you need to install cython, instructions are: http://pandas.pydata.org/pandas-docs/stable/contributing.html

otherwise you probably have an older version of pip -  it should normally install wheels - upgrade pip
