### ISSUE TITLE
test_round_trip_exception_  got stuck (on s390x)

### ISSUE THREAD

**Issue by yarikoptic** [pandas-dev/pandas#14834]
Just FYI and for reference (feel free to close)... was running all the tests and they got stuck on this one

then tried to rerun this one specifically and just lead to certificate verification problem :-/

```shell
(sid_s390x-dchroot)yoh@zelenka:~/pandas$ HOME=$PWD/build  LC_ALL=C.UTF-8 xvfb-run -a -s "-screen 0 1280x1024x24 -noreset" nosetests  -s -v pandas/io/tests/json/test_pandas.py:TestPandasContainer.test_round_trip_exception_
test_round_trip_exception_ (pandas.io.tests.json.test_pandas.TestPandasContainer) ... ERROR

======================================================================
ERROR: test_round_trip_exception_ (pandas.io.tests.json.test_pandas.TestPandasContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/pandas/pandas/util/testing.py", line 2259, in wrapper
    return t(*args, **kwargs)
  File "/home/yoh/pandas/pandas/io/tests/json/test_pandas.py", line 762, in test_round_trip_exception_
    df = pd.read_csv(csv)
  File "/home/yoh/pandas/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/yoh/pandas/pandas/io/parsers.py", line 385, in _read
    compression=kwds.get('compression', None))
  File "/home/yoh/pandas/pandas/io/common.py", line 240, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

----------------------------------------------------------------------
Ran 1 test in 0.120s

FAILED (errors=1)
```

**Comment by yarikoptic** [comment]
hm... seems to always get stuck now when running full sweep of tests :-/  I guess I will just set it to no network mode by providing a fake http_proxy - then it just would skip this test I believe

**Comment by yarikoptic** [comment]
and various  test_msgpack   get stuck -- so I guess it is some generic problem.  I am already running with `-A 'not network and not disabled'` and fake http_proxy so it shouldn't be a network.  What is the way to dump more information so we could determine the reason?

**Comment by yarikoptic** [comment]
scrape it all -- probably it was due to me having `--pdb` in the call to nose and then piping output to `tee` ;)  I will whine again if I discover otherwise
