### ISSUE TITLE
SystemError: ../Objects/listobject.c:290: bad argument to internal function [i386,armel,...]

### ISSUE THREAD

**Issue by yarikoptic** [pandas-dev/pandas#14852]
Any idea on what could cause such an exception on 32bit platform (Debian sid i386), 0.19.1

```
======================================================================
ERROR: test_frame_from_json_to_json (pandas.io.tests.json.test_pandas.TestPandasContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_pandas.py", line 272, in test_frame_from_json_to_json
    _check_all_orients(self.frame)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_pandas.py", line 246, in _check_all_orients
    check_index_type=False, check_column_type=False)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_pandas.py", line 165, in _check_orient
    numpy=numpy, convert_axes=convert_axes)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 281, in read_json
    date_unit).parse()
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 346, in parse
    self._parse_numpy()
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 541, in _parse_numpy
    precise_float=self.precise_float)
SystemError: ../Objects/listobject.c:290: bad argument to internal function

======================================================================
ERROR: test_misc_example (pandas.io.tests.json.test_pandas.TestPandasContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_pandas.py", line 743, in test_misc_example
    result = read_json('[{"a": 1, "b": 2}, {"b":2, "a" :1}]', numpy=True)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 281, in read_json
    date_unit).parse()
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 346, in parse
    self._parse_numpy()
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/json.py", line 541, in _parse_numpy
    precise_float=self.precise_float)
SystemError: ../Objects/listobject.c:290: bad argument to internal function

======================================================================
ERROR: testArrayNumpyLabelled (pandas.io.tests.json.test_ujson.NumpyJSONTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_ujson.py", line 1178, in testArrayNumpyLabelled
    output = ujson.loads(input_dumps, numpy=True, labelled=True)
SystemError: ../Objects/listobject.c:290: bad argument to internal function

======================================================================
ERROR: testDataFrameNumpyLabelled (pandas.io.tests.json.test_ujson.PandasJSONTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/json/test_ujson.py", line 1286, in testDataFrameNumpyLabelled
    numpy=True, labelled=True))
SystemError: ../Objects/listobject.c:290: bad argument to internal function
```

full build log: https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=i386&ver=0.19.1-3&stamp=1481348917

happens also on some other architectures: e.g. armel https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=armel&ver=0.19.1-3&stamp=1481359184

**Comment by jreback** [comment]
the exception is not being caught i think
e.g. https://github.com/pandas-dev/pandas/pull/14678/files

**Comment by yarikoptic** [comment]
Thanks @jreback !  When do you think 0.19.2 is to come out?  it seems to be full of useful bug fixes, so may be it should be the version altogether I should upload to debian

note: heh -- I kinda started to dislike this new feature of travis to allow merging PRs rewriting the commit for linear history... makes it harder to find from original listing -- hexsha changes, need to search by commit msg

**Comment by jreback** [comment]
shouldn't be long actually 1-2 weeks for 0.19.2.

**Comment by yarikoptic** [comment]
Tried to rebuild current master (0.19.1+git174-g81a2f79) with the same failures, so I guess that resolution wasn't it ... funny thing that it builds fine in my i386 sid chroots, so theoretically the only difference should be the kernel or something really subtle :-/
for the reference: https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=i386&ver=0.19.1%2Bgit174-g81a2f79-1&stamp=1481436461  (also interestingly new failure on big endian s390x... heh)

**Comment by jbrockmendel** [comment]
@yarikoptic can you see if this is fixed in a more recent version

**Comment by mroeschke** [comment]
It appears this example was run with a pretty old version of pandas. Let us know when you could provide a more recent run of this example and we'd be happy to reopen.
