### ISSUE TITLE
Constructing a Period having a multiple of the freq ignores the freq multiplier

### ISSUE THREAD

**Issue by dhirschfeld** [pandas-dev/pandas#15063]
When using a multiple of the freq, the `period_range` function behaves as expected - e.g. for a  half-yearly frequency (with a `DEC` anchor) it constructs a `PeriodIndex` with periods starting on the 1st and 3rd quarters:
```python
In [27]: pd.period_range('01-Jan-2017', '01-Jan-2019', freq='2Q-DEC')[:-1]
Out[27]: PeriodIndex(['2017Q1', '2017Q3', '2018Q1', '2018Q3'], dtype='period[2Q-DEC]', freq='2Q-DEC')
```
I would expect that when constructing a `Period` with a freq of `2Q-DEC` that you should only be able to get periods starting on the 1st and 3rd quarters - i.e. any date in[Q1, Q3) would give a period starting on Q1 and any date in [Q3, Q1) would give a period starting on Q3. What currently happens is that it appears to ignore the frequency multiplier and treat the periods if they were simply straight quarters:
```python
In [31]: [pd.Period('01-Feb-2017', freq='2Q'),
    ...: pd.Period('01-May-2017', freq='2Q'),
    ...: pd.Period('01-Aug-2017', freq='2Q'),
    ...: pd.Period('01-Nov-2017', freq='2Q')]
Out[31]: 
[Period('2017Q1', '2Q-DEC'),
 Period('2017Q2', '2Q-DEC'),
 Period('2017Q3', '2Q-DEC'),
 Period('2017Q4', '2Q-DEC')]
```
i.e. I would expect instead:
```python
[Period('2017Q1', '2Q-DEC'),
 Period('2017Q1', '2Q-DEC'),
 Period('2017Q3', '2Q-DEC'),
 Period('2017Q3', '2Q-DEC')]
```

**Comment by jreback** [comment]
@dhirschfeld not sure I understand. the top example is correct. can you should an incorrect one?

**Comment by MaximilianR** [comment]
@jreback what's the semantic difference between these? The periodicity is half year, but both of these are within a half year?

```python
Period('2017Q1', '2Q-DEC'),
 Period('2017Q2', '2Q-DEC'),
```

**Comment by ocschwar** [comment]
Might be the same bug, might be related, I ran into this: 

`>>> F.head()
datetime
2004-01-01 00:05:00    0.0
2004-01-01 00:10:00    0.0
2004-01-01 00:15:00    0.0
2004-01-01 00:20:00    0.0
2004-01-01 00:25:00    0.0
Freq: 300S, Name: ghi, dtype: float64
>>> dt
datetime.datetime(2004, 1, 1, 0, 5, 0, 999999)
>>> F[dt]
0.0
>>> dt_ = datetime.datetime(2004, 1, 1, 0, 5, 1,1)
>>> F[dt_]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/pandas/tseries/period.py", line 757, in get_value
    return com._maybe_box(self, self._engine.get_value(s, key),
  File "pandas/index.pyx", line 98, in pandas.index.IndexEngine.get_value (pandas/index.c:3557)
  File "pandas/index.pyx", line 106, in pandas.index.IndexEngine.get_value (pandas/index.c:3240)
  File "pandas/index.pyx", line 149, in pandas.index.IndexEngine.get_loc (pandas/index.c:4216)
  File "pandas/index.pyx", line 175, in pandas.index.IndexEngine._get_loc_duplicates (pandas/index.c:4663)
  File "pandas/index.pyx", line 421, in pandas.index.Int64Engine._maybe_get_bool_indexer (pandas/index.c:8636)
KeyError: 1072915501
>>> 
`

Should I open a new issue? 

To clarify: F is a Series with a PeriodIndex consisting of "300s" frequency periods. F[dt] DTRT for date-times under one second from the start of a period, but raise a KeyError for date-times from 1 to 299.99999 seconds. 

I can reproduce the same thing with a PeriodIndex of "5T". The first minute after a Period's start_time is dealt with correctly. The remaining 4 minutes are not.

**Comment by ocschwar** [comment]
This is >>> pandas.__version__
u'0.19.2'

**Comment by jreback** [comment]
@ocschwar pls post a copy-pastable example

**Comment by ocschwar** [comment]
```
>>> DR = pd.period_range(datetime.datetime.now(), freq='300S',periods=22)
>>> S = pd.Series( [0.0]*22,index=DR) 
>>> now = datetime.datetime.now()
>>> S[now]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
  File "/Library/Python/2.7/site-packages/pandas/tseries/period.py", line 757, in get_value
    return com._maybe_box(self, self._engine.get_value(s, key),
  File "pandas/index.pyx", line 98, in pandas.index.IndexEngine.get_value (pandas/index.c:3557)
  File "pandas/index.pyx", line 106, in pandas.index.IndexEngine.get_value (pandas/index.c:3240)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8564)
  File "pandas/src/hashtable_class_helper.pxi", line 410, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8508)
KeyError: 1491422454
>>> S.index[0]
Period('2017-04-05 20:00:23', '300S')
>>> S[datetime.datetime(2017,4,5,20,23)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
  File "/Library/Python/2.7/site-packages/pandas/tseries/period.py", line 757, in get_value
    return com._maybe_box(self, self._engine.get_value(s, key),
  File "pandas/index.pyx", line 98, in pandas.index.IndexEngine.get_value (pandas/index.c:3557)
  File "pandas/index.pyx", line 106, in pandas.index.IndexEngine.get_value (pandas/index.c:3240)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8564)
  File "pandas/src/hashtable_class_helper.pxi", line 410, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8508)
KeyError: 1491423780
>>> S[datetime.datetime(2017,4,5,20,0,23)]
0.0
>>> S[datetime.datetime(2017,4,5,20,0,23,999)]
0.0

```

**Comment by ocschwar** [comment]
And here's a 5T case.

```
>>> DR = pd.period_range(datetime.datetime.now(), freq='5T',periods=22)
>>> S = pd.Series( [0.0]*22,index=DR)
>>> now = datetime.datetime.now()
>>> S[now]
0.0
>>> S.index[0]
Period('2017-04-05 20:03', '5T')
>>> S[datetime.datetime(2017,4,5,20,3,23,999)]
0.0
>>> S[datetime.datetime(2017,4,5,20,4,23,999)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
  File "/Library/Python/2.7/site-packages/pandas/tseries/period.py", line 757, in get_value
    return com._maybe_box(self, self._engine.get_value(s, key),
  File "pandas/index.pyx", line 98, in pandas.index.IndexEngine.get_value (pandas/index.c:3557)
  File "pandas/index.pyx", line 106, in pandas.index.IndexEngine.get_value (pandas/index.c:3240)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8564)
  File "pandas/src/hashtable_class_helper.pxi", line 410, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8508)
KeyError: 24857044
```

**Comment by jorisvandenbossche** [comment]
@ocschwar Please open a new issue.
