### ISSUE TITLE
BUG: Series.cumin/cummax fails with datetime64[ns, tz] dtype

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15553]
- [x] ``.where``
- [x] ``.combine_first``
- [x] ``.update``
- [ ] ``.cummin/cummax``

works with naive dt, should work with tz-aware

```
In [40]: s = Series(pd.date_range('20130101', periods=2))

In [41]: s.where(s>s,s)
Out[41]: 
0   2013-01-01
1   2013-01-02
dtype: datetime64[ns]

In [42]: s = Series(pd.date_range('20130101', periods=2, tz='US/Eastern'))

In [43]: s.where(s>s,s)
TypeError: invalid type promotion
TypeError: Could not operate [array(['2013-01-01T05:00:00.000000000', '2013-01-02T05:00:00.000000000'], dtype='datetime64[ns]')] with block values [invalid type promotion]
```

**Comment by adbull** [comment]
Note there's also odd behaviour on tz-aware series with `update` or `combine_first`:

```python
>>> import pandas as pd
>>> utc = pd.Series(pd.to_datetime(['now'], utc=True))
>>> utc.dtype

datetime64[ns, UTC]

>>> utc.combine_first(utc).dtype

dtype('<M8[ns]')

>>> utc.update(utc)

~/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py:1517: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  new = new[mask]
Traceback (most recent call last):
  File "bug.py", line 1, in <module>
    utc.update(utc)
  File "~/anaconda3/lib/python3.5/site-packages/pandas/core/series.py", line 1718, in update
    self._data = self._data.putmask(mask=mask, new=other, inplace=True)
  File "~/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 3171, in putmask
    return self.apply('putmask', **kwargs)
  File "~/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "~/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 1517, in putmask
    new = new[mask]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by adbull** [comment]
And `cummax` or `cummin`:

```python
>>> utc.cummax().dtype

dtype('<M8[ns]')

>>> utc.cummin().dtype

dtype('<M8[ns]')
```

**Comment by mroeschke** [comment]
#21660 closed `where` (and` update` since it uses `where` under the hood) and `combine_first`

**Comment by jbrockmendel** [comment]
Looks like the DataFrame cummin/cummax methods are OK, just the Series ones are losing timezones
