### ISSUE TITLE
read_excel does not work on excel file binary text or buffered binary text object

### ISSUE THREAD

**Issue by alexanderwhatley** [pandas-dev/pandas#15914]
Python 3.5, Pandas 0.19.2

I have the following excel file, and I am trying to read its binary content, and then have read_excel read the binary content in, except this is not working, and there may be a bug somewhere, as I have specified the engine for reading.

>>> import pandas as pd
>>> f = open("Test_Prom_Data.xlsx", "rb")
>>> df = pd.read_excel(f.read(), engine = "xlrd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/pandas/io/excel.py", line 191, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/pandas/io/excel.py", line 251, in __init__
    raise ValueError('Must explicitly set engine if not passing in'
ValueError: Must explicitly set engine if not passing in buffer or path for io.
[Test_Prom_Data.xlsx](https://github.com/pandas-dev/pandas/files/901685/Test_Prom_Data.xlsx)

**Comment by TomAugspurger** [comment]
I don't think that's expected to work, from the doctoring:

```
io : string, path object (pathlib.Path or py._path.local.LocalPath),
    file-like object, pandas ExcelFile, or xlrd workbook.
    The string could be a URL. Valid URL schemes include http, ftp, s3,
    and file. For file URLs, a host is expected. For instance, a local
    file could be file://localhost/path/to/workbook.xlsx
```

We could have a better error message though, similar to `read_csv`:

```python
In [9]: pd.read_csv(b"abc,123", encoding='utf-8')
```

```pytb
Traceback (most recent call last):
  File "<ipython-input-9-d793693413f5>", line 1, in <module>
    pd.read_csv(b"abc,123", encoding='utf-8')
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas-0.19.0+733.gca8ef494d-py3.6-macosx-10.12-x86_64.egg/pandas/io/parsers.py", line 656, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas-0.19.0+733.gca8ef494d-py3.6-macosx-10.12-x86_64.egg/pandas/io/parsers.py", line 404, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas-0.19.0+733.gca8ef494d-py3.6-macosx-10.12-x86_64.egg/pandas/io/parsers.py", line 763, in __init__
    self._make_engine(self.engine)
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas-0.19.0+733.gca8ef494d-py3.6-macosx-10.12-x86_64.egg/pandas/io/parsers.py", line 967, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas-0.19.0+733.gca8ef494d-py3.6-macosx-10.12-x86_64.egg/pandas/io/parsers.py", line 1552, in __init__
    self._reader = libparsers.TextReader(src, **kwds)
  File "as/pandas/io/parsers.pyx", line 393, in pandas.io.libparsers.TextReader.__cinit__ (pandas/io/parsers.c:4209)
  File "as/pandas/io/parsers.pyx", line 727, in pandas.io.libparsers.TextReader._setup_parser_source (pandas/io/parsers.c:9050)
OSError: Expected file path name or file-like object, got <class 'bytes'> type
```

@alexanderwhatley interested in submitting a fix?

**Comment by vermastuti** [comment]
#Read and write to excel
dataFileUrl = R"D:\\real_names.xlsx"
data = pd.read_excel(dataFileUrl)
