### ISSUE TITLE
make html docs

### ISSUE THREAD

**Issue by gBopHuk** [pandas-dev/pandas#16329]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
python doc/make.py html
Traceback (most recent call last):
  File "./make.py", line 412, in <module>
    sys.exit(main())
  File "./make.py", line 404, in main
    func()
  File "./make.py", line 136, in html
    with maybe_exclude_notebooks():
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "./make.py", line 121, in maybe_exclude_notebooks
    except (ImportError, nbconvert.utils.pandoc.PandocMissing):
UnboundLocalError: local variable 'nbconvert' referenced before assignment

```
#### Problem description

Trying to build html docs

#### Expected Output
???
#### Output of ``pd.show_versions()``
Trying to build 0.20.1

**Comment by TomAugspurger** [comment]
Fixed in https://github.com/pandas-dev/pandas/pull/16330

You can work around it for now by installing nbconvert.
