### ISSUE TITLE
Cannot unpickle data frame made with 0.19.2 after upgrade to 0.20.1

### ISSUE THREAD

**Issue by mhooreman** [pandas-dev/pandas#16474]
Hello,

#### Problem description

When we create a data frame with pandas &le; 0.19.2 and pickle it (using pickle.dump), it is not possible to unpickle it using pandas 0.20.1.

```python
# Using pandas 0.19.2
import pandas as pd
import pickle as pkl
data = pd.DataFrame({'x': [1, 2]})
pkl.dump(data, open("data_pd_0.19.2.pkl", "wb"))
```
```python
# After upgrade to pandas 0.20.1
import pandas as pd
import pickle as pkl
pkl.load(open("data_pd_0.19.2.pkl", "rb"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas.indexes'
```

#### First analysis

- It seems that ```pandas.indexes``` has been refactored to ```pandas.core.indexes```.
- I don't know if there are other such incompatible changes

#### Proposal

It would be great to have:
- A deprecation warning when unpicking old data frame
- Load old data frame supported but automatically converted to the new format, so that we can upgrade by pickling the unpickled data frames

Thanks a lot for your help,
Best regards.

**Comment by jreback** [comment]
Big [red  box](http://pandas.pydata.org/pandas-docs/stable/io.html#pickling), is clear that ``pd.read_pickle`` is the pickle reader and makes things backward compatible. Further whatsnew notes have a quite large section on what changed [here](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#reorganization-of-the-library-privacy-changes)

sure a direct call will work to ``pickle.loads``, but this is not guaranteeed across versions.

**Comment by matjazk** [comment]
Going from panda 0.18.1 to 0.20.1 I encountered the same problem when loading with joblib. `joblib.load` fails with exactly the same error:
`ImportError: No module named 'pandas.indexes'`

When you fix this (see the first workaround), there is an error 
`AttributeError: module 'pandas.core.base' has no attribute 'FrozenNDArray'`

After workaround 2, files load. It seems that in my case this is more of a question for joblib devs.

Two (ugly) workarounds:

```
import sys
# 1
import pandas.core.indexes 
sys.modules['pandas.indexes'] = pandas.core.indexes
# 2
import pandas.core.base, pandas.core.indexes.frozen
setattr(sys.modules['pandas.core.base'],'FrozenNDArray', pandas.core.indexes.frozen.FrozenNDArray)
```

**Comment by jreback** [comment]
see the above and simply use pd.read_pickle

**Comment by matjazk** [comment]
I would if I could.  But... I have a complex class (consisting of numpy objects, pandas series and dataframes, dictionaries ...), stored in a compressed joblib archive, so pd.read_pickle is of no use to me. As I said, this might be useful for joblib developers as for now it is impossible to load any joblib archive created when pandas < 0.20. I first had to downgrade pandas and now I'm using the above workarounds.

**Comment by jorisvandenbossche** [comment]
@matjazk Would you like to open an issue at joblib for this?

**Comment by matjazk** [comment]
Already did and passed @jreback's suggestion.

**Comment by mhooreman** [comment]
Thanks. pd.read_pickle works, but, for your information, it is extremely slow - see benchmark.
I've made a script to pd.read_pickle and then pd.to_pickle every file.
![benchmark](https://user-images.githubusercontent.com/7373718/26933500-0590d156-4c67-11e7-986e-01568fca755d.jpg)

**Comment by jorisvandenbossche** [comment]
@mhooreman the timings of "reading old" look suspiciously consistent with "writing". Are you sure you timed the correct thing?

**Comment by mhooreman** [comment]
I need to double check, but I'm sure about the performance difference while
reading: I got performance issues and I converted to fix those.

**Comment by jreback** [comment]
@mhooreman of course its slower. its falling back to the python based unpickler which is much more flexible. so you can either have fast or correctness. you get to choose.

**Comment by TheodoreZhao** [comment]
I got the same problem when unpickling the data in pandas 0.20.2. I have used df.to_pickle() to pickle my dataframe under pandas 0.19.2 and failed to unpickle it using pandas.read_pickle(). I got the error message

`Traceback (most recent call last):
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 83, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 83, in <lambda>
    return read_wrapper(lambda f: pkl.load(f))
ImportError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 88, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 88, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 194, in load
    return up.load()
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1351, in load_stack_global
    self.append(self.find_class(module, name))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 117, in find_class
    return super(Unpickler, self).find_class(module, name)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1392, in find_class
    __import__(module, level=0)
ImportError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 94, in read_pickle
    return try_read(path)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 92, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 92, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 194, in load
    return up.load()
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1351, in load_stack_global
    self.append(self.find_class(module, name))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 117, in find_class
    return super(Unpickler, self).find_class(module, name)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1392, in find_class
    __import__(module, level=0)
ImportError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 83, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 83, in <lambda>
    return read_wrapper(lambda f: pkl.load(f))
ImportError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 88, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 88, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 194, in load
    return up.load()
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1351, in load_stack_global
    self.append(self.find_class(module, name))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 117, in find_class
    return super(Unpickler, self).find_class(module, name)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1392, in find_class
    __import__(module, level=0)
ImportError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 97, in read_pickle
    return try_read(path, encoding='latin1')
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 92, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 68, in read_wrapper
    return func(f)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/io/pickle.py", line 92, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 194, in load
    return up.load()
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1351, in load_stack_global
    self.append(self.find_class(module, name))
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/site-packages/pandas/compat/pickle_compat.py", line 117, in find_class
    return super(Unpickler, self).find_class(module, name)
  File "/Users/kangzhi/anaconda/envs/pystan/lib/python3.5/pickle.py", line 1392, in find_class
    __import__(module, level=0)
ImportError: No module named 'pandas.indexes'`

**Comment by jorisvandenbossche** [comment]
@TheodoreZhao If you have this error with `read_pickle` as well, please open a new issue with a reproducible example.

**Comment by seandickert** [comment]
@jreback similar to @matjazk, pd.read_pickle doesn't work if you're using pickle.loads to load a string (retrieved from some store other than the filesystem).  Can pd.read_pickle be updated to handle a file-like object rather than just a path?

**Comment by jreback** [comment]
its an open issue: https://github.com/pandas-dev/pandas/issues/5924

if you want to submit a PR to do this, its not difficult.
