### ISSUE TITLE
ENH: Improve error message when using DataFrame.from_items instead of DataFrame.from_records

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#17312]
User reported from an early version of pandas, but this is still present in master:

```
import pandas

counters = [
    ('a', 98172247543414),
    ('b', 7805009),
    ('c', 1172983),
    ]

df = pandas.DataFrame.from_items(counters)


# Traceback (most recent call last):                                                                                                                
#   File "/home/user/ptest.py", line 12, in <module>                                                                                               
#     df = pandas.DataFrame.from_items(counters)                                                                                                    
#   File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 932, in from_items                
#   File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 947, in _from_arrays              
#   File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 4463, in _arrays_to_mgr           
#   File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 4502, in extract_index            
# ValueError: If using all scalar values, you must must pass an index  
```

**Comment by chris-b1** [comment]
xref #4916 - not sure there are many usecases left where `from_items` is needed, possibly could be deprecated in favor of `pd.DataFrame(dict(items))`  (that's what I personally use)

**Comment by jreback** [comment]
@chris-b1 can you open an issue for the deprecation.

**Comment by reidy-p** [comment]
I've been looking at this issue and the problem seems to be that the value in each (key, value) pair should be an array or a Series as noted in the ``from_items`` docstring. Would it make sense to raise a ValueError with this message if the user passes a scalar instead of an array or Series as a value?

**Comment by jreback** [comment]
The problem is the user passed a dict, with keys that are all scalars; *maybe* meant to use a Series (or of course meant to pass values that are array-like)

```
In [6]: Series(dict(counters))
Out[6]: 
a    98172247543414
b           7805009
c           1172983
dtype: int64
```

I suppose the error message could be improved
