### ISSUE TITLE
DataFrame to_json Column -> [values] orientation and JSON able

### ISSUE THREAD

**Issue by Wall-ee** [pandas-dev/pandas#17566]
#7863  has mentioned that   to_dict(orient='list')  could be a solution.
here is the example code:

```
In [28]: df = pd.DataFrame(np.arange(1, 5).reshape(2,2), index=['r1', 'r2'], columns=['c1','c2'])

In [29]: df
Out[29]: 
    c1  c2
r1   1   2
r2   3   4

In [30]: df.reset_index().to_dict('list')
Out[30]: {'c1': [1, 3], 'c2': [2, 4], 'index': ['r1', 'r2']}
```
howere if the index of dataframe is Timestamp type.  this method would be useless:

```
aa.head(3)
Out[12]: 
            000423.stock  000825.stock  000959.stock  002011.stock  \
settledate                                                           
2017-07-10           0.0           0.0           0.0           0.0   
2017-07-11           0.0           0.0           0.0           0.0   
2017-07-12           0.0           0.0           0.0           0.0   

json.dumps(aa.to_dict(orient='list'))
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-8014f98ae600>", line 1, in <module>
    json.dumps(aa.to_dict(orient='list'))
  File "D:\anaconda\lib\json\__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "D:\anaconda\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\anaconda\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\anaconda\lib\json\encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Timestamp('2017-07-10 00:00:00') is not JSON serializable
```

so, is there a simple way to transfer the dataframe to json  with a format of  "column:[data1,data2]"?

**Comment by jreback** [comment]
these are some options

```
In [25]: df.reset_index().to_json(orient='records')
Out[25]: '[{"index":1356998400000,"c1":1,"c2":2},{"index":1357084800000,"c1":3,"c2":4}]'

In [26]: df.reset_index().to_json(orient='split')
Out[26]: '{"columns":["index","c1","c2"],"index":[0,1],"data":[[1356998400000,1,2],[1357084800000,3,4]]}'

```

you can also register Timestamp as a type with json.

**Comment by meditativeape** [comment]
Here's the solution that I came up with:
```
s = pd.Series(df.values.tolist(), index=df.columns) # convert df to series, where each value is the list of all values in a column original df
s.to_json()
```

**Comment by pgalilea** [comment]
I'm doing something like this:
`from collections import OrderedDict
from json import dumps
print dumps(df1.to_dict(orient='list', into=OrderedDict))`

**Comment by WillAyd** [comment]
This is now possible to do with the `orient='table'` option:

```python
In [18]: df = pd.DataFrame([[1, 2], [3, 4]], columns=['c1', 'c2'], index=pd.date_range('2018-01-01', freq='D', periods=2))

In [19]: df.to_json(orient='table')
Out[19]: '{"schema": {"fields":[{"name":"index","type":"datetime"},{"name":"c1","type":"integer"},{"name":"c2","type":"integer"}],"primaryKey":["index"],"pandas_version":"0.20.0"}, "data": [{"index":"2018-01-01T00:00:00.000Z","c1":1,"c2":2},{"index":"2018-01-02T00:00:00.000Z","c1":3,"c2":4}]}'

In [20]: pd.read_json(df.to_json(orient='table'), orient='table')
Out[20]: 
            c1  c2
2018-01-01   1   2
2018-01-02   3   4
```

**Comment by CAM-Gerlach** [comment]
@WillAyd Unless I'm missing something major, neither your or @jreback 's output so much as resemble what the OP nor the others here, including now myself, are requesting. What is being asked for is JSON output with the schema ``{index: [index], columns -> [values]}``, as is needed by libraries such as e.g. Plotly.js. For example, as given in the OP, ``{'c1': [1, 3], 'c2': [2, 4], 'index': ['r1', 'r2']}``.

While its fortunate there are a couple workarounds of varying degrees of hackiness as mentioned here, it would be beneficial, especially when it comes to usability and discoverability by average Pandas users, to include it as a built-in ``orient`` option (i.e. named ``list``, following that used for ``to_dict()``) for JSON output. How difficult would something like that be to implement? I'd like to offer to help but my knowledge of C is extremely limited at best, more so than even my time.
