### ISSUE TITLE
Cross compiling pandas with yocto

### ISSUE THREAD

**Issue by r4nd0m6uy** [pandas-dev/pandas#17614]
I'm trying to cross compile pandas from the yocto build system (pyro) with python3. I have an error about wrong elf file:

```txt
ImportError: /.../multiarray.cpython-35m-arm-linux-gnueabihf.so: wrong ELF class: ELFCLASS32
```

The file is ARM elf 32 as expected (my target):
```txt
file ../multiarray.cpython-35m-arm-linux-gnueabihf.so: 
../multiarray.cpython-35m-arm-linux-gnueabihf.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=f70fa82c34e7bf4262a11bd6b9e277dda83795ab, not stripped
```

Here is the detailed error:
```txt
DEBUG: Executing shell function do_compile
ERROR: python3 setup.py build_ext execution failed.
running build
running build_py
UPDATING build/lib.linux-x86_64-3.5/pandas/_version.py
set build/lib.linux-x86_64-3.5/pandas/_version.py to '0.20.3'
running build_ext
Traceback (most recent call last):
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools-32.1.1-py3.5.egg/pkg_resources/__init__.py", line 429, in get_provider
KeyError: 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/multiarray.py", line 7, in <module>
    __bootstrap__()
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/multiarray.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/multiarray.cpython-35m-arm-linux-gnueabihf.so: wrong ELF class: ELFCLASS32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 729, in <module>
    **setuptools_kwargs)
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 388, in build_extensions
    build_ext.build_extensions(self)
  File "setup.py", line 156, in build_extensions
    numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools-32.1.1-py3.5.egg/pkg_resources/__init__.py", line 1197, in resource_filename
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools-32.1.1-py3.5.egg/pkg_resources/__init__.py", line 431, in get_provider
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/pandas-0.20.3/.eggs/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/multiarray.cpython-35m-arm-linux-gnueabihf.so: wrong ELF class: ELFCLASS32

ERROR: Function failed: do_compile (log file is located at /home/moragu/sources/poky-pct-scripts/build/tmp/work/cortexa9hf-neon-comet-linux-gnueabi/python3-pandas/0.20.3-r0/temp/log.do_compile.8706)
```

Unfortunately I don't know much about the python build system but my suspect that something is missing in the setup.py so it is more aware about cross compilation ... Any pointers???

**Comment by gfyoung** [comment]
I suspect your `numpy` version is not compatible, judging from the output.  Did you do a clean install of `numpy` beforehand?  Otherwise, I would suggest trying that.

**Comment by r4nd0m6uy** [comment]
Yes I noticed that numpy (`import numpy`) is used from the setup.py, I guess I need a native version of numpy to run the setup.py script ... Let you know!

**Comment by r4nd0m6uy** [comment]
Pfff that was it! pythone3-numpy-native was a requirement to build the lib. If it can help someone, here is how my yocto recipe looks like:
```bitbake
SUMMARY  = "pandas library for high-performance data analysis tools"
DESCRIPTION = "pandas is an open source, BSD-licensed library providing \
high-performance, easy-to-use data structures and data analysis tools for \
the Python programming language."
HOMEPAGE = "http://pandas.pydata.org/"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=66017d3134349017409386be85176145"

PYPI_PACKAGE = "pandas"

inherit pypi
inherit setuptools3

SRC_URI[md5sum] = "4df858f28b4bf4fa07d9fbb7f2568173"
SRC_URI[sha256sum] = "a777e07633d83d546c55706420179551c8e01075b53c497dcf8ae4036766bc66"

DEPENDS += " \
  ${PYTHON_PN}-numpy-native \
  "

RDEPENDS_${PN} += " \
  ${PYTHON_PN}-numpy \
  ${PYTHON_PN}-dateutil \
  ${PYTHON_PN}-pytz \
  "
```

Sorry for all the noise and thanks for the support!
