### ISSUE TITLE
Commit 9732af248 broke importing pandas (ModuleNotFoundError)

### ISSUE THREAD

**Issue by louispotok** [pandas-dev/pandas#17686]
After commit 9732af248, the master branch no longer allows me to import pandas.
```
(pandas_dev) louispotok@oye:~/pandas-louispotok$ git checkout 9732af248
Previous HEAD position was 8276a420a... DOC: Remove experimental warning from custom offsets (#17584)
HEAD is now at 9732af248... Separate properties module (#17590)
(pandas_dev) louispotok@oye:~/pandas-louispotok$ python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/louispotok/pandas-louispotok/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/louispotok/pandas-louispotok/pandas/core/api.py", line 9, in <module>
    from pandas.core.categorical import Categorical
  File "/home/louispotok/pandas-louispotok/pandas/core/categorical.py", line 33, in <module>
    from pandas.core.base import (PandasObject, PandasDelegate,
  File "/home/louispotok/pandas-louispotok/pandas/core/base.py", line 17, in <module>
    from pandas.util._validators import validate_bool_kwarg
  File "/home/louispotok/pandas-louispotok/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import Appender, Substitution, cache_readonly  # noqa
  File "/home/louispotok/pandas-louispotok/pandas/util/_decorators.py", line 2, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
ModuleNotFoundError: No module named 'pandas._libs.properties'
```
On the previous commit:
```
(pandas_dev) louispotok@oye:~/pandas-louispotok$ git checkout 8276a420a
Previous HEAD position was 9732af248... Separate properties module (#17590)
HEAD is now at 8276a420a... DOC: Remove experimental warning from custom offsets (#17584)
(pandas_dev) louispotok@oye:~/pandas-louispotok$ python -c "import pandas"
(pandas_dev) louispotok@oye:~/pandas-louispotok$ 
```
cc @jbrockmendel who wrote this commit, maybe I'm missing something or doing something wrong?

**Comment by jschendel** [comment]
Try rebuilding the C extensions via `python setup.py build_ext --inplace`.

**Comment by louispotok** [comment]
Thanks! I see that's even in [the contribution documentation](https://pandas.pydata.org/pandas-docs/stable/contributing.html#making-changes), I must have missed it.
