### ISSUE TITLE
COMPAT: datetime.date comparisons with datetime64[ns]

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17965]
This should probably work
```
In [16]: df = pd.DataFrame({'A':[pd.Timestamp('20130101'), np.nan]})

In [17]: df
Out[17]: 
           A
0 2013-01-01
1        NaT

In [18]: pd.Timestamp('20130101').to_pydatetime()>=df.A
Out[18]: 
0     True
1    False
Name: A, dtype: bool

In [20]: pd.Timestamp('20130101').to_pydatetime().date()>=df.A
ValueError: cannot set a Timestamp with a non-timestamp
```

**Comment by jbrockmendel** [comment]
What would `date(2017, 10, 24) < Timestamp('2017-10-24 17:02')` be?

**Comment by jreback** [comment]
These just need wrapping
```
In [7]: pd.Timestamp(datetime.date(2017, 10, 24)) < pd.Timestamp('2017-10-24 17:02')
Out[7]: True
```

**Comment by jbrockmendel** [comment]
I think the internally consistent thing to do would be to wrap `date(2017, 10, 24)` with `pd.Period(date(2017, 10, 24), 'D')`

(the constructor should also be able to infer the freq should be "D", but that is a different issue)

**Comment by jreback** [comment]
no it’s a Timestamp (conceptually it’s just a shortened datetime)

**Comment by jbrockmendel** [comment]
> (conceptually it’s just a shortened datetime)

That part isn't obvious to me, but conditional on this, then I agree this issue is straightforward.

**Comment by TomAugspurger** [comment]
FWIW, python raises here

```
In [4]: datetime.datetime(2017, 1, 1, 12) > datetime.date(2017, 1, 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-c0cf43ef6360> in <module>()
----> 1 datetime.datetime(2017, 1, 1, 12) > datetime.date(2017, 1, 1)

TypeError: can't compare datetime.datetime to datetime.date
```

**Comment by liuli1735** [comment]
```temp = []
dates = data['TradingDay'].unique()
for date in dates:
print(date)
raw_data = data.loc[data['TradingDay'] == date].copy()

ValueError: cannot set a Timestamp with a non-timestamp```

I get the same error, i just upgrade my Anaconda yesterday.

**Comment by TomAugspurger** [comment]
You might want to try asking on StackOverflow with the "pandas" tag. And
they'll
ask you to make an MCVE: https://stackoverflow.com/help/mcve

**Comment by akrherz** [comment]
I think a MCVE for @liuli1735 's post is this

```python
import pandas as pd
df = pd.DataFrame({'dates': pd.date_range('2000-01-01', '2010-12-31')})
date = df['dates'].unique()[0]
print(df.loc[df['dates'] == date])
```
Result with `0.20.3-py27_1` on conda-forge (linux64 python2.7)
```
$ python mcve.py 
       dates
0 2000-01-01
```

Result with `0.21.0-py27_0` on conda-forge (linux64 python2.7)
```
$ python mcve.py 
Traceback (most recent call last):
  File "doy.py", line 5, in <module>
    print(df.loc[df['dates'] == date])
  File "/opt/miniconda2/lib/python2.7/site-packages/pandas/core/ops.py", line 879, in wrapper
    res = na_op(values, other)
  File "/opt/miniconda2/lib/python2.7/site-packages/pandas/core/ops.py", line 808, in na_op
    y = libindex.convert_scalar(x, _values_from_object(y))
  File "pandas/_libs/index.pyx", line 494, in pandas._libs.index.convert_scalar
  File "pandas/_libs/index.pyx", line 509, in pandas._libs.index.convert_scalar
ValueError: cannot set a Timestamp with a non-timestamp
```
