### ISSUE TITLE
read_csv doc says 1st param can be any object with read method--misleading

### ISSUE THREAD

**Issue by WDBell** [pandas-dev/pandas#17969]
#### Code Sample, a copy-pastable example if possible

```python

import pandas as pd

file_name = 'temp.txt'

class FileWrap:
    def __init__(self, path):
        self.file = open(path)
    def read(self):
        return self.file.read()

df = pd.read_csv(FileWrap(file_name), header=None)
print (df)

```
#### Problem description

The **documentation** is a problem because it suggests that any sort of definition of the read method will work. In fact, the one show above fails in a statement such as df = pd.read_csv(FileWrap(filename)).

The object must declare the read method in this way:

**def read(self, *args, **kwargs) **

**Comment by simonjayhawkins** [comment]
i'm unable to reproduce this if i change the read method as suggested by @WDBell.

the issue appears to be that the FileWrap object fails the is_file_like test:

```python
>>> from pandas.core.dtypes.inference import is_file_like
>>>
>>> class FileWrap:
...     def __init__(self, path):
...         self.file = open(path)
...     def read(self):
...         return self.file.read()
...
>>> is_file_like(FileWrap)
False
>>>
```

https://github.com/pandas-dev/pandas/blob/fac819692bd22d93e34dbcb207e43960147a6f17/pandas/core/dtypes/inference.py#L158-L167


should the documentation for pandas.read_csv be updated to reference the `hasattr(obj, "__iter__")` requirement for a file like object?

**Comment by simonjayhawkins** [comment]
if the object does contain an __iter__ method then the read method DOES still need *args, but not **kwargs

``` python
>>>
>>> import pandas as pd
>>>
>>> file_name = 'temp.txt'
>>>
>>> class FileWrap:
...     def __init__(self, path):
...         self.file = open(path)
...     def read(self, *args):
...         return self.file.read()
...     def __iter__(self):
...         pass
...
...
>>> df = pd.read_csv(FileWrap(file_name), header=None)
>>> print (df)
   0  1
0  a  b
>>>
```

otherwise:

```python
>>>
>>>
>>> import pandas as pd
>>>
>>> file_name = 'temp.txt'
>>>
>>> class FileWrap:
...     def __init__(self, path):
...         self.file = open(path)
...     def read(self):
...         return self.file.read()
...     def __iter__(self):
...         pass
...
...
>>> df = pd.read_csv(FileWrap(file_name), header=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 539, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 829, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 932, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2098, in pandas._libs.parsers.raise_parser_error
TypeError: read() takes 1 positional argument but 2 were given
>>>
```

and just for completeness, without __iter__ method:

```python
>>>
>>> import pandas as pd
>>>
>>> file_name = 'temp.txt'
>>>
>>> class FileWrap:
...     def __init__(self, path):
...         self.file = open(path)
...     def read(self, *args):
...         return self.file.read()
...
>>> df = pd.read_csv(FileWrap(file_name), header=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\parsers.py", line 424, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\pandas\io\common.py", line 218, in get_filepath_or_buffer
    raise ValueError(msg.format(_type=type(filepath_or_buffer)))
ValueError: Invalid file path or buffer object type: <class '__main__.FileWrap'>
>>>
```
