### ISSUE TITLE
DatetimeIndex comparison tzaware vs naive should raise

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18162]
```
>>> dr = pd.date_range('2016-01-01', periods=6)
>>> dz = dr.tz_localize('US/Pacific')
>>> dr < dz
array([ True,  True,  True,  True,  True,  True], dtype=bool)
>>> dr[0] < dz[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/_libs/tslib.pyx", line 1169, in pandas._libs.tslib._Timestamp.__richcmp__
  File "pandas/_libs/tslib.pyx", line 1230, in pandas._libs.tslib._Timestamp._assert_tzawareness_compat
TypeError: Cannot compare tz-naive and tz-aware timestamps
```

The vectorized comparison should raise too right?

**Comment by jreback** [comment]
yes this should raise
