### ISSUE TITLE
RecursionError when passing long to fillna

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18316]
```
>>> ser = pd.Series([1, np.nan])
>>> ser.fillna(2L)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pandas/core/series.py", line 2648, in fillna
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 4329, in fillna
    downcast=downcast)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3451, in fillna
    return self.apply('fillna', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3324, in apply
[...]
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 422, in fillna
    return self.split_and_operate(mask, f, inplace)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 464, in split_and_operate
    nv = f(mask, new_values, None)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 420, in f
    downcast=None)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 399, in fillna
    values, _, _, _ = self._try_coerce_args(self.values, value)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 696, in _try_coerce_args
    if np.any(notna(other)) and not self._can_hold_element(other):
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 1836, in _can_hold_element
    tipo = maybe_infer_dtype_type(element)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/dtypes/cast.py", line 513, in maybe_infer_dtype_type
    elif is_list_like(element):
  File "/usr/local/lib/python2.7/site-packages/pandas/core/dtypes/inference.py", line 266, in is_list_like
    return (isinstance(obj, Iterable) and
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
RuntimeError: maximum recursion depth exceeded
```

**Comment by gfyoung** [comment]
Most unusual indeed.  Investigation and PR is welcome!

**Comment by Scorpil** [comment]
I did a small investigation and problem seams to start [here](https://github.com/pandas-dev/pandas/blob/a172ff9dd32d7f6ba077c82b6cf6a31dcc7f2b45/pandas/core/internals.py#L403). [_try_coerce_args](https://github.com/pandas-dev/pandas/blob/a172ff9dd32d7f6ba077c82b6cf6a31dcc7f2b45/pandas/core/internals.py#L699) eventually throws exception for 2L because [_can_hold_element](https://github.com/pandas-dev/pandas/blob/a172ff9dd32d7f6ba077c82b6cf6a31dcc7f2b45/pandas/core/internals.py#L1845) does not check for long type.

I couldn't find tests for Block.fillna, and it might be tricky to set them up since Block is such an internal class. I will not have enough time to finish it, feel free to pick it up.

**Comment by Licht-T** [comment]
I am working on this, and the fixing is almost done.

**Comment by Licht-T** [comment]
@gfyoung This issue was fixed.
https://github.com/pandas-dev/pandas/pull/18385
