### ISSUE TITLE
Series[datetime64] - PeriodIndex vs DatetimeIndex - PeriodIndex

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18850]
`PeriodIndex` w/ `Series` is allowed, `PeriodIndex` w/ `DatetimeIndex` is not.  Is this intentional?  If not, which should be made to match the other?

```
>>> dti = pd.date_range('2016-01-01', periods=3)
>>> ser = pd.Series(dti)
>>> pi = dti.to_period()

>>> ser - pi
0   0 days
1   0 days
2   0 days
dtype: timedelta64[ns]

>>> dti - pi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/indexes/datetimelike.py", line 724, in __sub__
    typ2=type(other).__name__))
TypeError: cannot subtract DatetimeIndex and PeriodIndex

>>> pi - ser
0   0 days
1   0 days
2   0 days
dtype: timedelta64[ns]

>>> pi - dti
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/indexes/datetimelike.py", line 731, in __rsub__
    return -(self - other)
  File "pandas/core/indexes/datetimelike.py", line 724, in __sub__
    typ2=type(other).__name__))
TypeError: cannot subtract DatetimeIndex and PeriodIndex
```

**Comment by jbrockmendel** [comment]
It looks like this is caused [by a line](https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L538) in `ops._TimeOp._convert_to_array`

```
        elif inferred_type == 'integer':
            # py3 compat where dtype is 'm' but is an integer
            if values.dtype.kind == 'm':
                values = values.astype('timedelta64[ns]')
            elif isinstance(values, pd.PeriodIndex):
                values = values.to_timestamp().to_series()
```

**Comment by jbrockmendel** [comment]
@jreback if this can be confirmed as being incorrect behavior for Series, then the remaining point of contention in #18960 can be rendered moot.

**Comment by jreback** [comment]
series w pi is wrong doesn’t make any sense
