### ISSUE TITLE
Recognize np.timedelta64('NaT')

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18936]
```
>>> pd._libs.tslib._delta_to_nanoseconds(np.timedelta64('NaT'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/_libs/tslib.pyx", line 3154, in pandas._libs.tslib._delta_to_nanoseconds
  File "pandas/_libs/tslib.pyx", line 3162, in pandas._libs.tslib._delta_to_nanoseconds
TypeError: an integer is required

```

**Comment by jreback** [comment]
are you using an older version? that routine doesn't exist. maybe you mean

```
In [4]: pd._libs.tslibs.timedeltas.delta_to_nanoseconds(np.timedelta64('NaT'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-ef4970da64af> in <module>()
----> 1 pd._libs.tslibs.timedeltas.delta_to_nanoseconds(np.timedelta64('NaT'))

~/pandas/pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.delta_to_nanoseconds()
     79 # ----------------------------------------------------------------------
     80 
---> 81 cpdef int64_t delta_to_nanoseconds(delta) except? -1:
     82     if util.is_array(delta):
     83         return delta.astype('m8[ns]').astype('int64')

~/pandas/pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.delta_to_nanoseconds()
     87         delta = delta.delta
     88     if is_timedelta64_object(delta):
---> 89         return delta.astype("timedelta64[ns]").item()
     90     if is_integer_object(delta):
     91         return delta

TypeError: an integer is required
```
