### ISSUE TITLE
HDF5 file reading error: "Attribute 'block2_items_variety' does not exist in node:/data" 

### ISSUE THREAD

**Issue by seanysull** [pandas-dev/pandas#18972]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
data.to_hdf('data.h5',mode='w',format='f')

data = pd.read_hdf('data.h5')
####Traceback

AttributeError                            Traceback (most recent call last)
<ipython-input-5-13fe6d5eccfa> in <module>()
----> 1 ndata = pd.read_hdf('cleaned_data_v1.h5')

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    368                                      'contains multiple datasets.')
    369             key = candidate_only_group._v_pathname
--> 370         return store.select(key, auto_close=auto_close, **kwargs)
    371     except:
    372         # if there is an error, close the store

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    715                            chunksize=chunksize, auto_close=auto_close)
    716 
--> 717         return it.get_result()
    718 
    719     def select_as_coordinates(

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in get_result(self, coordinates)
   1455 
   1456         # directly return the result
-> 1457         results = self.func(self.start, self.stop, where)
   1458         self.close()
   1459         return results

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in func(_start, _stop, _where)
    708             return s.read(start=_start, stop=_stop,
    709                           where=_where,
--> 710                           columns=columns, **kwargs)
    711 
    712         # create the iterator

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in read(self, start, stop, **kwargs)
   2893         for i in range(self.nblocks):
   2894 
-> 2895             blk_items = self.read_index('block%d_items' % i)
   2896             values = self.read_array('block%d_values' % i,
   2897                                      start=_start, stop=_stop)

/opt/conda/lib/python3.6/site-packages/pandas/io/pytables.py in read_index(self, key, **kwargs)
   2475 
   2476     def read_index(self, key, **kwargs):
-> 2477         variety = _ensure_decoded(getattr(self.attrs, '%s_variety' % key))
   2478 
   2479         if variety == u('multi'):

/opt/conda/lib/python3.6/site-packages/tables/attributeset.py in __getattr__(self, name)
    290         if not name in self._v_attrnames:
    291             raise AttributeError("Attribute '%s' does not exist in node: "
--> 292                                  "'%s'" % (name, self._v__nodepath))
    293 
    294         # Read the attribute from disk. This is an optimization to read

AttributeError: Attribute 'block2_items_variety' does not exist in node: '/cleaned_data'

#### Problem description
We are working remotely on a Jupyter notebook on a server doing some 
data preprocessing, having loaded an unprocessed .h5 file that was created 
using the pd.to_hdf() command we then did a number of preprocessing operations
 and added some new columns to dataframe.

Next we saved the data using data.to_hdf command and generated the file data.h5. after 
that we used the command read_hdf to read the file but we get the error:
 "Attribute 'block2_items_variety' does not exist in node: /cleaned_data".


#### Expected Output
reading the file successfully.

#### Output of ``pd.show_versions()``


[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.5.7-docker-4
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: 3.3.1
pip: 9.0.1
setuptools: 36.6.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Could you edit your original post to include

1. code that creates a sample DataFrame that generates the exception when written and read
2. The traceback when reading

**Comment by seanysull** [comment]
I have added the full traceback, I am in the process of trying to recreate an example I can share here, however, I am working with data I can not easily share so it will take a while if I am even able to do it.

**Comment by jreback** [comment]
you would have to show a reproducible example

**Comment by JanKalin** [comment]
I get a similar error. I have an application that reads DEWESoft files, converts them to pandas DataFrame and writes them to HDF5 file(s). The complete code used for conversion is downloadable from https://github.com/JanKalin/python_dewesoft. The data file in question can be copied from ftp://zaguser:zagpublic@ftp.zag.si/publicftp/JanK/Pandas/Ravbarkomanda_2018_04_04_132938.dxd

Call `dws2hdf5 Ravbarkomanda_2018_04_04_132938.dxd  --fields 1` to start conversion, which fails:

```
2018-07-03 12:52:58.939000 1/1 Ravbarkomanda_2018_04_04_132938.dxd,
Traceback (most recent call last):
  File "J:\python\dws2hdf5.py", line 111, in <module>
    data.to_hdf(filename, dataset, complevel=5, complib='zlib')
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 1471, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 281, in to_hdf
    f(store)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 275, in <lambda>
    f = lambda store: store.put(key, value, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 866, in put
    self._write_to_group(key, value, append=append, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 1341, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 2930, in write
    self.write_array('block%d_values' % i, blk.values, items=blk_items)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 2671, in write_array
    ca[:] = value
  File "C:\Python27\lib\site-packages\tables\array.py", line 718, in __setitem__
    nparr = convert_to_np_atom2(value, self.atom)
  File "C:\Python27\lib\site-packages\tables\utils.py", line 128, in convert_to_np_atom2
    nparr = convert_to_np_atom(object, atom, copy)
  File "C:\Python27\lib\site-packages\tables\utils.py", line 96, in convert_to_np_atom
    nparr = array_of_flavor(arr, 'numpy')
  File "C:\Python27\lib\site-packages\tables\flavor.py", line 211, in array_of_flavor
    return array_of_flavor2(array, flavor_of(array), dst_flavor)
  File "C:\Python27\lib\site-packages\tables\flavor.py", line 133, in array_of_flavor2
    return convfunc(array)
  File "C:\Python27\lib\site-packages\tables\flavor.py", line 373, in conv_to_numpy
    nparr = nparr.copy()  # copying the array makes it contiguous
MemoryError
```

The HDF5 file available at ftp://zaguser:zagpublic@ftp.zag.si/publicftp/JanK/Pandas/2018_04_04_13_29_40_110000.hdf5  is left in a mangled state,:

```
quark % python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.read_hdf("2018_04_04_13_29_40_110000.hdf5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 370, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 717, in select
    return it.get_result()
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 1457, in get_result
    results = self.func(self.start, self.stop, where)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 710, in func
    columns=columns, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 2902, in read
    blk_items = self.read_index('block%d_items' % i)
  File "C:\Python27\lib\site-packages\pandas\io\pytables.py", line 2484, in read_index
    variety = _ensure_decoded(getattr(self.attrs, '%s_variety' % key))
  File "C:\Python27\lib\site-packages\tables\attributeset.py", line 305, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'block0_items_variety' does not exist in node: '/a_2018_04_04_13_29_40_110000'
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.3
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 5.6.0
sphinx: 1.7.4
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: 4.2.1
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by JanKalin** [comment]
The problem apparently only occurs on 32-bit Python. With 64-bit running inside a 64-bit virtual machine the conversion goes well:

```
Y:\>c:\Users\jank\test\dws2hdf5.py Ravbarkomanda_2018_04_04_132938.dxd --fields
1 @rename.opt
2018-07-04 09:53:22.973000 1/1 Ravbarkomanda_2018_04_04_132938.dxd, a_2018_04_04
_13_29_40_110000, T_2018_04_04_13_29_40_110000, done

Y:\>python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.1
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.5
scipy: None
pyarrow: None
xarray: None
IPython: 5.7.0
sphinx: 1.7.5
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.5
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by JanKalin** [comment]
And the problem disappears with the latest version of Pandas, 0.23.2

**Comment by AiAlex** [comment]
Got this error
`AttributeError: Attribute 'block1_items_variety' does not exist in node: '/dataset'`

on
Pandas  0.25.3
Python 3.6.3 :: Anaconda, Inc.

**Comment by alice17** [comment]
I experienced the same error:

`AttributeError: Attribute 'block0_items_variety' does not exist in node: '/train'` when calling the function `pd.read_hdf(fileInPath, key="train")`. 


pandas 0.24.2
tables 3.5.2
python 3.6

**Comment by gerritholl** [comment]
I experience this error with the attached file.

[72047299999.h5.gz](https://github.com/pandas-dev/pandas/files/4096382/72047299999.h5.gz)

MWE is rather simple:

```python
import pandas
pandas.read_hdf("/data/gholl/cache/fogtools/2019/72047299999.h5", "root")
```

The resulting traceback:

```
Traceback (most recent call last):
  File "mwe15.py", line 2, in <module>
    pandas.read_hdf("/data/gholl/cache/fogtools/2019/72047299999.h5", "root")
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 428, in read_hdf
    auto_close=auto_close,
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 814, in select
    return it.get_result()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 1829, in get_result
    results = self.func(self.start, self.stop, where)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 798, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 3068, in read
    blk_items = self.read_index(f"block{i}_items")
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/pandas/io/pytables.py", line 2752, in read_index
    variety = _ensure_decoded(getattr(self.attrs, f"{key}_variety"))
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/tables/attributeset.py", line 301, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'block0_items_variety' does not exist in node: '/root'
Closing remaining open files:/data/gholl/cache/fogtools/2019/72047299999.h5...done
```

Software versions:

Pandas 1.0.0rc0, pytables 3.6.1, Python 3.7.3.  See below for a full output of `conda list`:

```
# packages in environment at /media/nas/x21324/miniconda3/envs/py37e:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
affine                    2.3.0                      py_0    conda-forge
aggdraw                   1.3.11           py37hc56bac0_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.3                    pypi_0    pypi
asciitree                 0.3.3                      py_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
awscli                    1.16.287                 py37_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.1                    py37_0    conda-forge
behave                    1.2.6                 py37_1000    conda-forge
bitstring                 3.1.6                    pypi_0    pypi
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               he1b5a44_1    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
boto3                     1.10.23                    py_0    conda-forge
botocore                  1.13.23                    py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
cartopy                   0.17.0          py37hc5b2455_1008    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cfgrib                    0.9.7.3                    py_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
codecov                   2.0.15                     py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
coverage                  4.5.4            py37h516909a_0    conda-forge
coveralls                 1.9.2                      py_0    conda-forge
cryptography              2.8              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.8.0                      py_1    conda-forge
dask-core                 2.8.0                      py_0    conda-forge
datashader                0.8.0                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.8.0                      py_1    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
eccodes                   2.14.1               hc4140ea_3    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fcitools                  0.1.0.post0.dev5+ga19d0d1          pypi_0    pypi
fiona                     1.8.11           py37h900e953_0    conda-forge
flake8                    3.7.9                    py37_0    conda-forge
fogpy                     1.2.0+dev21.g2b0d49d.get.validation.output.for.fog.mask          pypi_0    pypi
fogtools                  0.0.post0.dev8+g85b3564.dirty           dev_0    <develop>
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freetype-py               2.1.0.post1                py_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.0                      py_0    conda-forge
g2clib                    1.6.0                hf3f1b0b_9    conda-forge
gdal                      3.0.2            py37hbb6b9fb_3    conda-forge
geopandas                 0.6.2                      py_0    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
geoviews                  1.6.5                      py_0    conda-forge
geoviews-core             1.6.5                      py_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
goesr                     0.5.2                    pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5netcdf                  0.7.4                      py_0    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_100    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
hdfeos2                   2.20              h64bfcee_1000    conda-forge
hdfeos5                   5.1.16               h8b6279f_5    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.12.6                     py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.23                     py37_0    conda-forge
ipdb                      0.12.2                     py_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.9.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0           default_hde54327_4    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgdal                   3.0.2                h5534617_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_101    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4f6d029_1032    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   0.4.2                    pypi_0    pypi
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
line_profiler             2.1.2           py37h516909a_1003    conda-forge
llvmlite                  0.30.0           py37h8b12597_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.4.1            py37h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mechanicalsoup            0.12.0                     py_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mock                      3.0.5                    py37_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3            py37hf3213d6_0    conda-forge
networkx                  2.4                        py_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
nspr                      4.23                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.46.0           py37hb3f55d8_1    conda-forge
numcodecs                 0.6.4            py37he1b5a44_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv-python             4.1.0.25                 pypi_0    pypi
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.0                     py_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    1.0.0rc0                 pypi_0    pypi
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.9.2                      py_0    conda-forge
parse                     1.12.1                     py_0    conda-forge
parse_type                0.5.2                    py37_0    conda-forge
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
progressbar2              3.47.0                     py_0    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.6.5            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pycoast                   1.3.1                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydap                     3.2.2                 py37_1000    conda-forge
pydecorate                0.2.1                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pygrib                    2.0.4            py37h55c65ac_0    conda-forge
pyhdf                     0.10.1           py37h3a4e923_1    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pynio                     1.5.5            py37h2e5bc1a_7    conda-forge
pyopengl                  3.1.3b2                    py_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyorbital                 1.5.0                    pypi_0    pypi
pyparsing                 2.4.5                      py_0    conda-forge
pyproj                    2.4.1            py37h12732c1_1    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5                     5.13.1                   pypi_0    pypi
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtgraph                 0.10.0                     py_7    conda-forge
pyqtwebengine             5.12.1                   pypi_0    pypi
pyresample                1.13.2           py37hb3f55d8_0    conda-forge
pyrsistent                0.15.5           py37h516909a_0    conda-forge
pyscaffold                3.2.2                      py_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pyspectral                0.8.9                    pypi_0    pypi
pytables                  3.6.1            py37h9f153d1_1    conda-forge
pytest                    5.3.0                    py37_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
pytest-mock               1.12.1                   py37_0    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-geotiepoints       1.1.8                    pypi_0    pypi
python-utils              2.3.0                      py_1    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.2                      py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
quamash                   0.6.1                    pypi_0    pypi
rasterio                  1.1.1            py37h900e953_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rsa                       3.4.2                      py_1    conda-forge
rtree                     0.8.3           py37h7b0cdae_1003    conda-forge
s3fs                      0.4.0                      py_0    conda-forge
s3transfer                0.2.1                    py37_0    conda-forge
satpy                     0.19.2.dev31+gf537a14d          pypi_0    pypi
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scipy                     1.3.2            py37h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
shapely                   1.6.4           py37hec07ddf_1006    conda-forge
six                       1.13.0                   py37_0    conda-forge
snakeviz                  2.0.1                      py_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sphinx                    2.2.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlalchemy                1.3.11           py37h516909a_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
trollbufr                 0.11.0                   pypi_0    pypi
trollimage                1.9.0                    pypi_0    pypi
trollsift                 0.3.2                    pypi_0    pypi
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
uwsift                    1.0.6                    pypi_0    pypi
vispy                     0.6.2            py37hf5ce8a7_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
webob                     1.8.5                      py_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xarray                    0.14.1                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zarr                      2.3.2                    py37_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

**Comment by gerritholl** [comment]
@jreback  I have attached a file with a reproduceable example.  Are you able to reproduce this?  Could this be reopened please?

**Comment by jreback** [comment]
@gerritholl 

you would need to show writing and reading
read_hdf is only capable of reading its own format

pls open a new issue if you have a repro example

**Comment by gerritholl** [comment]
@jreback See #31199
