### ISSUE TITLE
AttributeError: LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by vishnusuman** [pandas-dev/pandas#19050]
I'm working on a python program which reads parquet type file and converts it in to pandas dataframe. It works fine while i use the python command to run it (python framework1.py arg1 arg2). But after converting it to an executable file using pyinstaller and when the executable file is ran , it gives the following error.

Traceback (most recent call last):
  File "framework1.py", line 325, in <module>
  File "filetype.py", line 24, in fileTypeSelector
  File "pandas/io/parquet.py", line 256, in read_parquet
  File "pandas/io/parquet.py", line 38, in get_engine
  File "pandas/io/parquet.py", line 89, in __init__
  File "distutils/version.py", line 296, in __cmp__
AttributeError: LooseVersion instance has no attribute 'version'
[17249] Failed to execute script framework1

**Comment by jreback** [comment]
you would have to take this up with pyinstaller.
