### ISSUE TITLE
DatetimeIndex + ndarray[int] wrong, reverse op errors

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19123]
In both 0.22.0 and 1265f66860a1a
```
dti = pd.date_range('2016-01-01', periods=3, freq='D')
tdi = pd.TimedeltaIndex(['1 day', '2days', '3 days'], freq='D')
arr = np.array([1, 2, 3], dtype=np.int64)

>>> dti + arr
DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03'], dtype='datetime64[ns]', freq='86400000000001N')

>>> dti - arr
DatetimeIndex(['2015-12-31 23:59:59.999999999',
               '2016-01-01 23:59:59.999999998',
               '2016-01-02 23:59:59.999999997'],
              dtype='datetime64[ns]', freq='86399999999999N')

>>> arr + dti
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'DatetimeIndex'

>>> tdi + arr
TimedeltaIndex(['1 days 00:00:00.000000', '2 days 00:00:00.000000',
                '3 days 00:00:00.000000'],
               dtype='timedelta64[ns]', freq='86400000000001N')

>>> arr + tdi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'TimedeltaIndex'

>>> tdi - arr
TimedeltaIndex(['0 days 23:59:59.999999', '1 days 23:59:59.999999',
                '2 days 23:59:59.999999'],
               dtype='timedelta64[ns]', freq='86399999999999N')

>>> arr - tdi
TimedeltaIndex(['-1 days +00:00:00.000000', '-2 days +00:00:00.000000',
                '-3 days +00:00:00.000000'],
               dtype='timedelta64[ns]', freq='-86399999999999N')
```

Expected:
```
dti = pd.date_range('2016-01-01', periods=3, freq='D')
tdi = pd.TimedeltaIndex(['1 day', '2days', '3 days'], freq='D')
arr = np.array([1, 2, 3], dtype=np.int64)

>>> dti + arr
DatetimeIndex(['2016-01-02', '2016-01-04', '2016-01-06'], dtype='datetime64[ns]', freq='2D')

>>> arr + dti
DatetimeIndex(['2016-01-02', '2016-01-04', '2016-01-06'], dtype='datetime64[ns]', freq='2D')

>>> tdi + arr
TimedeltaIndex(['2 days', '4 days', '6 days'], dtype='timedelta64[ns]', freq='2D')

>>> arr + tdi
TimedeltaIndex(['2 days', '4 days', '6 days'], dtype='timedelta64[ns]', freq='2D')

>>> tdi - arr
TimedeltaIndex(['0 days', '0 days', '0 days'], dtype='timedelta64[ns]', freq=None)

>>> arr - tdi
TimedeltaIndex(['0 days', '0 days', '0 days'], dtype='timedelta64[ns]', freq=None)
```

**Comment by jreback** [comment]
what do you think about banning *all* integer arithmetic with DTI (wether has a freq or not) and TDI  (already banned), (but leave for PI)?

I know its sometimes convenient but it relies much to heavily on the 'freq'. which is kind of a hack for DTI.

**Comment by jbrockmendel** [comment]
It would have the upside of making Series[datetime64] and DatetimeIndex more interchangeable.  We'd have to (get to) get rid of Timestamp integer arithmetic at the same time.

**Comment by jreback** [comment]
yeah I wrote this then erased it. It IS convenient.

**Comment by jbrockmendel** [comment]
Hmm this also leads to a weird non-commutativity:

```
dti = pd.date_range('2016-01-01', periods=3, freq='D')
arr = np.array([1, 2, 3], dtype=np.int64)

>>> dti + arr
DatetimeIndex(['2016-01-02', '2016-01-04', '2016-01-06'], dtype='datetime64[ns]', freq='2D')
>>> (dti + arr) - arr
DatetimeIndex(['2015-12-31', '2015-12-31', '2015-12-31'], dtype='datetime64[ns]', freq=None)
```

Since `dti+arr` comes back with freq=2D, the subtraction operation doens't just undo the addition.

**Comment by jbrockmendel** [comment]
This is fixed in master, not sure when

**Comment by jbrockmendel** [comment]
Made a note in #18824 to track down what PR fixed this.  Closing.
