### ISSUE TITLE
Groupby.mode() - feature request

### ISSUE THREAD

**Issue by j-musial** [pandas-dev/pandas#19254]
#### Feature Request
Hi,

I use pandas a lot in my projects and I got stack with a problem of running the "mode" function (most common element) on a huge groupby object. There are few solutions available using aggregate and  scipy.stats.mode, but they are unbearably slow in comparison to e.g. groupby.mean(). Thus, I would like to make a feature request to add cytonized version of  groupby.mode() operator.

Thanks in advance!

Jan Musial

**Comment by chris-b1** [comment]
xref #19165 (master tracker)

A PR would be welcome!  As you note the key thing would be implementing a single-pass group mode function in cython, can look at others for examples. 

https://github.com/pandas-dev/pandas/blob/aa9e002463d104b6dc37cdb32b2726bafcb5aa36/pandas/_libs/groupby_helper.pxi.in#L213

**Comment by jreback** [comment]
how is this different that ``.value_counts()`` ?

**Comment by j-musial** [comment]
Hi Jeff,

As you can see below .value_counts() does not apply to groupby object.
Furthermore, returning sorted values and counts within thousands/millions
of groups gives huge overheads, whereas all you want is the most frequent
value.

Best,

Jan


>>>
pd.DataFrame({'a':['a','a','a','a','b','b','b','b'],'b':[1,1,2,3,1,2,2,3]}).groupby('a').value_counts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 529,
in __getattr__
    (type(self).__name__, attr))
AttributeError: 'DataFrameGroupBy' object has no attribute 'value_counts'
>>> pd.__version__
'0.19.2'

**Comment by jreback** [comment]
``.value_counts()`` is a series method. I guess mode would simply give back the max per group.

```
In [32]: pd.options.display.max_rows=12

In [33]: ngroups = 100; N = 100000; np.random.seed(1234)

In [34]: df = pd.DataFrame({'key': np.random.randint(0, ngroups, size=N), 'value': np.random.randint(0, 10000, size=N)})

In [35]: df.groupby('key').value.value_counts()
Out[35]: 
key  value
0    5799     3
     7358     3
     8860     3
     185      2
     583      2
     872      2
             ..
99   9904     1
     9916     1
     9922     1
     9932     1
     9935     1
     9936     1
Name: value, Length: 95112, dtype: int64
```

**Comment by j-musial** [comment]
Thanks Jeff!

Unlike .value_counts() the .mode() would act like a reduction function
returning just one value. Returning entire histogram just to get the most
frequent value is huge waste of computing resources.

Best,

Jan

**Comment by jaradc** [comment]
What would `.mode()` do in the case of text data?

Ex data:
```
import pandas as pd
import numpy as np

nan = np.nan
df = pd.DataFrame({'D1': ['mobile', nan, 'mobile', 'mobile', 'mobile', 'desktop', 'desktop',
                          'desktop', 'desktop', 'desktop', 'desktop', 'mobile', 'mobile', nan],
                   'D2': [nan, 'm.site.com', 'www.site.com', 'm.site.com', 'm.site.com',
                          'www.site.com', nan, 'www.site.com', 'www.site.com', 'm.site.com',
                          'm.site.com', 'm.site.com', nan, 'www.site.com'],
                   'D3': ['New Visitor', 'New Visitor', 'New Visitor', 'New Visitor', nan,
                          'New Visitor', 'New Visitor', 'New Visitor', 'New Visitor', nan,
                          'Returning Visitor', 'New Visitor', 'New Visitor', 'New Visitor'],
                   'D4': [nan, 2, 2, 1, 1, 6, 4, 2, 8, 8, nan, 5, 6, 7],
                   'ID1': [0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
                   'ID2': ['1513947210589.498foauq', '1514422572948.4vyo6zj',
                           '1514422572948.4vyo6zj', '1514422572948.4vyo6zj',
                           '1514425695272.dzsx0r5', '1514222583279.vn2j3ath',
                           '1514222583279.vn2j3ath', '1514222583279.vn2j3ath',
                           '1514383627556.zc6t10sll2', '1514383700797.eqetpiviq',
                           '1514383700797.eqetpiviq', '1514841713220.wjrcnsml',
                           '1514841713220.wjrcnsml', '1514841713220.wjrcnsml']},
                  columns=['ID1', 'ID2', 'D1', 'D2', 'D3', 'D4'])
```

Looks like:

```
    ID1                       ID2       D1            D2                 D3   D4
0     0    1513947210589.498foauq   mobile           NaN        New Visitor  NaN
1     1     1514422572948.4vyo6zj      NaN    m.site.com        New Visitor  2.0
2     1     1514422572948.4vyo6zj   mobile  www.site.com        New Visitor  2.0
3     1     1514422572948.4vyo6zj   mobile    m.site.com        New Visitor  1.0
4     1     1514425695272.dzsx0r5   mobile    m.site.com                NaN  1.0
5     2    1514222583279.vn2j3ath  desktop  www.site.com        New Visitor  6.0
6     2    1514222583279.vn2j3ath  desktop           NaN        New Visitor  4.0
7     2    1514222583279.vn2j3ath  desktop  www.site.com        New Visitor  2.0
8     3  1514383627556.zc6t10sll2  desktop  www.site.com        New Visitor  8.0
9     3   1514383700797.eqetpiviq  desktop    m.site.com                NaN  8.0
10    3   1514383700797.eqetpiviq  desktop    m.site.com  Returning Visitor  NaN
11    4    1514841713220.wjrcnsml   mobile    m.site.com        New Visitor  5.0
12    4    1514841713220.wjrcnsml   mobile           NaN        New Visitor  6.0
13    4    1514841713220.wjrcnsml      NaN  www.site.com        New Visitor  7.0
```

Calling mode on the groupby object directly:
```
>>> df.groupby(['ID1', 'ID2']).mode()
			      
Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    df.groupby(['ID1', 'ID2']).mode()
  File "C:\python36\lib\site-packages\pandas\core\groupby.py", line 673, in __getattr__
    return self._make_wrapper(attr)
  File "C:\python36\lib\site-packages\pandas\core\groupby.py", line 687, in _make_wrapper
    raise AttributeError(msg)
AttributeError: Cannot access callable attribute 'mode' of 'DataFrameGroupBy' objects, try using the 'apply' method
```
Calling mode on a specific column in the groupby:
```
>>> df.groupby(['ID1', 'ID2'], as_index=False)['D1'].mode()
		       
Traceback (most recent call last):
  File "<pyshell#56>", line 1, in <module>
    df.groupby(['ID1', 'ID2'], as_index=False)['D1'].mode()
  File "C:\python36\lib\site-packages\pandas\core\groupby.py", line 673, in __getattr__
    return self._make_wrapper(attr)
  File "C:\python36\lib\site-packages\pandas\core\groupby.py", line 687, in _make_wrapper
    raise AttributeError(msg)
AttributeError: Cannot access callable attribute 'mode' of 'DataFrameGroupBy' objects, try using the 'apply' method
```

You can use `idxmax()` and `value_counts` but I agree with @j-musial that it's a computational waste just to get the most frequent.
```
>>> df.groupby(['ID1', 'ID2'], as_index=False)['D4'].apply(lambda x: x.value_counts(dropna=False).idxmax())
ID1  ID2                     
0    1513947210589.498foauq      NaN
1    1514422572948.4vyo6zj       2.0
     1514425695272.dzsx0r5       1.0
2    1514222583279.vn2j3ath      2.0
3    1514383627556.zc6t10sll2    8.0
     1514383700797.eqetpiviq     NaN
4    1514841713220.wjrcnsml      7.0
dtype: float64
```

The `mode()` function creator might need to ask:

1. numeric and text data or just numeric data?
2. what to do in the case of a tie-breaker of modes?
3. what to do when no mode exists (ex: nans)?

I'll provide one example where I'd like to use this type of functionality:

I'd like to fill nans with the most-common value (mode) in a groupby. Said a different way, I'd like to impute text data to fill with the most-frequent in a groupby. ([SO example here](https://stackoverflow.com/a/45741963/1577947) but this approach fails when index `[0]` does not exist).

This effectively does nothing:
```
df.groupby(['ID1', 'ID2'], as_index=False).apply(lambda x: x.fillna(x.mode()))
```

If I approach this with `ffill()` and `bfill()`, it's very slow because those in a groupby is not vectorized (is pure Python) is my understanding.

`groupby.mode()` request turns out to not be a trivial request imo. Clear examples and use-cases would really help sketch out the idea I think.

**Comment by farrerb** [comment]
If I have a DataFrame that includes a column a cities, and I want to know the most frequent city to occur on the list. I'm pretty new to python and pandas, so maybe there's an easy alternative, but I'm not aware of one.

**Comment by BrittonWinterrose** [comment]
I am interested in this feature as well. +1

**Comment by rogerioluizsi** [comment]
i'm too

**Comment by Arregator** [comment]
I can't find a good solution for the problem of populating missing values of my dataset with **a most frequent** value **in a group** (NOTE: not mean, but most frequent). 

I thought that would be way too often intention for those handling missing values.

I have a dataset:

```python
In [425]: df
Out[425]:
      brand     model fuelType  engineDisplacement
0      audi      a100   petrol              2000.0
1       bmw  3-series   diesel              2000.0
2  mercedes   e-class   petrol              3000.0
3  mercedes   e-class   petrol                 NaN
4    nissan      leaf  electro                 NaN
5     tesla   model x  electro                 NaN
6  mercedes   e-class   petrol              2000.0
7  mercedes   e-class   petrol              2000.0
8  mercedes   e-class   petrol              2000.0
```

and I want for my `mercedes   e-class   petrol                 NaN` to fill its `NaN` with `2000` as a most frequent value in the group `brand-model-fuelType`. I try somthing like:

```python
df.groupby(['brand', 'model', 'fuelType'])['engineDisplacement'].transform(
    lambda x: x.fillna(x.mode())
)

In [427]: df.groupby(['brand', 'model', 'fuelType'])['engineDisplacement'].transform(
     ...:     lambda x: x.fillna(x.mode())
     ...:     )
Out[427]:
0    2000.0
1    2000.0
2    3000.0
3       NaN
4       NaN
5       NaN
6    2000.0
7    2000.0
8    2000.0
Name: engineDisplacement, dtype: float64
```
you see? it does not fill `NaN` with `2000` as I would expect :(

Again, it is important to have a most frequent value, because in many-many cases we have to deal with a categorical values, not numeric, so we need this feature badly.

**Comment by kashumi-m** [comment]
+1 for this

**Comment by lithomas1** [comment]
take

**Comment by arw2019** [comment]
+1 - had someone ask about this

**Comment by lithomas1** [comment]
Unassigning myself as I don't have time for this.(Had hit a issue with Cython generating duplicate C functions).

**Comment by rhshadrach** [comment]
```
def gb_mode(df, keys, column):
    return df.groupby(keys + [column])[column].size().unstack(column).idxmax(axis=1)

df = pd.DataFrame({'a': [1, 1, 1, 2, 2, 2], 'b': [3, 4, 3, 4, 3, 4]})
print(gb_mode(df, ['a'], 'b'))
```

produces

```
a
1    3
2    4
dtype: int64
```

Seems to have decent performance, at least when the categorical ('b', here) has few values, but still +1 on adding a cythonized mode.

**Comment by lithomas1** [comment]
I think there needs to be a discussion on the API for mode before we should proceed with anything. The question being "What happens if multimodal?" (Should we raise warning, return last mode, return smallest mode?). Also, I think there may be complexity around extension types when implementing in Cython? 

I think I was able to hack up something by reintroducing the tempita template for groupby, and modifying _get_cythonized_result(which iterates over columns in python?), but I'm not sure if this is the right result.

**Comment by trevor-pope** [comment]
"What happens if multimodal?"

Why not all of them? It could just be an argument to the function. 

`keep='raise'` could raise a warning, `keep='smallest'` or `keep='largest'` returns the smallest/largest, etc. 

Something like `df.groupby('col').mode(keep='all')` will give all modes as a list (if a category is multimodal, thus making the resulting dtype `object`). This might run into efficiency concerns however. I've personally had this use case (getting all modes), but I am not sure how necessary it is to support when you could get by using `.value_counts()`, albeit with a bit more work and computation.

I could try to implement this, but I am not sure where to do it at. Is the tempita template still the way to go?

**Comment by wesley-cheek** [comment]
Hoping for this feature..
