### ISSUE TITLE
Series.loc with MultiIndex does not handle repeated keys properly

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#19414]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
s = pd.Series([1, 2], pd.MultiIndex.from_arrays([['a', 'b']]))
print(s.loc[['a', 'a', 'b', 'b']])
```

#### Problem description

This prints the full series, not the series with repeated elements:
```
a    1
b    2
dtype: int64
```

#### Expected Output

```
a    1
a    1
b    2
b    2
dtype: int64
```

An easy work around is to use `s.reindex(['a', 'a', 'b', 'b'])` instead. But `loc` and `reindex` should return the same thing when all labels are found.

#### Output of ``pd.show_versions()``

pandas 0.22.0

I think this behavior is present on earlier versions of pandas, too, but previously it was very difficult to construct a MultiIndex with only a single level, because they were automatically turned in a base Index.

**Comment by phofl** [comment]
This raises now
```
Traceback (most recent call last):
  File "/home/developer/.config/JetBrains/PyCharm2020.2/scratches/scratch_4.py", line 28, in <module>
    print(s.loc[['a', 'a', 'b', 'b']])
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexing.py", line 887, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexing.py", line 1105, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexing.py", line 1045, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexing.py", line 1246, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexes/multi.py", line 2463, in _convert_listlike_indexer
    _, indexer = self.reindex(keyarr, level=level)
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexes/multi.py", line 2378, in reindex
    target, indexer, _ = self._join_level(
  File "/home/developer/PycharmProjects/pandas/pandas/core/indexes/base.py", line 3826, in _join_level
    raise NotImplementedError(
NotImplementedError: Index._join_level on non-unique index is not implemented

Process finished with exit code 1
```

which seems to be intentional?

**Comment by jbrockmendel** [comment]
This now works as expected by the OP, could use a test.

**Comment by johnmantios** [comment]
take
