### ISSUE TITLE
CI: conda build test failing

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19572]
Don't think we have an issue for this yet

```
[building conda recipe]

Leaving build/test directories:
  Work:	 /home/travis/miniconda3/conda-bld/work 
  Test:	 /home/travis/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  /home/travis/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:	source activate  /home/travis/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 441, in decorated
    return f(*args, **kwds)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 540, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 317, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 697, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - numpy[version='>=1.14.0,<1.14']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1032, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 582, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1845, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 670, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 281, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 117, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 708, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"numpy[version='>=1.14.0,<1.14']"}

real	0m9.261s
user	0m9.234s
sys	0m1.117s
```

https://api.travis-ci.org/v3/job/338476528/log.txt

Seems like `min_pin='1.14', max_pin='1.14'` is what we would want if want want 1.14.

**Comment by TomAugspurger** [comment]
I wonder if this is causing collection failures:

```
==================================== ERRORS ====================================
___________ ERROR at setup of TestPandasContainer.test_read_s3_jsonl ___________
[gw1] linux -- Python 3.5.4 /home/travis/miniconda3/envs/pandas/bin/python

tips_file = '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/tips.csv'
jsonl_file = '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/items.jsonl'

[1m    @pytest.fixture(scope='module')[0m
[1m    def s3_resource(tips_file, jsonl_file):[0m
[1m        """Fixture for mocking S3 interaction.[0m
[1m    [0m
[1m        The primary bucket name is "pandas-test". The following datasets[0m
[1m        are loaded.[0m
[1m    [0m
[1m        - tips.csv[0m
[1m        - tips.csv.gz[0m
[1m        - tips.csv.bz2[0m
[1m        - items.jsonl[0m
[1m    [0m
[1m        A private bucket "cant_get_it" is also created. The boto3 s3 resource[0m
[1m        is yielded by the fixture.[0m
[1m        """[0m
[1m        pytest.importorskip('s3fs')[0m
[1m        moto.mock_s3().start()[0m
[1m    [0m
[1m        test_s3_files = [[0m
[1m            ('tips.csv', tips_file),[0m
[1m            ('tips.csv.gz', tips_file + '.gz'),[0m
[1m            ('tips.csv.bz2', tips_file + '.bz2'),[0m
[1m            ('items.jsonl', jsonl_file),[0m
[1m        ][0m
[1m    [0m
[1m        def add_tips_files(bucket_name):[0m
[1m            for s3_key, file_name in test_s3_files:[0m
[1m                with open(file_name, 'rb') as f:[0m
[1m                    conn.Bucket(bucket_name).put_object([0m
[1m                        Key=s3_key,[0m
[1m                        Body=f)[0m
[1m    [0m
[1m        boto3 = pytest.importorskip('boto3')[0m
[1m        # see gh-16135[0m
[1m        bucket = 'pandas-test'[0m
[1m    [0m
[1m        conn = boto3.resource("s3", region_name="us-east-1")[0m
[1m        conn.create_bucket(Bucket=bucket)[0m
[1m>       add_tips_files(bucket)[0m

[1m[31m/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/conftest.py[0m:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

bucket_name = 'pandas-test'

[1m    def add_tips_files(bucket_name):[0m
[1m        for s3_key, file_name in test_s3_files:[0m
[1m>           with open(file_name, 'rb') as f:[0m
[1m[31mE           FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/items.jsonl'[0m

[1m[31m/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/conftest.py[0m:56: FileNotFoundError
____________ ERROR at setup of TestS3.test_parse_public_s3n_bucket _____________
[gw1] linux -- Python 3.5.4 /home/travis/miniconda3/envs/pandas/bin/python

tips_file = '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/tips.csv'
jsonl_file = '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/items.jsonl'

[1m    @pytest.fixture(scope='module')[0m
[1m    def s3_resource(tips_file, jsonl_file):[0m
[1m        """Fixture for mocking S3 interaction.[0m
[1m    [0m
[1m        The primary bucket name is "pandas-test". The following datasets[0m
[1m        are loaded.[0m
[1m    [0m
[1m        - tips.csv[0m
[1m        - tips.csv.gz[0m
[1m        - tips.csv.bz2[0m
[1m        - items.jsonl[0m
[1m    [0m
[1m        A private bucket "cant_get_it" is also created. The boto3 s3 resource[0m
[1m        is yielded by the fixture.[0m
[1m        """[0m
[1m        pytest.importorskip('s3fs')[0m
[1m        moto.mock_s3().start()[0m
[1m    [0m
[1m        test_s3_files = [[0m
[1m            ('tips.csv', tips_file),[0m
[1m            ('tips.csv.gz', tips_file + '.gz'),[0m
[1m            ('tips.csv.bz2', tips_file + '.bz2'),[0m
[1m            ('items.jsonl', jsonl_file),[0m
[1m        ][0m
[1m    [0m
[1m        def add_tips_files(bucket_name):[0m
[1m            for s3_key, file_name in test_s3_files:[0m
[1m                with open(file_name, 'rb') as f:[0m
[1m                    conn.Bucket(bucket_name).put_object([0m
[1m                        Key=s3_key,[0m
[1m                        Body=f)[0m
[1m    [0m
[1m        boto3 = pytest.importorskip('boto3')[0m
[1m        # see gh-16135[0m
[1m        bucket = 'pandas-test'[0m
[1m    [0m
[1m        conn = boto3.resource("s3", region_name="us-east-1")[0m
[1m        conn.create_bucket(Bucket=bucket)[0m
[1m>       add_tips_files(bucket)[0m

[1m[31m/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/conftest.py[0m:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

bucket_name = 'pandas-test'

[1m    def add_tips_files(bucket_name):[0m
[1m        for s3_key, file_name in test_s3_files:[0m
[1m>           with open(file_name, 'rb') as f:[0m
[1m[31mE           FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/parser/data/items.jsonl'[0m

[1m[31m/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/tests/io/conftest.py[0m:56: FileNotFoundError
```

It seems like we end up just installing the conda package from conda-forge?

```


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-0.22.0              |   py35hf484d3e_0        10.6 MB

The following NEW packages will be INSTALLED:

    pandas:  0.22.0-py35hf484d3e_0            

The following packages will be UPDATED:

    certifi: 2017.11.5-py35_0      conda-forge --> 2018.1.18-py35_0 
    openssl: 1.0.2n-0              conda-forge --> 1.0.2n-hb7f436b_0

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

[show pandas]
# packages in environment at /home/travis/miniconda3/envs/pandas:
#
# Name                    Version                   Build  Channel
pandas                    0.22.0           py35hf484d3e_0  
pandas-gbq                0.3.0                     <pip>
```

**Comment by jreback** [comment]
this works on master, but not on branches, this is why I moved the build to allowed failures.
