### ISSUE TITLE
Pip build test CI failures

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19668]
I've seen a couple of these. Is this intermittent? Any idea what's going on?

https://travis-ci.org/pandas-dev/pandas/jobs/340640051

```
    running build_ext
    pandas._libs.algos: -> [['pandas/_libs/algos.c']]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-nv04tz46-build/setup.py", line 741, in <module>
        **setuptools_kwargs)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/travis/miniconda3/envs/pandas/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-nv04tz46-build/setup.py", line 367, in build_extensions
        self.check_cython_extensions(self.extensions)
      File "/tmp/pip-nv04tz46-build/setup.py", line 364, in check_cython_extensions
        """.format(src=src))
    Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                    Cython is required to compile pandas from a development branch.
                    Please install Cython or download a release package of pandas.
    
```

**Comment by chris-b1** [comment]
a little further up
```
gcc -pthread -shared -B /home/travis/miniconda3/envs/pandas/compiler_compat -L/home/travis/miniconda3/envs/pandas/lib -Wl,-rpath=/home/travis/miniconda3/envs/pandas/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pandas/_libs/tslibs/conversion.o build/temp.linux-x86_64-3.6/pandas/_libs/src/datetime/np_datetime.o build/temp.linux-x86_64-3.6/pandas/_libs/src/datetime/np_datetime_strings.o -o build/lib.linux-x86_64-3.6/pandas/_libs/tslibs/conversion.cpython-36m-x86_64-linux-gnu.so
  build/temp.linux-x86_64-3.6/pandas/_libs/tslibs/conversion.o: file not recognized: File truncated
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pandas
```

ccache seems like a suspect
https://stackoverflow.com/questions/5713894/file-not-recognized-file-truncated-gcc-error

It is used a little further up to build `conversion.o`, but I'm not familiar enough with it to know offhand what's actually going wrong or how to fix (blunt fix is probably to disable ccache entirely for now).  cc @jbrockmendel 

```
ccache gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/home/travis/miniconda3/envs/pandas/lib/python3.6/site-packages/numpy/core/include -I/home/travis/miniconda3/envs/pandas/include/python3.6m -c pandas/_libs/tslibs/conversion.c -o build/temp.linux-x86_64-3.6/pandas/_libs/tslibs/conversion.o -Wno-unused-function
```

**Comment by jreback** [comment]
not don’t disable caching!!!

but u can clear the travis cache on master of u want

**Comment by TomAugspurger** [comment]
@hexgnu it's looking like https://github.com/pandas-dev/pandas/commit/39e7b6916b07982240bac87132848fb2665806a2#diff-2eeaed663bd0d25b7e608891384b7298 is the commit that started causing issues here (that's the first commit that touched `setup.py` that broke things).

The issue is that we want users to be able to install pandas from source without Cython. Any ideas?

To test you can run `bash scripts/build_dist_for_release.sh` from an env with Cython, and then `pip install path/to/pandas/dist/*.tar.gz` from an env without cython.

**Comment by hexgnu** [comment]
Think I found the issue hold on...

**Comment by jreback** [comment]
this is now being build in https://github.com/pandas-dev/pandas-ci
