### ISSUE TITLE
Building documentation fails with `ImportError: cannot import name 'Directive'`

### ISSUE THREAD

**Issue by miguelmorin** [pandas-dev/pandas#20955]
#### Code Sample, a copy-pastable example if possible

I build `pandas` from source following [these steps](https://github.com/pandas-dev/pandas/tree/master/doc), then I run this command to build the documentation:

```
$ python make.py html
Running Sphinx v1.7.4
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/Users/mmorin/miniconda3/envs/pandas-dev-pip9/lib/python3.6/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/Users/mmorin/Software/pandas/doc/sphinxext/numpydoc/__init__.py", line 3, in <module>
    from .numpydoc import setup
  File "/Users/mmorin/Software/pandas/doc/sphinxext/numpydoc/numpydoc.py", line 29, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name 'Directive'

```
#### Problem description

The documentation build fails. I found [this issue](https://github.com/spinus/sphinxcontrib-images/issues/41) on the Sphinx Github issues list and replaced

```
from sphinx.util.compat import Directive
```

with
```
try:
    from sphinx.util.compat import Directive
except ImportError:
    from docutils.parsers.rst import Directive
```

in both `doc/sphinxext/numpydoc/numpydoc.py` and `doc/sphinxext/ipython_sphinxext/ipython_directive.py`.

#### Expected Output

```
$ python make.py html
Running Sphinx v1.7.4
WARNING: while setting up extension conf.py: directive 'autosummary' is already registered, it will be overridden
loading pickled environment... not yet created
...
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.22.0
pytest: 3.5.1
pip: 9.0.3
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.2
scipy: 1.0.1
pyarrow: 0.9.0
xarray: 0.10.3
IPython: 6.3.1
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: 0.8.0
psycopg2: None
jinja2: 2.10
s3fs: 0.1.4
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Can you try on master? We updated our numpydoc, and I dont' see references to sphinx.util.compat anymore.

**Comment by miguelmorin** [comment]
Yes, it works on `master` as of today. Shall I do a pull request with my fix on `0.22.x`?

**Comment by gfyoung** [comment]
`0.23.x` is coming out soon, so I would just wait until we release, or you can just pull `master` and use that.
