### ISSUE TITLE
Categorical `fillna` with custom objects raises TypeError

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21097]
This behavior appears new in 0.23.0.

Setup copied from #21002:

```
from pandas.core.base import StringMixin

class County(StringMixin):
    name = u'San Sebastián'
    state = u'PR'
    def __unicode__(self):
        return self.name + u', ' + self.state

cat = pd.Categorical([County() for n in range(61)])
>>> cat.fillna(cat[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pandas/util/_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/arrays/categorical.py", line 1769, in fillna
    '"{0}"'.format(type(value).__name__))
TypeError: "value" parameter must be a scalar, dict or Series, but you passed a "County"
```

I don't see any reason why passing one of the categories to `fillna` should be disallowed, so it looks like the issue is with being too strict about what qualifies as a scalar.

**Comment by jbrockmendel** [comment]
@TomAugspurger I think this might be up your alley.

**Comment by TomAugspurger** [comment]
Comes from https://github.com/pandas-dev/pandas/pull/19684

We check `is_scalar(value)`, and for `County` that's false.

`is_scalar` doesn't quite seem like the right check. We want to see if it's in the categories... Here's a simpler repro:

```python
In [25]: c = pd.Categorical([(0, 1), (1, 2)])

In [26]: c.fillna((0, 1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-69f5393b61c6> in <module>()
----> 1 c.fillna((0, 1))

~/sandbox/pandas/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    175                 else:
    176                     kwargs[new_arg_name] = new_arg_value
--> 177             return func(*args, **kwargs)
    178         return wrapper
    179     return _deprecate_kwarg

~/sandbox/pandas/pandas/core/arrays/categorical.py in fillna(self, value, method, limit)
   1767                 raise TypeError('"value" parameter must be a scalar, dict '
   1768                                 'or Series, but you passed a '
-> 1769                                 '"{0}"'.format(type(value).__name__))
   1770
   1771         return self._constructor(values, categories=self.categories,

TypeError: "value" parameter must be a scalar, dict or Series, but you passed a "tuple"
```

We'll need to watch out for non-hashable `value`
