### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fetchall' on Update

### ISSUE THREAD

**Issue by isantolin** [pandas-dev/pandas#21232]
#### Code Sample, a copy-pastable example if possible

```python
engine = sqlalchemy.create_engine("mssql+pymssql://" + user + ":" + password + "@" + server + '/' + db)

pd.read_sql_query("UPDATE tb_VC_P SET lastUpdate='2018-05-28 20:55:10' WHERE idVisualCreativeProcess=9"), engine)

```
#### Problem description

When i try to execute an update query shows that error

```
Traceback (most recent call last):
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 1082, in _fetchall_impl
    return self.cursor.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx.xxxx\workspace\Projeto\SM_VC.py", line 70, in <module>
    pd.read_sql_query("UPDATE tb_VC_P SET lastUpdate='2018-05-28 20:55:10' WHERE idVisualCreativeProcess=9", engine)
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\sql.py", line 314, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\sql.py", line 1094, in read_query
    data = result.fetchall()
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 1137, in fetchall
    self.cursor, self.context)
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 1131, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 1084, in _fetchall_impl
    return self._non_result([])
  File "C:\Users\xxxx.xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 1089, in _non_result
    "This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```
#### Expected Output
Execute without error

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.6.0
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.5.3
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Similar to #20943 - this is not a bug as it is not the intended usage of `read_sql`
