### ISSUE TITLE
Issue with head() on custom dtype

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#21461]
#### Code Sample, a copy-pastable example if possible

```python
class NumPyBackedExtensionArrayMixin(ExtensionArray):
    """
    Geo-Specific Extension Array Mixin
    """
    @property
    def dtype(self):
        """The dtype for this extension array, GeoType"""
        return self._dtype

    @classmethod
    def _constructor_from_sequence(cls, scalars):
        return cls(scalars)

    @classmethod
    def _from_factorized(cls, values, original):
        return cls(values)

    @property
    def shape(self):
        return (len(self.data),)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, *args):
        result = operator.getitem(self.data, *args)
        return result
        #if isinstance(result, tuple):
            #return self._box_scalar(result)
        #elif result.ndim == 0:
            #return self._box_scalar(result.item())
        #else:
            #return type(self)(result)

    def setitem(self, indexer, value):
        """Set the 'value' inplace.
        """

        self[indexer] = value
        return self

    @property
    def nbytes(self):
        return self._itemsize * len(self)

    def _formatting_values(self):
        return np.array(self._format_values(), dtype='object')

    def copy(self, deep=False):
        return type(self)(self.data.copy())

    @classmethod
    def _concat_same_type(cls, to_concat):
        return cls(np.concatenate([array.data for array in to_concat]))

    def tolist(self):
        return self.data.tolist()

    def argsort(self, axis=-1, kind='quicksort', order=None):
        return self.data.argsort()

    def unique(self):
        _, indices = np.unique(self.data, return_index=True)
        data = self.data.take(np.sort(indices))
        return self._from_ndarray(data)


class GeoType(ExtensionDtype):
    name = 'geometry'
    type = Geometry
    kind = 'O'
    _record_type = np.dtype('O')
    na_value = None

    @classmethod
    def construct_from_string(cls, string):
        if string == cls.name:
            return cls()
        else:
            raise TypeError("Cannot construct a '{}' from "
                            "'{}'".format(cls, string))

class GeoArray(NumPyBackedExtensionArrayMixin):
    """Array for Geometry data.
    """
    # What type(s) do we support?
    # MAC-48 or EUI-64?
    _dtype = GeoType()
    _itemsize = 8
    ndim = 1
    can_hold_na = True

    def __init__(self, values, copy=True):
        # TODO: parse hex / strings
        self.data = np.array(values, dtype='O', copy=copy)

    @classmethod
    def _from_ndarray(cls, data, copy=False):
        return cls(data, copy=copy)

    @property
    def na_value(self):
        return self.dtype.na_value

    def __repr__(self):
        formatted = self._format_values()
        return "GeoArray({!r})".format(formatted)
    
    def _format_values(self):
        return [_format(x) for x in self.data]

    @classmethod
    def from_geometry(cls, data, copy=False):
        """"""
        if copy:
            data = data.copy()
        new = GeoArray([])
        new.data = np.array(data)
        return new

    def __setitem__(self, key, value):
        value = Geometry(value)
        self.data[key] = value

    def __iter__(self):
        return iter(self.data.tolist())

    def __eq__(self, other):
        return self.data == other

    def equals(self, other):
        if not isinstance(other, type(self)):
            raise TypeError
        return (self.data == other.data).all()

    def _values_for_factorize(self):
        # Should hit pandas' UInt64Hashtable
        return self, 0

    def isna(self):
        return (self.data == self._dtype.na_value)

    @property
    def _parser(self):
        return lambda x: x

    def take(self, indexer, allow_fill=True, fill_value=None):
        mask = indexer == -1
        result = self.data.take(indexer)
        result[mask] = self.dtype.na_value
        return type(self)(result, copy=False)

    def _formatting_values(self):
        return np.array(self._format_values(), dtype='object')

    @classmethod
    def _concat_same_type(cls, to_concat):
        return cls(np.concatenate([array.data for array in to_concat]))

    def take_nd(self, indexer, allow_fill=True, fill_value=None):
        return self.take(indexer, allow_fill=allow_fill, fill_value=fill_value)

    def copy(self, deep=False):
        return type(self)(self.data.copy())

    from arcgis.geometry import BaseGeometry
    @property
    def is_valid(self):
        """Checks if the Geometry is Valid"""
        return pd.Series([g.is_valid for g in self])

#### TO GET THE ERROR
>>> geoms = [{
  "rings" : [[[-97.06138,32.837],[-97.06133,32.836],[-97.06124,32.834],[-97.06127,32.832],
              [-97.06138,32.837]],[[-97.06326,32.759],[-97.06298,32.755],[-97.06153,32.749],
              [-97.06326,32.759]]],
  "spatialReference" : {"wkid" : 4326}
}
]
>>> v = GeoArray(geoms)
>>> df = pd.DataFrame({"SHAPE": v})
>>> small = df.head(1)
>>> print(small)


```
#### Problem description

Here is where the error occurs with I do a print(df.head(1)) 

``` builtins.AttributeError: 'numpy.ndarray' object has no attribute '_formatting_values'```

```
    def formatting_values(self):
        return self.values._formatting_values()
```

I've implemented the override in the GeoArray, but it doesn't seem to ever get called instead it's calling the `_formatting_values()` on the `ExtensionBlock` class.

Any suggestions on how to resolve this issue?

#### Expected Output

A html version of the dataframe.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252

pandas: 0.23.0
pytest: 3.5.0
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.2
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Can you post the full traceback?

**Comment by achapkowski** [comment]
Sure thing

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\base.py in __repr__(self)
     80         Yields Bytestring in Py2, Unicode String in py3.
     81         """
---> 82         return str(self)
     83 
     84 

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\base.py in __str__(self)
     59 
     60         if compat.PY3:
---> 61             return self.__unicode__()
     62         return self.__bytes__()
     63 

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\frame.py in __unicode__(self)
    661             width = None
    662         self.to_string(buf=buf, max_rows=max_rows, max_cols=max_cols,
--> 663                        line_width=width, show_dimensions=show_dimensions)
    664 
    665         return buf.getvalue()

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, line_width, max_rows, max_cols, show_dimensions)
   1966                                            max_cols=max_cols,
   1967                                            show_dimensions=show_dimensions)
-> 1968         formatter.to_string()
   1969 
   1970         if buf is None:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\format.py in to_string(self)
    609         else:
    610 
--> 611             strcols = self._to_str_columns()
    612             if self.line_width is None:  # no need to wrap around just print
    613                 # the whole frame

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\format.py in _to_str_columns(self)
    544                 header_colwidth = max(self.col_space or 0,
    545                                       *(self.adj.len(x) for x in cheader))
--> 546                 fmt_values = self._format_col(i)
    547                 fmt_values = _make_fixed_width(fmt_values, self.justify,
    548                                                minimum=header_colwidth,

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\format.py in _format_col(self, i)
    719         frame = self.tr_frame
    720         formatter = self._get_formatter(i)
--> 721         values_to_format = frame.iloc[:, i]._formatting_values()
    722         return format_array(values_to_format, formatter,
    723                             float_format=self.float_format, na_rep=self.na_rep,

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\series.py in _formatting_values(self)
    471         and DataFrameFormatter)
    472         """
--> 473         return self._data.formatting_values()
    474 
    475     def get_values(self):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\internals.py in formatting_values(self)
   4748     def formatting_values(self):
   4749         """Return the internal values used by the DataFrame/SeriesFormatter"""
-> 4750         return self._block.formatting_values()
   4751 
   4752     def get_values(self):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\internals.py in formatting_values(self)
   1989 
   1990     def formatting_values(self):
-> 1991         return self.values._formatting_values()
   1992 
   1993     def concat_same_type(self, to_concat, placement=None):

AttributeError: 'numpy.ndarray' object has no attribute '_formatting_values'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\frame.py in _repr_html_(self)
    694 
    695             return self.to_html(max_rows=max_rows, max_cols=max_cols,
--> 696                                 show_dimensions=show_dimensions, notebook=True)
    697         else:
    698             return None

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\frame.py in to_html(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, bold_rows, classes, escape, max_rows, max_cols, show_dimensions, notebook, decimal, border, table_id)
   2032                                            decimal=decimal, table_id=table_id)
   2033         # TODO: a generic formatter wld b in DataFrameFormatter
-> 2034         formatter.to_html(classes=classes, notebook=notebook, border=border)
   2035 
   2036         if buf is None:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\format.py in to_html(self, classes, notebook, border)
    749                                       table_id=self.table_id)
    750         if hasattr(self.buf, 'write'):
--> 751             html_renderer.write_result(self.buf)
    752         elif isinstance(self.buf, compat.string_types):
    753             with open(self.buf, 'w') as f:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\html.py in write_result(self, buf)
    178         indent += self.indent_delta
    179         indent = self._write_header(indent)
--> 180         indent = self._write_body(indent)
    181 
    182         self.write('</table>', indent)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\html.py in _write_body(self, indent)
    334         fmt_values = {}
    335         for i in range(min(len(self.columns), self.max_cols)):
--> 336             fmt_values[i] = self.fmt._format_col(i)
    337 
    338         # write values

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\io\formats\format.py in _format_col(self, i)
    719         frame = self.tr_frame
    720         formatter = self._get_formatter(i)
--> 721         values_to_format = frame.iloc[:, i]._formatting_values()
    722         return format_array(values_to_format, formatter,
    723                             float_format=self.float_format, na_rep=self.na_rep,

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\series.py in _formatting_values(self)
    471         and DataFrameFormatter)
    472         """
--> 473         return self._data.formatting_values()
    474 
    475     def get_values(self):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\internals.py in formatting_values(self)
   4748     def formatting_values(self):
   4749         """Return the internal values used by the DataFrame/SeriesFormatter"""
-> 4750         return self._block.formatting_values()
   4751 
   4752     def get_values(self):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-dev\lib\site-packages\pandas\core\internals.py in formatting_values(self)
   1989 
   1990     def formatting_values(self):
-> 1991         return self.values._formatting_values()
   1992 
   1993     def concat_same_type(self, to_concat, placement=None):

AttributeError: 'numpy.ndarray' object has no attribute '_formatting_values'
```

**Comment by TomAugspurger** [comment]
It seems like your `ExtensionBlock.values` is an ndarray, while it should be an ndarray.

I would take a look at `df._data`.

**Comment by TomAugspurger** [comment]
You might also try subclassing the tests in https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/base/__init__.py, starting with https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/base/constructors.py, to ensure that the data is being handled correctly, before moving on to other methods.

**Comment by achapkowski** [comment]
@TomAugspurger  I'll take a look at `df._data`

**Comment by jorisvandenbossche** [comment]
The original dataframe is correctly constructed (the ExtensionBlock values is still geometry dtype), but not anymore after you subsetted it with `head()`. Which points to a problem in your take or getitem implementation. 
Looking at that, the `__getitem__` returns a plain array, instead of wrapping it again in a GeoArray (take does seem to do it correctly).

Using the tests as @TomAugspurger indicated should indeed normally have catched this (or at least give an indication which parts of the api are still failing)

(sidenote: you are aware of geopandas that (will) implements a GeometryArray?)

**Comment by jorisvandenbossche** [comment]
Closing since I think fixing `getitem` will solve the problem, but feel free to reopen if that is not yet the case! 
Also welcome to provide feedback on the API and workflow to create an ExtensionArray in general.

**Comment by achapkowski** [comment]
@jorisvandenbossche 

I am not aware of GeoPandas efforts, but this isn't for the project, but another GIS venue.

**Comment by achapkowski** [comment]
@jorisvandenbossche @TomAugspurger Thank you for the help fixing the `getitem` resolved my issue.

**Comment by jorisvandenbossche** [comment]
@achapkowski No problem!

> I am not aware of GeoPandas efforts, but this isn't for the project, but another GIS venue.

I only mentioned it to make sure you were aware of it, and not unknowingly duplicating efforts

**Comment by achapkowski** [comment]
@jorisvandenbossche @TomAugspurger So I fixed the get items as suggested, but now I can't use `iloc` to get single row data.

```
    def __getitem__(self, *args):
        result = operator.getitem(self.data, *args)
        if not isinstance(result, GeoArray):
            return GeoArray(result)
        return result
```

I get the following error:

```

Traceback (most recent call last):
  Debug Probe, prompt 236, line 1
  File "d:\SVN\git_hub\ArcGIS\geo_public\geo\_array.py", line 118, in __repr__
    formatted = self._format_values()
  File "d:\SVN\git_hub\ArcGIS\geo_public\geo\_array.py", line 125, in _format_values
    return [_format(x) for x in self.data]
builtins.TypeError: iteration over a 0-d array

```

I can make it work if I put an `if` statement in the GeoArray, but then all the results return as a GeoArray instead of my `Geometry` object.

Any ideas?

**Comment by TomAugspurger** [comment]
Does your extension array pass the indexing tests in
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/base/getitem.py
?

I would focus on passing those, before trying the higher-level things like
formatting, since those use getitem internally.
