### ISSUE TITLE
BUG: PeriodIndex comparisons break on listlike

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21793]
```
idx = pd.period_range('2016', periods=3, freq='M')

>>> idx == idx.values
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pandas/core/indexes/period.py", line 107, in wrapper
    other = Period(other, freq=self.freq)
  File "pandas/_libs/tslibs/period.pyx", line 1777, in pandas._libs.tslibs.period.Period.__new__
TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by mroeschke** [comment]
This looks to work on master now. Could use a test

```
In [56]: pd.__version__
Out[56]: '1.1.0.dev0+1536.ga7fb88fd5'

In [57]: idx == idx.values
Out[57]: array([ True,  True,  True])
```
