### ISSUE TITLE
Conflict with anaconda's gcc

### ISSUE THREAD

**Issue by fujiisoup** [pandas-dev/pandas#21929]
#### Code Sample, a copy-pastable example if possible

Importing pandas==0.23 with Anaconda's gcc environment raises an ImportError.

In order to reproduce
```
conda install gcc pandas
python -c "import pandas"
```
which results in

```
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/series.py", line 3981, in <module>
    Series._add_series_or_dataframe_operations()
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/generic.py", line 8897, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  File "/home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/core/window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: /home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/_libs/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/keisukefujii/anaconda3/envs/fac/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so)
```

I confirmed that with pandas==0.22, there is no problem.

I think it is an issue around cython, but I am not sure what changes in pandas causes this problem.
I also tried to update / downdate cython, but it did not solve this problem.

#### Problem description

Should not raise an Error.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-130-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.6.2
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: None
pyarrow: None
xarray: 0.10.7
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
>>> 

</details>

**Comment by chris-b1** [comment]
ref
https://github.com/ContinuumIO/anaconda-issues/issues/5191

**Comment by fujiisoup** [comment]
I didn't notice that anaconda's gcc is deprecated.
I clean installed `gcc_linux-64` and found newest pandas can be successfully installed.
Thanks for the support.
