### ISSUE TITLE
TypeError: cannot convert datetimelike to dtype [datetime64[s]]

### ISSUE THREAD

**Issue by alvaromorono** [pandas-dev/pandas#22292]
#### This is part of the function that generates the warning 

``` 
    data = urllib.request.urlopen(dataLink)
    data = data.read().decode("utf-8")
    data = json.loads(data)
    
    data = data["btc_usd"]
    data = pd.DataFrame(data)
    
    buys = data[(data['type']=="bid")]
    buys["datestamp"] = np.array(buys["timestamp"]).astype("datetime64[s]")
    buyDates = (buys["datestamp"]).tolist()
    
    sells = data[(data['type']=="ask")]
    sells["datestamp"] = np.array(sells["timestamp"]).astype("datetime64[s]")
    sellDates = (sells["datestamp"]).tolist()
    
    a.clear()
    a.plot_date(buyDates, buys["price"])
    a.plot_date(sellDates, sells["price"])
```
#### Problem description - It throws me this warning

```
__main__:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
__main__:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```

-----------------------------------------------------------------------------------------------------------------
#### As far as I understand, all I had to do is to use .loc this way:
``` 
    buys = data[(data['type']=="bid")]
    buys.loc[:, "datestamp"] = np.array(buys["timestamp"]).astype("datetime64[s]")
    buyDates = (buys["datestamp"]).tolist()
    

    sells = data[(data['type']=="ask")]
    sells.loc[:, "datestamp"] = np.array(sells["timestamp"]).astype("datetime64[s]")
    sellDates = (sells["datestamp"]).tolist()
```
However, if I run that I get this error:

```
Traceback (most recent call last):
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\animation.py", line 1081, in _start
    self._init_draw()
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\animation.py", line 1792, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\animation.py", line 1814, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "<ipython-input-2-71112d20e664>", line 36, in animate
    buys.loc[:, "datestamp"] = np.array(buys["timestamp"]).astype("datetime64[s]")
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 189, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 362, in _setitem_with_indexer
    self.obj[key] = _infer_fill_value(value)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3194, in _set_item
    value = self._sanitize_column(key, value)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3411, in _sanitize_column
    value = maybe_cast_to_datetime(value, value.dtype)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1001, in maybe_cast_to_datetime
    "dtype [{dtype}]".format(dtype=dtype))
TypeError: cannot convert datetimelike to dtype [datetime64[s]]
```
Up to this point I am completely lost and I would really apreciate If anyone could answer this post with the code above modified, so that the warning and the error don´t appear anymore.

Also if I did something wrong when using .loc PLEASE let me now so that I can change it and avoid any errors 

Note: I am using Python 3.5, and I can´t upgrade it nor downgrade it for various reasons, and this is part of a tutorial in Python 3.4

**Comment by jreback** [comment]
this is clearly showing an expected warning
you can ask on SO if you want but please read the docs

**Comment by alvaromorono** [comment]
I also tried:
```
pd.options.mode.chained_assignment = None
```
After pandas had been imported and it seems to work, but sometimes it throws this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\amoro\Anaconda3\lib\tkinter\__init__.py", line 1558, in __call__
    return self.func(*args)
  File "C:\Users\amoro\Anaconda3\lib\tkinter\__init__.py", line 605, in callit
    func(*args)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1097, in __call__
    self.refresh()
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1117, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\dates.py", line 875, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\dates.py", line 466, in num2date
    return _from_ordinalf(x, tz)
  File "C:\Users\amoro\Anaconda3\lib\site-packages\matplotlib\dates.py", line 279, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1
```

Could anyone help please?
