### ISSUE TITLE
Cannot import pandas after building from source

### ISSUE THREAD

**Issue by pulkitmaloo** [pandas-dev/pandas#22507]
#### Code Sample, a copy-pastable example if possible

```bash
(pandas-dev) pulkitmaloo@Pulkits-MacBook-Pro ~/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/core (master)
$ git pull upstream master --ff-only
From https://github.com/pandas-dev/pandas
 * branch                master     -> FETCH_HEAD
Already up to date.
(pandas-dev) pulkitmaloo@Pulkits-MacBook-Pro ~/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/core (master)
$ python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "/Users/pulkitmaloo/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/Users/pulkitmaloo/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/_libs/__init__.py", line 4, in <module>
    from .tslibs import (
  File "/Users/pulkitmaloo/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/_libs/tslibs/__init__.py", line 4, in <module>
    from .conversion import normalize_date, localize_pydatetime, tz_convert_single
ImportError: cannot import name 'normalize_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pulkitmaloo/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'normalize_date' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
>>>

```
#### Output of ``pd.show_versions()``

<details>

</details>

**Comment by mroeschke** [comment]
You need to build the C extensions: `python setup.py build_ext --inplace --force`

**Comment by pulkitmaloo** [comment]
I tried to run the command `python setup.py build_ext --inplace --force` which led me to the following error 

```
gcc -bundle -undefined dynamic_lookup -L/Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib -arch x86_64 -L/Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/pandas/_libs/groupby.o -o /Users/pulkitmaloo/Box Sync/Workspace/Github/Open-Source/pandas-pulkitmaloo/pandas/_libs/groupby.cpython-36m-darwin.so
building 'pandas._libs.hashing' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/pulkitmaloo/anaconda3/envs/pandas-dev/include -arch x86_64 -I/Users/pulkitmaloo/anaconda3/envs/pandas-dev/include -arch x86_64 -I/Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib/python3.6/site-packages/numpy/core/include -I/Users/pulkitmaloo/anaconda3/envs/pandas-dev/include/python3.6m -c pandas/_libs/hashing.c -o build/temp.macosx-10.7-x86_64-3.6/pandas/_libs/hashing.o -Wno-unused-function
In file included from pandas/_libs/hashing.c:525:
In file included from /Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:
/Users/pulkitmaloo/anaconda3/envs/pandas-dev/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "
      "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
pandas/_libs/hashing.c:528:10: fatal error: 'numpy_helper.h' file not found
#include "numpy_helper.h"
         ^~~~~~~~~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by TomAugspurger** [comment]
Can you try with a clean directory?


```
git clean -xdf
python setup.py build_ext -i
```

If that fails, what version of Cython and NumPy do you have?

**Comment by pulkitmaloo** [comment]
Thank you. This worked.
