### ISSUE TITLE
pandas fails to install if Cython is not installed

### ISSUE THREAD

**Issue by UnitedMarsupials** [pandas-dev/pandas#22757]
#### Problem description
Trying to install pandas using pip3 (and Python-3.6.6), I get:
```
% pip3 install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/e9/ad/5e92ba493eff96055a23b0a1323a9a803af71ec859ae3243ced86fcbd0a4/pandas-0.23.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xaf0phg7/pandas/setup.py", line 38, in <module>
        ver = Cython.__version__
    AttributeError: module 'Cython' has no attribute '__version__'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xaf0phg7/pandas/
```
Note, that Cython is available -- the version installed with Python itself, not as a pip. The work-around is to `pip3 install Cython` first:
```
% pip3 install Cython
Collecting Cython
  Downloading https://files.pythonhosted.org/packages/21/89/ca320e5b45d381ae0df74c4b5694f1471c1b2453c5eb4bac3449f5970481/Cython-0.28.5.tar.gz (1.9MB)
    100% |################################| 1.9MB 4.0MB/s 
Installing collected packages: Cython
  Running setup.py install for Cython ... done
Successfully installed Cython-0.28.5
% pip3 install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/e9/ad/5e92ba493eff96055a23b0a1323a9a803af71ec859ae3243ced86fcbd0a4/pandas-0.23.4.tar.gz
Collecting python-dateutil>=2.5.0 (from pandas)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.9.0 in /prod/pfe/local/lib/python3.6/site-packages (from pandas) (1.15.1)
Requirement already satisfied: six>=1.5 in /prod/pfe/local/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)
Installing collected packages: python-dateutil, pytz, pandas
  Running setup.py install for pandas ... done
Successfully installed pandas-0.23.4 python-dateutil-2.7.3 pytz-2018.5
```
but it should not be necessary, should it be? And if for some reason it _is_ necessary, pandas needs to explicitly require it...

**Comment by chris-b1** [comment]
You're right that Cython isn't required for install, only dev.

That check is guarded in a try block after a Cython import - possible you had an old or otherwise incomplete install?  Standard python installations shouldn't ship with Cython 
https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/setup.py#L38

**Comment by alimcmaster1** [comment]
Yes I would try in a fresh virtual env here.

**Comment by UnitedMarsupials** [comment]
> That check is guarded in a try block

But it is only guarded against `ImportError`, not `AttributeError`...

> possible you had an old or otherwise incomplete install?

It may be possible, I guess...

> Standard python installations shouldn't ship with Cython

Ok, am I _gaining_ anything -- such as speedier pandas -- from having it?

> Yes I would try in a fresh virtual env here.

There is no virtual environment in use.

**Comment by UnitedMarsupials** [comment]
RedHat-6 -- with a cutstom-built Python-3.6.6

> env SHELL=sh tmp/bin/python -m pip install --no-binary pandas pandas

Yes, it worked:
```
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/e9/ad/5e92ba493eff96055a23b0a1323a9a803af71ec859ae3243ced86fcbd0a4/pandas-0.23.4.tar.gz
Collecting python-dateutil>=2.5.0 (from pandas)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from pandas)
  Using cached https://files.pythonhosted.org/packages/65/ab/4dfcc20234fae12ee40c714b98077d6e3a10652496bd1488fa4828529b22/numpy-1.15.1.zip
Collecting six>=1.5 (from python-dateutil>=2.5.0->pandas)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, pytz, numpy, pandas
  Running setup.py install for numpy ... done
  Running setup.py install for pandas ... done
Successfully installed numpy-1.15.1 pandas-0.23.4 python-dateutil-2.7.3 pytz-2018.5 six-1.11.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by TomAugspurger** [comment]
OK, then things seem to be fine from pandas' end. There must be something in your other environment that's messing things up. Let us know if you find a solution.

**Comment by qiujiangkun** [comment]
A fresh install of AWS CentOS 8 Stream aarch64 will cause the problem.
```shell
sudo dnf install python3
sudo pip3 install pandas
```
but it doesn't matter

**Comment by Anton-Velikodnyy** [comment]
When I encountered this error with a docker install I did `pip3 install pandas==1.0.5` and it worked
