### ISSUE TITLE
iloc bug / memory error

### ISSUE THREAD

**Issue by mtaboga** [pandas-dev/pandas#22999]
I am using Pandas version '0.23.4' with IPython 6.5.0 and Python 3.6 on a Windows 7 pc.
I have a very large dataframe df, but plenty of free ram.
When i do
`c=df.iloc[1:10,:]`
everything works fine, but when I do 
`c=df.iloc[1,:]`
I get a memory error. See below:

Traceback (most recent call last):

  File "<ipython-input-28-4f47c9ad2dd2>", line 1, in <module>
    c=df_train.iloc[1,:]

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\indexing.py", line 2029, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=axis)

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\indexing.py", line 2104, in _getitem_axis
    return self._get_loc(key, axis=axis)

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\indexing.py", line 145, in _get_loc
    return self.obj._ixs(key, axis=axis)

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\frame.py", line 2616, in _ixs
    new_values = self._data.fast_xs(i)

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\internals.py", line 4068, in fast_xs
    result = self._interleave()

  File "C:\Anaconda\envs\py36\lib\site-packages\pandas\core\internals.py", line 3960, in _interleave
    result = np.empty(self.shape, dtype=dtype)

MemoryError

**Comment by troels** [comment]
Hmm... Are you running 64-bit or 32-bit python? (you can tell, by e.g.:)
```
import sys
print('64-bit' if sys.maxsize > 2**32 else '32-bit')
```

If it's 32-bit you might get around the error by using 64-bit version instead. 

Still it's rather strange that Pandas wants to do a large allocation in the second case, but not the first. There is probably something there that could be improved.

**Comment by mtaboga** [comment]
Hi! It's 64-bit.

**Comment by Akmazad** [comment]
Hi,
Any update on this? I'm also using 64-bit and having similar error. Here's my try to provide the reproducible:
===
import sys
import pandas as pd

if __name__ == '__main__':
    df = pd.read_csv("myData.dat")

    print("load complete")
    bpLength = len(df["dna.seq"][0])
    train_df = df[df['chr'] != 'chr1']
    rows = df.shape[0]

    endIndex = 1000
    values = df["dna.seq"][0:endIndex].apply(lambda x: pd.Series(list(x)))  # make a matrix of neucleotides

    classes_acc = df.iloc[:, 6:8][0:endIndex]
    classes_rnaSeq = df.iloc[:, 8:9][0:endIndex]
    classes_tf = df.iloc[:, 9:][0:endIndex]
    classes_acc_rnaSeq = df.iloc[:, 6:9][0:endIndex]
    classes_rnaSeq_tf = df.iloc[:, 8:][0:endIndex]
    classes_all = df.iloc[:, 6:][0:endIndex]

    print("slicing complete!")
====
Error:
Traceback (most recent call last):
  File "C:/Users/Azad/.PyCharmCE2018.3/config/scratches/scratch_1.py", line 19, in <module>
    classes_rnaSeq_tf = df.iloc[:, 8:][0:endIndex]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2159, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=axis)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2210, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2180, in _get_slice_axis
    return self._slice(slice_obj, axis=axis, kind='iloc')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 151, in _slice
    return self.obj._slice(obj, axis=axis, kind=kind)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3162, in _slice
    result = self._constructor(self._data.get_slice(slobj, axis=axis))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 689, in get_slice
    new_blocks = self._slice_take_blocks_ax0(slobj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1312, in _slice_take_blocks_ax0
    fill_tuple=None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 1234, in take_nd
    allow_fill=False, fill_value=fill_value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py", line 1651, in take_nd
    out = np.empty(out_shape, dtype=dtype)
MemoryError

**Comment by jreback** [comment]
reproducible example means you can just copy paste code; a file that i cannot see is useless
