### ISSUE TITLE
Install numpy and cython when you run make  if they were not present 

### ISSUE THREAD

**Issue by srinivasreddy** [pandas-dev/pandas#23920]
I created a new virtual env  and run `make`, the installation exited with saying 
```
02:31 $ make
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "/home/dtdev/.virtualenvs/pandas/lib/python3.6/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 727, in <module>
    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
  File "setup.py", line 470, in maybe_cythonize
    numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
  File "/home/dtdev/.virtualenvs/pandas/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1142, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/home/dtdev/.virtualenvs/pandas/lib/python3.6/site-packages/pkg_resources/__init__.py", line 359, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'numpy'
```
then installed `numpy`, then ran make again,

```
02:31 $ make
python setup.py build_ext --inplace
running build_ext
pandas._libs.algos: -> [['pandas/_libs/algos.c']]
Traceback (most recent call last):
  File "setup.py", line 738, in <module>
    **setuptools_kwargs)
  File "/home/dtdev/.virtualenvs/pandas/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 366, in build_extensions
    self.check_cython_extensions(self.extensions)
  File "setup.py", line 363, in check_cython_extensions
    """.format(src=src))
Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                Cython is required to compile pandas from a development branch.
                Please install Cython or download a release package of pandas.
```

Why not install numpy and cython if they were not present ?  

I think we should fix the Makefile .

**Comment by gfyoung** [comment]
That seems reasonable.  Or at the very least, do some dependency checking and provide nicer error messages than the ones you're showing here.

**Comment by TomAugspurger** [comment]
The question is how should you install them? pip, conda, other?

I think we can provide targets for building a dev environment via conda or the requirements-dev.txt.

**Comment by jbrockmendel** [comment]
I don't think we should spend a lot of effort in figuring out of a user (dev) is using pip vs conda.  If someone is using make, they should have a fairly good idea what they're doing.  @srinivasreddy did you have a particular change in mind you'd like to add to the makefile?
