### ISSUE TITLE
BLD/CI: conda cannot resolve two azure environments

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#24564]
Noticed this in two PRs, also on the two latest commits on master:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6360
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6368
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6366
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6363

@jreback @TomAugspurger @datapythonista 

Error log:
<details>

```
2019-01-02T18:40:17.7324141Z ##[section]Starting: Before Install
2019-01-02T18:40:17.7327525Z ==============================================================================
2019-01-02T18:40:17.7327628Z Task         : Command Line
2019-01-02T18:40:17.7327726Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-01-02T18:40:17.7327826Z Version      : 2.142.2
2019-01-02T18:40:17.7327895Z Author       : Microsoft Corporation
2019-01-02T18:40:17.7327991Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-01-02T18:40:17.7328096Z ==============================================================================
2019-01-02T18:40:19.4264876Z Generating script.
2019-01-02T18:40:19.4364403Z Script contents:
2019-01-02T18:40:19.4372263Z ci\\incremental\\setup_conda_environment.cmd
2019-01-02T18:40:19.5002033Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ad60c1a4-5ff9-487d-b98e-949d069780ca.cmd""
2019-01-02T18:40:19.5122315Z 
2019-01-02T18:40:19.5122782Z D:\a\1\s>call deactivate 
2019-01-02T18:40:28.1808784Z 
2019-01-02T18:40:28.1809524Z D:\a\1\s>conda list 
2019-01-02T18:40:42.5276089Z # packages in environment at C:\Miniconda:
2019-01-02T18:40:42.5276638Z #
2019-01-02T18:40:42.5276874Z # Name                    Version                   Build  Channel
2019-01-02T18:40:42.5277087Z asn1crypto                0.24.0                   py37_0  
2019-01-02T18:40:42.5277286Z ca-certificates           2018.03.07                    0  
2019-01-02T18:40:42.5277470Z certifi                   2018.8.24                py37_1  
2019-01-02T18:40:42.5277666Z cffi                      1.11.5           py37h74b6da3_1  
2019-01-02T18:40:42.5277864Z chardet                   3.0.4                    py37_1  
2019-01-02T18:40:42.5278059Z conda                     4.5.11                   py37_0  
2019-01-02T18:40:42.5278240Z conda-env                 2.6.0                         1  
2019-01-02T18:40:42.5278482Z console_shortcut          0.1.1                         3  
2019-01-02T18:40:42.5279073Z cryptography              2.3.1            py37h74b6da3_0  
2019-01-02T18:40:42.5279335Z idna                      2.7                      py37_0  
2019-01-02T18:40:42.5279552Z menuinst                  1.4.14           py37hfa6e2cd_0  
2019-01-02T18:40:42.5279753Z openssl                   1.0.2p               hfa6e2cd_0  
2019-01-02T18:40:42.5279967Z pip                       10.0.1                   py37_0  
2019-01-02T18:40:42.5280186Z pycosat                   0.6.3            py37hfa6e2cd_0  
2019-01-02T18:40:42.5280403Z pycparser                 2.18                     py37_1  
2019-01-02T18:40:42.5280604Z pyopenssl                 18.0.0                   py37_0  
2019-01-02T18:40:42.5280820Z pysocks                   1.6.8                    py37_0  
2019-01-02T18:40:42.5281033Z python                    3.7.0                hea74fb7_0  
2019-01-02T18:40:42.5281260Z pywin32                   223              py37hfa6e2cd_1  
2019-01-02T18:40:42.5281485Z requests                  2.19.1                   py37_0  
2019-01-02T18:40:42.5281684Z ruamel_yaml               0.15.46          py37hfa6e2cd_0  
2019-01-02T18:40:42.5281895Z setuptools                40.2.0                   py37_0  
2019-01-02T18:40:42.5282108Z six                       1.11.0                   py37_1  
2019-01-02T18:40:42.5282558Z urllib3                   1.23                     py37_0  
2019-01-02T18:40:42.5282753Z vc                        14                   h0510ff6_3  
2019-01-02T18:40:42.5282955Z vs2015_runtime            14.0.25123                    3  
2019-01-02T18:40:42.5283157Z wheel                     0.31.1                   py37_0  
2019-01-02T18:40:42.5283354Z win_inet_pton             1.0.1                    py37_1  
2019-01-02T18:40:42.5283547Z wincertstore              0.2                      py37_0  
2019-01-02T18:40:42.5283999Z yaml                      0.1.7                hc54c509_2  
2019-01-02T18:40:42.5741388Z 
2019-01-02T18:40:42.5744045Z D:\a\1\s>conda remove --all -q -y -n pandas-dev 
2019-01-02T18:40:43.5472657Z 
2019-01-02T18:40:43.5473087Z D:\a\1\s>conda env create --file=ci\deps\azure-windows-36.yaml 
2019-01-02T18:40:57.1976820Z Solving environment: ...working... failed
2019-01-02T18:40:57.4366039Z 
2019-01-02T18:40:57.4366771Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2019-01-02T18:40:57.4366905Z 
2019-01-02T18:40:57.4367069Z     Traceback (most recent call last):
2019-01-02T18:40:57.4367255Z       File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 819, in __call__
2019-01-02T18:40:57.4367741Z         return func(*args, **kwargs)
2019-01-02T18:40:57.4367999Z       File "C:\Miniconda\lib\site-packages\conda_env\cli\main.py", line 74, in do_call
2019-01-02T18:40:57.4368237Z         exit_code = getattr(module, func_name)(args, parser)
2019-01-02T18:40:57.4368503Z       File "C:\Miniconda\lib\site-packages\conda_env\cli\main_create.py", line 108, in execute
2019-01-02T18:40:57.4368746Z         installer.install(prefix, pkg_specs, args, env)
2019-01-02T18:40:57.4368992Z       File "C:\Miniconda\lib\site-packages\conda_env\installers\conda.py", line 35, in install
2019-01-02T18:40:57.4369214Z         unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
2019-01-02T18:40:57.4369456Z       File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 518, in solve_for_transaction
2019-01-02T18:40:57.4369674Z         force_remove, force_reinstall)
2019-01-02T18:40:57.4369890Z       File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 451, in solve_for_diff
2019-01-02T18:40:57.4370125Z         final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
2019-01-02T18:40:57.4370344Z       File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state
2019-01-02T18:40:57.4370574Z         index, r = self._prepare(prepared_specs)
2019-01-02T18:40:57.4370793Z       File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 592, in _prepare
2019-01-02T18:40:57.4371188Z         self.subdirs, prepared_specs)
2019-01-02T18:40:57.4371509Z       File "C:\Miniconda\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
2019-01-02T18:40:57.4371684Z         new_records = query_all(spec)
2019-01-02T18:40:57.4372033Z       File "C:\Miniconda\lib\site-packages\conda\core\index.py", line 184, in query_all
2019-01-02T18:40:57.4372222Z         return tuple(concat(future.result() for future in as_completed(futures)))
2019-01-02T18:40:57.4372403Z       File "C:\Miniconda\lib\site-packages\conda\core\subdir_data.py", line 95, in query
2019-01-02T18:40:57.4372553Z         self.load()
2019-01-02T18:40:57.4372723Z       File "C:\Miniconda\lib\site-packages\conda\core\subdir_data.py", line 149, in load
2019-01-02T18:40:57.4372892Z         _internal_state = self._load()
2019-01-02T18:40:57.4373246Z       File "C:\Miniconda\lib\site-packages\conda\core\subdir_data.py", line 246, in _load
2019-01-02T18:40:57.4373436Z         _internal_state = self._process_raw_repodata_str(raw_repodata_str)
2019-01-02T18:40:57.4373609Z       File "C:\Miniconda\lib\site-packages\conda\core\subdir_data.py", line 374, in _process_raw_repodata_str
2019-01-02T18:40:57.4373802Z         package_record = PackageRecord(**info)
2019-01-02T18:40:57.4373989Z       File "C:\Miniconda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __call__
2019-01-02T18:40:57.4374173Z         instance = super(EntityType, cls).__call__(*args, **kwargs)
2019-01-02T18:40:57.4374352Z       File "C:\Miniconda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 736, in __init__
2019-01-02T18:40:57.4501407Z         setattr(self, key, kwargs[key])
2019-01-02T18:40:57.4501860Z       File "C:\Miniconda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 427, in __set__
2019-01-02T18:40:57.4502420Z         instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
2019-01-02T18:40:57.4503339Z       File "C:\Miniconda\lib\site-packages\conda\models\records.py", line 102, in box
2019-01-02T18:40:57.4503522Z         val = tuple(f for f in (ff.strip() for ff in val) if f)
2019-01-02T18:40:57.4503686Z     TypeError: 'NoneType' object is not iterable
2019-01-02T18:40:57.4503802Z 
2019-01-02T18:40:57.4504025Z `$ C:\Miniconda\Scripts\conda-env create --file=ci\deps\azure-windows-36.yaml`
2019-01-02T18:40:57.4504158Z 
2019-01-02T18:40:57.4504292Z   environment variables:
2019-01-02T18:40:57.4504459Z          ANDROID_NDK_PATH=C:\Microsoft\AndroidNDK64\android-ndk-r15c
2019-01-02T18:40:57.4504616Z BUILD_REPOSITORY_LOCALPATH=D:\a\1\s
2019-01-02T18:40:57.4504765Z                  CIO_TEST=<not set>
2019-01-02T18:40:57.4504906Z                 CLASSPATH=.;
2019-01-02T18:40:57.4505056Z                     CONDA=C:\Miniconda
2019-01-02T18:40:57.4505203Z   CONDA_AUTO_UPDATE_CONDA=false
2019-01-02T18:40:57.4505377Z             CONDA_INSTALL=cmd /C conda install -q -y
2019-01-02T18:40:57.4505532Z                  CONDA_PY=36
2019-01-02T18:40:57.4505694Z                CONDA_ROOT=C:\Miniconda
2019-01-02T18:40:57.4505853Z                  HOMEPATH=\Users\VssAdministrator
2019-01-02T18:40:57.4506026Z                      PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\agents\2.144.0\externals\git\cmd;
2019-01-02T18:40:57.4506199Z                           C:\tools\mingw64\bin;C:\Program
2019-01-02T18:40:57.4506366Z                           Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\jdk1.8.0
2019-01-02T18:40:57.4506548Z                           _181\bin;C:\npm\prefix;C:\hostedtoolcache\windows\Ruby\2.5.0\x64\bin;C
2019-01-02T18:40:57.4506724Z                           :\Go1.11\bin;C:\Program Files\Git\bin;C:\Program
2019-01-02T18:40:57.4506897Z                           Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files
2019-01-02T18:40:57.4507087Z                           (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Microsoft
2019-01-02T18:40:57.4507927Z                           Visual Studio\Shared\Python36_64\Scripts;C:\Program Files
2019-01-02T18:40:57.4508173Z                           (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program
2019-01-02T18:40:57.4508400Z                           Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\Sys
2019-01-02T18:40:57.4508629Z                           tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\
2019-01-02T18:40:57.4508849Z                           Chocolatey\bin;C:\Program Files\Docker;C:\Program
2019-01-02T18:40:57.4509055Z                           Files\dotnet\;C:\Program Files\Microsoft SQL
2019-01-02T18:40:57.4509273Z                           Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
2019-01-02T18:40:57.4509502Z                           Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
2019-01-02T18:40:57.4509733Z                           Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
2019-01-02T18:40:57.4509954Z                           Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
2019-01-02T18:40:57.4510172Z                           Server\140\DTS\Binn\;C:\Program Files\Microsoft Service
2019-01-02T18:40:57.4510397Z                           Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service
2019-01-02T18:40:57.4510622Z                           Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program
2019-01-02T18:40:57.4511059Z                           Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program
2019-01-02T18:40:57.4511425Z                           Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\VssAdministrator\App
2019-01-02T18:40:57.4511593Z                           Data\Local\Microsoft\WindowsApps
2019-01-02T18:40:57.4511761Z              PSMODULEPATH=C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules;C:\Progr
2019-01-02T18:40:57.4512088Z                           am Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShe
2019-01-02T18:40:57.4512532Z                           ll\v1.0\Modules;C:\Program Files\Microsoft SQL
2019-01-02T18:40:57.4512693Z                           Server\130\Tools\PowerShell\Modules\
2019-01-02T18:40:57.4512865Z               PYTHON_HOME=C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
2019-01-02T18:40:57.4513027Z        REQUESTS_CA_BUNDLE=<not set>
2019-01-02T18:40:57.4513179Z             SSL_CERT_FILE=<not set>
2019-01-02T18:40:57.4513290Z 
2019-01-02T18:40:57.4513435Z      active environment : None
2019-01-02T18:40:57.4513596Z        user config file : C:\Users\VssAdministrator\.condarc
2019-01-02T18:40:57.4513744Z  populated config files : 
2019-01-02T18:40:57.4513891Z           conda version : 4.5.11
2019-01-02T18:40:57.4514040Z     conda-build version : not installed
2019-01-02T18:40:57.4514191Z          python version : 3.7.0.final.0
2019-01-02T18:40:57.4514363Z        base environment : C:\Miniconda  (writable)
2019-01-02T18:40:57.4514528Z            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
2019-01-02T18:40:57.4514696Z                           https://repo.anaconda.com/pkgs/main/noarch
2019-01-02T18:40:57.4514865Z                           https://repo.anaconda.com/pkgs/free/win-64
2019-01-02T18:40:57.4515033Z                           https://repo.anaconda.com/pkgs/free/noarch
2019-01-02T18:40:57.4515191Z                           https://repo.anaconda.com/pkgs/r/win-64
2019-01-02T18:40:57.4515357Z                           https://repo.anaconda.com/pkgs/r/noarch
2019-01-02T18:40:57.4515521Z                           https://repo.anaconda.com/pkgs/pro/win-64
2019-01-02T18:40:57.4515686Z                           https://repo.anaconda.com/pkgs/pro/noarch
2019-01-02T18:40:57.4516025Z                           https://repo.anaconda.com/pkgs/msys2/win-64
2019-01-02T18:40:57.4516190Z                           https://repo.anaconda.com/pkgs/msys2/noarch
2019-01-02T18:40:57.4516344Z           package cache : C:\Miniconda\pkgs
2019-01-02T18:40:57.4516674Z                           C:\Users\VssAdministrator\AppData\Local\conda\conda\pkgs
2019-01-02T18:40:57.4516828Z        envs directories : C:\Miniconda\envs
2019-01-02T18:40:57.4516975Z                           C:\Users\VssAdministrator\AppData\Local\conda\conda\envs
2019-01-02T18:40:57.4517130Z                           C:\Users\VssAdministrator\.conda\envs
2019-01-02T18:40:57.4517274Z                platform : win-64
2019-01-02T18:40:57.4517799Z              user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.14393
2019-01-02T18:40:57.4518055Z           administrator : True
2019-01-02T18:40:57.4518237Z              netrc file : None
2019-01-02T18:40:57.4518421Z            offline mode : False
2019-01-02T18:40:57.4518566Z 
2019-01-02T18:40:57.4518694Z 
2019-01-02T18:40:57.4518881Z An unexpected error has occurred. Conda has prepared the above report.
2019-01-02T18:40:57.4519099Z If submitted, this report will be used by core maintainers to improve
2019-01-02T18:40:57.4519302Z future releases of conda.
2019-01-02T18:40:57.4519497Z Would you like conda to send this report to the core maintainers?
2019-01-02T18:40:57.4519687Z [y/N]: 
2019-01-02T18:40:57.4519867Z No report sent. To permanently opt-out, use
2019-01-02T18:40:57.4520007Z 
2019-01-02T18:40:57.4520185Z     $ conda config --set report_errors false
2019-01-02T18:40:57.4520324Z 
2019-01-02T18:40:57.7688456Z 
2019-01-02T18:40:57.7689272Z D:\a\1\s>call activate pandas-dev 
2019-01-02T18:40:57.9957099Z Could not find conda environment: pandas-dev
2019-01-02T18:40:57.9958179Z You can list all discoverable environments with `conda info --envs`.
2019-01-02T18:40:57.9958421Z 
2019-01-02T18:40:58.0177642Z 
2019-01-02T18:40:58.0178197Z D:\a\1\s>conda list 
2019-01-02T18:40:58.4726844Z # packages in environment at C:\Miniconda:
2019-01-02T18:40:58.4727632Z #
2019-01-02T18:40:58.4728290Z # Name                    Version                   Build  Channel
2019-01-02T18:40:58.4728723Z asn1crypto                0.24.0                   py37_0  
2019-01-02T18:40:58.4728927Z ca-certificates           2018.03.07                    0  
2019-01-02T18:40:58.4729145Z certifi                   2018.8.24                py37_1  
2019-01-02T18:40:58.4729357Z cffi                      1.11.5           py37h74b6da3_1  
2019-01-02T18:40:58.4729569Z chardet                   3.0.4                    py37_1  
2019-01-02T18:40:58.4729766Z conda                     4.5.11                   py37_0  
2019-01-02T18:40:58.4729985Z conda-env                 2.6.0                         1  
2019-01-02T18:40:58.4730198Z console_shortcut          0.1.1                         3  
2019-01-02T18:40:58.4730409Z cryptography              2.3.1            py37h74b6da3_0  
2019-01-02T18:40:58.4730617Z idna                      2.7                      py37_0  
2019-01-02T18:40:58.4730824Z menuinst                  1.4.14           py37hfa6e2cd_0  
2019-01-02T18:40:58.4731045Z openssl                   1.0.2p               hfa6e2cd_0  
2019-01-02T18:40:58.4731270Z pip                       10.0.1                   py37_0  
2019-01-02T18:40:58.4731633Z pycosat                   0.6.3            py37hfa6e2cd_0  
2019-01-02T18:40:58.4731972Z pycparser                 2.18                     py37_1  
2019-01-02T18:40:58.4732162Z pyopenssl                 18.0.0                   py37_0  
2019-01-02T18:40:58.4732348Z pysocks                   1.6.8                    py37_0  
2019-01-02T18:40:58.4732537Z python                    3.7.0                hea74fb7_0  
2019-01-02T18:40:58.4732723Z pywin32                   223              py37hfa6e2cd_1  
2019-01-02T18:40:58.4732892Z requests                  2.19.1                   py37_0  
2019-01-02T18:40:58.4733078Z ruamel_yaml               0.15.46          py37hfa6e2cd_0  
2019-01-02T18:40:58.4733269Z setuptools                40.2.0                   py37_0  
2019-01-02T18:40:58.4733465Z six                       1.11.0                   py37_1  
2019-01-02T18:40:58.4733642Z urllib3                   1.23                     py37_0  
2019-01-02T18:40:58.4733829Z vc                        14                   h0510ff6_3  
2019-01-02T18:40:58.4734018Z vs2015_runtime            14.0.25123                    3  
2019-01-02T18:40:58.4734205Z wheel                     0.31.1                   py37_0  
2019-01-02T18:40:58.4734393Z win_inet_pton             1.0.1                    py37_1  
2019-01-02T18:40:58.4734562Z wincertstore              0.2                      py37_0  
2019-01-02T18:40:58.4734749Z yaml                      0.1.7                hc54c509_2  
2019-01-02T18:40:58.5180660Z 
2019-01-02T18:40:58.5181631Z D:\a\1\s>if 0 NEQ 0 exit /b 0 
2019-01-02T18:40:58.5796216Z ##[section]Finishing: Before Install
```

</details>

.
As a side issue, this error does not correctly fail the `Before Install` step, and only fails in `Build` because `numpy` is not available...

**Comment by TomAugspurger** [comment]
Both https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6360 and https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6359 use conda 4.5.11. So possibly something with the repodata.

**Comment by jreback** [comment]
cc @datapythonista

**Comment by TomAugspurger** [comment]
I think this is on the anaconda side. They're working on it.

**Comment by TomAugspurger** [comment]
https://github.com/conda/conda/issues/8051

**Comment by jreback** [comment]
shall we fix conda version?

**Comment by TomAugspurger** [comment]
This has been fixed upstream. I restarted https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6377 and it seems to be running OK.

Ping if you want a build restarted. @h-vetinari I did https://github.com/pandas-dev/pandas/pull/23723

**Comment by h-vetinari** [comment]
@TomAugspurger 
Thanks! Could you restart #24560 as well please?

**Comment by simonjayhawkins** [comment]
@TomAugspurger  #24563 and #24557 Thanks.
