### ISSUE TITLE
error:   File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 0

### ISSUE THREAD

**Issue by aravindkota** [pandas-dev/pandas#24672]
I am getting an error for the following line in the code:

'ids_train = pd.Series(df_train[0]).map(lambda s: s.split('.')[0])'
 in a tensorflow gpu environment on ubuntu 16.04 system.

error: 
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 111, in <module>
    ids_train = pd.Series(df_train[0]).map(lambda s: s.split('.')[0])
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/home/a/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

system configuration:
Ubuntu 16.04 LTS
tensorflow-gpu 1.9.0
nvidia geforce gtx 1050

**Comment by WillAyd** [comment]
As mentioned above this is lacking a lot of required information. It's at the very least not clear what type of objects you are indexing and what their structure is, so it's entirely plausible to be getting a KeyError here.

If you can provide the information as requested above feel free to reopen!
