### ISSUE TITLE
pandas.core.config.OptionError

### ISSUE THREAD

**Issue by chiboreache** [pandas-dev/pandas#24796]
Hi! It just poping up after a few seconds in interactive REPL

#### Code Sample
```python

from arepldump import dump
# AREPL 1.0.6
# Name            : visual-studio-code-bin
# Version         : 1.30.2-1

import pandas as pd
df = pd.DataFrame()
print(df)

```

#### What I expected
Empty DataFrame
Columns: []
Index: []

#### But what I got

```Traceback

Traceback (most recent call last):
  line 4, in <module>
  File "/usr/lib/python3.7/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib/python3.7/site-packages/pandas/core/frame.py", line 456, in _init_dict
    columns = data_names = Index(keys)
  File "/usr/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 264, in __new__
    from .range import RangeIndex
  File "/usr/lib/python3.7/site-packages/pandas/core/indexes/range.py", line 20, in <module>
    from pandas.core.indexes.base import Index, _index_shared_docs
  File "/usr/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 17, in <module>
    from pandas.core.arrays import ExtensionArray
  File "/usr/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 2, in <module>
    from .categorical import Categorical  # noqa
  File "/usr/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 35, in <module>
    from pandas.core.base import (PandasObject,
  File "/usr/lib/python3.7/site-packages/pandas/core/base.py", line 23, in <module>
    import pandas.core.nanops as nanops
  File "/usr/lib/python3.7/site-packages/pandas/core/nanops.py", line 55, in <module>
    set_use_bottleneck(get_option('compute.use_bottleneck'))
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 227, in __call__
    return self.__func__(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 97, in _get_option
    key = _get_single_key(pat, silent)
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 83, in _get_single_key
    raise OptionError('No such keys(s): {pat!r}'.format(pat=pat))
pandas.core.config.OptionError: "No such keys(s): 'compute.use_bottleneck'"

Print Output:
{}
0 ms

```

#### Output of ``pd.show_versions()``

<details>

```

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.20.1-arch1-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: 1.8.3
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.7.0
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

```
</details>

**Comment by TomAugspurger** [comment]
Is `arepldump` relevant?

What's the output of `pd.get_option(''compute.use_bottleneck")`?

How'd you install pandas?

**Comment by chiboreache** [comment]
> Is arepldump relevant?

Yep, in simple REPL(code runner) all works just fine ;)

> output of `("'compute.use_bottleneck'")`


```

Traceback (most recent call last):
  line 7, in <module>
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 227, in __call__
    return self.__func__(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 97, in _get_option
    key = _get_single_key(pat, silent)
  File "/usr/lib/python3.7/site-packages/pandas/core/config.py", line 83, in _get_single_key
    raise OptionError('No such keys(s): {pat!r}'.format(pat=pat))
pandas.core.config.OptionError: 'No such keys(s): "\'compute.use_bottleneck\'"'

```

a bit lesser error footprint heh, btw `(''compute.use_bottleneck")` doesn't affect at all

>How'd you install pandas?
pacman

**Comment by chiboreache** [comment]
so I guess better to report about this issue to author of addon, meh ~_~

**Comment by TomAugspurger** [comment]
So IIUC, this is an issue with the other package. Let me know if that's not the case.
