### ISSUE TITLE
HDFExtError: Problem creating the table

### ISSUE THREAD

**Issue by mullachv** [pandas-dev/pandas#24823]
#### Code Sample, a copy-pastable example if possible

```python
def store_data(df, data_key, **kwargs):
	os.makedirs(data_folder, exist_ok=True)
	store = pd.HDFStore(data_filename, mode='a')
	store.put(data_key, df, format='table', data_columns=True)
	store.close

```
#### Problem description

HDFExtError: Problem creating the table when calling store.put()
This error occurs when the format is 'table' in the store.put line above

The following call stack is spit out. Note the performance warning of exceeding 512 columns:
```
/Users/vm/anaconda/envs/dl3.6/bin/python /Users/vm/probabilistic-gwas-playgound/framework/synthetic_data.py
/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py:993: PerformanceWarning: table ``/trn_data_100x1000__x_nm/table`` is exceeding the recommended maximum number of columns (512); be ready to see PyTables asking for *lots* of memory and possibly slow I/O
  PerformanceWarning)
/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/attributeset.py:473: PerformanceWarning: node ``/trn_data_100x1000__x_nm/table`` is exceeding the recommended maximum number of attributes (4096);be ready to see PyTables asking for *lots* of memory and possibly slow I/O
  PerformanceWarning)
/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py:993: PerformanceWarning: table ``/trn_data_100x1000__pi_nm/table`` is exceeding the recommended maximum number of columns (512); be ready to see PyTables asking for *lots* of memory and possibly slow I/O
  PerformanceWarning)
Traceback (most recent call last):
  File "/Users/vm/probabilistic-gwas-playgound/framework/synthetic_data.py", line 222, in <module>
    store_data(pi_nm, data_key_pre + 'pi_nm', shape=pi_nm.shape)
  File "/Users/vm/probabilistic-gwas-playgound/framework/synthetic_data.py", line 121, in store_data
    store.put(data_key, df, format='table', data_columns=True)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py", line 890, in put
    self._write_to_group(key, value, append=append, **kwargs)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py", line 1367, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py", line 3963, in write
    self._handle.create_table(self.group, **options)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/file.py", line 1055, in create_table
    chunkshape=chunkshape, byteorder=byteorder)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py", line 833, in __init__
    byteorder, _log)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/leaf.py", line 272, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/node.py", line 266, in __init__
    self._v_objectid = self._g_create()
  File "/Users/vm/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py", line 1020, in _g_create
    self._v_new_title, self.filters.complib or '', obversion)
  File "tables/tableextension.pyx", line 211, in tables.tableextension.Table._create_table
tables.exceptions.HDF5ExtError: Problems creating the table
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
```
(dl3.6) $ python -c 'import pandas as pd; print(pd.show_versions())'

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.0.5
pip: 18.0
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.13.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.5
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None
(dl3.6) $ 

```

```
(dl3.6) $ conda list pytables
# packages in environment at /Users/vm/anaconda/envs/dl3.6:
#
# Name                    Version                   Build  Channel
pytables                  3.4.2               np113py36_0  
(dl3.6) $ conda list pandas
# packages in environment at /Users/vm/anaconda/envs/dl3.6:
#
# Name                    Version                   Build  Channel
pandas                    0.23.4                    <pip>
pandas                    0.20.3                   py36_0  
(dl3.6) $ conda list hdf
# packages in environment at /Users/vm/anaconda/envs/dl3.6:
#
# Name                    Version                   Build  Channel
hdf5                      1.8.17                        1  
(dl3.6) $ conda list python
# packages in environment at /Users/vm/anaconda/envs/dl3.6:
#
# Name                    Version                   Build  Channel
ipython                   5.1.0                    py36_1  
ipython_genutils          0.1.0                    py36_0  
msgpack-python            0.5.6            py36h04f5b5a_1  
python                    3.6.7                haf84260_0  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
(dl3.6) $ 
```
</details>

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Can you reproduce the error using just pytables?

**Comment by mullachv** [comment]
I tried it with pandas as below. With ncols=1000, it works alright, when ncols=2000 it fails with error "HDF5ExtError: Problems creating the table". 
Not sure how to create this with PyTables:

```
#
# github issue
#
import pandas as pd
def store_data(df, data_key='/data', data_filename='store_test.h5', **kwargs):
	store = pd.HDFStore(data_filename, mode='a')
	store.put(data_key, df, format='table', data_columns=True)
	store.close
ncols = 2000
df = pd.DataFrame(np.random.randn(100, ncols), columns=['A_'+str(i) for i in range(ncols)])
store_data(df)

```

```
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-52-286c4dfd5086> in <module>()
      9 ncols = 2000
     10 df = pd.DataFrame(np.random.randn(100, ncols), columns=['A_'+str(i) for i in range(ncols)])
---> 11 store_data(df)

<ipython-input-52-286c4dfd5086> in store_data(df, data_key, data_filename, **kwargs)
      5 def store_data(df, data_key='/data', data_filename='store_test.h5', **kwargs):
      6         store = pd.HDFStore(data_filename, mode='a')
----> 7         store.put(data_key, df, format='table', data_columns=True)
      8         store.close
      9 ncols = 2000

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py in put(self, key, value, format, append, **kwargs)
    888             format = get_option("io.hdf.default_format") or 'fixed'
    889         kwargs = self._validate_format(format, kwargs)
--> 890         self._write_to_group(key, value, append=append, **kwargs)
    891 
    892     def remove(self, key, where=None, start=None, stop=None):

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1365 
   1366         # write the object
-> 1367         s.write(obj=value, append=append, complib=complib, **kwargs)
   1368 
   1369         if s.is_table and index:

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/pandas/io/pytables.py in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   3961 
   3962             # create the table
-> 3963             self._handle.create_table(self.group, **options)
   3964         else:
   3965             pass

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/file.py in create_table(self, where, name, description, title, filters, expectedrows, chunkshape, byteorder, createparents, obj)
   1053                       description=description, title=title,
   1054                       filters=filters, expectedrows=expectedrows,
-> 1055                       chunkshape=chunkshape, byteorder=byteorder)
   1056 
   1057         if obj is not None:

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py in __init__(self, parentnode, name, description, title, filters, expectedrows, chunkshape, byteorder, _log)
    831 
    832         super(Table, self).__init__(parentnode, name, new, filters,
--> 833                                     byteorder, _log)
    834 
    835     def _g_post_init_hook(self):

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/leaf.py in __init__(self, parentnode, name, new, filters, byteorder, _log)
    270         # is a lazy property that automatically handles their loading.
    271 
--> 272         super(Leaf, self).__init__(parentnode, name, _log)
    273 
    274     def __len__(self):

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    264             #   Create or open the node and get its object ID.
    265             if new:
--> 266                 self._v_objectid = self._g_create()
    267             else:
    268                 self._v_objectid = self._g_open()

/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/tables/table.py in _g_create(self)
   1018         # set because it is needed for setting attributes afterwards.
   1019         self._v_objectid = self._create_table(
-> 1020             self._v_new_title, self.filters.complib or '', obversion)
   1021         self._v_recarray = None  # not useful anymore
   1022         self._rabyteorder = None  # not useful anymore

tables/tableextension.pyx in tables.tableextension.Table._create_table()

HDF5ExtError: Problems creating the table
```

**Comment by mullachv** [comment]
The requirement from my end of the code is:
- Use a batch reader of data (chunked reading) in pandas
- Which requires that we store the H5 file in 'table' format (so as to select using where clauses)
- When I use 'table' format, the write operation fails when the number of columns approach 2000 or so

**Comment by Maarten-vd-Sande** [comment]
Happens for me with:

```
df = pd.DataFrame(index=["row_"+str(x) for x in range(300_000)], columns=["col_"+str(x) for x in range(2_000)])
df.to_hdf("hg_bins.hdf", key="test", format='table', data_columns=True)
```

**Comment by jbrockmendel** [comment]
Maarten's reproducer also reproduces the issue for me, but AFAICT this an a limitation of hdf5, not pandas. Closing.
