### ISSUE TITLE
GET_WRITER() do not find openpyxl version

### ISSUE THREAD

**Issue by AntonioSecchi** [pandas-dev/pandas#25053]
Running my easy test_excel.py, containing:

import pandas as pd
df = pd.read_excel('foo.xlsx')
df.to_excel('foo_1.xlsx')

I'm getting the error:

Traceback (most recent call last):
  File "test_excel.py", line 5, in <module>
    df.to_excel('foo_1.xlsx')
  File "/python3/lib/python3.6/site-packages/pandas/core/frame.py", line 1545, in to_excel
    engine=engine)
  File "/python3/lib/python3.6/site-packages/pandas/io/formats/excel.py", line 643, in write
    writer = ExcelWriter(_stringify_path(writer), engine=engine)
  File "/python3/lib/python3.6/site-packages/pandas/io/excel.py", line 726, in __new__
    cls = get_writer(engine)
  File "/python3/lib/python3.6/site-packages/pandas/io/excel.py", line 194, in get_writer
    if LooseVersion(openpyxl.__version__) < '2.0.0':
AttributeError: module 'openpyxl' has no attribute '__version__'

I've solved it, adding inside "/python3/lib/python3.6/site-packages/pandas/io/excel.py" in line 194:
after the line of code: import openpyxl, the specific version of openpyxl:

import openpyxl
openpyxl__version__ = '2.5.12' #in my case this was my openpyxl version

Hope it's helpfull

**Comment by WillAyd** [comment]
What version of pandas is this? I don't see the lines of code shown in your traceback on master
