### ISSUE TITLE
Vectorized datetetime replace

### ISSUE THREAD

**Issue by mhooreman** [pandas-dev/pandas#25212]
#### Problem description

It seems that the ``replace``method of pandas Timestamps cannot be called in a vectorized way.

It obliges us to use ``apply`` or ``np.vectorize``, which is not good for performances.

#### Example code (unit test)

```python
#!/usr/bin/env python3

import pandas as pd
import unittest


class VectorizedTimestampReplaceTests(unittest.TestCase):
    def setUp(self):
        tmp = '2019-01-01T12:34:56'
        self.tsIn = pd.to_datetime(tmp + 'Z')  # input value
        self.tsExp = pd.to_datetime(tmp)  # expected value

    def testSingleValue(self):
        """Test conversion of a single Timestamp value"""
        # It runs correclty
        tsOut = self.tsIn.replace(tzinfo=None)
        self.assertTrue(tsOut == self.tsExp)

    def testSeries(self):
        """Test conversion of a Series of Timestamp values"""
        # It fails
        tsOut = pd.Series(self.tsIn).replace(tzinfo=None)
        self.assertTrue(tsOut == self.tsExp)

    def testSeriesDt(self):
        """Test conversion of a Series of Timestamp values using dt method"""
        # It fails
        tsOut = pd.Series(self.tsIn).dt.replace(tzinfo=None)
        self.assertTrue(tsOut == self.tsExp)


if __name__ == "__main__":
    unittest.main(verbosity=2)
```

#### Curent Output

```
testSeries (__main__.VectorizedTimestampReplaceTests)
Test conversion of a Series of Timestamp values ... ERROR
testSeriesDt (__main__.VectorizedTimestampReplaceTests)
Test conversion of a Series of Timestamp values using dt method ... ERROR
testSingleValue (__main__.VectorizedTimestampReplaceTests)
Test conversion of a single Timestamp value ... ok

======================================================================
ERROR: testSeries (__main__.VectorizedTimestampReplaceTests)
Test conversion of a Series of Timestamp values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitTests.py", line 20, in testSeries
    tsOut = pd.Series(self.tsIn).replace(tzinfo=None)
TypeError: replace() got an unexpected keyword argument 'tzinfo'

======================================================================
ERROR: testSeriesDt (__main__.VectorizedTimestampReplaceTests)
Test conversion of a Series of Timestamp values using dt method
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitTests.py", line 25, in testSeriesDt
    tsOut = pd.Series(self.tsIn).dt.replace(tzinfo=None)
AttributeError: 'DatetimeProperties' object has no attribute 'replace'

----------------------------------------------------------------------
Ran 3 tests in 0.005s

FAILED (errors=2)
```

#### Expected Output

All unit test are OK

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: 4.2.0
pip: 19.0.1
setuptools: 40.6.3
Cython: 0.29.4
numpy: 1.16.1
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.2
lxml.etree: 4.3.0
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by vladserkoff** [comment]
You should probably call one of `pd.Series.dt.tz_localize` or `pd.Series.dt.tz_convert` to remove the timezone.

**Comment by jreback** [comment]
-1 on .replace for DTI it is overly complicated in datetimesnans easier solutions already exist (look at .map / tz_localize and the accessors)

**Comment by mhooreman** [comment]
Oops!

Thanks
