### ISSUE TITLE
pip doen't install numpy as prerequist

### ISSUE THREAD

**Issue by Dremor** [pandas-dev/pandas#25373]
#### Code Sample, a copy-pastable example if possible

```bash
./env/bin/pip install --upgrade pandas
```
#### Problem description
Installing Pandas in a Python2 VirtualEnv, install fails as Numpy cannot be locally found.

#### Expected Output
Pandas install in the VirtuaEnv

#### Output of ```./env/bin/pip install --upgrade pandas```

```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/81/fdb1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WhPCxJ/pandas/setup.py", line 732, in <module>
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "/tmp/pip-install-WhPCxJ/pandas/setup.py", line 475, in maybe_cythonize
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "/erpnext/package/erpnext-py2/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1144, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/erpnext/package/erpnext-py2/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
        __import__(moduleOrReq)
    ImportError: No module named numpy

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-WhPCxJ/pandas/
```

**Comment by TomAugspurger** [comment]
We have another issue for this. Can you search for duplicates and close
this one?

**Comment by Dremor** [comment]
I've searched for duplicates, did not found one. In another hand, manually install numpy works, but is far from ideal. Now I've got a similar issue with cython, still with the same install command.

**Comment by Dremor** [comment]
Correction : I've finally found the issue (did not find it with my initial search) : #25193

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/issues/2519

https://github.com/pandas-dev/pandas/pull/25227 for the numpy side. No PR yet for the Cython issue.
