### ISSUE TITLE
Pandas KeyError: "Index not in index"

### ISSUE THREAD

**Issue by Kay-cwc** [pandas-dev/pandas#25428]
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame(["1","2","3","4","5"], ["a","b","c","d","e"], ["w"])
df.plot.line(x=df.index,y="w")

```
**Problem**

I was going to create a data frame and run it as a line plot. 

When I run the command print(df) and hide the line of df.plot.line, I was able to see the data frame exactly as I expected

However, once I put it as a plot with the code above, an error occurs, How do it solve this problem?

Traceback (most recent call last):
  File "version.py", line 5, in <module>
    df.plot.line(x=df.index,y="w")
  File "C:\Anaconda3\lib\site-packages\pandas\plotting\_core.py", line 3005, in line
    return self(kind='line', x=x, y=y, **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\plotting\_core.py", line 2941, in __call__
    sort_columns=sort_columns, **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\plotting\_core.py", line 1977, in plot_frame
    **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\plotting\_core.py", line 1766, in _plot
    elif not isinstance(data[x], ABCSeries):
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "Index(['a', 'b', 'c', 'd', 'e'], dtype='object') not in index"

**pd.version**

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 17 Stepping 0, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: zh_TW.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

**Comment by WillAyd** [comment]
What plot are you expecting here exactly?

**Comment by WillAyd** [comment]
Think this is a usage question. Better served asking on QA sites like SO
