### ISSUE TITLE
BUG: User-facing AssertionError with DataFrame.to_html(classes=<invalid type>)

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#25608]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.DataFrame().to_html(classes=True)
```
#### Problem description

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\frame.py", line 2212, in to_html
    formatter.to_html(classes=classes, notebook=notebook, border=border)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\io\formats\format.py", line 729, in to_html
    html = Klass(self, classes=classes, border=border).render()
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\io\formats\html.py", line 146, in render
    self._write_table()
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\io\formats\html.py", line 167, in _write_table
    .format(typ=type(self.classes)))
AssertionError: classes must be list or tuple, not <class 'bool'>
```

#### Expected Output

```python-traceback
TypeError: classes must be a string, list or tuple, not <class 'bool'>
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by simonjayhawkins** [comment]
@mroeschke : the solution requires a change to one line of code, add a simple parametrised test and a whatsnew entry under bugfix. Can this be labelled good first issue?

**Comment by mroeschke** [comment]
Thanks for the suggestion!

**Comment by ArtificialQualia** [comment]
I can work on this
