### ISSUE TITLE
Problem with pandas loc, which can't find date value in index (first row)

### ISSUE THREAD

**Issue by rvic** [pandas-dev/pandas#25747]
#### Code Sample, a copy-pastable example if possible

I have next CSV sample file:
```
time,value
2018-09-17,0.0002897
2018-09-16,0.0002955
2018-09-15,0.0002862
2018-09-14,0.0003054
2018-09-13,0.000312
2018-09-12,0.0003467
2018-09-11,0.0003433
2018-09-10,0.0003287
2018-09-09,0.0003355
2018-09-08,0.0003288
```

```python
>>> import pandas as pd
>>> s1 = pd.read_csv("series1.csv")
>>> s1['time'] = pd.to_datetime(s1['time'])
>>> s1.set_index('time', inplace=True)
>>> s1
               value
time
2018-09-17  0.000290
2018-09-16  0.000296
2018-09-15  0.000286
2018-09-14  0.000305
2018-09-13  0.000312
2018-09-12  0.000347
2018-09-11  0.000343
2018-09-10  0.000329
2018-09-09  0.000336
2018-09-08  0.000329
>>> s1.loc['2018-09-16']
               value
time
2018-09-16  0.000296
>>> s1.loc['2018-09-17']
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pandas\core\indexing.py", line 1506, in _has_valid_type
    error()
  File "C:\Python36\lib\site-packages\pandas\core\indexing.py", line 1501, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [2018-09-17] is not in the [index]'
```
#### Problem description

Above is sample code session which shows failure of loc to locate first row in index, which it obviously should do without problem as it finds second row (see in code session)

#### Output of ``pd.show_versions()``

<details>
Output of pd.show_versions is too long, i can't grab it whole content.
Version of pandas is 0.22.0, version of python is 3.6.7
</details>

**Comment by mroeschke** [comment]
This is fixed in the latest release of pandas. Please upgrade for the fixed behavior.

```
In [6]: s1.loc['2018-09-17']
Out[6]:
              value
time
2018-09-17  0.00029

In [7]: pd.__version__
Out[7]: '0.24.2'
```
