### ISSUE TITLE
to_parquet using PyArrow fails silently on S3 errors

### ISSUE THREAD

**Issue by pgeez** [pandas-dev/pandas#25921]
`pandas==0.24.2`

#### Code

```python
#!/usr/bin/env python

import pandas as pd


df = pd.DataFrame({'col0': []})
s3_filepath = 's3://some-bogus-bucket/df.parquet'

try:
    print('>> TEST: pd.DataFrame.to_parquet using PyArrow')
    df.copy().to_parquet(s3_filepath, engine='pyarrow')
except OSError:
    print('>>>> TEST: OSError raised!')
else:
    print('>>>> TEST: OSError **NOT** raised!')
```

#### Output
```
>> TEST: pd.DataFrame.to_parquet using PyArrow
Exception ignored in: <bound method S3File.__del__ of <S3File some-bogus-bucket/df.parquet>>
Traceback (most recent call last):
  File "<redacted>/lib/python3.6/site-packages/s3fs/core.py", line 1476, in __del__
    self.close()
  File "<redacted>/lib/python3.6/site-packages/s3fs/core.py", line 1454, in close
    raise_from(IOError('Write failed: %s' % self.path), e)
  File "<string>", line 3, in raise_from
OSError: Write failed: some-bogus-bucket/df.parquet
>>>> TEST: OSError **NOT** raised!
```

#### Problem description

The PyArrowImpl Parquet writer fails silently when it encounters errors while writing to S3. In the above example, I try writing a parquet file using `engine='pyarrow'` to a phony bucket `some-bogus-bucket` which is causing `boto3` is raising a `NoSuchBucket` exception "under-the-hood." While the write clearly does fail, it does *not* raise an `OSError`, as is expected and as is the behavior when using the `engine='fastparquet'`.

I dug a little more into this and tried writing to S3 using the `pyarrow` lib directly in two different ways:

```
from s3fs import S3File, S3FileSystem
import pyarrow as pa
import pyarrow.parquet as pq
# use S3File --> fails silently
pq.write_table(pa.Table.from_pandas(df.copy()),
               S3File(S3FileSystem(), s3_filepath, mode='wb'))

# use filepath and S3FileSystem --> raises OSError, as expected
pq.write_table(pa.Table.from_pandas(df.copy()),
               s3_filepath,
               filesystem=S3FileSystem())
```

The first, which is similar to how `pandas.io.parquet.PyArrowImpl` calls `pyarrow.write_table`, fails while the second, which explicitly uses an S3 filepath and an `S3FileSystem()`, does not.

#### Expected Output
```
>> TEST: pd.DataFrame.to_parquet using PyArrow
>>>> TEST: OSError raised!
Exception ignored in: <bound method S3File.__del__ of <S3File some-bogus-bucket/df.parquet>>
Traceback (most recent call last):
  File "<redacted>/lib/python3.6/site-packages/s3fs/core.py", line 1476, in __del__
    self.close()
  File "<redacted>/lib/python3.6/site-packages/s3fs/core.py", line 1454, in close
    raise_from(IOError('Write failed: %s' % self.path), e)
  File "<string>", line 3, in raise_from
OSError: Write failed: some-bogus-bucket/df.parquet
```

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: 0.12.1
xarray: None
IPython: 7.3.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: None
s3fs: 0.2.0
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None
```

</details>

**Comment by WillAyd** [comment]
Based off of your second example have you raised this with the pyarrow library?

**Comment by pgeez** [comment]
I have not...I will, though.

**Comment by pgeez** [comment]
see: https://github.com/apache/arrow/issues/4078

**Comment by jorisvandenbossche** [comment]
This has been reported to the arrow project, so closing here.
