### ISSUE TITLE
Doc Check Failures

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26187]
This just started showing up in the CI failures today:

```sh
Traceback (most recent call last):
  File "ci/../scripts/validate_docstrings.py", line 991, in <module>
    args.ignore_deprecated))
  File "ci/../scripts/validate_docstrings.py", line 891, in main
    result = validate_all(prefix, ignore_deprecated)
  File "ci/../scripts/validate_docstrings.py", line 845, in validate_all
    doc_info = validate_one(func_name)
  File "ci/../scripts/validate_docstrings.py", line 801, in validate_one
    errs, wrns, examples_errs = get_validation_data(doc)
  File "ci/../scripts/validate_docstrings.py", line 749, in get_validation_data
    if not doc.see_also:
  File "ci/../scripts/validate_docstrings.py", line 477, in see_also
    in self.doc['See Also'])
  File "ci/../scripts/validate_docstrings.py", line 476, in <genexpr>
    for name, desc, _
ValueError: not enough values to unpack (expected 3, got 2)
```

I think it's an issue with upgrading to numpydoc 0.9 but will look in more detail and confirm

**Comment by WillAyd** [comment]
Here's the relevant issue on the numpydoc side released in v0.9:

https://github.com/numpy/numpydoc/pull/172
