### ISSUE TITLE
BUG: Sorting MultiIndex with NaNs 

### ISSUE THREAD

**Issue by eoincondron** [pandas-dev/pandas#26210]
#### Code Sample, a copy-pastable example if possible

```python
>>> ix = pd.MultiIndex(levels=[['B', 'A'], ['x']], codes=[[-1, 0, 1], [0, 0, 0]],
...             names=['symbol', 'date'])
>>> ix._sort_levels_monotonic()
MultiIndex(levels=[['A', 'B'], ['x']],
           codes=[[0, 1, 0], [0, 0, 0]],
           names=['symbol', 'date'])

# MultiIndex silently accepts Nan in codes when inside a NumPy array and cast to 0:

>>> pd.MultiIndex(levels=[['B', 'A'], ['x']], codes=[np.array([np.nan, 0, 1]), [0, 0, 0]],
...             names=['symbol', 'date'])
MultiIndex(levels=[['B', 'A'], ['x']],
           codes=[[0, 0, 1], [0, 0, 0]],
           names=['symbol', 'date'])
```
#### Problem description

When sorting a `MultiIndex`, NaNs in any level which is not already sorted are replaced with the first non-null value in the sorted orders. Effectively, the `-1` values in the `codes` get replaced with `0`. I've tracked this to two separate parts. The first part is in this line in `MultiIndex._sort_levels_monotonic`:

                    level_codes = algos.take_1d(ri, level_codes)

The output has `np.nan` where the input had `-1`. This could be fixed by:

                    level_codes = algos.take_1d(ri, level_codes, fill_value=-1)

The second part, which also seems unexpected to me, is that `MultiIndex` silently accepts NaN in codes when inside a NumPy array and casts to 0 (see second part of example above).
In particular, this is inconsistent with the behaviour when we pass NaNs inside a `list` which throws an error:

```python

>>> pd.MultiIndex(levels=[['B', 'A'], ['x']], codes=[[np.nan, 0, 1], [0, 0, 0]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 235, in __new__
    result._set_codes(codes, copy=copy, validate=False)
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 683, in _set_codes
    for lev, level_codes in zip(self.levels, codes))
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 683, in <genexpr>
    for lev, level_codes in zip(self.levels, codes))
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/core/indexes/frozen.py", line 192, in _ensure_frozen
    array_like = coerce_indexer_dtype(array_like, categories)
  File "/opt/dtc/conda_envs/condron/envs/pd24/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 556, in coerce_indexer_dtype
    return ensure_int8(indexer)
  File "pandas/_libs/algos_common_helper.pxi", line 333, in pandas._libs.algos.ensure_int8
ValueError: cannot convert float NaN to integer

```

#### Expected Output

I think the expected output of `_sort_levels_monotonic` in this case would preserve the `-1` codes.  Patching `_sort_levels_monotonic` with this fix I get:

````python

>>> s = pd.Series([1, 2, 3], ix)
>>> s.sort_index(na_position='first')
symbol  date
NaN     x       1
A       x       3
B       x       2

>>> s.sort_index(na_position='last')
symbol  date
A       x       3
B       x       2
NaN     x       1

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.162-94.72-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: None
pip: 9.0.1
setuptools: 36.4.0
Cython: None
numpy: 1.13.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by eoincondron** [comment]
Happy to do a PR for these changes.

**Comment by WillAyd** [comment]
Thanks for the report.  Do you see anything from an end user perspective that this would effect (this isn't the way that end users would construct a MI nor is the method shown public)

@mroeschke for thoughts on this

**Comment by eoincondron** [comment]
I reported the lowest-level construction I could to illustrate the bug but from an end-user perspective. I tried a few ways to construct it naturally but couldn't. So is it the case that each of the natural or public ways to construct a `MultiIndex`, e.g. `DataFrame.set_index`, `from_tuples, from_arrays` etc. always set up such that the `levels` are sorted and thus this code path is not reached?

**Comment by mroeschke** [comment]
We discourage constructing indexes `nan`s (but understandably they can end up in the index after operations). I agree with @eoincondron and the coercion of a `nan` code to 0 is a bug and should raise in that particular case.

Gladly accept a PR to patch this case.

**Comment by eoincondron** [comment]
I've tracked the coercion of the `nan` code to a surprising (to me) behaviour of `numpy`. 
Consider the following
```
>>> import numpy as np
>>> np.array([np.nan]).astype('int8')
array([0], dtype=int8)

>>> np.array([np.nan], 'int8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot convert float NaN to integer
```

When we pass a `numpy` array with null values through `coerce_indexer_dtype` we get the coercion as it does `.astype('int8')`, but when we pass a `list`, say, we get the error because it does `np.array(codes, dtype='int8')`. I'm not sure if one would consider this a bug in `numpy`. 

Nonetheless, should we be checking for null elements in `coerce_indexer_dtype` and raising an exception there? Moreover, it seems like this function should raise if a non-integer type is passed. 
I've just discovered that one can also pass `floats` to `codes` and it doesn't complain:

```
>>> pd.MultiIndex(levels=[['a'], ['b']], codes=[np.array([0.5, 0, 0]), [-1, -1, 0]])
MultiIndex(levels=[['a'], ['b']],
           codes=[[0, 0, 0], [-1, -1, 0]])
```

So I suggest that we check for integer type in either of `MultiIndex._set_codes` or `coerce_indexer_dtype`. 
The latter would have a broader impact, of course, and I haven't looked for where else this method is used so I'm not best placed to make that call.
