### ISSUE TITLE
Exception has occurred: KeyError 'Diameter'

### ISSUE THREAD

**Issue by pengguanjun** [pandas-dev/pandas#26448]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt  
from matplotlib.ticker import MultipleLocator, FormatStrFormatter
plt.rcParams['font.sans-serif'] = ['KaiTi']
plt.rcParams['font.serif'] = ['KaiTi']
# plt.rcParams['axes.unicode_minus'] = False # 解决保存图像是负号'-'显示为方块的问题,或者转换负号为字符串
import seaborn as sns  
sns.set_style("darkgrid",{"font.sans-serif":['KaiTi', 'Arial']})   #这是方便seaborn绘图得时候得字体设置

sns.set( palette="muted", color_codes=True)  
d = pd.read_csv('C:/Users/MaiBenBen/Desktop/nicetable/2-图片1.csv',encoding='gbk')
f, ax = plt.subplots( figsize=(7,7))
plt.title('Histgram of Rock Fragmentation', fontsize=22)

print(d)
print(type(d))
y = list(d.loc[:,'Diameter'])
print(type(y))
print(y)

sns.distplot(y,kde=False,color="r")  
group_labels = ['0', '10', '20','30','40','50','60', '70','80','90','100']
ax.set_yticklabels(group_labels,#设置刻度对应的标签
                   rotation=0, fontsize='small')#rotation选项设定x刻度标签倾斜30度。

plt.xlabel('size (cm)')
plt.ylabel('quantity of fragmentations')  #只有最后一个图有改变

fig = ax.get_figure()
#fig.savefig('a.png', dpi=100, bbox_inches='tight')
plt.show()  

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

![图片](https://user-images.githubusercontent.com/29192658/57972778-ad0dcf80-79d1-11e9-931f-996a4d1220c4.png)

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
            x;Diameter;;
0   1.078;0.00197;;1.078
1      11.822;-0.00373;;
2      12.363;-0.00481;;
3       16.199;0.04331;;
4       16.815;0.09224;;
5       19.813;0.28407;;
6          20.43;0.333;;
7       21.046;0.38193;;
8       21.663;0.43087;;
9        22.279;0.4798;;
10      22.896;0.52873;;
11      24.692;0.68536;;
12      24.771;0.69119;;
13      26.384;0.69122;;
14      29.148;0.73823;;
15      33.525;0.78526;;
16      39.508;0.82841;;
17      47.636;0.86767;;
18        50.34;0.8775;;
19      54.138;0.89909;;
20       56.83;0.90109;;
21      68.699;0.92671;;
22       81.087;0.9406;;
23      94.019;0.95842;;
24      106.41;0.97427;;
25     111.799;0.98218;;
26     119.329;0.98426;;
27     132.242;0.99033;;
28     145.684;0.99054;;
29     158.594;0.99466;;
30      169.35;0.99678;;
31     172.038;0.99682;;
32     184.404;0.99702;;
33     197.848;0.99918;;
34     211.289;0.99939;;
35     220.976;1.00542;;
36     224.196;1.00155;;
37      237.096;0.9998;;
38     250.541;1.00197;;
39     263.982;1.00218;;
40       277.43;1.0063;;
41     277.964;0.96383;;
<class 'pandas.core.frame.DataFrame'>
Traceback (most recent call last):
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Diameter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\MaiBenBen\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\MaiBenBen\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 410, in main
    run()
  File "c:\Users\MaiBenBen\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\MaiBenBen\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\MaiBenBen\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\MaiBenBen\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\MaiBenBen\Desktop\nicetable\HIST.py", line 19, in <module>
    y = list(d.loc[:,'Diameter'])
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\generic.py", line 3576, in xs
    return self[key]
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Diameter'

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 28.8.0
Cython: None
numpy: 1.16.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.1
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: 0.9.0
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0
gcsfs: None
>>> pd.__version__
'0.24.2'

</details>

**Comment by simonjayhawkins** [comment]
from the output of `print(d)` above, it could be that the parsing of the excel file is the source of the issue. can you print the output of `d.columns`?

**Comment by pengguanjun** [comment]
> 
> 
> from the output of `print(d)` above, it could be that the parsing of the csv file is the source of the issue. can you print the output of `d.columns`?

Em,it can work
print(d.columns)
Index(['x;Diameter;;'], dtype='object')
But,KeyError 'Diameter' disturbs me ,could you help me?

y = list(d.loc[:,'Diameter'])#any wrong?

**Comment by pengguanjun** [comment]
I add ; in the end.
y = list(d.loc[:,'Diameter;'])
It also happen Exception has occurred: KeyError 'Diameter;'

y = d.loc[:,'Diameter']#KeyError: 'Diameter'



Exception has occurred: KeyError
'Diameter;'
  File "C:\Users\MaiBenBen\Desktop\nicetable\pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\generic.py", line 3576, in xs
    return self[key]
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\MaiBenBen\Python36\Lib\site-packages\pandas\core\indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\MaiBenBen\Desktop\nicetable\HIST.py", line 20, in <module>
    y = list(d.loc[:,'Diameter;'])
  File "C:\Users\MaiBenBen\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MaiBenBen\Python36\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\MaiBenBen\Python36\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)

**Comment by pengguanjun** [comment]
thanke you!


print(d.columns)
 Index(['x;Diameter;;'], dtype='object')


I add ; in the end.
y = list(d.loc[:,'Diameter;'])    #It also happen Exception has occurred: KeyError 'Diameter;'
 
y = d.loc[:,'Diameter']    #KeyError: 'Diameter'

https://github.com/pandas-dev/pandas/issues/26448
Could you help me?


------------------ 原始邮件 ------------------
发件人: "Simon Hawkins"<notifications@github.com>;
发送时间: 2019年5月19日(星期天) 凌晨3:08
收件人: "pandas-dev/pandas"<pandas@noreply.github.com>;
抄送: "这真了不起！热心"<1570320831@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pandas-dev/pandas] Exception has occurred: KeyError 'Diameter'(#26448)




from the output of print(d) above, it could be that the parsing of the excel file is the source of the issue. can you print the output of d.columns?

**Comment by simonjayhawkins** [comment]
It looks like you need to use `sep=';'` in the call to  `pd.read_csv`

**Comment by pengguanjun** [comment]
> 
> 
> It looks like you need to use `sep=';'` in the call to `pd.read_csv`
d = pd.read_csv('C:/Users/MaiBenBen/Desktop/nicetable/2-图片1.csv',sep=';', encoding='gbk')
It works well,thank you!
