### ISSUE TITLE
assert_frame_equal with check_like throws exception if frames have repeat indices

### ISSUE THREAD

**Issue by fiendish** [pandas-dev/pandas#26494]
#### Code Sample, a copy-pastable example if possible

```python
a = pandas.DataFrame({'A': [1, 2, 1]}, index=[0, 1, 0])
b = pandas.DataFrame({'A': [1, 1, 2]}, index=[0, 0, 1])
pandas.testing.assert_frame_equal(a, b, check_like=True)
```
#### Problem description

It raises an exception (and with a not helpful message)
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/util/testing.py", line 1461, in assert_frame_equal
    left, right = left.reindex_like(right), right
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 3757, in reindex_like
    return self.reindex(**d)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/util/_decorators.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3809, in reindex
    return super(DataFrame, self).reindex(**kwargs)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 4356, in reindex
    fill_value, copy).__finalize__(self)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3741, in _reindex_axes
    fill_value, limit, tolerance)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3752, in _reindex_index
    allow_dups=False)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 4490, in _reindex_with_indexers
    copy=copy)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1224, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/Users/kelmana/Documents/kids-first/kf-lib-data-ingest/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3087, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

#### Expected Output

It should return that they are equal because, ignoring index order, the two dataframes are equal.

#### Output of ``pd.show_versions()``

```
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.4.0
pip: 19.1.1
setuptools: 41.0.1
Cython: None
numpy: 1.15.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
```
</details>

**Comment by WillAyd** [comment]
See discussion in #29191 I think this is rather ambiguous, so not something that really can / should be supported
