### ISSUE TITLE
Inconsistent behaviour of __getitem__ and .loc with slices for DataFrames with MultiIndex columns

### ISSUE THREAD

**Issue by plammens** [pandas-dev/pandas#26511]
#### Code Sample

```python
import numpy as np
import pandas as pd

data = np.zeros((3, 6), dtype=np.int16)
col_index = pd.MultiIndex.from_product([['A', 'B', 'C'], ['t1', 't2']])
df = pd.DataFrame(data, columns=col_index)
```

```python
>>> df
      A           B           C
  test1 test2 test1 test2 test1 test2
0     0     0     0     0     0     0
1     0     0     0     0     0     0
2     0     0     0     0     0     0
```

```python
>>> df['A']
   t1  t2
0   0   0
1   0   0
2   0   0
```

```python
>>> df[:, 't1']
Traceback (most recent call last):
  File "<ipython-input-20-c0e18fe6137b>", line 1, in <module>
    df[:, 't1']
  File "c:\users\paolo\code\ipython\lib\site-packages\pandas\core\frame.py", line 2926, in __getitem__
    return self._getitem_multilevel(key)
  File "c:\users\paolo\code\ipython\lib\site-packages\pandas\core\frame.py", line 2972, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "c:\users\paolo\code\ipython\lib\site-packages\pandas\core\indexes\multi.py", line 2406, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 665, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
TypeError: '(slice(None, None, None), 't1')' is an invalid key
```

but

```python
>>> df.loc[:, (slice(None), 't1')]
   A  B  C
  t1 t1 t1
0  0  0  0
1  0  0  0
2  0  0  0
```

#### Problem description

Dataframes with `MultiIndex` columns aren't able to make a "cross section" slice (i.e., selecting all sub-columns of a certain label for every "major" column). I know this behaviour is provided by [`DataFrame.xs` & company](http://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#cross-section), but I don't see why it is beneficial to ignore this inconsistency and make a separate method for the purpose, since `DataFrame.__getitem__` already interprets a tuple indexer as a column indexing when `columns` is a `MultiIndex` (but it just supports selecting exactly one label for each sub-index). 

Maybe I don't know what I'm talking about, but each day that goes by, `DataFrame.__getitem__` seems more and more of a mess to me.

#### Expected Output

`df[:, 't1']` doesn't throw; it returns a `DataFrame` with only the `t1` sub-columns from columns `A`, `B`, and `C` (like the one returned by `df.loc[:, (slice(None), 't1')]`.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TannhauserGate42** [comment]
No, the behaviour is not inconsistent!

Try this example as a thought-experiment
```python
col_index = pd.MultiIndex.from_product([['t1', 't2', 't3'], ['t1', 't2']])
```

What would you then like to get for the following query?

```python
>>> df[:, 't1']
```

**Comment by TannhauserGate42** [comment]
You need (!) to specify in some way the level / dimension on the MultiIndex, on which you want to slice. 

In my example above, both would work, but with another result:


```python
>>> df[:, 't1']
>>> df[:, (slice(None), 't1')]
```

**Comment by plammens** [comment]
> No, the behaviour is not inconsistent!
> 
> Try this example as a thought-experiment
> 
> ```python
> col_index = pd.MultiIndex.from_product([['t1', 't2', 't3'], ['t1', 't2']])
> ```
> 
> What would you then like to get for the following query?
> 
> ```python
> >>> df[:, 't1']
> ```

This is exactly the same example as above, just changing the names `'A', 'B', 'C'` to `'t1', 't2', 't3'`. In this case I would expect `df[:, 't1']` to return
```text
  t1 t2 t3
  t1 t1 t1
0  0  0  0
1  0  0  0
2  0  0  0
```

> In my example above, both would work, but with another result:
> ```
> >>> df[:, 't1']
> >>> df[:, (slice(None), 't1')]
> ```

No, the first one still raises `TypeError` (and the second one does too, but i presume you meant `df.loc[:, (slice(None), 't1')].

**Comment by TannhauserGate42** [comment]
In any case I overlooked something, as you already noticed ... I should have used .loc[...] in my example. Did not realise, that you used both, [] and loc[] in yours.

**Comment by TannhauserGate42** [comment]
I went through your examples again. 

This inconsistency of indexing on the 'columns' and on the 'index' is very unfortunate and already in place for quite a long time. Well, but even knowing that DataFrames are tables and not matrices, I agree with you, that one expects the example above to work. I think the syntax/signatures could show more symmetry. 

BTW, this asymmetry/inconsistency was one of our reasons to use dataframes with dimensions (MultiIndex) on the 'index' and scenarios (simulations) on the 'columns' axis in one of our business applications ... (But is a main concern for performance now on the data consumption ... https://github.com/pandas-dev/pandas/issues/26502)

**Comment by TomAugspurger** [comment]
@plammens can you double check the output of your first block? I think the `test1`, `test2`, etc. should be `t1`, `t2`.

`DataFrame.__getitem__(key)` not being the same as `DataFrame.loc[:, key]` is probably a bug. Though there may be some subtlety of `DataFrame.__getitem__` that I'm missing.

**Comment by TomAugspurger** [comment]
I'm not really sure what would be going wrong, but I'd probably start with a `pdb`inside `DataFrame.__getitem__` and see where things differ from loc.

**Comment by TannhauserGate42** [comment]
A few notes here, which might help you if you want to fix it ...

As you said, the following does not work:
```python
>>> df[:, (slice(None), 't1')]
```
In the end it happens, because 
```pyhton
>>> slice(None, None, None)
```
is not hashable. But the main cause is a wrong case switch already before somewhere.

Some symmetry/asymetry in success/failure you can deduct from the follwing examples on the transposed dataframe. Hence, having the MultiIndex on the index-axis.

The following works fine
```python
>>> tf = df.transpose()
>>> tf.loc[('A', 't2')]  # works
```
... while the following breads
```python
>>> tf = df.transpose()
>>> tf.loc[('A', 't2'), :]  # TypeError
```

Additionally, the following breaks
```python
>>> tf = df.transpose()
>>> tf.loc[(slice(None), 't2')]  # TypeError
```
... while the following works fine
```python
>>> tf = df.transpose()
>>> tf.loc[(slice(None), 't2'), :] # works
```

**Comment by TannhauserGate42** [comment]
Whenever the code runs over 
```pyhton
        # We are left with two options: a single key, and a collection of keys,
        # We interpret tuples as collections only for non-MultiIndex
        is_single_key = isinstance(key, tuple) or not is_list_like(key)
```
... a Type error is raises.

You might investigate in 2850
```pyhton
        # Do we have a slicer (on rows)?
        indexer = convert_to_index_sliceable(self, key)
        if indexer is not None:
            return self._slice(indexer, axis=0)
```
further.

**Comment by plammens** [comment]
> @plammens can you double check the output of your first block? I think the `test1`, `test2`, etc. should be `t1`, `t2`.

Yep, I forgot to edit that.

As for the inconsistencies, are there any reasons why `df[key]` doesn't delegate to `df.loc[:, key]` when `key` is one of  the types interpreted as column indexers and to `df.loc[key, :]` when `key` is one of the types interpreted as row indexing?  (Or `iloc` if appropriate?) Other cases can be managed separately (as when indexing with a boolean `DataFrame`), but I don't see why those first two cases are handled separately, causing inconsistencies like this one.

**Comment by TomAugspurger** [comment]
> are there any reasons why df[key] doesn't delegate to df.loc[:, key] when key is one of the types interpreted as column indexers and to df.loc[key, :] when key is one of the types interpreted as row indexing? 

I'm not sure. Probably just history / edge cases, but hard to say.

**Comment by JeffMII** [comment]
Pandas does a lot of great things, but it also has a lot of inconsistencies. With large and complex datasets, it can be difficult to deal with. Specifically, DataFrame.loc can either result in another DataFrame if there are multiple rows in the result, or a Series if there is only one row. Since we're supposed to use DataFrame.iloc and Series.iloc to access individual rows or Scalars, it causes problems. It would be a lot better if DataFrame.loc always resulted in another DataFrame, Series.loc always resulted in another Series, DataFrame.iloc always resulted in a Series, and Series.iloc always resulted in a Scalar, even if the results only have a length of one respectively.
