### ISSUE TITLE
Incompatiblle min/max function with Rolling

### ISSUE THREAD

**Issue by JayMan91** [pandas-dev/pandas#26539]
index | date |time | value
-- | -- | -- | --
0|2018-05-03 | 09:16:00 | 1.194844e-07
1|2018-05-03 | 09:17:00 | 1.834664e-08
2|2018-05-03 | 09:18:00 | 3.856525e-07
3|2018-05-03 | 09:19:00 | 1.173971e-06
4|2018-05-03 | 09:20:00 | 5.734758e-07

I have dataframe with 3 columns. I want to calculate rolling sum of 15 consecutive observations and minimum  time of those 15 observations. 
 

```python
df.rolling(15).agg({'value':[sum]}) # works fine for the rolling sum
```
 
  | sum
-- | --
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
6.467453e-06

But when I include the min function:
```python
df.rolling(15).agg({'value':[sum],'time':[min]})
# throws  value error( show details)
```
But if the minimum of a number (float/integer) is asked, code works fine.
```python
df.rolling(15).agg({'value':[sum,min]}) # works fine
```
Also min function works seamlessly with date and time outside rolling window.

<details>

~/anaconda3/lib/python3.7/site-packages/pandas/core/window.py in aggregate(self, arg, *args, **kwargs)
   1683     @Appender(_shared_docs['aggregate'])
   1684     def aggregate(self, arg, *args, **kwargs):
-> 1685         return super(Rolling, self).aggregate(arg, *args, **kwargs)
   1686 
   1687     agg = aggregate

~/anaconda3/lib/python3.7/site-packages/pandas/core/window.py in aggregate(self, arg, *args, **kwargs)
    310 
    311     def aggregate(self, arg, *args, **kwargs):
--> 312         result, how = self._aggregate(arg, *args, **kwargs)
    313         if result is None:
    314             return self.apply(arg, raw=False, args=args, kwargs=kwargs)

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    496 
    497                 try:
--> 498                     result = _agg(arg, _agg_1dim)
    499                 except SpecificationError:
    500 

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _agg(arg, func)
    447                 result = compat.OrderedDict()
    448                 for fname, agg_how in compat.iteritems(arg):
--> 449                     result[fname] = func(fname, agg_how)
    450                 return result
    451 

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _agg_1dim(name, how, subset)
    430                     raise SpecificationError("nested dictionary is ambiguous "
    431                                              "in aggregation")
--> 432                 return colg.aggregate(how, _level=(_level or 0) + 1)
    433 
    434             def _agg_2dim(name, how):

~/anaconda3/lib/python3.7/site-packages/pandas/core/window.py in aggregate(self, arg, *args, **kwargs)
   1683     @Appender(_shared_docs['aggregate'])
   1684     def aggregate(self, arg, *args, **kwargs):
-> 1685         return super(Rolling, self).aggregate(arg, *args, **kwargs)
   1686 
   1687     agg = aggregate

~/anaconda3/lib/python3.7/site-packages/pandas/core/window.py in aggregate(self, arg, *args, **kwargs)
    310 
    311     def aggregate(self, arg, *args, **kwargs):
--> 312         result, how = self._aggregate(arg, *args, **kwargs)
    313         if result is None:
    314             return self.apply(arg, raw=False, args=args, kwargs=kwargs)

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    557             return self._aggregate_multiple_funcs(arg,
    558                                                   _level=_level,
--> 559                                                   _axis=_axis), None
    560         else:
    561             result = None

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _aggregate_multiple_funcs(self, arg, _level, _axis)
    615         # if we are empty
    616         if not len(results):
--> 617             raise ValueError("no results")
    618 
    619         try:

ValueError: no results

</details>

**Comment by WillAyd** [comment]
Can you please make the code to reproduce copy/pastable?

**Comment by JayMan91** [comment]
It is only one line command
```python
df.rolling(15).agg({'value':[sum],'time':[min]})

```
where time is column of object type time.

**Comment by TomAugspurger** [comment]
@JayMan91 see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by JayMan91** [comment]
The following code :
```python
import pandas as pd
df = pd.DataFrame({'time': ['09:16:00', '09:17:00', '09:15:00','09:20:00',
                                    '09:16:00','09:19:00','09:21:00','09:28:00','09:16:00',
                                    '09:22:00','09:24:00','09:16:00'],
                   'value': [i for i in range(2,14)],
                   'date': ['2018-05-03']*12})
df.time = pd.to_datetime(df.time,format= '%H:%M:%S' ).dt.time
df.date = pd.to_datetime(df.date)
df.rolling(4).agg({'value':[sum],'time':[min]})

```

**Comment by TomAugspurger** [comment]
Thanks, can you add that to the original post for ease of reference?

Are you interested in debugging this?

**Comment by JayMan91** [comment]
Yes any help in debugging would be appreciated

**Comment by TomAugspurger** [comment]
It looks like SelectionMixin._aggregate in core/base.py isn't returning
anything. I would drop a pdb in there and see why.
May want to look at `roll_min` too.

It's possible / probable that we're trying to pass an ndarray of objects to
Cython and that's raising. Not sure.

**Comment by phofl** [comment]
Should that even work? When I execute this now, I get

```
Traceback (most recent call last):
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 416, in _aggregate
    result = _agg(arg, _agg_1dim)
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 383, in _agg
    result[fname] = func(fname, agg_how)
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 367, in _agg_1dim
    return colg.aggregate(how)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 2040, in aggregate
    return super().aggregate(func, *args, **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 608, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 483, in _aggregate
    return self._aggregate_multiple_funcs(arg, _axis=_axis), None
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 513, in _aggregate_multiple_funcs
    new_res = colg.aggregate(a)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 2040, in aggregate
    return super().aggregate(func, *args, **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 608, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/base.py", line 489, in _aggregate
    return getattr(self, f)(), None
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 2088, in min
    return super().min(*args, **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 1489, in min
    return self._apply(window_func, center=self.center, name="min", **kwargs)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 605, in _apply
    return self._apply_blockwise(homogeneous_func)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 490, in _apply_blockwise
    return self._apply_series(homogeneous_func)
  File "/home/developer/PycharmProjects/pandas/pandas/core/window/rolling.py", line 477, in _apply_series
    raise DataError("No numeric types to aggregate") from err
pandas.core.base.DataError: No numeric types to aggregate
```

for the time column

**Comment by WillAyd** [comment]
@phofl yea this should work - not sure what is tripping it up at the moment but any investigation is certainly welcome
