### ISSUE TITLE
If tuples used as index pd.read_json( orient='split') does not read file saved by df.to_json(orient='split)

### ISSUE THREAD

**Issue by achatrian** [pandas-dev/pandas#26692]
#### Code Sample, a copy-pastable example if possible
```python
a = pd.DataFrame()
a['example'] = [0, 1 ,2, 3 ,4 ,5 ,6]
a.index = [(i, i) for i in range(7)]
a.to_json('test2.json', orient='split')
b = pd.read_json('test2.json', orient='split')
```
#### Problem description

After using tuples as index and saving DataFrame with orient='split', error is thrown during loading via pd.read_json( orient='split').

Full traceback:
--------------------------------------------------------
ValueError             Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1666         blocks = form_blocks(arrays, names, axes)
-> 1667         mgr = BlockManager(blocks, axes)
   1668         mgr._consolidate_inplace()

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in __init__(self, blocks, axes, do_integrity_check)
    113         if do_integrity_check:
--> 114             self._verify_integrity()
    115 

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in _verify_integrity(self)
    310             if block._verify_integrity and block.shape[1:] != mgr_shape[1:]:
--> 311                 construction_error(tot_items, block.shape[1:], self.axes)
    312         if len(self.items) != tot_items:

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in construction_error(tot_items, block_shape, axes, e)
   1690     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 1691         passed, implied))
   1692 

ValueError: Shape of passed values is (7, 1), indices imply (3, 1)

During handling of the above exception, another exception occurred:

ValueError             Traceback (most recent call last)
<ipython-input-36-f5b064e2d9e4> in <module>
      3 a.index = [(i, i, i) for i in range(7)]
      4 a.to_json('test2.json', orient='split')
----> 5 b = pd.read_json('test2.json', orient='split')

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/json.py in read_json(path_or_buf, orient, typ, dtype, convert_axes, convert_dates, keep_default_dates, numpy, precise_float, date_unit, encoding, lines, chunksize, compression)
    425         return json_reader
    426 
--> 427     result = json_reader.read()
    428     if should_close:
    429         try:

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/json.py in read(self)
    535             )
    536         else:
--> 537             obj = self._get_object_parser(self.data)
    538         self.close()
    539         return obj

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/json.py in _get_object_parser(self, json)
    554         obj = None
    555         if typ == 'frame':
--> 556             obj = FrameParser(json, **kwargs).parse()
    557 
    558         if typ == 'series' or obj is None:

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/json.py in parse(self)
    650 
    651         else:
--> 652             self._parse_no_numpy()
    653 
    654         if self.obj is None:

~/anaconda3/lib/python3.7/site-packages/pandas/io/json/json.py in _parse_no_numpy(self)
    874                 loads(json, precise_float=self.precise_float))}
    875             self.check_keys_split(decoded)
--> 876             self.obj = DataFrame(dtype=None, **decoded)
    877         elif orient == "index":
    878             self.obj = DataFrame(

~/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    446 
    447                     mgr = arrays_to_mgr(arrays, columns, index, columns,
--> 448                                         dtype=dtype)
    449                 else:
    450                     mgr = init_ndarray(data, index, columns, dtype=dtype,

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     59     axes = [ensure_index(columns), index]
     60 
---> 61     return create_block_manager_from_arrays(arrays, arr_names, axes)
     62 
     63 

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1669         return mgr
   1670     except ValueError as e:
-> 1671         construction_error(len(arrays), arrays[0].shape, axes, e)
   1672 
   1673 

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in construction_error(tot_items, block_shape, axes, e)
   1689         raise ValueError("Empty data passed with indices specified.")
   1690     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 1691         passed, implied))
   1692 
   1693 

ValueError: Shape of passed values is (7, 1), indices imply (2, 1)

2 in last tuple is number of elements of tuples I use as index.

#### Expected Output

b = a -- dataframe with same content as a

        example
(0, 0)    0
(1, 1)    1
(2, 2)    2
(3, 3)    3
(4, 4)    4
(5, 5)    5
(6, 6)    6

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: 4.5.0
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: 2.0.1
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.3
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by WillAyd** [comment]
Thanks for the report. Would certainly welcome investigation into the error though a Tuple is not something that can be guaranteed to roundtrip losslessly as the concept of that does not exist in JSON

**Comment by MicaelJarniac** [comment]
I've had what I believe was the same issue, but with a MultiIndex:

`df`:
```
               x                     y                     z          
               f         m           f         m           f         m
harm                                                                  
1      20.195632  0.000223   20.448604  0.000258   19.141580  0.000339
2      38.030188  0.000240   40.559912  0.000202   38.325323  0.000486
3      58.942575  0.000162   61.767434  0.000152   60.207437  0.000313
4      79.644152  0.000171   78.210642  0.000141   78.337128  0.000213
5     101.652753  0.000129  101.357619  0.000113  101.863564  0.000212
```

`print(df.to_json(orient="split", indent=2))`:
<details>
<summary>Show</summary>

```json
{
  "columns":[
    [
      "x",
      "f"
    ],
    [
      "x",
      "m"
    ],
    [
      "y",
      "f"
    ],
    [
      "y",
      "m"
    ],
    [
      "z",
      "f"
    ],
    [
      "z",
      "m"
    ]
  ],
  "index":[
    1,
    2,
    3,
    4,
    5
  ],
  "data":[
    [
      20.1956320094,
      0.0002228482,
      20.4486044354,
      0.0002580977,
      19.1415802344,
      0.0003394854
    ],
    [
      38.0301880428,
      0.0002402415,
      40.5599123029,
      0.0002019173,
      38.3253225398,
      0.0004859068
    ],
    [
      58.9425752593,
      0.0001624382,
      61.7674340164,
      0.000151864,
      60.2074373893,
      0.0003132975
    ],
    [
      79.6441521208,
      0.0001710509,
      78.2106417067,
      0.0001407802,
      78.3371279197,
      0.0002133032
    ],
    [
      101.6527531832,
      0.0001290145,
      101.3576186862,
      0.0001134344,
      101.8635635382,
      0.000212252
    ]
  ]
}
```
</details>

```python
my_json_string = df.to_json(orient="split")

pd.read_json(my_json_string, orient="split")
```

</details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "c:\Users\Micael Jarniac\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 416, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    dff = pd.read_json(split, orient="split")
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\venv\dev\lib\site-packages\pandas\util\_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "...\venv\dev\lib\site-packages\pandas\util\_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "...\venv\dev\lib\site-packages\pandas\io\json\_json.py", line 618, in read_json
    result = json_reader.read()
  File "...\venv\dev\lib\site-packages\pandas\io\json\_json.py", line 755, in read
    obj = self._get_object_parser(self.data)
  File "...\venv\dev\lib\site-packages\pandas\io\json\_json.py", line 777, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "...\venv\dev\lib\site-packages\pandas\io\json\_json.py", line 886, in parse
    self._parse_no_numpy()
  File "...\venv\dev\lib\site-packages\pandas\io\json\_json.py", line 1127, in _parse_no_numpy
    self.obj = DataFrame(dtype=None, **decoded)
  File "...\venv\dev\lib\site-packages\pandas\core\frame.py", line 509, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "...\venv\dev\lib\site-packages\pandas\core\internals\construction.py", line 524, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "...\venv\dev\lib\site-packages\pandas\core\internals\construction.py", line 564, in _list_to_arrays
    columns = _validate_or_indexify_columns(content, columns)
  File "...\venv\dev\lib\site-packages\pandas\core\internals\construction.py", line 702, in _validate_or_indexify_columns
    raise ValueError(
ValueError: 2 columns passed, passed data had 6 columns
```
</details>
