### ISSUE TITLE
ImportError: cannot import name 'Timedelta'

### ISSUE THREAD

**Issue by CapitalZe** [pandas-dev/pandas#26690]
#### Code Sample, a copy-pastable example if possible

```python
# X@ubuntu:~/Desktop$ pylivetrader run -f algo.py --backend-config config.yaml


```
#### Problem description

I'm trying to run pylivetrader locally in a conda environment with all requisites met, so far as I can see.
Pandas continually fails.

I have tried multiple Pandas versions and explored both the help sections here as well as thoroughly searched online for possible solutions.

I believe there is a conflict of Pandas versions going on, but based on the output of ``pd.show_versions()``, as I detail below, I'm not quite sure what is going on.

#### Expected Output

I expect pylivetrader to be able to run the algo.py, instead I am faced with ``` ImportError: cannot import name 'Timedelta' ```.

#### Output of ``pd.show_versions()``

Furthermore, the output of the above is:

details>

 ```AttributeError: module 'pandas' has no attribute 'show_versions'```

However, if I run ```conda list``` in the specific env then I see that:

```  pandas                    0.24.2           py37he6710b0_0  ```

/details>
 ```
Traceback (most recent call last):
  File "/home/X.local/bin/pylivetrader", line 7, in <module>
    from pylivetrader.__main__ import main
  File "/home/X/.local/lib/python3.5/site-packages/pylivetrader/__init__.py", line 16, in <module>
    from pylivetrader import api # noqa
  File "/home/X/.local/lib/python3.5/site-packages/pylivetrader/api.py", line 25, in <module>
    from pylivetrader.finance.asset_restrictions import (
  File "/home/X/.local/lib/python3.5/site-packages/pylivetrader/finance/asset_restrictions.py", line 20, in <module>
    import pandas as pd
  File "/home/X/.local/lib/python3.5/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/frame.py", line 66, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/generic.py", line 43, in <module>
    from pandas.core.internals import BlockManager
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/internals/__init__.py", line 2, in <module>
    from .blocks import (  # noqa:F401
  File "/home/X/.local/lib/python3.5/site-packages/pandas/core/internals/blocks.py", line 11, in <module>
    from pandas._libs.tslibs import Timedelta, conversion, is_null_datetimelike
ImportError: cannot import name 'Timedelta'
```

**Comment by jbrockmendel** [comment]
Can you import pandas independent of pylivetrader?  i.e. just `import pandas as pd`?

Did you install pandas via conda?

**Comment by CapitalZe** [comment]
I just tried your suggestion using ipython within my conda env:

```
In [1]: import pandas as pd                                                     
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7dd3504c366f> in <module>
----> 1 import pandas as pd

~/.local/lib/python3.5/site-packages/pandas/__init__.py in <module>
     40 import pandas.core.config_init
     41 
---> 42 from pandas.core.api import *
     43 from pandas.core.sparse.api import *
     44 from pandas.tseries.api import *

~/.local/lib/python3.5/site-packages/pandas/core/api.py in <module>
      8 from pandas.core.dtypes.missing import isna, isnull, notna, notnull
      9 from pandas.core.arrays import Categorical
---> 10 from pandas.core.groupby.groupby import Grouper
     11 from pandas.io.formats.format import set_eng_float_format
     12 from pandas.core.index import (Index, CategoricalIndex, Int64Index,

~/.local/lib/python3.5/site-packages/pandas/core/groupby/__init__.py in <module>
      1 # flake8: noqa
----> 2 from pandas.core.groupby.groupby import (
      3     Grouper, GroupBy, SeriesGroupBy, DataFrameGroupBy
      4 )

~/.local/lib/python3.5/site-packages/pandas/core/groupby/groupby.py in <module>
     47                                CategoricalIndex, _ensure_index)
     48 from pandas.core.arrays import ExtensionArray, Categorical
---> 49 from pandas.core.frame import DataFrame
     50 from pandas.core.generic import NDFrame, _shared_docs
     51 from pandas.core.internals import BlockManager, make_block

~/.local/lib/python3.5/site-packages/pandas/core/frame.py in <module>
     64 
     65 
---> 66 from pandas.core.generic import NDFrame, _shared_docs
     67 from pandas.core.index import (Index, MultiIndex, _ensure_index,
     68                                _ensure_index_from_sequences)

~/.local/lib/python3.5/site-packages/pandas/core/generic.py in <module>
     41 from pandas.core.indexes.datetimes import DatetimeIndex
     42 from pandas.core.indexes.period import PeriodIndex, Period
---> 43 from pandas.core.internals import BlockManager
     44 import pandas.core.algorithms as algos
     45 import pandas.core.common as com

~/.local/lib/python3.5/site-packages/pandas/core/internals/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from .blocks import (  # noqa:F401
      3     _block2d_to_blocknd, _factor_indexer, _block_shape,  # io.pytables
      4     _safe_reshape,  # io.packers
      5     make_block,     # io.pytables, io.packers

~/.local/lib/python3.5/site-packages/pandas/core/internals/blocks.py in <module>
      9 
     10 from pandas._libs import internals as libinternals, lib, tslib, tslibs
---> 11 from pandas._libs.tslibs import Timedelta, conversion, is_null_datetimelike
     12 import pandas.compat as compat
     13 from pandas.compat import range, zip

ImportError: cannot import name 'Timedelta'```

Yes, it is installed via conda.

Thanks!

**Comment by CapitalZe** [comment]
Interestingly, if I run the pylivertrader script outside of Pandas then I am confronted with this Pandas error instead:

`    from pandas.tseries.holiday import AbstractHolidayCalendar
ModuleNotFoundError: No module named 'pandas.tseries'
`

**Comment by jbrockmendel** [comment]
OK, let's stay optimistic and try some potential easy fixes.  Is it fixed if you do a conda reinstall?

If that doesn't work I'll ask you to try with a virtualenv instead of a conda environment.

It looks like you're on Ubuntu.  What version?  Does it happen to be an obscure architecture?

**Comment by CapitalZe** [comment]
Thank you very much for the input.

I am using Ubuntu 16.04 on VMWare running on a Mac.

I tried your suggestions and the virtuanenv worked.

I simply created a venv as you suggested:

`virtualenv --no-site-packages venv
. venv/bin/activate
pip install ipython`

I then installed pandas and pylivetrader via pip and it worked right away.

What could be causing the failure via Conda?

**Comment by jbrockmendel** [comment]
> What could be causing the failure via Conda?

Best guess is it involves Ubuntu/VMWare/Mac setup, emphasis on "guess".  cc @jreback

**Comment by CapitalZe** [comment]
It works for what I need this way. Many thanks.

Will close.
