### ISSUE TITLE
Error importing name 'DataFrame' from 'pandas.core.api'

### ISSUE THREAD

**Issue by connerpate** [pandas-dev/pandas#26798]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas
```
#### Problem description

Whenever I run a script containing pandas, I get the following error:

Traceback (most recent call last):
  File "csv.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\api.py", line 26, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.groupby import GroupBy  # noqa: F401
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\groupby\groupby.py", line 37, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\frame.py", line 87, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\generic.py", line 49, in <module>
    from pandas.io.formats.format import DataFrameFormatter, format_percentiles
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\io\formats\format.py", line 34, in <module>
    from pandas.io.common import _expand_user, _stringify_path
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\io\common.py", line 5, in <module>
    import csv
  File "C:\Users\conne\Documents\Work\Career & New Jobs\2019\button\csv.py", line 2, in <module>
    import pandasql as ps
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandasql\__init__.py", line 1, in <module>
    from .sqldf import *
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandasql\sqldf.py", line 3, in <module>
    from pandas.io.sql import to_sql, read_sql
  File "C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\io\sql.py", line 26, in <module>
    from pandas.core.api import DataFrame, Series
ImportError: cannot import name 'DataFrame' from 'pandas.core.api' (C:\Users\conne\Anaconda3\envs\asdf\lib\site-packages\pandas\core\api.py)

I am currently using the Anaconda Python distribution with the most recent version of pandas, but I've also used all combinations of the following:
 - Python 3.7.3
 - pandas 0.23
 - pandas 0.24

Additionally, I've uninstalled and reinstalled pandas (using pip) and Python, and I just finished resetting Windows 10 on my machine, to no avail.

Interestingly, I am able to import pandas in a command line interface with no issue.

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by WillAyd** [comment]
It looks like your script might be messing up import cycles by doing `import pandasql as ps`. Does removing that fix it?

**Comment by connerpate** [comment]
Just updating this script to contain _only_ "import pandas as pd" still yields this error. However, copying the "import pandas as pd" script to a different folder and running from the new location was successful.

**Comment by connerpate** [comment]
Did naming pandasql 'ps' mess with something?

**Comment by TomAugspurger** [comment]
The standard library has a module named `csv`, which may be throwing things off. Try renaming your file to `csv_.py`

**Comment by connerpate** [comment]
Works. Thank you so much.
