### ISSUE TITLE
Missing FIle for Indexing

### ISSUE THREAD

**Issue by liamward14** [pandas-dev/pandas#26907]
#### Code Sample, a copy-pastable example if possible
##Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

def read_data():
    file_name = 'temperature_2017.csv'
    data = pd.read_csv(file_name)
    df = pd.DataFrame(data,columns=['timestamp', 'temperature'])
    #print(df) #display data
    return df

data = read_data()

def plot_data(df):
    fig, axes = plt.subplots()
    x_data = df.loc['timestamp']
    y_data = df.loc['temperature']
    plt.plot(x_data,y_data,'--r')
    plt.show()

plot_data(data)

Issue Description: I get an error whenever I try to index a dataframe using df.loc[] - stating that "index_class_helper.pxi' file does not exist. Here is the error: 

Traceback (most recent call last):
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 129, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\liamw\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\liamw\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\liamw\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\liamw\Python\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\liamw\Python\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\liamw\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\liamw\OneDrive\McMasterUniversity\2019-2020 School Year\SpringSummerProjects\DataScience\bee_temp.py", line 28, in <module>
    plot_data(data)
  File "c:\Users\liamw\OneDrive\McMasterUniversity\2019-2020 School Year\SpringSummerProjects\DataScience\bee_temp.py", line 23, in plot_data
    x_data = df.loc['timestamp']
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\liamw\Python\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 129, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
KeyError: 'timestamp'

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
Should output a series based on my selection from the dataframe

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by mroeschke** [comment]
`.loc` is specified by `.loc[index_labels, column_labels]`. `'timestamp'`,` 'temperature'` are both column labels.

For usage questions, please consult the docs or StackOverflow.
