### ISSUE TITLE
Building pandas complains missng algos.c

### ISSUE THREAD

**Issue by soilstack** [pandas-dev/pandas#27038]
#### Code Sample, a copy-pastable example if possible
Want to create a pull-request to solve [another Issue I filed last week](https://github.com/pandas-dev/pandas/issues/26944).   Am trying to follow the [pandas-dev instructions for creating a development environment](https://dev.pandas.io/development/contributing.html#working-with-the-code).  

I have installed VisualStudio2019 with the `Python development workload` and the `Python native development tools` options.  I can launch Visual Studio from the Start Menu.

I am using a fresh conda virtualenv which does not have pandas installed.    I then forked and cloned the pandas repository.   I am working in a python `3.7.3` installation

The next step fails

```python
(pandafix) PS C:\Users\kanugu\code\pfix\pandas-soilstack> python .\setup.py build_ext --inplace -j 4
running build_ext
pandas._libs.algos: -> [['pandas\\_libs/algos.c']]
Traceback (most recent call last):
  File ".\setup.py", line 787, in <module>
    **setuptools_kwargs)
  File "C:\Users\kanugu\.conda\envs\pandafix\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\kanugu\.conda\envs\pandafix\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\kanugu\.conda\envs\pandafix\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\kanugu\.conda\envs\pandafix\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\kanugu\.conda\envs\pandafix\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File ".\setup.py", line 377, in build_extensions
    self.check_cython_extensions(self.extensions)
  File ".\setup.py", line 374, in check_cython_extensions
    """.format(src=src))
Exception: Cython-generated file 'pandas\_libs/algos.c' not found.
                Cython is required to compile pandas from a development branch.
                Please install Cython or download a release package of pandas.
```
#### Problem description

I am not sure where the problem originates from.   Some issue with the source?  Cannot find VisualStudio? Something else?  

#### Output of ``pd.show_versions()``

Am using `python 3.7.3`

**Comment by soilstack** [comment]
Sorry, i realized I didn't create a conda environment with the `environment.yml` that comes with the pandas source....
