### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__

### ISSUE THREAD

**Issue by bilalghanem** [pandas-dev/pandas#27244]
While I was saving large dataframe I got this error!
the dataframe contains two string columns and one has lists of words.

```python
1840679it [1:16:28, 401.19it/s]
Traceback (most recent call last):
  File ".../main.py", line 15, in <module>
    data.load_data()
  File ".../data.py", line 118, in load_data
    self.tweets.to_pickle(join(self.path, 'tweets_0'))
  File "C:\Python35\lib\site-packages\pandas\core\generic.py", line 2593, in to_pickle
    protocol=protocol)
  File "C:\Python35\lib\site-packages\pandas\io\pickle.py", line 77, in to_pickle
    f.write(pkl.dumps(obj, protocol=protocol))
  File "stringsource", line 2, in spacy.tokens.span.Span.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__

```

**Comment by jreback** [comment]
the error is coming from Spacy

you should post an actual reproducible example there
