### ISSUE TITLE
DataFrame.copy(), at least, should be threadsafe

### ISSUE THREAD

**Issue by bshanks** [pandas-dev/pandas#2728]
dataframe.copy() should happen atomically/be threadsafe, meaning that it should produce a consistent dataframe even if the call to .copy() is made while another thread is deleting entries from the dataframe, or if another thread calls a deletion method while the call to .copy() is working (in other words, i guess .copy() should acquire a lock that prevents mutation during the copy). That is, the following code, which crashes in 0.7.3, should succeed:

``` python

import pandas
import threading

df = pandas.DataFrame()

def mutateDf(df):
    while True:
        df[0] = pandas.Series([1,2,3])
        del df[0]

def readDf(df):
    while True:
        dfCopy = df.copy()
        if 0 in dfCopy and 1 in dfCopy[0]:
            a = dfCopy[0][1]

t1 = threading.Thread(target=mutateDf, args=(df,))
t2 = threading.Thread(target=readDf, args=(df,))

t1.start()
t2.start()
```

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<ipython-input-5-8aef72c7f1b4>", line 4, in readDf
    if 0 in dfCopy and 1 in dfCopy[0]:
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.7.3-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 1458, in __getitem__
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.7.3-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 294, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.7.3-py2.7-linux-x86_64.egg/pandas/core/internals.py", line 625, in get
    _, block = self._find_block(item)
TypeError: 'NoneType' object is not iterable
```

**Comment by kokes** [comment]
I cannot replicate the error posted, see [this gist](https://gist.github.com/kokes/b51cf3cf5172f5c6b23b). Either there have been new developments in atomicity of `pandas` or perhaps `threading` has a different scheduler, or...?

(Tried under both Python 2.7 and 3.5)

**Comment by jreback** [comment]
this almost certainly had to do with the unsafe-threadness (is that a word?) with ``numexpr``. ``numexpr>=2.5`` (and even ``>=2.4.6``) now don't much with the global thread state. @kokes what version do you have?

**Comment by kokes** [comment]
Good! I've got 2.4.6 (under conda), upgraded to 2.5 and got the same.

**Comment by stuz5000** [comment]
> copy might be thread safe with a single dtype (but prob not)
> multiple dtypes now are not thread safe
> (as @wes points out a lock will fix all this)
> I would be in favor of providing this as an option, default to False though

Doubtful:

https://github.com/pandas-dev/pandas/issues/25870

... fails on the second call to Series.reindex.

**Comment by stuz5000** [comment]
... to be clear, it seems that .copy is not safe, even if no-one else it writing.

**Comment by stuz5000** [comment]
I'm deeply confused about this issue.
The original discussion was that .copy is not thread safe. My assumption was that it would not be, because someone may be writing to the dataframe. However, is .copy also unsafe in other situations (where no-one is performing impure functional operations, such as modifying the columns/index/labels/cells of a dataframe or series)?

I ask because, my expectation is that `Series.reindex(..., copy=True)` is a pure function (except for memomization of things like the internal index). Yet it is seem to not be thread safe _while no other types of operation are happening_. Copy is happening, but no-one is writing. So what?

```
s = pd.Series(...)
f(s)  # Success!

# Thread 1:
   while True: f(s)  

# Thread 2:
   while True: f(s)  # BANG! Exception !
```
... where ` f(s): s.reindex(..., copy=True)`. Can the thread-unsafeness of `.copy` really the cause?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Why is threading usefull with Pandas?
Threading helps when you have to much IO things.

But with Pandas you do a lot of CPU stuff. In that case multiprocessing would be much better - if you have enough RAM.

**Comment by stuz5000** [comment]
There are lots of reasons to want threading that are unrelated to IO. In
fact, in most languages *except* Python threading is the first choice for
parallelism.
In my use case, I was hoping to use Pandas to hold a large static datatable
(~8Gb) to answer optimized web requests (where a database would have been
excessively slow).
Python's forking/spawning of separate processes can carry excessive
overheads shifting data between the processes, or try-as-you-might
copy-on-write ends up consuming a lot of memory if you have a lot of
processes.
If your data-access is shared-access-read-only, being able to access it in
a threaded fashion is optimal. Threading is frowned upon in Python
circles only because it hasn't been able to shake itself of the unresolved
GIL design bug. However, the GIL is a non-issue for me because most of the
heavy-lifting can be done by C code not involved with the interpreter.

As for Pandas, it's not threadsafe is in any sense that you can rely on.
Not even for read-only use cases, because pandas is not read-only, even
when for reading-type operations.
https://stackoverflow.com/questions/13592618/python-pandas-dataframe-thread-safe/55382886#55382886

- Stuart

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks for your thoughts which help to dive more into Panda-thinking. ;)

I am aware of Pythons "GIL-problem". But in some cases it can be used as an advantage. E.g. in the context of non-thread-safe Pandas I have to multiply the data between the processes and do not have to think about race conditions anymore.

But am I right to say that threads are running always on the same CPU core, no matter which language (C, Python) they are from, right?

> There are lots of reasons to want threading that are unrelated to IO.
> In fact, in most languages *except* Python threading is the first
> choice for parallelism.

It is not "parallel" when running on the same Core - IMHO.

> In my use case, I was hoping to use Pandas to hold a large static datatable (~8Gb) to answer optimized web requests

That is a nice IO use case. Web requests are IO because the thread has to wait a lot of time for the data.

**Comment by stuz5000** [comment]
> It is not "parallel" when running on the same Core - IMHO.
>
That is true for the Python interpreter only. Generally, threads of a
single process can use multiple cores, and vectorized code (called from
Python) can make use of multiple cores.


In my use case, I was hoping to use Pandas to hold a large static datatable
> (~8Gb) to answer optimized web requests
>
> That is a nice IO use case. Web requests are IO because the thread has to
> wait a lot of time for the data.
>
In my case, Python was the database. I had static data and the need to
aggregate and process some 100’s of thousands of records for each request.
SQL doesn’t an provide efficient query language for large matrix operations
(our queries took under second in memory, but some minutes to run in SQL,
even with careful indexing). This case is not unusual- using pandas or
numpy to do what is too slow or cumbersome in SQL.

So, CPU bound, not IO bound, since there was no external database to wait
on.

To resolve this problem, we switched to numpy for these queries, since
pandas didn’t allow to support multiple queries safely.

**Comment by MarcoGorelli** [comment]
> I would be in favor of providing this as an option, default to False though

a decade's passed and nobody's implemented this - let's close for now then

**Comment by jbrockmendel** [comment]
Discussed briefly on this week's dev call.  My main question is whether `copy` is in some way special, or if we're inevitably going to be asked to put locks around all public APIs.

**Comment by alippai** [comment]
@jbrockmendel My expectation is that the copy() shouldn’t mutate the underlying data structure of the original DF/Series/Index. This means no locking would be needed for a read-only workload. Having pure, side-effect free functions sounds to be a smaller task than supporting threading everywhere

**Comment by allComputableThings** [comment]
My understanding is that operations that you would think are read-only are
lazy-computed and cached… although it’s not obvious to me that copy() is
the only source of mutation via “value read only/Id think this would be
idempotent” methods.

Generally speaking, an excellent pattern I’ve used in my own work with
objects that are essentially immutable - updates always return an object
with modifications as a new object. And then for lazy computation use
@cache_property everywhere, relying on its result assignment to be thread
safe (GIL and no other explicit locks). It hugely simplifies code (you
don’t have to add or check an attributes to hold the cached (the method
that computes it is the property), and there’s usually no need to consider
thread safety further in the implementation. Largely I able to totally
ignore locks and race conditions where two threads might access the
property and rely on (assume) value-idempotence of property methods (which
I can do because of the immutability assumption).
The leak in this abstraction where identity matter over value-equality.
It’s *possible* to do this in pandas… however because mutating operations
are so pervasive, I’m not sure how sensible it is. Actually I’m a little
confused how pandas handles mutating (invalidating of computed cached
views) operations, especially since handles to its numpy arrays are so
readily available in its interface.

**Comment by jbrockmendel** [comment]
> My expectation is that the copy() shouldn’t mutate the underlying data structure of the original DF/Series/Index. This means no locking would be needed for a read-only workload. Having pure, side-effect free functions sounds to be a smaller task than supporting threading everywhere

The only side effect I can think of would be a call to `_consolidate_inplace` that used to be made before some operations.  We got rid of those entirely in 2.0.  The OP example runs fine on main.

**Comment by alippai** [comment]
Maybe I found what @max-sixty noticed in xarray for a read-only workload (it's not `copy()`).
This could be in scope as a bugfix today:
```python
import pandas as pd, numpy as np, threading, traceback

print("pandas:", pd.__version__)

# Unique, immutable values
idx = pd.Index(np.arange(1_000_000, dtype=np.int64))

barrier = threading.Barrier(2)
errors = []

def worker():
    try:
        barrier.wait()  # synchronize to stress lazy engine init
        for _ in range(10000):
            idx.get_indexer(np.array([1, 2, 3, 4, 5], dtype=np.int64))
    except Exception:
        errors.append(traceback.format_exc())

t1 = threading.Thread(target=worker); t2 = threading.Thread(target=worker)
t1.start(); t2.start(); t1.join(); t2.join()

print("FAIL\n", errors[0] if errors else "PASS")
```

`copy()` needs changing the underlying and accessing dtypes in parallel to fail, this is more relevant to the discussion above, what kind of transaction or atomicity pandas wants to provide:
```python
import pandas as pd
import numpy as np
import threading
import time
import traceback

print("pandas:", pd.__version__)

# Shared DataFrame (mix numeric + object to increase reshapes)
n = 200_000
df = pd.DataFrame({
    "a": np.arange(n, dtype=np.int64),
    "obj": [[i] for i in range(n)],
})

stop = threading.Event()
first_error = []
barrier = threading.Barrier(3)  # 1 writer + 2 readers
timeout_secs = 30

def writer():
    barrier.wait()
    while not stop.is_set():
        try:
            # Reshape manager by add/drop
            df["tmp"] = np.arange(n, dtype=np.int64)
            df.drop(columns=["tmp"], inplace=True)
            # Flip dtype back and forth (new blocks)
            df["a"] = df["a"].astype(np.float64)
            df["a"] = df["a"].astype(np.int64)
            # Reassign object column (new Python objects)
            df["obj"] = [[i] for i in range(n)]
        except Exception:
            # keep stressing; reader will stop the run on first error
            pass

def reader():
    barrier.wait()
    while not stop.is_set():
        try:
            c = df.copy()
            _ = c.dtypes  # fail-fast: touch immediately after copy
        except Exception:
            if not first_error:
                first_error.append(traceback.format_exc())
                stop.set()
            break

# Launch threads
tw = threading.Thread(target=writer, daemon=True)
tr1 = threading.Thread(target=reader, daemon=True)
tr2 = threading.Thread(target=reader, daemon=True)
tw.start(); tr1.start(); tr2.start()

# Run until first error or timeout
t0 = time.time()
while not stop.is_set() and (time.time() - t0) < timeout_secs:
    time.sleep(0.01)

stop.set()
tw.join(timeout=1.0); tr1.join(timeout=1.0); tr2.join(timeout=1.0)

if first_error:
    print("FAIL (first reader traceback):\n", first_error[0])
else:
    print("PASS: no reader exceptions within time limit")
```

**Comment by jbrockmendel** [comment]
I’m not at a keyboard. What error do you get? What is being mutated?

**Comment by alippai** [comment]
The first (`idx.get_indexer()`) doesn't have mutation, just a cold, empty cache, it reliably prints:
```
pandas: 2.3.3
FAIL
 Traceback (most recent call last):
  File "/tmp/ipykernel_3365892/587165201.py", line 15, in worker
    idx.get_indexer(np.array([1, 2, 3, 4, 5], dtype=np.int64))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/pandas/core/indexes/base.py", line 3892, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

The second (`copy()`) needs mutation. It prints:
```
pandas: 2.3.3
FAIL (first reader traceback):
 Traceback (most recent call last):
  File "/tmp/ipykernel_3365892/1631107009.py", line 42, in reader
    _ = c.dtypes  # fail-fast: touch immediately after copy
        ^^^^^^^^
  File "/wq/misc/qes/common/miniconda3/envs/alippai_pandas233/lib/python3.13/site-packages/pandas/core/generic.py", line 6482, in dtypes
    data = self._mgr.get_dtypes()
  File "/wq/misc/qes/common/miniconda3/envs/alippai_pandas233/lib/python3.13/site-packages/pandas/core/internals/managers.py", line 289, in get_dtypes
    return dtypes.take(self.blknos)
           ~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: index 2 is out of bounds for axis 0 with size 2
```
As I understand, here the problem is that the dtypes are mutated on the source and that can result in invalid copied df.

**Comment by jbrockmendel** [comment]
Thanks.  I can't replicate the `idx.get_indexer` failure, but can replicate the other one.  In that one, it isn't the copy that is causing the mutation, but the other thread that is explicitly doing the mutating.  We could reasonably put a lock around `__setitem__` calls.

**Comment by alippai** [comment]
Maybe it’s fixed on main or it behaves differently on windows etc. This online sandbox produces the same on an older (2.2.3) version: https://onecompiler.com/python/43zcctrrh
