### ISSUE TITLE
CI: failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#27541]
https://travis-ci.org/pandas-dev/pandas/builds/562549143

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 257, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 67, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 79, in run_one_test
INTERNALERROR> IndexError: list index out of range
[gw2] node down: Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1374, in _save
    dispatch = self._dispatch[tp]
KeyError: <enum 'ExitCode'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1063, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 249, in <module>
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "<remote exec>", line 46, in pytest_sessionfinish
  File "<remote exec>", line 31, in sendevent
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 708, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1345, in dumps_internal
    return _Serializer().save(obj)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1363, in save
    self._save(obj)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1466, in save_tuple
    self._save(item)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 1379, in _save
    raise DumpError("can't serialize {}".format(tp))
execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>
fReplacing crashed worker gw2
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/_pytest/main.py", line 257, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/dsession.py", line 207, in worker_errordown
INTERNALERROR>     self._clone_node(node)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/dsession.py", line 290, in _clone_node
INTERNALERROR>     node = self.nodemanager.setup_node(spec, self.queue.put)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/workermanage.py", line 68, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/multi.py", line 127, in makegateway
INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_io.py", line 117, in create_io
INTERNALERROR>     return Popen2IOMaster(args, execmodel)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_io.py", line 20, in __init__
INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/execnet/gateway_base.py", line 169, in PopenPiped
INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/subprocess.py", line 729, in __init__
INTERNALERROR>     restore_signals, start_new_session)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/subprocess.py", line 1295, in _execute_child
INTERNALERROR>     restore_signals, start_new_session, preexec_fn)
INTERNALERROR> OSError: [Errno 12] Cannot allocate memory
```

**Comment by jreback** [comment]
cc @pandas-dev/pandas-core

**Comment by sameshl** [comment]
@jreback Even I am facing this on my PR https://github.com/pandas-dev/pandas/pull/27520

**Comment by TomAugspurger** [comment]
The only difference in deps between https://travis-ci.org/pandas-dev/pandas/jobs/562161384 and https://travis-ci.org/pandas-dev/pandas/jobs/562067088 is numb going from 0.44.1 to 0.45.0. I doubt that's likely to be the cause though...

**Comment by jbrockmendel** [comment]
The traceback is not super-helpful.  Maybe it would mean something to the pytest folks?
