### ISSUE TITLE
BUG: AttributeError in scripts/validate_docstrings for doc.returns[0].name

### ISSUE THREAD

**Issue by albertvillanova** [pandas-dev/pandas#27622]
#### Code Sample, a copy-pastable example if possible

```shell
python scripts/validate_docstrings.py pandas.Series.item
```
```
Traceback (most recent call last):
  File "scripts/validate_docstrings.py", line 1047, in <module>
    args.ignore_deprecated,
  File "scripts/validate_docstrings.py", line 969, in main
    result = validate_one(func_name)
  File "scripts/validate_docstrings.py", line 836, in validate_one
    errs, wrns, examples_errs = get_validation_data(doc)
  File "scripts/validate_docstrings.py", line 760, in get_validation_data
    if len(doc.returns) == 1 and doc.returns[0].name:
AttributeError: 'tuple' object has no attribute 'name'
```
#### Problem description

I get an AttributeError when running the script.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by datapythonista** [comment]
Based on the discussion in #27623 I think this can be closed.
