### ISSUE TITLE
ravel missing for IntegerArray Series

### ISSUE THREAD

**Issue by gijzelaerr** [pandas-dev/pandas#27638]
pandas version `0.24.2` on Linux.
```
import pandas
s1 = pandas.Series([1])
s2 = pandas.Series([1], dtype='Int64')
s1.ravel()
s2.ravel()
```
gives:
```
array([1])
Traceback (most recent call last):
  File "/home/gijs/Work/alliander/rpy2/.venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-82-c5c390b559b3>", line 1, in <module>
    s2.ravel()
  File "/home/gijs/Work/alliander/rpy2/.venv/lib/python3.6/site-packages/pandas/core/series.py", line 520, in ravel
    return self._values.ravel(order=order)
AttributeError: 'IntegerArray' object has no attribute 'ravel'
```

thanks!

**Comment by gijzelaerr** [comment]
This seems to be resolved in `0.25`
