### ISSUE TITLE
Conversion from Arrow to datetime not working since pandas 0.22.0

### ISSUE THREAD

**Issue by insysion** [pandas-dev/pandas#27817]
#### Code Sample

```python
import arrow
import pandas as pd

date = arrow.Arrow(2019, 8, 8)
data = {'date': [date]}
df = pd.DataFrame(data)
df.astype('<M8[ns]')
```
#### Problem description

```
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    df.astype('<M8[ns]')
  File "/lib/python3.5/site-packages/pandas/core/generic.py", line 5691, in astype
    **kwargs)
  File "/lib/python3.5/site-packages/pandas/core/internals/managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/lib/python3.5/site-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/lib/python3.5/site-packages/pandas/core/internals/blocks.py", line 534, in astype
    **kwargs)
  File "/lib/python3.5/site-packages/pandas/core/internals/blocks.py", line 633, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 690, in astype_nansafe
    return astype_nansafe(to_datetime(arr).values, dtype, copy=copy)
  File "/lib/python3.5/site-packages/pandas/core/tools/datetimes.py", line 609, in to_datetime
    result = convert_listlike(arg, box, format)
  File "/lib/python3.5/site-packages/pandas/core/tools/datetimes.py", line 302, in _convert_listlike_datetimes
    allow_object=True)
  File "/lib/python3.5/site-packages/pandas/core/arrays/datetimes.py", line 1857, in objects_to_datetime64ns
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 460, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 685, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 813, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 659, in pandas._libs.tslib.array_to_datetime
TypeError: <class 'arrow.arrow.Arrow'> is not convertible to datetime
```

#### Expected Output

DataFrame with datetime data. 

#### Output of ``pd.show_versions()``

Failing version:

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-55-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.2.1
setuptools: 39.1.0
Cython: None
numpy: 1.17.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

Working version:

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-55-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.22.0
pytest: None
pip: 19.2.1
setuptools: 39.1.0
Cython: None
numpy: 1.17.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jbrockmendel** [comment]
does arrow.Arrow subclass the stdlib datetime?

**Comment by mroeschke** [comment]
Doesn't appear so:

https://github.com/crsmithdev/arrow/blob/905850a1bd3a6c3be6ba5f0e097a09bafc7251b3/arrow/arrow.py#L21

**Comment by TomAugspurger** [comment]
Are we likely to support this? I'd rather see arrow add a way to get a datetime64[ns] or the integer equivalent, and then have the user call that before passing to pandas.

**Comment by mroeschke** [comment]
Agreed with @TomAugspurger. I don't think we should be supporting Arrow objects outright.

**Comment by jbrockmendel** [comment]
I’m still curious how it used to work.

One solution would be for Arrow to subclass datetime, otherwise requiring users to cast to something supported seems reasonable.

**Comment by mroeschke** [comment]
We might have replaced a `hasattr` check with an `isinstance` to `PyDatetime` check.

**Comment by mroeschke** [comment]
Doesn't look like there's much expectation to support arrow datetimes moving forward since they don't subclass `datetime.datetime`. Closing
