### ISSUE TITLE
BUG/ERR: pd.DataFrame.to_hdf saving yields error message 

### ISSUE THREAD

**Issue by obarnstedt** [pandas-dev/pandas#27839]
#### Code Sample, a copy-pastable example if possible 

```python 
testingthisout.to_hdf('test.h5',key='testme') 
Traceback (most recent call last): 

  File "<ipython-input-20-37a68cfcdb3c>", line 1, in <module> 
   testingthisout.to_hdf('test.h5',key='testme') 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pandas\core\generic.py", line 2377, in to_hdf 
    return pytables.to_hdf(path_or_buf, key, self, **kwargs) 

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pandas\io\pytables.py", line 273, in to_hdf 
   complib=complib) as store: 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pandas\io\pytables.py", line 466, in __init__ 
   import tables  # noqa 

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\tables\__init__.py", line 142, in <module> 
    from .tests import print_versions, test 

   File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\tables\tests\__init__.py", line 22, in <module> 
    from tables.tests.common import print_versions 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\tables\tests\common.py", line 27, in <module> 
    from pkg_resources import resource_filename 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3241, in <module> 
    @_call_aside 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside 
    f(*args, **kwargs) 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set 
    working_set = WorkingSet._build_master() 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master 
    ws = cls() 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 567, in __init__ 
    self.add_entry(entry) 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 623, in add_entry 
    for dist in find_distributions(entry, True): 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 1960, in find_distributions 
    importer = get_importer(path_item) 

    File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\pkgutil.py", line 419, in get_importer 
    importer = path_hook(path_item) 

  TypeError: expected str, bytes or os.PathLike object, not function 

``` 

#### Problem description 

Hi, 

I've been trying to debug the above error message for hours now, and it seems I'm getting stuck here. 
Whatever kind of data frame I'm producing (real data or simply just a few numbers), every time I try to save this to HDF5 (no matter the path or naming), I am receiving the above error message, whereas saving as .csv presents no problem. This error message occurs in pandas 0.25.0+138.g78c6843dc, 0.25, 0.24.2, 0.24.0, 0.23.0, but the above is from 0.24.2. I have also tried several versions of PyTables, but to no avail. 
This is on Win10, conda 4.7.11, pytables 3.5.2, Python 3.7.3.
 
Thanks in advance, everyone!
Oliver

#### Expected Output 
(a successfully saved .h5 file)
  
#### Output of ``pd.show_versions()`` 

  
<details> 

  
[paste the output of ``pd.show_versions()`` here below this line] 
pd.show_versions()
Traceback (most recent call last):

  File "<ipython-input-10-3d232a07e144>", line 1, in <module>
    pd.show_versions()

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pandas-0.25.0+138.g78c6843dc-py3.7-win-amd64.egg\pandas\util\_print_versions.py", line 99, in show_versions
    modname, raise_on_missing=False, on_version="ignore"

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pandas-0.25.0+138.g78c6843dc-py3.7-win-amd64.egg\pandas\compat\_optional.py", line 90, in import_optional_dependency
    module = importlib.import_module(name)

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\setuptools\__init__.py", line 18, in <module>
    import setuptools.version

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\setuptools\version.py", line 1, in <module>
    import pkg_resources

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3241, in <module>
    @_call_aside

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws = cls()

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 567, in __init__
    self.add_entry(entry)

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\site-packages\pkg_resources\__init__.py", line 1960, in find_distributions
    importer = get_importer(path_item)

  File "C:\Users\user-adm.BN-W-3015622\Anaconda3\envs\mouserun\lib\pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)

TypeError: expected str, bytes or os.PathLike object, not function
  

</details>

**Comment by obarnstedt** [comment]
So after uninstalling pandas, and re-installing from GitHub, pip, or conda, and re-doing the entire virtual environment, the latest installation from conda-forge (0.25.0 #py37he350917_0) seems to have done the trick.
(In the course, I also pip-installed cython and importlib, and conda-installed python-dateutil, pytz, setuptools, numexpr, bottleneck, pytables, matplotlib, xlrd before the final conda install pandas)

**Comment by obarnstedt** [comment]
I just encountered the problem again without changing the installation, after restarting the kernel and receiving the message that open H5 files were being closed. After trying several things, the problem seems to lie in an open H5 connection to our Samba fileserver (to/from which I previously saved/read H5 files), which is somehow blocking further H5 read/write. The solution was simply to disconnect and map again the fileserver drive.
