### ISSUE TITLE
Pandas 0.25.0 - “ ImportError: cannot import name 'StringIO' ” - [removed pandas.compat.]

### ISSUE THREAD

**Issue by DarkLord1111** [pandas-dev/pandas#27854]
```python
# import pandas_datareader
```
#### Problem description
Import error, probably because in version .25 pandas.compat. has been removed
#### Output 
C:\PycharmProjects\Demo\venv\Scripts\python.exe C:/PycharmProjects/Demo/stock.py
Traceback (most recent call last):
  File "C:/PycharmProjects/Demo/stock.py", line 3, in <module>
    import pandas_datareader as wb
  File "C:\PycharmProjects\Demo\venv\lib\site-packages\pandas_datareader\__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "C:\PycharmProjects\Demo\venv\lib\site-packages\pandas_datareader\data.py", line 7, in <module>
    from pandas_datareader.av.forex import AVForexReader
  File "C:\PycharmProjects\Demo\venv\lib\site-packages\pandas_datareader\av\__init__.py", line 3, in <module>
    from pandas_datareader.base import _BaseReader
  File "C:\PycharmProjects\Demo\venv\lib\site-packages\pandas_datareader\base.py", line 11, in <module>
    from pandas.compat import StringIO, bytes_to_str
ImportError: cannot import name 'StringIO'
<details>

</details>

**Comment by jreback** [comment]
this board is for pandas issues 
pls post to https://github.com/pydata/pandas-datareader

though i think this is fixed if you install the latest version
