### ISSUE TITLE
CI: Unpin 3.7.3 pins

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27867]
Seen in at least two builds: https://travis-ci.org/pandas-dev/pandas/jobs/570645656

```
$ ci/run_tests.sh
2333pytest -m "single and (not slow and not network)" -n 1 -s --strict --durations=10 --junitxml=test-data-single.xml pandas
2334ImportError while loading conftest '/home/travis/build/pandas-dev/pandas/pandas/conftest.py'.
2335pandas/__init__.py:38: in <module>
2336    "the C extensions first.".format(module)
2337E   ImportError: C extension: No module named 'pandas._libs.tslibs.conversion' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
2338The command "ci/run_tests.sh" exited with 4.
2339
```

Fixing in https://github.com/pandas-dev/pandas/pull/27868

Leaving this open to revert.

**Comment by TomAugspurger** [comment]
Although, only 6 extension modules were rebuilt


```
Build extensions and install pandas
10384.8.4
1039Compiling pandas/_libs/algos.pyx because it depends on pandas/_libs/algos_rank_helper.pxi.
1040Compiling pandas/_libs/groupby.pyx because it depends on pandas/_libs/groupby_helper.pxi.
1041Compiling pandas/_libs/hashtable.pyx because it depends on pandas/_libs/hashtable_func_helper.pxi.
1042Compiling pandas/_libs/index.pyx because it depends on pandas/_libs/index_class_helper.pxi.
1043Compiling pandas/_libs/interval.pyx because it depends on pandas/_libs/intervaltree.pxi.
1044Compiling pandas/_libs/sparse.pyx because it depends on pandas/_libs/sparse_op_helper.pxi.
1045[1/6] Cythonizing pandas/_libs/algos.pyx
1046[2/6] Cythonizing pandas/_libs/groupby.pyx
1047[3/6] Cythonizing pandas/_libs/hashtable.pyx
1048[4/6] Cythonizing pandas/_libs/index.pyx
1049[5/6] Cythonizing pandas/_libs/interval.pyx
1050[6/6] Cythonizing pandas/_libs/sparse.pyx
1051running build_ext
1052building 'pandas._libs.algos' extension
1053
```

**Comment by TomAugspurger** [comment]
Failing on azure too, so probably not related to caching

```
##[section]Starting: Test
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/08746f1c-8615-41b2-8baf-deee73677b45.sh
Traceback (most recent call last):
  File "/home/vsts/work/1/s/pandas/__init__.py", line 33, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/vsts/work/1/s/pandas/_libs/__init__.py", line 3, in <module>
    from .tslibs import (
  File "/home/vsts/work/1/s/pandas/_libs/tslibs/__init__.py", line 3, in <module>
    from .conversion import localize_pydatetime, normalize_date
ModuleNotFoundError: No module named 'pandas._libs.tslibs.conversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vsts/work/1/s/pandas/__init__.py", line 41, in <module>
    "the C extensions first.".format(module)
ImportError: C extension: No module named 'pandas._libs.tslibs.conversion' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
##[error]Bash exited with code '1'.
##[section]Finishing: Test
```

**Comment by TomAugspurger** [comment]
Probably a separate issue, but we seem to be trying to build NumPy and Scipy from source in the numpydev build. Those should be pulling in wheels.

```
Ran pip subprocess with arguments:
['/home/vsts/miniconda3/envs/pandas-dev/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/vsts/work/1/s/ci/deps/condaenv.vntic8w4.requirements.txt']
Pip subprocess output:
20171010
Looking in links: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com
Collecting git+git://github.com/dateutil/dateutil.git (from -r /home/vsts/work/1/s/ci/deps/condaenv.vntic8w4.requirements.txt (line 1))
  Cloning git://github.com/dateutil/dateutil.git to /tmp/pip-req-build-_xgk0upj
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting numpy (from -r /home/vsts/work/1/s/ci/deps/condaenv.vntic8w4.requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip (6.5MB)
Collecting scipy (from -r /home/vsts/work/1/s/ci/deps/condaenv.vntic8w4.requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'

Pip subprocess error:
  Running command git clone -q git://github.com/dateutil/dateutil.git /tmp/pip-req-build-_xgk0upj
    ERROR: Complete output from command /home/vsts/miniconda3/envs/pandas-dev/bin/python /home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpze_ebd5r:
    ERROR: setup.py:388: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-install-ova3mujl/scipy/pip-wheel-metadata'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Traceback (most recent call last):
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
        from . import multiarray
    ImportError: cannot import name 'multiarray' from 'numpy.core' (/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/core/__init__.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 155, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 234, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 141, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 481, in setup_package
        from numpy.distutils.core import setup
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
        from . import add_newdocs
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 26, in <module>
        raise ImportError(msg)
    ImportError:
    Importing the multiarray numpy extension module failed.  Most
    likely you are trying to import a failed build of numpy.
    If you're working with a numpy git repo, try `git clean -xdf` (removes all
    files not under version control).  Otherwise reinstall numpy.
    
    Original error was: cannot import name 'multiarray' from 'numpy.core' (/tmp/pip-build-env-2mfq7qm0/overlay/lib/python3.7/site-packages/numpy/core/__init__.py)
    
    ----------------------------------------
ERROR: Command "/home/vsts/miniconda3/envs/pandas-dev/bin/python /home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpze_ebd5r" failed with error code 1 in /tmp/pip-install-ova3mujl/scipy
```

**Comment by TomAugspurger** [comment]
Note: this is maybe caused by Python 3.7.4 being released on conda.

**Comment by TomAugspurger** [comment]
Maybe related: https://github.com/ContinuumIO/anaconda-issues/issues/11195

**Comment by TomAugspurger** [comment]
This is resolved.
