### ISSUE TITLE
`The default of the 'keep_tz' keyword in DatetimeIndex.to_series will change to True in a future release.`

### ISSUE THREAD

**Issue by teto** [pandas-dev/pandas#28083]
#### Code Sample, a copy-pastable example if possible

How am I supposed to turn this warning down without patching pandas ?
```
DEBUG:mptcpanalyzer.connection:Filling mptcp destinations
Traceback (most recent call last):
  File "/nix/store/a5sg76c2q39jk0lgn5bxi4vfm0j36rrx-python3.7-cmd2-0.9.17/lib/python3.7/site-packages/cmd2/cmd2.py", line 1764, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/nix/store/a5sg76c2q39jk0lgn5bxi4vfm0j36rrx-python3.7-cmd2-0.9.17/lib/python3.7/site-packages/cmd2/cmd2.py", line 2159, in onecmd
    stop = func(statement)
  File "/nix/store/a5sg76c2q39jk0lgn5bxi4vfm0j36rrx-python3.7-cmd2-0.9.17/lib/python3.7/site-packages/cmd2/cmd2.py", line 217, in cmd_wrapper
    return func(cmd2_app, args, unknown)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 1158, in do_plot
    result = plotter.run(**dataframes, **dargs)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/plot.py", line 269, in run
    fig = self.plot(*pargs, styles=styles, **kwargs)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/plots/dss.py", line 113, in plot
    df = con.fill_dest(rawdf)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/connection.py", line 336, in fill_dest
    df_dest = df.query(q, engine="python")
  File "/nix/store/mczyj76z8r6mnlkp3q71nmy2qv3mv3db-python3.7-pandas-0.25.0/lib/python3.7/site-packages/pandas/core/frame.py", line 3179, in query
    res = self.eval(expr, **kwargs)
  File "/nix/store/mczyj76z8r6mnlkp3q71nmy2qv3mv3db-python3.7-pandas-0.25.0/lib/python3.7/site-packages/pandas/core/frame.py", line 3289, in eval
    index_resolvers = self._get_index_resolvers()
  File "/nix/store/mczyj76z8r6mnlkp3q71nmy2qv3mv3db-python3.7-pandas-0.25.0/lib/python3.7/site-packages/pandas/core/generic.py", line 473, in _get_index_resolvers
    d.update(self._get_axis_resolvers(axis_name))
  File "/nix/store/mczyj76z8r6mnlkp3q71nmy2qv3mv3db-python3.7-pandas-0.25.0/lib/python3.7/site-packages/pandas/core/generic.py", line 457, in _get_axis_resolvers
    s = level_values.to_series()
  File "/nix/store/mczyj76z8r6mnlkp3q71nmy2qv3mv3db-python3.7-pandas-0.25.0/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 721, in to_series
    stacklevel=2,
FutureWarning: The default of the 'keep_tz' keyword in DatetimeIndex.to_series will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
EXCEPTION of type 'FutureWarning' occurred with message: 'The default of the 'keep_tz' keyword in DatetimeIndex.to_series will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.'
```
...since the `level_values.to_series()` call is in pandas.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.1.0
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.2.14
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
I can't reproduce with the following

```python

In [13]: df = pd.DataFrame({"A": pd.date_range('2000', periods=12, tz='UTC')})

In [14]: df.query("A > Timestamp('2000', tz='UTC')", engine="python")
Out[14]:
                           A
1  2000-01-02 00:00:00+00:00
2  2000-01-03 00:00:00+00:00
3  2000-01-04 00:00:00+00:00
4  2000-01-05 00:00:00+00:00
5  2000-01-06 00:00:00+00:00
6  2000-01-07 00:00:00+00:00
7  2000-01-08 00:00:00+00:00
8  2000-01-09 00:00:00+00:00
9  2000-01-10 00:00:00+00:00
10 2000-01-11 00:00:00+00:00
11 2000-01-12 00:00:00+00:00


```

let us know if you can provide an example.
