### ISSUE TITLE
GroupBy.rank with "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by kukuwa** [pandas-dev/pandas#28109]
#### Code Sample, a copy-pastable example if possible

```python
factor_data.groupby(grouper)['factor'].rank()

```
#### Problem description
when I use groupby.rank method , TypeError occur in "pandas\core\groupby\ops.py" file.

Traceback (most recent call last):

  File "<ipython-input-3-fdfa537b4972>", line 1, in <module>
    runfile('E:/myStra/factor/funfile/analysis/factorAnaCNE6.py', wdir='E:/myStra/factor/funfile/analysis')

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/myStra/factor/funfile/analysis/factorAnaCNE6.py", line 21, in <module>
    factor_data.groupby(grouper)['factor'].rank()

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\groupby.py", line 1846, in rank
    na_option=na_option, pct=pct, axis=axis)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\groupby.py", line 807, in _cython_transform
    **kwargs)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\ops.py", line 551, in transform
    return self._cython_operation('transform', values, how, axis, **kwargs)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\ops.py", line 511, in _cython_operation
    **kwargs)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\ops.py", line 584, in _transform
    transform_func(result, values, comp_ids, is_datetimelike, **kwargs)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\ops.py", line 397, in wrapper
    return f(afunc, *args, **kwargs)

  File "C:\ProgramData\Anaconda2\envs\py_36\lib\site-packages\pandas\core\groupby\ops.py", line 348, in <lambda>
    kwargs.get('na_option', 'keep')

TypeError: 'NoneType' object is not callable

After debugging the file I find the Error breakout in ops.py >_get_cython_function > func = afunc = get_func(ftype['name']) (line 390), return fun get a None Object. if I use "getattr(libgroupby, 'group_rank')" I find that "AttributeError: module 'pandas._libs.groupby' has no attribute 'group_rank'"

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.3.0
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: 0.9.3
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by kukuwa** [comment]
> Can you fill out the issue template with a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

I find the problem. my Code is like:
``` python
    grouper = [factor_data.index.get_level_values('date')]
    factor_data['factor'] = factor_data['factor']
    factor_data.groupby(grouper)['factor'].rank()
```
factor_data is like:
                                         D             A             ...       factor 
date              asset                                                   
2009-01-05  000001.SZ  0.060762  0.015448  ... -0.365255 
                    000002.SZ  0.029851  0.016418  ... -0.172206 
                    000005.SZ  0.031250  0.027344  ...  0.062430 
The type of columns ‘factor’ is **float**,when I change the type to  np.float64, the method work well.
new code is like:
``` python
    grouper = [factor_data.index.get_level_values('date')]
    factor_data['factor'] = factor_data['factor'].apply(pd.np.float64)
    factor_data.groupby(grouper)['factor'].rank()
```
