### ISSUE TITLE
Rolling methods should support lists

### ISSUE THREAD

**Issue by mrjbq7** [pandas-dev/pandas#2813]
Looks like the `pandas` rolling methods only support numpy arrays, while numpy and bottleneck methods also support lists for convenience:

```
>>> l = [1,2,3,4]

>>> import numpy as np
>>> np.cumsum(l)
array([ 1,  3,  6, 10])

>>> import bottleneck as bn
>>> bn.move_sum(l, 1)
array([ 1.,  2.,  3.,  4.])

>>> import pandas
>>> pandas.rolling_sum(l, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pandas-0.10.1-py2.7-linux-x86_64.egg/pandas/stats/moments.py", line 507, in f
    time_rule=time_rule, **kwargs)
  File "/usr/lib/python2.7/site-packages/pandas-0.10.1-py2.7-linux-x86_64.egg/pandas/stats/moments.py", line 281, in _rolling_moment
    return_hook, values = _process_data_structure(arg)
  File "/usr/lib/python2.7/site-packages/pandas-0.10.1-py2.7-linux-x86_64.egg/pandas/stats/moments.py", line 325, in _process_data_structure
    if not issubclass(values.dtype.type, float):
AttributeError: 'list' object has no attribute 'dtype'
```

**Comment by dsm054** [comment]
Now that we're using the `Series.rolling` interface and deprecating pd.rolling_*, I'm not sure this fits into the new API.

**Comment by jreback** [comment]
good point
