### ISSUE TITLE
BUG: descriptor 'axes' for 'BlockManager' objects doesn't apply to 'SingleBlockManager' object

### ISSUE THREAD

**Issue by ventouris** [pandas-dev/pandas#28178]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
pd.read_csv('../Data/features/data.csv')
```
#### Problem description

Trying to read a csv file with 300+ columns. The first two of them are string, 300 float numbers and the rest a boolean (0, 1). However, I get this error

```
Traceback (most recent call last):

  File "<ipython-input-20-5031bb2145ff>", line 1, in <module>
    pd.read_csv('../Data/features/ΔΙΚ4.csv')

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/io/parsers.py", line 1169, in read
    df = DataFrame(col_dict, columns=columns, index=index)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 224, in init_dict
    arrays = Series(data, index=columns, dtype=object)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/series.py", line 259, in __init__
    data, index = self._init_dict(data, index, dtype)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/series.py", line 353, in _init_dict
    s = Series(values, index=keys, dtype=dtype)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/series.py", line 313, in __init__
    data = SingleBlockManager(data, index, fastpath=True)

  File "/Users/uuser/anaconda3/envs/news/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1486, in __init__
    self.axes = [axis]

TypeError: descriptor 'axes' for 'BlockManager' objects doesn't apply to 'SingleBlockManager' object
```
I checked the csv in online validators and it passes from all of them.

#### Expected Output

The expected output would be to read the csv in a dataframe variable

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by simonjayhawkins** [comment]
@ventouris closing for now.

can you provide a reproducible example. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
