### ISSUE TITLE
import pandas not working on CentOS 7

### ISSUE THREAD

**Issue by sarathsairam** [pandas-dev/pandas#28359]
#### Code Sample, a copy-pastable example if possible
[root@rc14e00h003 recon]# python
Python 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pandas/__init__.py", line 42, in <module>
    import pandas.core.config_init
  File "/usr/lib64/python2.7/site-packages/pandas/core/config_init.py", line 13, in <module>
    import pandas.core.config as cf
  File "/usr/lib64/python2.7/site-packages/pandas/core/config.py", line 807, in <module>
    is_text = is_instance_factory((str, bytes))
  File "/usr/lib64/python2.7/site-packages/pandas/core/config.py", line 778, in is_instance_factory
    from pandas.core.common import pprint_thing
  File "/usr/lib64/python2.7/site-packages/pandas/core/common.py", line 21, in <module>
    from pandas.core.dtypes import CategoricalDtype, CategoricalDtypeType, DatetimeTZDtype, DatetimeTZDtypeType
ImportError: cannot import name CategoricalDtype

```python

Can we still post this? as in the documentation page it says pandas is only supported with python 3.6

**Comment by TomAugspurger** [comment]
The docs note that pandas 0.0.25 and higher only support Python 3.5.3 and higher: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html.

For new enough versions of pip, `pip install pandas` will give you 0.24.2 in a python 2.7 environment. If your pip is too old you'll need to manually request pandas 0.24
