### ISSUE TITLE
ImportError: Can't determine version for tables

### ISSUE THREAD

**Issue by shan224** [pandas-dev/pandas#28381]
#### This is probably some configuration issue on my end. 

```python
Traceback (most recent call last):
  File ".\utils.py", line 70, in <module>
    sql_to_hdf5(chunked_dfs)
  File ".\utils.py", line 27, in sql_to_hdf5
    store = pd.HDFStore(file_path)
  File "C:\Users\J68531\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\pytables.py", line 484, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\J68531\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 99, in import_optional_dependency
    version = _get_version(module)
  File "C:\Users\J68531\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 48, in _get_version
    raise ImportError("Can't determine version for {}".format(module.__name__))
ImportError: Can't determine version for tables

```

**Comment by WillAyd** [comment]
Can you post pd.show_versions()?

**Comment by shan224** [comment]
I created a module named "tables" and didn't see it in the directory. 
Renaming the module fixed the naming collision
