### ISSUE TITLE
AttributeError: module 'pandas.core.common' has no attribute '_unpickle_array'

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#28898]
mypy errors
```
pandas\core\frame.py:2742:23: error: Module has no attribute "_unpickle_array"  [attr-defined]
pandas\core\frame.py:2744:17: error: Module has no attribute "_unpickle_array"  [attr-defined]
pandas\core\frame.py:2751:17: error: Module has no attribute "_unpickle_array"  [attr-defined]
pandas\core\frame.py:2752:51: error: Module has no attribute "_unpickle_array"  [attr-defined]
pandas\core\frame.py:2757:45: error: Module has no attribute "_unpickle_array"  [attr-defined]
```

```python
>>> import pandas as pd
>>>
>>> pd.__version__
'0.26.0.dev0+521.g93183bab1'
>>>
>>> df = pd.DataFrame()
>>>
>>> state = df.__getstate__()
>>>
>>> state
{'_data': BlockManager
Items: Index([], dtype='object')
Axis 1: Index([], dtype='object'), '_typ': 'dataframe', '_metadata': []}
>>>
>>> df._unpickle_frame_compat(state)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas-simonjayhawkins\pandas\core\frame.py", line 2717, in _unpickle_frame_compat
    columns = com._unpickle_array(cols)
AttributeError: module 'pandas.core.common' has no attribute '_unpickle_array'
>>>
```

we don't have any tests hitting DataFrame._unpickle_frame_compat or DataFrame._unpickle_matrix_compat

https://github.com/pandas-dev/pandas/blob/f625730eb1e729a3f58b213cb31ccf625307b198/pandas/core/frame.py#L2707-L2738

can this code be removed?

**Comment by jbrockmendel** [comment]
Looks like there exists such a function in io.pickle.  I'd be pretty happy to see this untested code removed

**Comment by simonjayhawkins** [comment]
the one in io.pickle is preceded with `# compat with sparse pickle / unpickle`

**Comment by simonjayhawkins** [comment]
also in NDFrame.__setstate__ there is a `self._unpickle_panel_compat(state)` which seems iffy. so I think NDFrame.__setstate__ needs a bit of a clean.
