### ISSUE TITLE
BLD: macOS 3.5 wheel build on master started failing 

### ISSUE THREAD

**Issue by robbuckley** [pandas-dev/pandas#28954]
#### Problem description

rebuilding the last release 0.25.1 without any changes results in the macOS 3.5 build failing https://travis-ci.com/robbuckley/pandas-wheels/jobs/244876276.

This seems to be due to https://github.com/pypa/setuptools/issues/1320  / https://github.com/pypa/packaging-problems/issues/134.  A simple workaround is to install the latest pip and affected packages (only `setuptools_scm` AFAICT) before they are pulled in as `setup_requires` dependencies, as per https://github.com/pypa/packaging-problems/issues/134#issuecomment-379940442

```
Collecting pytest-forked (from pytest-xdist)

  Downloading https://files.pythonhosted.org/packages/ae/9c/8f0c51c98ee5165ff575f196662a4a314ff07c9d3de64a94580c982edcee/pytest-forked-1.1.1.tar.gz

    ERROR: Command errored out with exit status 1:

     command: /Users/travis/build/robbuckley/pandas-wheels/venv/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-bgj0_5n7/pytest-forked/setup.py'"'"'; __file__='"'"'/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-bgj0_5n7/pytest-forked/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info

         cwd: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-bgj0_5n7/pytest-forked/

    Complete output (26 lines):

    Download error on https://pypi.org/simple/setuptools_scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!

    Download error on https://pypi.org/simple/setuptools-scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!

    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)

    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!

    No local packages or working download links found for setuptools_scm

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-bgj0_5n7/pytest-forked/setup.py", line 41, in <module>

        'Programming Language :: Python :: 3.7',

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup

        _install_setup_requires(attrs)

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires

        dist.fetch_build_eggs(dist.setup_requires)

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/setuptools/dist.py", line 720, in fetch_build_eggs

        replace_conflicting=True,

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve

        replace_conflicting=replace_conflicting

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match

        return self.obtain(req, installer)

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain

        return installer(requirement)

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/setuptools/dist.py", line 787, in fetch_build_egg

        return cmd.easy_install(req)

      File "/Users/travis/build/robbuckley/pandas-wheels/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 673, in easy_install

        raise DistutilsError(msg)

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by robbuckley** [comment]
more information: its only python 3.5 builds on macOS that are affected. 

`easy_install`, used for `setup_requires` dependencies, uses the system openssl up to python 3.5. On macOS that hasnt been updated in a long while, and only supports TLS 1.1 The issue was exposed when pypi recently stopped allowing TLS<1.2. 

python.org 3.6+ builds include their own openssl build, avoiding the issue. As does pip since  version 9.something
