### ISSUE TITLE
DUVIDA

### ISSUE THREAD

**Issue by Apolinho** [pandas-dev/pandas#29003]
File "C:/Users/T-Gamer/PycharmProjects/untitled/tcc.py", line 80, in <module>
    result = df.pivot(index='c1', columns=['c2' , 'c3'], values='c4') a better solution.]

Eu preciso usar mais de uma instacia em um mapa de calor, mas da esse erro nas variaveis disponiveis..

**Comment by Apolinho** [comment]
Traceback (most recent call last):
  File "C:/Users/T-Gamer/PycharmProjects/untitled/tcc.py", line 80, in <module>
    result = df.pivot(index=['c1'], columns=['c2' , 'c3'], values=['c4'])
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\frame.py", line 5628, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\reshape\pivot.py", line 384, in pivot
    columns=values)
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\frame.py", line 424, in __init__
    copy=copy)
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\internals\construction.py", line 167, in init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\internals\managers.py", line 1660, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "C:\Users\T-Gamer\PycharmProjects\untitled\venv\lib\site-packages\pandas\core\internals\managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (4, 1), indices imply (1, 1)

**Comment by TomAugspurger** [comment]
Can you edit the post to fill out the issue template with a minimal example? It's not clear what the issue is: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mroeschke** [comment]
I think you'll want to use `pivot_table` instead of `pivot`

```
In [12]: df.pivot_table(index='c1', columns=['c2', 'c3'], values='c4')
Out[12]:
c2   0.0
c3   0.0
c1
0.0  0.0
```

If you have any followups, please post a copy-pastable example.
