### ISSUE TITLE
Installing numexpr breaks previously working pandas code

### ISSUE THREAD

**Issue by bra-fsn** [pandas-dev/pandas#29027]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({'test':[[1,2],[2,3],[3,4]], 'other': [1,2,3]}) 
df.query('other.isnull()')

```

```python
import pandas as pd

df = pd.DataFrame({'test':[[1,2],[2,3],[3,4]], 'other': [1,2,3]}) 
df[['other']].query('other.isnull()')

```

#### Problem description
The above codes fail if `numexpr` is installed on the system, and work fine if it's not.
The error depends on what I have in the `query` parameter.
If I have:
```python
df.query('other.isnull()')
```
the error is:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    df.query('other.isnull()')
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 3184, in query
    res = self.eval(expr, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 3300, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/eval.py", line 327, in eval
    ret = eng_inst.evaluate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 70, in evaluate
    res = self._evaluate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 118, in _evaluate
    _check_ne_builtin_clash(self.expr)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 27, in _check_ne_builtin_clash
    names = expr.names
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expr.py", line 850, in names
    return frozenset([self.terms.name])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 1886, in __hash__
    " hashed".format(self.__class__.__name__)
TypeError: 'Series' objects are mutable, thus they cannot be hashed
```

If I have:
```python
df.query('other == 0 | other.isnull()')
```
the error is:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    df.query('other == 0 | other.isnull()')
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 3184, in query
    res = self.eval(expr, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 3300, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/eval.py", line 327, in eval
    ret = eng_inst.evaluate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 70, in evaluate
    res = self._evaluate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 118, in _evaluate
    _check_ne_builtin_clash(self.expr)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py", line 27, in _check_ne_builtin_clash
    names = expr.names
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expr.py", line 851, in names
    return frozenset(term.name for term in com.flatten(self.terms))
TypeError: unhashable type: 'numpy.ndarray'
```

Also, if I try to disable `numexpr` with:
```python
pd.set_option('compute.use_numexpr', False)
```
I get the same errors. Only uninstalling `numexpr` helps.

The following code fail as well:
```python
df = pd.DataFrame({'test':[[1,2],[2,3],[3,4]], 'other': [1,2,3]})
df = df[['other']].copy()
df.query('other == 0 | other.isnull()')
```

```python
df = pd.DataFrame({'test':[[1,2],[2,3],[3,4]], 'other': [1,2,3]})
df = df.drop('test', axis=1)
df.query('other == 0 | other.isnull()')
```

#### Expected Output
I expect `pandas` not to fail on these code snippets, like it does when `numexpr` is not installed.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-13-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 39.0.1
Cython           : 0.29
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by hwalinga** [comment]
Use `df.query("..", engine='python')`

**Comment by bra-fsn** [comment]
> Use `df.query("..", engine='python')`

Thanks, it works. Is this considered a workaround or a fix for this issue?

**Comment by Liam3851** [comment]
@bra-fsn See the [query documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) for a discussion of the numexpr vs python backends. Using numexpr changes the semantics, this is expected.

**Comment by hwalinga** [comment]
I think this can be closed now.
