### ISSUE TITLE
Pandas will not install on Python 3.8 Docker Image

### ISSUE THREAD

**Issue by snelson3** [pandas-dev/pandas#29043]
#### Code Sample, a copy-pastable example if possible

Use this dockerfile
```
FROM python:3.8-slim
RUN pip install pandas
```
#### Problem description

Running "docker build . -f <above_docker_file>" results in the error seen below. If I change the dockerfile to be "python:3.7-slim" then pandas installs. The only major difference I can see between the two dockerfiles is the Python version. Not 100% sure it's the version since I haven't tried installing pandas on a native version of 3.8, but it seems likely.

#### Output

<details>

```
Sending build context to Docker daemon  56.83kB
Step 1/2 : FROM python:3.8-slim
 ---> de57bccf5f31
Step 2/2 : RUN pip install pandas
 ---> Running in 78165c545ab0
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/07/cf/1b6917426a9a16fd79d56385d0d907f344188558337d6b81196792f857e9/pandas-0.25.1.tar.gz (12.6MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ggo_fivb/pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ggo_fivb/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ggo_fivb/pandas/pip-egg-info
         cwd: /tmp/pip-install-ggo_fivb/pandas/
    Complete output (178 lines):
    /bin/sh: 1: svnversion: not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/random': 'src/splitmix64/splitmix.h'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    Running from numpy source directory.
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/system_info.py:690: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      self.calc_info()
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/system_info.py:690: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/system_info.py:690: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/setup.py", line 443, in <module>
        cmdclass["cython"] = CythonCommand
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/setup.py", line 435, in setup_package
        pass
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/core.py", line 171, in setup
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 153, in build_sources
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 286, in build_library_sources
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 669, in get_mathlib_info
        "depends": tseries_depends,
    RuntimeError: Broken toolchain: cannot link a simple C program

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ggo_fivb/pandas/setup.py", line 807, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/setup.py", line 443, in <module>
        cmdclass["cython"] = CythonCommand
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/setup.py", line 435, in setup_package
        pass
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/core.py", line 171, in setup
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 153, in build_sources
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 286, in build_library_sources
      File "/tmp/easy_install-q3g08y_k/numpy-1.17.2/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 669, in get_mathlib_info
        "depends": tseries_depends,
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install pandas' returned a non-zero code: 1
```

</details>

**Comment by jbrockmendel** [comment]
Until numpy distributes a wheel, I think you need apt-get install build-essential

**Comment by TomAugspurger** [comment]
That failed while compiling numpy

```
      File "numpy/core/setup.py", line 669, in get_mathlib_info
        "depends": tseries_depends,
    RuntimeError: Broken toolchain: cannot link a simple C program

    During handling of the above exception, another exception occurred:
```

NumPy 1.17.2 isn't compatible with Python 3.8. NumPy 1.17.3 is.

And for pandas, 0.25.2 is the first to be compatible with 3.8 (releasing today).

**Comment by AkhileshShahare** [comment]
> That failed while compiling numpy
> 
> ```
>       File "numpy/core/setup.py", line 669, in get_mathlib_info
>         "depends": tseries_depends,
>     RuntimeError: Broken toolchain: cannot link a simple C program
> 
>     During handling of the above exception, another exception occurred:
> ```
> 
> NumPy 1.17.2 isn't compatible with Python 3.8. NumPy 1.17.3 is.
> 
> And for pandas, 0.25.2 is the first to be compatible with 3.8 (releasing today).

This worked!! Thank you so much
