### ISSUE TITLE
BLD: ModuleNotFoundError: No module named 'sphinx' during dev setup

### ISSUE THREAD

**Issue by jgehrcke** [pandas-dev/pandas#29154]
Following https://dev.pandas.io/docs/development/contributing.html#creating-a-python-environment-pip I ran into:

```
$ python -m pip install -r requirements-dev.txt
Collecting git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master (from -r requirements-dev.txt (line 68))
  Cloning https://github.com/pandas-dev/pandas-sphinx-theme.git (to revision master) to /tmp/pip-req-build-zo7xt1n7
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zo7xt1n7/setup.py", line 4, in <module>
        from pandas_sphinx_theme import __version__
      File "/tmp/pip-req-build-zo7xt1n7/pandas_sphinx_theme/__init__.py", line 8, in <module>
        import sphinx.builders.html
    ModuleNotFoundError: No module named 'sphinx'
```

One ignorant but simple solution would be to do a `python -m pip install sphinx` prior to doing `python -m pip install -r requirements-dev.txt`. WDYT?

**Comment by TomAugspurger** [comment]
cc @jorisvandenbossche. Would using versioneer avoid this?

That project does specify sphinx as an install_requires, but it also does a top-level import of the package in `setup.py`.
