### ISSUE TITLE
read_csv encode operation on source

### ISSUE THREAD

**Issue by abellerarj** [pandas-dev/pandas#29233]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> df = pd.read_csv("historical_dataset.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'historical_dataset.csv' does not exist
```
#### Problem description

Noticed that when source does not exist, there is a leading 'b' on the source on the error message. For Python3, is it necessary to do the encode operation on line 667 of https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/parsers.pyx? Works fine for Python2.

#### Output of ``pd.show_versions()``
<details>
```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-31-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.14.5
pytz             : 2018.5
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : 1.7.6
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.2.3
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.3
matplotlib       : 2.2.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.3.8
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```
</details>

**Comment by gfyoung** [comment]
@abellerarj : The reason for the `b` is that we encode the name of the file to account for special characters (xref: https://github.com/pandas-dev/pandas/pull/24758).  In Python2, the visual representation of encoded and non-encoded strings looked one and the same, whereas in Python3, a distinction is made visually.

**Comment by jbrockmendel** [comment]
@gfyoung to get the non-prefixed filename, would we need to reverse the encoding done in #24758?  that is now done in a .c file that i dont want to futz with

**Comment by gfyoung** [comment]
> would we need to reverse the encoding done in #24758

That would a be logical first step to investigate.

**Comment by gfyoung** [comment]
Fat fingers, my bad.
