### ISSUE TITLE
config.register_option allows re-registering previously registered option.

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#29242]
```python
>>> import pandas as pd
>>>
>>> pd.__version__
'0.26.0.dev0+684.g953757a3e'
>>>
>>> from pandas._config import config
>>>
>>> config.register_option("a.b.c", 1)
>>>
>>> config.get_option("a.b.c")
1
>>>
>>> config.register_option("a.b.c", 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 445, in register_option
    raise OptionError(msg.format(key=key))
pandas._config.config.OptionError: "Option 'a.b.c' has already been registered"
>>>
>>> config.register_option("a.b", {"c": 2})
>>>
>>> config.get_option("a.b.c")
2
>>>
```

**Comment by jreback** [comment]
why would you not want this? it’s a pretty clear message

**Comment by simonjayhawkins** [comment]
if a.b.c is registered you shouldn't be able to register a.b

**Comment by simonjayhawkins** [comment]
```
>>> import pandas as pd
>>>
>>> pd.__version__
'0.26.0.dev0+684.g953757a3e'
>>>
>>> from pandas._config import config
>>>
>>> config.get_option("a.b.c")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 233, in __call__
    return self.__func__(*args, **kwds)
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 102, in _get_option
    key = _get_single_key(pat, silent)
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 88, in _get_single_key
    raise OptionError("No such keys(s): {pat!r}".format(pat=pat))
pandas._config.config.OptionError: "No such keys(s): 'a.b.c'"
>>>
>>> config.register_option("a.b.c", 1)
>>>
>>> config.get_option("a.b.c")
1
>>>
>>> config.register_option("a.b.c", 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 445, in register_option
    raise OptionError(msg.format(key=key))
pandas._config.config.OptionError: "Option 'a.b.c' has already been registered"
>>>
>>> config.register_option("a.b", "foo")
>>>
>>> config.get_option("a.b.c")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 233, in __call__
    return self.__func__(*args, **kwds)
  File "C:\Users\simon\pandas\pandas\_config\config.py", line 106, in _get_option
    return root[k]
TypeError: string indices must be integers
>>>
```

**Comment by jreback** [comment]
i would be more concerned with registering invalid options

**Comment by simonjayhawkins** [comment]
i'll update the title
