### ISSUE TITLE
After Anaconda upgrade to 0.25.3 can't import pandas

### ISSUE THREAD

**Issue by boardtc** [pandas-dev/pandas#29714]
#### Code Sample, a copy-pastable example if possible

```
conda update pandas
```
#### Problem description
I did a conda update pandas at the anaconda prompt today to update from 0.23.x to 0.25.3 and now I get this error in Spyder simply importing pandas.

```
Traceback (most recent call last):

  File "<ipython-input-4-7dd3504c366f>", line 1, in <module>
    import pandas as pd

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\core\api.py", line 5, in <module>
    from pandas.core.arrays.integer import (

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 7, in <module>
    from .categorical import Categorical  # noqa: F401

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 54, in <module>
    from pandas.core.base import NoNewAttributesMixin, PandasObject, _shared_docs

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\core\base.py", line 36, in <module>
    import pandas.core.nanops as nanops

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\core\nanops.py", line 38, in <module>
    bn = import_optional_dependency("bottleneck", raise_on_missing=False, on_version="warn")

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\compat\_optional.py", line 99, in import_optional_dependency
    version = _get_version(module)

  File "D:\Applications\Anaconda3\lib\site-packages\pandas\compat\_optional.py", line 48, in _get_version
    raise ImportError("Can't determine version for {}".format(module.__name__))

ImportError: Can't determine version for bottleneck
```
[29181](https://github.com/pandas-dev/pandas/issues/29181) is similar but the iPython was already installed as part of Anaconda,

#### Expected Output

None. Should be able to import pandas as pd

#### Output of ``pd.show_versions()``

<details>
Traceback (most recent call last):

  File "<ipython-input-5-3d232a07e144>", line 1, in <module>
    pd.show_versions()

NameError: name 'pd' is not defined
</details>

**Comment by boardtc** [comment]
Fixed by a conda update --all, 
I will open an issues against Anaconda

**Comment by vikalpjain91** [comment]
Any update on this? I am still facing the same issue.

**Comment by cris-bytes** [comment]
Realized I wasn't running python but ipython, probably with an old version.
conda install ipython solved this problem for me.
