### ISSUE TITLE
GroupBy Regression with Categorical On Master

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29746]
Seems to be an issue on master as this works on 0.25.3:

```python
>>> ser = pd.Series(pd.Categorical(["first", "second", "third", "fourth"], ordered=True))
>>> ser.groupby([1, 1, 1, 1]).first()
[first]
Categories (4, object): [first < fourth < second < third]
```

But fails on master:

```python
>>> ser = pd.Series(pd.Categorical(["first", "second", "third", "fourth"], ordered=True))
>>> ser.groupby([1, 1, 1, 1]).first()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/williamayd/clones/pandas/pandas/core/groupby/groupby.py", line 1368, in f
    return self._cython_agg_general(alias, alt=npfunc, **kwargs)
  File "/Users/williamayd/clones/pandas/pandas/core/groupby/groupby.py", line 880, in _cython_agg_general
    obj._values, how, min_count=min_count
  File "/Users/williamayd/clones/pandas/pandas/core/groupby/ops.py", line 572, in aggregate
    "aggregate", values, how, axis, min_count=min_count
  File "/Users/williamayd/clones/pandas/pandas/core/groupby/ops.py", line 456, in _cython_operation
    "{dtype} dtype not supported".format(dtype=values.dtype)
NotImplementedError: category dtype not supported
```

@jbrockmendel for visibility. Looking at this on my end

**Comment by WillAyd** [comment]
Note that this works with a frame on master:

```python
>>> ser.to_frame().groupby([1, 1, 1, 1]).first()
       0
1  first
```

So I think just related to some of the exception handling in cython_agg_general and a lack of test coverage

**Comment by jbrockmendel** [comment]
might be related to #28949

**Comment by simonjayhawkins** [comment]
closing this in favour of #33090 since the bahaviour has changed and no longer raises `NotImplementedError: category dtype not supported`
