### ISSUE TITLE
Different index when creating a DataFrame than when changing a column in the DataFrame

### ISSUE THREAD

**Issue by Terseus** [pandas-dev/pandas#29740]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
from pandas.testing import assert_frame_equal


if __name__ == "__main__":
    df_left = pandas.DataFrame(data={'number': [1, 2, 3]})
    df_right = pandas.DataFrame(data={1: [2, 4, 6]})
    df_left[1] = df_left['number'].map(lambda x: x * 2)
    df_left.drop('number', axis=1, inplace=True)
    assert_frame_equal(df_left, df_right)
```

The result of running this code is:
```
Traceback (most recent call last):
  File "pandas_index_bug.py", line 10, in <module>
    assert_frame_equal(df_left, df_right)
  File "/home/terseus/.cache/pypoetry/virtualenvs/pandas-index-bug-py3.7/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/home/terseus/.cache/pypoetry/virtualenvs/pandas-index-bug-py3.7/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/home/terseus/.cache/pypoetry/virtualenvs/pandas-index-bug-py3.7/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/home/terseus/.cache/pypoetry/virtualenvs/pandas-index-bug-py3.7/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/home/terseus/.cache/pypoetry/virtualenvs/pandas-index-bug-py3.7/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index([1], dtype='object')
[right]: Int64Index([1], dtype='int64')
```

#### Problem description

Pandas assigns a different index when creating a dataframe with a given column than when adding that same column to an existing dataframe.

Please refer to the code example to see the behavior I'm trying to describe.

#### Expected Output

I expected that assert to *not* raise an `AssertionError`.

#### Output of ``pd.show_versions()``

<details>
```python
Python 3.7.4 (default, Oct  4 2019, 06:57:26)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.5-arch1-1-ARCH
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : es_ES.UTF-8
LOCALE           : es_ES.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
>>>
```
</details>

**Comment by TomAugspurger** [comment]
I don't think DataFrame.drop should implicitly convert an Index to a RangeIndex.

You can avoid the assertion error with `assert_frame_equal(df_left, df_right, check_column_type=False)`.

**Comment by Terseus** [comment]
@TomAugspurger But then the assert isn't checking the columns types, which would make the test incomplete IMHO.

I'm new to Pandas so I don't understand its internals but this behavior looks quite counterintuitive to me; I mean, after all the DataFrames have the same columns with the same type and the same value, why whould they differ?

**Comment by TomAugspurger** [comment]
The values are the same, but they’re in a different type of Index class.  By default we want to be strict.

It may also work if you pass =True for that parameter, not sure.

**Comment by Terseus** [comment]
@TomAugspurger After reading the docs of [assert_frame_equal](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html) I found that there's a parameter that looks made just for this case, `check_index_type`:
```
check_index_type : bool / string {‘equiv’}, default ‘equiv’

    Whether to check the Index class, dtype and inferred_type are identical.
```

However even with `check_index_type=False` the same error happens.

I don't think anymore that I understand what's the desired behavior of assert_frame_equal in this case...

**Comment by TomAugspurger** [comment]
IIUC, the issue is with the columns, not the index.

**Comment by Terseus** [comment]
@TomAugspurger After diving more into Pandas I now understand why the column doesn't change (TBH when I opened this issue I didn't even understood what a "dtype" is :sweat_smile: ).

I'll close this issue for now.
