### ISSUE TITLE
Pandas Doesn't work

### ISSUE THREAD

**Issue by tumzera** [pandas-dev/pandas#30198]
Installed pandas to pyton3.8 and i get this:

**>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (  # noqa: F401
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 44, in <module>
    from pandas.core.frame import DataFrame
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 88, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 70, in <module>
    from pandas.io.formats.format import DataFrameFormatter, format_percentiles
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 48, in <module>
    from pandas.io.common import _expand_user, _stringify_path
  File "/home/toxess/.local/lib/python3.8/site-packages/pandas/io/common.py", line 3, in <module>
    import bz2
  File "/usr/local/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'**

Please help me out

**Comment by 0xF4D3C0D3** [comment]
did you try [this](https://stackoverflow.com/a/12806325/7899226) or `sudo apt-get install liblzma-dev`?

and yes it seems to be needed to recompile your python after this. I think this is not a problem of 
pandas itself, rather it's a general problem with python dependencies.

**Comment by mroeschke** [comment]
@0xF4D3C0D3 has the right idea. See https://stackoverflow.com/a/22346519/12145780
