### ISSUE TITLE
pct_change can't work well with groupby, when fill_method =None

### ISSUE THREAD

**Issue by ForrestLin0805** [pandas-dev/pandas#30463]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
data = pd.DataFrame(np.random.random((10,2)), index=['a', 'b']*5)
data.iloc[1:3,:] = np.nan
```
for pct_change function, when the fill_method = None, it works

```
data.pct_change(1, fill_method=None, limit=1)
	0	1
a	NaN	NaN
b	NaN	NaN
a	NaN	NaN
b	NaN	NaN
a	-0.498169	-0.568501
b	-0.315982	1.340587
a	1.341901	-0.489576
b	0.088594	-0.691063
a	-0.514451	0.054695
b	0.844514	-0.604511
```
but when use it with gourpby , it raise a error

```
data.reset_index().groupby('index')[0].pct_change(1, fill_method=None, limit=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-60898304743e> in <module>
----> 1 data.reset_index().groupby('index')[0].pct_change(1, fill_method=None, limit=1)

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py in pct_change(self, periods, fill_method, limit, freq)
   1344                 )
   1345             )
-> 1346         filled = getattr(self, fill_method)(limit=limit)
   1347         fill_grp = filled.groupby(self.grouper.labels)
   1348         shifted = fill_grp.shift(periods=periods, freq=freq)

TypeError: getattr(): attribute name must be string
```
else, `limit = 0` worked with gourpby, but can't run in pct_change

```
data.reset_index().groupby('index')[0].pct_change(1, fill_method='pad', limit=0)  
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5   -0.656739
6    0.601904
7    1.549380
8   -0.471434
9   -0.104398
Name: 0, dtype: float64  
``` 
```
data[0].pct_change(1, fill_method='pad', limit=0)  

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/missing.py in pad_2d(values, limit, mask, dtype)
    546 
    547     if np.all(values.shape):
--> 548         algos.pad_2d_inplace(values, mask, limit=limit)
    549     else:
    550         # for test coverage

pandas/_libs/algos.pyx in pandas._libs.algos.pad_2d_inplace()

ValueError: Limit must be greater than 0
```

pandas version is 0.25.1

**Comment by jreback** [comment]
pls try on master

**Comment by fujiaxiang** [comment]
Tried on master. It does seem we have an issue here.

```python
np.random.seed(0)
data = pd.DataFrame(np.random.random((6, 2)), index=['a', 'b'] * 3)
data.iloc[0, :] = np.nan
data

          0         1
a       NaN       NaN
b  0.602763  0.544883
a  0.423655  0.645894
b  0.437587  0.891773
a  0.963663  0.383442
b  0.791725  0.528895
```

This gives us all null values 
```python
data.pct_change(fill_method=None)

    0   1
a NaN NaN
b NaN NaN
a NaN NaN
b NaN NaN
a NaN NaN
b NaN NaN
```

GroupBy.pct_change with default parameters seems ok
```python
data.groupby(level=0).pct_change()

          0         1
a       NaN       NaN
b       NaN       NaN
a       NaN       NaN
b -0.274032  0.636632
a  1.274641 -0.406340
b  0.809297 -0.406918
```

However, this raises an error
```python
data.groupby(level=0).pct_change(fill_method=None)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fujia\PycharmProjects\pandas\pandas\core\groupby\groupby.py", line 2365, in pct_change
    filled = getattr(self, fill_method)(limit=limit)
TypeError: getattr(): attribute name must be string
```

This is even more weird. Somehow only index=b has values and they are all the same values.
```python
data = pd.DataFrame(np.random.random((6, 2)), index=['a', 'b'] * 3)
data.iloc[2, :] = np.nan
data

          0         1
a  0.568045  0.925597
b  0.071036  0.087129
a       NaN       NaN
b  0.778157  0.870012
a  0.978618  0.799159
b  0.461479  0.780529

data.pct_change(fill_method=None)
          0         1
a       NaN       NaN
b -0.874946 -0.905867
a       NaN       NaN
b -0.874946 -0.905867
a       NaN       NaN
b -0.874946 -0.905867
```

**Comment by fujiaxiang** [comment]
I will take a look at this

**Comment by fujiaxiang** [comment]
take

**Comment by fujiaxiang** [comment]
There are two separate issues:
1. `Series / DataFrame.pct_change` incorrectly reindex(es) results when `freq is None`
1. `SeriesGroupBY / DataFrameGroupBY` did not handle the case when `fill_method is None`

Will create separate PRs to address them
