### ISSUE TITLE
Plotting error with datetime indices and horizontal line

### ISSUE THREAD

**Issue by pepicello** [pandas-dev/pandas#30643]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
import datetime
a = pd.Series([1, 2], index=[datetime.date(2020, 1, 1), datetime.date(2020, 1, 2)])
fig, ax = plt.subplots(1, 1)
a.plot(ax=ax)
ax.axhline(1)
a.plot(ax=ax)

```
#### Problem description

Last line results in error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\pandas\plotting\_core.py", line 794, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 62, in plot
    plot_obj.generate()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 287, in generate
    self._post_plot_logic_common(ax, self.data)
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 441, in _post_plot_logic_common
    self._apply_axis_properties(ax.xaxis, rot=self.rot, fontsize=self.fontsize)
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 525, in _apply_axis_properties
    labels = axis.get_majorticklabels() + axis.get_minorticklabels()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\axis.py", line 1252, in get_majorticklabels
    ticks = self.get_major_ticks()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\axis.py", line 1407, in get_major_ticks
    numticks = len(self.get_majorticklocs())
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\axis.py", line 1324, in get_majorticklocs
    return self.major.locator()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\dates.py", line 1428, in __call__
    self.refresh()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\dates.py", line 1448, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "C:\Users\gpepe\AppData\Local\Continuum\anaconda3\envs\latest\lib\site-packages\matplotlib\dates.py", line 1199, in viewlim_to_dt
    .format(vmin))
ValueError: view limit minimum 0.0 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units
```

This does not happen if ```axhline``` is run last. Feel free to close if this is a matplotlib issue and I will open this issue in that repo.

#### Expected Output

No error.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2.post20191203
Cython           : 0.29.13
pytest           : 5.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.1
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : 1.3.7
tables           : None
xarray           : 0.12.3
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.8

</details>

**Comment by charlesdong1991** [comment]
thanks for the issue report!

can you try to run it on master? looks okay to me

**Comment by MarcoGorelli** [comment]
I could reproduce this on v0.25.3, but not on master

**Comment by charlesdong1991** [comment]
thanks @MarcoGorelli  yeah, i think this fix is not released yet

**Comment by TomAugspurger** [comment]
I also can't see this on master. Let us know if it's not fixed already @pepicello
