### ISSUE TITLE
local test failure: test_maybe_promote_datetimetz_with_datetimetz

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30868]
```
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other0] FAILED [  4%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other1] FAILED [  8%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other2] FAILED [ 12%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other3] FAILED [ 16%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other4] FAILED [ 20%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other5] FAILED [ 25%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other6] FAILED [ 29%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other7] FAILED [ 33%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other8] FAILED [ 37%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_arraylike_invalid[tzlocal()-other9] FAILED [ 41%]
pandas/tests/arithmetic/test_datetime64.py::TestDatetime64ArrayLikeComparisons::test_dt64arr_cmp_mixed_invalid[tzlocal()] FAILED [ 45%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz['UTC'-tzlocal()] FAILED [ 50%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz['US/Eastern'-tzlocal()] FAILED [ 54%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz['Asia/Tokyo'-tzlocal()] FAILED [ 58%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz['dateutil/US/Pacific'-tzlocal()] FAILED [ 62%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz['dateutil/Asia/Singapore'-tzlocal()] FAILED [ 66%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[tzutc()-tzlocal()] FAILED [ 70%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[tzlocal()-tzlocal()] FAILED [ 75%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[pytz.FixedOffset(300)-tzlocal()] FAILED [ 79%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[<UTC>-tzlocal()] FAILED [ 83%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[pytz.FixedOffset(-300)-tzlocal()] FAILED [ 87%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[datetime.timezone.utc-tzlocal()] FAILED [ 91%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[datetime.timezone(datetime.timedelta(seconds=3600))-tzlocal()] FAILED [ 95%]
pandas/tests/dtypes/cast/test_promote.py::test_maybe_promote_datetimetz_with_datetimetz[datetime.timezone(datetime.timedelta(days=-1, seconds=82800), 'foo')-tzlocal()] FAILED [100%]

```

#### traceback of one case

<details>

```
_ test_maybe_promote_datetimetz_with_datetimetz[datetime.timezone(datetime.timedelta(days=-1, seconds=82800), 'foo')-tzlocal()] _
[gw2] win32 -- Python 3.7.5 C:\Users\simon\Anaconda3\envs\pandas-dev\python.exe

data = <[OSError("[Errno 22] Invalid argument") raised in repr()] ndarray object at 0x25accfedf80>
dayfirst = False, yearfirst = False, utc = False, errors = 'raise'
require_iso8601 = False, allow_object = True

    def objects_to_datetime64ns(
        data,
        dayfirst,
        yearfirst,
        utc=False,
        errors="raise",
        require_iso8601=False,
        allow_object=False,
    ):
        """
        Convert data to array of timestamps.

        Parameters
        ----------
        data : np.ndarray[object]
        dayfirst : bool
        yearfirst : bool
        utc : bool, default False
            Whether to convert timezone-aware timestamps to UTC.
        errors : {'raise', 'ignore', 'coerce'}
        allow_object : bool
            Whether to return an object-dtype ndarray instead of raising if the
            data contains more than one timezone.

        Returns
        -------
        result : ndarray
            np.int64 dtype if returned values represent UTC timestamps
            np.datetime64[ns] if returned values represent wall times
            object if mixed timezones
        inferred_tz : tzinfo or None

        Raises
        ------
        ValueError : if data cannot be converted to datetimes
        """
        assert errors in ["raise", "ignore", "coerce"]

        # if str-dtype, convert
        data = np.array(data, copy=False, dtype=np.object_)

        try:
            result, tz_parsed = tslib.array_to_datetime(
                data,
                errors=errors,
                utc=utc,
                dayfirst=dayfirst,
                yearfirst=yearfirst,
>               require_iso8601=require_iso8601,
            )

pandas\core\arrays\datetimes.py:1852:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   cpdef array_to_datetime(ndarray[object] values, str errors='raise',

pandas\_libs\tslib.pyx:481:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise ValueError('Tz-aware datetime.datetime '
E   ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

pandas\_libs\tslib.pyx:559: ValueError

During handling of the above exception, another exception occurred:

>   return tzinfo._utcoffset
E   AttributeError: 'tzlocal' object has no attribute '_utcoffset'

pandas\_libs\tslibs\timezones.pyx:153: AttributeError

During handling of the above exception, another exception occurred:

tz_aware_fixture = datetime.timezone(datetime.timedelta(days=-1, seconds=82800), 'foo')
tz_aware_fixture2 = tzlocal()

    def test_maybe_promote_datetimetz_with_datetimetz(tz_aware_fixture, tz_aware_fixture2):
        dtype = DatetimeTZDtype(tz=tz_aware_fixture)
        fill_dtype = DatetimeTZDtype(tz=tz_aware_fixture2)

        # create array of given dtype; casts "1" to correct dtype
>       fill_value = pd.Series([10 ** 9], dtype=fill_dtype)[0]

pandas\tests\dtypes\cast\test_promote.py:429:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\core\series.py:304: in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
pandas\core\construction.py:442: in sanitize_array
    subarr = maybe_cast_to_datetime(subarr, dtype)
pandas\core\dtypes\cast.py:1220: in maybe_cast_to_datetime
    value = to_datetime(value, errors=errors).array
pandas\core\tools\datetimes.py:741: in to_datetime
    result = convert_listlike(arg, format)
pandas\core\tools\datetimes.py:447: in _convert_listlike_datetimes
    allow_object=True,
pandas\core\arrays\datetimes.py:1856: in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
pandas\_libs\tslibs\conversion.pyx:189: in pandas._libs.tslibs.conversion.datetime_to_datetime64
    _ts = convert_datetime_to_tsobject(val, None)
pandas\_libs\tslibs\conversion.pyx:388: in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
    offset = get_utcoffset(obj.tzinfo, ts)
pandas\_libs\tslibs\timezones.pyx:155: in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
..\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py:216: in utcoffset
    if self._isdst(dt):
..\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py:288: in _isdst
    if self.is_ambiguous(dt):
..\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py:250: in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = tzlocal()
dt = <[OSError("[Errno 22] Invalid argument") raised in repr()] Timestamp object at 0x25acc12a148>

    def _naive_is_dst(self, dt):
        timestamp = _datetime_to_timestamp(dt)
>       return time.localtime(timestamp + time.timezone).tm_isdst
E       OSError: [Errno 22] Invalid argument

..\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py:254: OSError
---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Exception ignored in: 'pandas._libs.tslibs.tzconversion._tz_convert_tzlocal_utc'
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\simon\pandas\pandas\core\arrays\datetimes.py", line 1852, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas\_libs\tslib.pyx", line 481, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(ndarray[object] values, str errors='raise',
  File "pandas\_libs\tslib.pyx", line 559, in pandas._libs.tslib.array_to_datetime
    raise ValueError('Tz-aware datetime.datetime '
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Exception ignored in: 'pandas._libs.tslibs.tzconversion._tz_convert_tzlocal_utc'
Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\simon\pandas\pandas\core\arrays\datetimes.py", line 1852, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas\_libs\tslib.pyx", line 481, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(ndarray[object] values, str errors='raise',
  File "pandas\_libs\tslib.pyx", line 559, in pandas._libs.tslib.array_to_datetime
    raise ValueError('Tz-aware datetime.datetime '
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Exception ignored in: 'pandas._libs.tslibs.tzconversion._tz_convert_tzlocal_utc'
Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 288, in _isdst
    if self.is_ambiguous(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 250, in is_ambiguous
    (naive_dst != self._naive_is_dst(dt - self._dst_saved)))
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\simon\pandas\pandas\core\arrays\datetimes.py", line 1852, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas\_libs\tslib.pyx", line 481, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(ndarray[object] values, str errors='raise',
  File "pandas\_libs\tslib.pyx", line 559, in pandas._libs.tslib.array_to_datetime
    raise ValueError('Tz-aware datetime.datetime '
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 285, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Exception ignored in: 'pandas._libs.tslibs.tzconversion._tz_convert_tzlocal_utc'
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 285, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\simon\pandas\pandas\core\arrays\datetimes.py", line 1852, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas\_libs\tslib.pyx", line 481, in pandas._libs.tslib.array_to_datetime
    cpdef array_to_datetime(ndarray[object] values, str errors='raise',
  File "pandas\_libs\tslib.pyx", line 559, in pandas._libs.tslib.array_to_datetime
    raise ValueError('Tz-aware datetime.datetime '
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 153, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo._utcoffset
AttributeError: 'tzlocal' object has no attribute '_utcoffset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 285, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
Exception ignored in: 'pandas._libs.tslibs.tzconversion._tz_convert_tzlocal_utc'
Traceback (most recent call last):
  File "pandas\_libs\tslibs\timezones.pyx", line 155, in pandas._libs.tslibs.timezones.get_utcoffset
    return tzinfo.utcoffset(obj)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 216, in utcoffset
    if self._isdst(dt):
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 285, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:\Users\simon\Anaconda3\envs\pandas-dev\lib\site-packages\dateutil\tz\tz.py", line 254, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
```

</details>

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3ddd495e43ab878b6d139e2458cb3c387f7237c4
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 0.26.0.dev0+1731.g3ddd495e4
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.6.0.post20191030
Cython           : 0.29.13
pytest           : 5.2.2
hypothesis       : 4.36.2
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.2
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: 0.8.1
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.2.2
s3fs             : 0.3.4
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : 3.5.1
tabulate         : None
xarray           : 0.13.0
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.2
numba            : 0.46.0

</details>

**Comment by jbrockmendel** [comment]
I think I recently removed a windows-specific xfail in this test, might have been too optimistic

**Comment by jbrockmendel** [comment]
@simonjayhawkins are these still broken for you?

**Comment by mroeschke** [comment]
These looks to be running OK on the CI so closing
