### ISSUE TITLE
Pip 20 ruins builds.

### ISSUE THREAD

**Issue by baevpetr** [pandas-dev/pandas#31174]
#### Problem description:

During testing, it was noticed that setting up the environment with version 20 pip fails.
New release was several hours ago.

#### Output
```
[Updating pip]
Collecting pip
  Downloading https://files.pythonhosted.org/packages/60/65/16487a7c4e0f95bb3fc89c2e377be331fd496b7a9b08fd3077de7f3ae2cf/pip-20.0-py2.py3-none-any.whl (1.5MB)
Requirement already up-to-date: wheel in /home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages (0.33.6)
Requirement already up-to-date: setuptools in /home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages (45.1.0.post20200119)
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-20.0
[Install pandas]
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/distributions/__init__.py", line 1, in <module>
    from pip._internal.distributions.source import SourceDistribution
ImportError: cannot import name 'SourceDistribution' from 'pip._internal.distributions.source' (/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pip/_internal/distributions/source/__init__.py)
##[error]Process completed with exit code 1.
```

**Comment by jreback** [comment]
you should report to pip issue tracker
