### ISSUE TITLE
Cannot add pandas_profiling module into SQL Server

### ISSUE THREAD

**Issue by huyanh1511** [pandas-dev/pandas#31264]
#### Code Sample, a copy-pastable example if possible

```python
import sqlmlutils
connection = sqlmlutils.ConnectionInfo(server="localhost", database="SQLAI")
sqlmlutils.SQLPackageManager(connection).install("pandas-profiling")
```
#### Problem description

I was trying to install some module (i.e. pandas_profiling) in SQL Server so I can run the script directly from there. I was utilizing a Microsoft tool called 'sqlmlutils' to achieve this, but it returned an error specifically when I tried to install pandas_profiling (in fact another library called 'text-tools' was successfully installed.

#### Expected Output (this is the output I got by running the scripts)

Traceback (most recent call last):

  File "<ipython-input-2-e8db1d445900>", line 1, in <module>
    runfile('C:/Users/BusinessUser/Desktop/abc.py', wdir='C:/Users/BusinessUser/Desktop')

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/BusinessUser/Desktop/abc.py", line 3, in <module>
    sqlmlutils.SQLPackageManager(connection).install("pandas_profiling")

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 74, in install
    self._install_from_pypi(package, upgrade, version, install_dependencies, scope, out_file=out_file)

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 151, in _install_from_pypi
    self._install_from_file(target_package_file, scope, upgrade, out_file=out_file)

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 171, in _install_from_file
    required_installs = resolver.get_required_installs(target_package_requirements)

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\sqlmlutils\packagemanagement\dependencyresolver.py", line 34, in get_required_installs
    self._server_packages, requirement.name, spec)

  File "C:\Users\BusinessUser\Anaconda3\lib\site-packages\sqlmlutils\packagemanagement\dependencyresolver.py", line 60, in _check_if_installed_package_meets_spec
    return getattr(operator, operator_map[op_str])(LooseVersion(installed_version), LooseVersion(req_version))

  File "C:\Users\BusinessUser\Anaconda3\lib\distutils\version.py", line 46, in __eq__
    c = self._cmp(other)

  File "C:\Users\BusinessUser\Anaconda3\lib\distutils\version.py", line 337, in _cmp
    if self.version < other.version:

TypeError: '<' not supported between instances of 'int' and 'str'

#### Output of ``pd.show_versions()``

<details>

Not sure what this mean but it was saying 'The version installed on the server is 0.23.4'

</details>

**Comment by WillAyd** [comment]
Thanks for reaching out but pandas-profiling and sqlmlutils are separate projects. You might need to search for help with those packages specifically
