### ISSUE TITLE
Aggregate with categorical variables but without groupby

### ISSUE THREAD

**Issue by GregKarabinos** [pandas-dev/pandas#31298]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd 

df = pd.DataFrame( {"col_1" : [1, 2, 3, 4, 5],
                  "col_2" : [3, 5, 3, 4, 9],
                  "col_3" : ["cat", "dog", "dog", "cat", "cat"],
                  "col_4" : ["feline", "canine", "canine", "feline", "feline"]})

func_list = [lambda x : len(x),
             lambda x : x.isnull().sum()]

num_col = df.select_dtypes(include="number").columns
cat_col = df.select_dtypes(include="object").columns

#works correctly for numeric columns
print(df[num_col].agg(func_list))
print(df[cat_col].agg(func_list))

```
#### Problem description

There is an issue with aggregating and applying a list of functions.  These functions should be able to be applied to categorical or object columns but cannot currently. 

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.0.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.9
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1

**Comment by Rik-de-Kort** [comment]
Inserting a print statement to raise the original error that leads to this particular error. Don't have the time at the moment to look into it further right this second, but this might help.
````
Traceback (most recent call last):
  File "/home/rik/pandas/pandas/core/base.py", line 559, in _aggregate_multiple_funcs
    return concat(results, keys=keys, axis=1, sort=False)
  File "/home/rik/pandas/pandas/core/reshape/concat.py", line 281, in concat
    sort=sort,
  File "/home/rik/pandas/pandas/core/reshape/concat.py", line 356, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'numpy.int64'>'; only Series and DataFrame objs are valid````

**Comment by dsaxton** [comment]
Interesting find. If you take a look at the output of `len` by itself it works fine, but the shape changes when put into a list. `lambda x: x.isna().sum()` works also, but the error happens when you try to combine the two. I would guess it's caused by the misshapen output of `df.agg([len])`.

```python
>>> df
   a
0  x
1  y
2  z
>>> df.agg(len)
a    3
dtype: int64
>>> df.agg([len])
    a
  len
0   1
1   1
2   1
>>> df.agg([len, len])
    a    
  len len
0   1   1
1   1   1
2   1   1
>>> df.agg([lambda x: x.isna().sum()])
          a
<lambda>  0
>>> df.agg([lambda x: x.isna().sum(), len])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielsaxton/opt/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6712, in aggregate
    result, how = self._aggregate(func, axis=axis, *args, **kwargs)
  File "/Users/danielsaxton/opt/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6726, in _aggregate
    return super()._aggregate(arg, *args, **kwargs)
  File "/Users/danielsaxton/opt/miniconda3/lib/python3.7/site-packages/pandas/core/base.py", line 564, in _aggregate
    return self._aggregate_multiple_funcs(arg, _level=_level, _axis=_axis), None
  File "/Users/danielsaxton/opt/miniconda3/lib/python3.7/site-packages/pandas/core/base.py", line 621, in _aggregate_multiple_funcs
    raise ValueError("no results")
ValueError: no results
```

**Comment by Dr-Irv** [comment]
Definitely a bug - getting different results for applying these 2 functions to numeric versus object columns.
