### ISSUE TITLE
Bug in AbstractHolidayCalendar.holidays

### ISSUE THREAD

**Issue by dhirschfeld** [pandas-dev/pandas#31415]
...when there are no rules.

```python
from pandas.tseries.holiday import AbstractHolidayCalendar

class ExampleCalendar(AbstractHolidayCalendar):
    pass

cal = ExampleCalendar()
```
```python
In [58]: cal.holidays(pd.Timestamp('01-Jan-2020'), pd.Timestamp('01-Jan-2021'))
Traceback (most recent call last):

  File "<ipython-input-58-022244d4e794>", line 1, in <module>
    cal.holidays(pd.Timestamp('01-Jan-2020'), pd.Timestamp('01-Jan-2021'))

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\pandas\tseries\holiday.py", line 422, in holidays
    self._cache = (start, end, holidays.sort_index())

AttributeError: 'NoneType' object has no attribute 'sort_index'

In [59]: pd.__version__
Out[59]: '0.25.3'
```

**Comment by dhirschfeld** [comment]
As can be seen below:
https://github.com/pandas-dev/pandas/blob/ec0996c6751326eed17a0bb456fe1c550689a618/pandas/tseries/holiday.py#L409-L421

when `self.rules` is empty
```python
In [61]: cal.rules
Out[61]: []
```
You drop through the loop to L421:
```python
self._cache = (start, end, holidays.sort_index()) 
```
where `holidays` remains unchanged from being set to `None` before the loop on L409.
