### ISSUE TITLE
BUG: groupby _cython_agg_blocks implicitly assumes unique columns

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#31735]
xref #31616, the two test cases that adds both have unique columns.  Editing test_agg_split_object_part_datetime to make columns non-unique breaks it:

```
df = pd.DataFrame(
            {
                "A": pd.date_range("2000", periods=4),
                "B": ["a", "b", "c", "d"],
                "C": [1, 2, 3, 4],
                "D": ["b", "c", "d", "e"],
                "E": pd.date_range("2000", periods=4),
                "F": [1, 2, 3, 4],
            }
).astype(object)
df.columns = ["A", "B", "B", "D", "E", "F"]

>>> result = df.groupby([0, 0, 0, 0]).min()
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

cc @WillAyd @TomAugspurger

**Comment by WillAyd** [comment]
Is this getting thrown from `_wrap_agged_blocks`? There was a lot of work outside of the block code to use `OutputKey` in groupby.base as a key and have the `wrap_*` functions be able to work with that

**Comment by jbrockmendel** [comment]
> Is this getting thrown from _wrap_agged_blocks?

No, it is in the _cython_agg_blocks call, full traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/groupby/groupby.py", line 1392, in func
    min_count=min_count,
  File "pandas/core/groupby/generic.py", line 1007, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count
  File "pandas/core/groupby/generic.py", line 1059, in _cython_agg_blocks
    result = s.aggregate(lambda x: alt(x, axis=self.axis))
  File "pandas/core/groupby/generic.py", line 963, in aggregate
    result = self._aggregate_multiple_funcs([func], _axis=self.axis)
  File "pandas/core/base.py", line 555, in _aggregate_multiple_funcs
    return concat(results, keys=keys, axis=1, sort=False)
  File "pandas/core/reshape/concat.py", line 283, in concat
    sort=sort,
  File "pandas/core/reshape/concat.py", line 452, in __init__
    self.new_axes = self._get_new_axes()
  File "pandas/core/reshape/concat.py", line 515, in _get_new_axes
    for i in range(ndim)
  File "pandas/core/reshape/concat.py", line 515, in <listcomp>
    for i in range(ndim)
  File "pandas/core/reshape/concat.py", line 571, in _get_concat_axis
    indexes, self.keys, self.levels, self.names
  File "pandas/core/reshape/concat.py", line 671, in _make_concat_multiindex
    mapped = level.get_indexer(hlevel)
  File "pandas/core/indexes/base.py", line 2990, in get_indexer
    "Reindexing only valid with uniquely valued Index objects"
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

```

**Comment by phofl** [comment]
Seems to work now. I get the following output on master:

```
           A  B  B  D          E  F
0 2000-01-01  a  1  b 2000-01-01  1
```

**Comment by jbrockmendel** [comment]
this was likely fixed by the recent changes to operate via BlockManager.apply; IIRC those didnt implement any tests specific to this issue
