### ISSUE TITLE
Categorical.from_codes fails for the (new nullable) Int64 dtype

### ISSUE THREAD

**Issue by mila** [pandas-dev/pandas#31779]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> codes = pd.Series([1, 0], dtype="Int64")
>>> pd.Categorical.from_codes(codes, categories=["foo", "bar"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 649, in from_codes
    raise ValueError("codes need to be array-like integers")
ValueError: codes need to be array-like integers
```
#### Problem description

`Categories.from_codes` works with Series with the Numpy `"int64"` dtype. 

```python
>>> codes = pd.Series([1, 0])
>>> pd.Categorical.from_codes(codes, categories=["foo", "bar"])
[bar, foo]
Categories (2, object): [foo, bar]
```

I would expect that it will work with the new Pandas `"Int64"` dtype.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by mila** [comment]
Thanks, that was fast!
