### ISSUE TITLE
pandas read_excel error:TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.

### ISSUE THREAD

**Issue by rosefun** [pandas-dev/pandas#31904]
#### My code 

```python
import pandas as pd 
f = 'F:/example.xlsx'
ex_file = pd.ExcelFile(f)
sheet_names = ex_file.sheet_names
for name in sheet_names:
    print(name)
    dc = pd.read_excel(ex_file, sheet_name=name)
```
#### Problem details

```
Traceback (most recent call last):
  File "D:\pandas\core\categorical.py", line 330, in __init__
    codes, categories = factorize(values, sort=True)
  File "D:\pandas\core\algorithms.py", line 479, in factorize
    assume_unique=True)
  File "D:\pandas\core\sorting.py", line 443, in safe_sort
    ordered = sort_mixed(values)
  File "D:\pandas\core\sorting.py", line 436, in sort_mixed
    nums = np.sort(values[~str_pos])
  File "D:\numpy\core\fromnumeric.py", line 847, in sort
    a.sort(axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\testReadexcel.py", line 8, in <module>
    dc = pd.read_excel(ex_file, sheet_name=name)
  File "D:\pandas\util\_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "D:\pandas\io\excel.py", line 238, in read_excel
    false_values=false_values, squeeze=squeeze, **kwds)
  File "D:\pandas\io\excel.py", line 543, in _parse_excel
    output[asheetname] = parser.read()
  File "D:\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "D:\pandas\io\parsers.py", line 2273, in read
    index, columns = self._make_index(data, alldata, columns, indexnamerow)
  File "D:\pandas\io\parsers.py", line 1412, in _make_index
    index = self._agg_index(index)
  File "D:\pandas\io\parsers.py", line 1512, in _agg_index
    index = _ensure_index_from_sequences(arrays, names)
  File "D:\pandas\core\indexes\base.py", line 4152, in _ensure_index_from_sequences
    return MultiIndex.from_arrays(sequences, names=names)
  File "D:\pandas\core\indexes\multi.py", line 1150, in from_arrays
    labels, levels = _factorize_from_iterables(arrays)
  File "D:\pandas\core\categorical.py", line 2352, in _factorize_from_iterables
    return map(list, lzip(*[_factorize_from_iterable(it) for it in iterables]))
  File "D:\pandas\core\categorical.py", line 2352, in <listcomp>
    return map(list, lzip(*[_factorize_from_iterable(it) for it in iterables]))
  File "D:\pandas\core\categorical.py", line 2324, in _factorize_from_iterable
    cat = Categorical(values, ordered=True)
  File "D:\pandas\core\categorical.py", line 336, in __init__
    raise TypeError("'values' is not ordered, please "
TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.
```

#### Expected Output
It can print the sheet name, but pandas can't read the first sheet correctly.

#### Output of ``pd.show_versions()``
0.22.0

**Comment by rosefun** [comment]
I find that the header of the excel file is almost empty, and  solve the problem by add `header = 1`.
