### ISSUE TITLE
Add generic buffer (s3) support to read_hdf

### ISSUE THREAD

**Issue by pedroreys** [pandas-dev/pandas#31902]
Hey folks, this is not a bug but a question/feature request.

Today `read_hdf` does not support reading hdf files directly from `s3`.

If you try to pass an _s3_ url directly, as you can do with `read_csv` you get a  _file does not exist error message:
```python
>>> import pandas as pd
>>> df = pd.read_hdf('s3://mybucket/myfile.h5', 'df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pandas/io/pytables.py", line 395, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File s3://mybucket/myfile.h5 does not exist
```

And if we try to pass a _file-like_ as the path, we get a error saying that support for generic buffers is not implemented

```python
>>> import pandas as pd
>>> from s3fs import S3FileSystem
>>> s3 = S3FileSystem(anon=False)
>>> df = pd.read_hdf(s3.open('mybucket/myfile.h5', mode='rb'), 'df')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pandas/io/pytables.py", line 385, in read_hdf
    "Support for generic buffers has not been implemented."
NotImplementedError: Support for generic buffers has not been implemented.
```
Are there any plans to implement generic buffers for `read_hdf`, so that we could read from s3 directly?

I took a quick look and this seems to be a restriction with _tables_ not supporting s3 or file-like but I'm not sure.

**Comment by WillAyd** [comment]
We support this for other readers so I think OK to do here. Should be some generic machinery already in the code base - if you give it a look and want to make a PR would be welcome

**Comment by jreback** [comment]
this not likely as HDF5 doesn’t have much support  for this

**Comment by pedroreys** [comment]
I just [found out that](https://www.hdfgroup.org/2019/11/webinar-announcement-learn-about-new-features-in-hdf5-1-12-0/) the HDF Group added support to S3 VFD in HDF5s upcoming new major release (1.12.0) so it _might_ be possible to do it in the near future.

Thanks for the quick responses.

**Comment by WestXu** [comment]
So the HDF 1.12.0 has [been released 2 months ago](https://www.hdfgroup.org/2020/03/release-of-hdf5-1-12-0-newsletter-172). Maybe this feature implementation is possible now.

**Comment by saccodd** [comment]
Is there any workaround to read hdf files from s3 at the moment?

**Comment by pedroreys** [comment]
the only option that I know works is downloading the file from s3 to your local file system first, and only then calling `read_hdf` passing the local file path to it

**Comment by Hagibaer** [comment]
Whats the current status of this issue? I faced a similiar problem and was wondering if there is an update on this, or if the workaround still is to download the files to the local file system first. In the mentioned issue someone wanted to work on this, but apparently nothing happened. Any feedback is greatly appreciated :)

**Comment by giacomo-maxinfo** [comment]
facing the same issue, it would be nice to read a hdf5 without having to download it

**Comment by ExyteSGTomfeng** [comment]
Same issue for azure datalake url

**Comment by jbrockmendel** [comment]
pandas support for HDF is in bugfix-only mode, closing as no-action.
