### ISSUE TITLE
Pandas 1.0.1 fails get_loc on timeindex (0.25.3 works)

### ISSUE THREAD

**Issue by AndrewMoscoe** [pandas-dev/pandas#32140]
```python
findtime = pd.Timestamp('2019-12-12 10:19:25', tz='US/Eastern')
start = pd.Timestamp('2019-12-12 0:0:0', tz='US/Eastern')
end = pd.Timestamp('2019-12-13 0:0:0', tz='US/Eastern')
testindex = pd.date_range(start, end, freq='5s')
testindex.get_loc(findtime, method='nearest')

```
#### Problem description
With pandas 1.0.1, python 3.8.1

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\pandas\core\indexes\datetimes.py", line 699, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "C:\Program Files\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2649, in get_loc
    indexer = self.get_indexer([key], method=method, tolerance=tolerance)
  File "C:\Program Files\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2740, in get_indexer
    indexer = self._get_nearest_indexer(target, limit, tolerance)
  File "C:\Program Files\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2821, in _get_nearest_indexer
    left_distances = abs(self.values[left_indexer] - target)
numpy.core._exceptions.UFuncTypeError: ufunc 'subtract' cannot use operands with types dtype('<M8[ns]') and dtype('O')
```

With 0.25.3, this returns index location 7433 as expected.

I've tested this on Windows 10 1909, and Ubuntu WSL, and get the same error on both.

#### Output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Canada.1252

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
```

**Comment by jorisvandenbossche** [comment]
@AndrewMoscoe Thanks for the report!

This is already working again on master. But so we should verify it if also works on the 1.0.x branch (to become 1.0.2), or if there is something we need to backport.

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche This bug was noticed in https://github.com/pandas-dev/pandas/issues/26683#issuecomment-580515579 and fixed in #31511.

so we need to backport that PR. and move the whatsnew. any particular order? Also, do we need to add another test for this?

**Comment by jorisvandenbossche** [comment]
The order is not that important. I think the easiest is to backport the PR (can first try asking MeeseeksDev, in case there is no conflict), and update the branch with moving the whatsnew. And then a separate PR moving the whatsnew just in master. 

I would also still add a test, since the case seems a bit different.

**Comment by simonjayhawkins** [comment]
xref #31964

**Comment by simonjayhawkins** [comment]
OK will 
1. backport #31511 with whatsnew moved.
2. PR to mater with whatsnew move
3. PR to master with this code sample as test case (no need to backport?) to close this issue 
3. PR to master with code sample from  #31964 as test case to close that issue

**Comment by jorisvandenbossche** [comment]
Sounds good, thanks!

**Comment by simonjayhawkins** [comment]
> (can first try asking MeeseeksDev, in case there is no conflict)

had already cherry-picked locally to test. so just created backport manually.
