### ISSUE TITLE
read_csv option 'skipfooter' crashes with lines starting with "

### ISSUE THREAD

**Issue by thomas-haslwanter** [pandas-dev/pandas#32495]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# Generate the test-file
data_file = 'test.txt'

txt = """yyyy
1991
2002
"a
"""

with open(data_file, 'w') as fh:
    fh.write(txt)
    
# Parsing working with:
df_ok = pd.read_csv(data_file, nrows=2)
print(df_ok)

# ... and with
df_ok2 = pd.read_csv(data_file, skipfooter=1, delimiter='[,]', engine='python')
print(df_ok2)

# ... but crashes with
df_crash1 = pd.read_csv(data_file, skipfooter=1, delimiter=',', engine='python')
print(df_crash1)

# ... and with 
df_crash2 = pd.read_csv(data_file, skipfooter=1)
print(df_crash2)
# in order to reach those last 2 lines, you have to comment out lines 24-25

# with the error message:
# ------------------------
# pandas.errors.ParserError: unexpected end of data. Error could possibly be
# due to parsing errors in the skipped footer rows (the skipfooter keyword is
# only applied after Python's csv library has parsed all rows).
# Process terminated with an exit code of 1


```
#### Problem description

Lines in txt-files that start with 
"
can lead to crashes when these lines should be skipped with the option 'skipfooter'.
Funnily, this does NOT happen then the option
delimiter='[,]', engine='python'
is set, but DOES crash when the same option is set with
delimiter=',', engine='python'

The same data are read in correctly when the number of rows is limited with the option 'nrows'.

#### Expected Output
   yyyy
0  1991
1  2002
   yyyy
0  1991
1  2002
   yyyy
0  1991
1  2002
   yyyy
0  1991
1  2002
#### Output of above code sample:

<details>

Traceback (most recent call last):
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 2854, in _next_iter_line
    return next(self.data)
_csv.Error: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Users\thomas\Data\CloudStation\Teaching\Stats\Coding\error_report.py", line 24, in <module>
    df_crash1 = pd.read_csv(data_file, skipfooter=1, delimiter=',', engine='python')
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 2388, in read
    content = self._get_lines(rows)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 3128, in _get_lines
    row_num=self.pos + rows + 1)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 2873, in _next_iter_line
    self._alert_malformed(msg, row_num)
  File "c:\Programs\WPy64-3740\python-3.7.4.amd64\lib\site-packages\pandas\io\parsers.py", line 2835, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: unexpected end of data. Error could possibly be due to parsing errors in the skipped footer rows (the skipfooter keyword is only applied after Python's csv library has parsed all rows).
Process terminated with an exit code of 1

</details>

**Comment by TomAugspurger** [comment]
Doesn't the error message describe this exact situation? You've requested that the rows be skipped, but the parser still has to parse them so any parse errors will be rasied?

**Comment by thomas-haslwanter** [comment]
You are correct - Sorry I missed that!

One more question, though:
what threw me was the fact that it works with the option
`delimiter='[,]'`
but fails with
`delimiter=','`
I still don't understand that, since I thought the two should be the same. But anyway, you can go ahead and close the issue.

Thanks for the quick feedback!
