### ISSUE TITLE
Restore 32 Bit Linux CI 

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#32709]
Noticed in #32706 and temporarily disabled in a follow up #32708

**Comment by TomAugspurger** [comment]
Any details on what went wrong? (azure pipelines deletes their logs fairly quickly)

**Comment by WillAyd** [comment]
Not able to check right now but IIRC correctly was an internal error with the environment itself. The tests themselves never got to running

**Comment by WillAyd** [comment]
Here is the actual failure for now:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=30621&view=logs&j=9d5147b6-7a88-5254-4bdd-57f573fc8952&t=73bf654c-d85c-5eee-993f-c67991c083d2&l=240

**Comment by WillAyd** [comment]
```sh
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/workermanage.py", line 316, in process_from_remote
INTERNALERROR>     rep = unserialize_report(eventname, kwargs["data"])
INTERNALERROR>   File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/workermanage.py", line 423, in unserialize_report
INTERNALERROR>     return runner.TestReport(**assembled_report(reportdict))
INTERNALERROR>   File "/home/vsts/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/xdist/workermanage.py", line 403, in assembled_report
INTERNALERROR>     style=data["style"],
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'filelocrepr'
```
