### ISSUE TITLE
A strange bug in version 1.0.3

### ISSUE THREAD

**Issue by geeeekDing** [pandas-dev/pandas#32917]
```python
# Your code here

import pandas as pd

```
#### Problem description
When I import pandas 1.03  in pycharm, an error message was returned. This error did not occur when I lowered the version of the package to 0.23.4. In addition, this error no occur in spyder .

Traceback (most recent call last):
  File "E:/coherenceestimation/code/venv/ROC_classifier.py", line 8, in <module>
    import pandas as pd
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\core\computation\api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\core\computation\eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\core\computation\engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\core\computation\ops.py", line 17, in <module>
    from pandas.core.computation.scope import _DEFAULT_GLOBALS
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\core\computation\scope.py", line 17, in <module>
    from pandas.compat.chainmap import DeepChainMap
  File "D:\Users\ThinkPad\Anaconda3\envs\MeachineLing\lib\site-packages\pandas\compat\chainmap.py", line 1, in <module>
    from typing import ChainMap, MutableMapping, TypeVar, cast
ImportError: cannot import name 'ChainMap'

**Comment by jbrockmendel** [comment]
what python version is this running?

**Comment by ctheissen** [comment]
I get the same error with Python 3.6.0 and Pandas 1.0.3.

**Comment by TomAugspurger** [comment]
We require Python>=3.6.1.

@geeeekDing let us know if you're using 3.6.1 or newer and we'll reopen.

**Comment by TomAugspurger** [comment]
Actually... are we missing a python requirement in our conda-forge package? https://github.com/conda-forge/pandas-feedstock/blob/master/recipe/meta.yaml Does anyone know how conda-forge sets that?

**Comment by geeeekDing** [comment]
> Actually... are we missing a python requirement in our conda-forge package? https://github.com/conda-forge/pandas-feedstock/blob/master/recipe/meta.yaml Does anyone know how conda-forge sets that?



> We require Python>=3.6.1.
> 
> @geeeekDing let us know if you're using 3.6.1 or newer and we'll reopen.

Thanks, It should be my problem. I met this error in python 3.6.0, Thank you.

**Comment by jbrockmendel** [comment]
Closing as we now require 3.7+
