### ISSUE TITLE
ImportError: Unable to import required dependencies. Most likely due to a circular import. Conflict with numpy

### ISSUE THREAD

**Issue by GrzegorzKrug** [pandas-dev/pandas#32982]
I am working in python 3.8.1 to be specific.
This error appears when runing script in conda environment and also in docker image.

### Reproducing code example:

```
conda create -n analzyer python=3.8.1
conda activate analyzer
pip install -r requirements.txt
python db_initiator.py
```
```
# Requirements.txt
numpy==1.18.2  # This package has conflict 
pandas==1.0.1  
PyQt5==5.14.1
request==2019.4.13
requests==2.23.0
requests_oauthlib==1.3.0
pytest==5.3.5
psycopg2-binary==2.8.4
SQLAlchemy==1.3.15
```
```
#  db_initiator.py
from sqlalchemy import Column, Integer, String, ForeignKey
```

### Error message:
```
Traceback (most recent call last):
  File "/home/greg/_Local/git/TwitterAnalyzer/twitter_analyzer/analyzer/db_initiator.py", line 1, in <module>
    from sqlalchemy import Column, Integer, String, ForeignKey
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/sqlalchemy/util/__init__.py", line 9, in <module>
    from collections import defaultdict  # noqa
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "/home/greg/_Local/git/TwitterAnalyzer/twitter_analyzer/analyzer/operator.py", line 6, in <module>
    import pandas as pd
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/home/greg/anaconda3/envs/analyzer/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: cannot import name 'namedtuple' from partially initialized module 'collections' (most likely due to a circular import) (/home/greg/anaconda3/envs/analyzer/lib/python3.8/collections/__init__.py)


Process finished with exit code 1
```
### Numpy/Python version information:
```
numpy==1.18.2
pandas==1.0.1
```

I can not do this. Got error when importing numpy itself
```
import sys, numpy; print(numpy.__version__, sys.version)
```
```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/numpy/core/multiarray.py", line 9, in <module>
    import functools
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/functools.py", line 17, in <module>
    from collections import namedtuple
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "/home/greg/_Local/git/TwitterAnalyzer/twitter_analyzer/analyzer/operator.py", line 6, in <module>
    import pandas as pd
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/site-packages/pandas/compat/__init__.py", line 10, in <module>
    import platform
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/platform.py", line 117, in <module>
    import re
  File "/home/greg/anaconda3/envs/analyzer/lib/python3.8/re.py", line 313, in <module>
    @functools.lru_cache(_MAXCACHE)
AttributeError: partially initialized module 'functools' has no attribute 'lru_cache' (most likely due to a circular import)
```

From my test, I know that conflict is when I install `pandas` and `numpy` only. Error is the same when importing numpy.
```
$ pip list
Package         Version            
--------------- -------------------
certifi         2019.11.28         
numpy           1.18.2             
pandas          1.0.3              
pip             20.0.2             
python-dateutil 2.8.1              
pytz            2019.3             
setuptools      46.1.1.post20200323
six             1.14.0             
wheel           0.34.2 
```

**Comment by GrzegorzKrug** [comment]
I got operator.py in my files. It breaks everything, but this was problem. I just renamed it and it ok.
