### ISSUE TITLE
Can't Seem to install pandas in python

### ISSUE THREAD

**Issue by kartikdutt18** [pandas-dev/pandas#33035]
I tried running
```
sudo pip install pandas
```
#### Problem description

Tried Installing pandas for python 2.7 . Can't seem to figure it out. Checked similar issues, but they didn't seem to help me.

Numpy version : 1.16.6 (tried other versions as well)

#### Expected Output

Pandas installed successfully.

####Got this output instead:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Using cached pandas-1.0.3.tar.gz (5.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/kd/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/tmpUhhGpr
       cwd: /private/var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/pip-install-6SkeqV/pandas
  Complete output (19 lines):
  Traceback (most recent call last):
    File "/Users/kd/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/Users/kd/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/kd/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/pip-build-env-IK81LY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/pip-build-env-IK81LY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/pip-build-env-IK81LY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/pip-build-env-IK81LY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 42
      f"numpy >= {min_numpy_ver}",
                                ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/kd/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/30/00757twx74l3jppj5c4nq7380000gn/T/tmpUhhGpr Check the logs for full command output
```

**Comment by ei-grad** [comment]
Faced the same issue with Python=3.5, but it looks like it is already fixed some minutes ago.

**Comment by kartikdutt18** [comment]
Yes, Got it working. Thanks a lot @ei-grad. Looks the team here works very fast. Closing this then.

**Comment by JohannesBuchner** [comment]
f-strings are still used here https://github.com/pandas-dev/pandas/blob/master/setup.py#L751
and seem to cause an issue in Python3.5 in travis https://travis-ci.org/github/JohannesBuchner/stan_utility/jobs/694561908 
Does pandas require Python>3.5?

**Comment by JohannesBuchner** [comment]
Oh, I see it now, it says python_requires=">=3.6.1". OK.

**Comment by kartikdutt18** [comment]
Hey @JohannesBuchner, there is pandas 0.24 (I think) that supports python 3.5 other than that you need to python 3.6.
