### ISSUE TITLE
import pandas error.

### ISSUE THREAD

**Issue by HarishGajjar** [pandas-dev/pandas#33258]
dear pandas-dev,
I am writing this to yo because I have facing problem with pandas lib to use it with python 3.8,
when I try to import pandas its shows error, please check attachment for more details.
Thanks.

=========================================================
error message
==========================================================
>>> import pandas
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import pandas
  File "C:\Python\Python38-32\lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\groupby\generic.py", line 60, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\frame.py", line 124, in <module>
    from pandas.core.series import Series
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\series.py", line 4572, in <module>
    Series._add_series_or_dataframe_operations()
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 10349, in _add_series_or_dataframe_operations
    from pandas.core.window import EWM, Expanding, Rolling, Window
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
    from pandas.core.window.ewm import EWM  # noqa:F401
  File "C:\Python\Python38-32\lib\site-packages\pandas\core\window\ewm.py", line 5, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed while importing aggregations: The specified module could not be found.
==============================================================
[import pandas error report.pdf](https://github.com/pandas-dev/pandas/files/4426773/import.pandas.error.report.pdf)

**Comment by HarishGajjar** [comment]
import pandas error

**Comment by TomAugspurger** [comment]
See https://github.com/pandas-dev/pandas/issues/32857. Hoping to have it fixed soon.

pandas 1.0.1 and earlier should be OK.

**Comment by HarishGajjar** [comment]
@TomAugspurger Thanks for the solution.
