### ISSUE TITLE
BUG: User-facing AssertionError in Series.to_timestamp

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33327]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python

In [5]: import pandas as pd

In [6]: pd.Series([0]).to_timestamp()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-1a9d08d7daba> in <module>
----> 1 pd.Series([0]).to_timestamp()

~/sandbox/pandas/pandas/core/series.py in to_timestamp(self, freq, how, copy)
   4565             new_values = new_values.copy()
   4566
-> 4567         assert isinstance(self.index, (ABCDatetimeIndex, ABCPeriodIndex))
   4568         new_index = self.index.to_timestamp(freq=freq, how=how)
   4569         return self._constructor(new_values, index=new_index).__finalize__(

AssertionError:
```

#### Problem description

Users shouldn't see AssertionErrors like this, since they may be disabled when the interpreter starts up.

#### Expected Output

We probably want this to be a `TypeError`.

**Comment by TomAugspurger** [comment]
Same issue applies to Series.to_period

**Comment by dsaxton** [comment]
@TomAugspurger Are those assertions in order to placate mypy? Wonder if there's another way of doing that?

**Comment by TomAugspurger** [comment]
Not sure. I would hope that with

```python
if not isinstance(self.index (ABCDatetimeIndex, ABCPeriodIndex)):
    raise TypeError(...)

# hopefully mypy knows the types here
```

but we can make the `assert` for mypy after we've done the user-facing check if needed.

**Comment by CerseiO** [comment]
take

**Comment by vipulrai91** [comment]
Hello @CerseiO are you working on this or shall I work ?

**Comment by CerseiO** [comment]
Hello @vipulrai91, not now, you can work on this.

**Comment by vipulrai91** [comment]
> Hello @vipulrai91, not now, you can work on this.

Thanks for confirming.

**Comment by vipulrai91** [comment]
take

**Comment by vipulrai91** [comment]
@TomAugspurger 

Does this work ?

```python
>>> pd.Series([0]).to_timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vipul/Work/Github/pandas/pandas/core/series.py", line 4665, in to_timestamp
    raise TypeError(f"unsupported Type {self.index}")
TypeError: unsupported Type RangeIndex(start=0, stop=1, step=1)
```

The code change made was:
```python
if not isinstance(self.index, (ABCDatetimeIndex, ABCPeriodIndex)):
          raise TypeError(f"unsupported Type {self.index}")
new_index = self.index.to_timestamp(freq=freq, how=how)
return self._constructor(new_values, index=new_index).__finalize__(
            self, method="to_timestamp")
```

**Comment by simonjayhawkins** [comment]
> * [x]  I have confirmed this bug exists on the latest version of pandas.

the assertion was added in #31126

on 1.0.3

```
>>> import pandas as pd
>>>
>>> pd.__version__
'1.0.3'
>>>
>>> pd.Series([0]).to_timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\core\series.py", line 4529, in to_timestamp
    new_index = self.index.to_timestamp(freq=freq, how=how)
AttributeError: 'RangeIndex' object has no attribute 'to_timestamp'
>>>
```
