### ISSUE TITLE
BUG:RecursionError occur when running the script which belongs to other directories

### ISSUE THREAD

**Issue by RH-bB** [pandas-dev/pandas#33841]
This is my first issue. So, if I'm wrong, please teach me to be kind!

I cannot import pandas when running the script which belongs to other directories.

```python
# workdir/src/sample.py
import numpy as np
import pandas as pd

```
```bash
/workdir$ python src/sample.py
```
```
Traceback (most recent call last):
  File "src/sample.py", line 2, in <module>
    import pandas as pd
  File "/usr/local/share/pip-global/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/usr/local/share/pip-global/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/usr/local/share/pip-global/pandas/core/arrays/__init__.py", line 7, in <module>
    from .categorical import Categorical  # noqa: F401
  File "/usr/local/share/pip-global/pandas/core/arrays/categorical.py", line 54, in <module>
    from pandas.core.base import NoNewAttributesMixin, PandasObject, _shared_docs
  File "/usr/local/share/pip-global/pandas/core/base.py", line 36, in <module>
    import pandas.core.nanops as nanops
  File "/usr/local/share/pip-global/pandas/core/nanops.py", line 38, in <module>
    bn = import_optional_dependency("bottleneck", raise_on_missing=False, on_version="warn")
  File "/usr/local/share/pip-global/pandas/compat/_optional.py", line 90, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.7/site-packages/bottleneck/__init__.py", line 41, in <module>
    from numpy.testing import Tester
  File "/usr/local/share/pip-global/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/opt/conda/lib/python3.7/unittest/__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "/opt/conda/lib/python3.7/unittest/case.py", line 6, in <module>
    import logging
  File "/workdir/src/logging.py", line 5, in <module>
    from lightgbm.callback import _format_eval_result
  File "/usr/local/share/pip-global/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset
  File "/usr/local/share/pip-global/lightgbm/basic.py", line 12, in <module>
    import scipy.sparse
  File "/usr/local/share/pip-global/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/local/share/pip-global/scipy/sparse/base.py", line 7, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/usr/local/share/pip-global/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns
  File "/usr/local/share/pip-global/numpy/__init__.py", line 213, in __getattr__
    import numpy.testing as testing
  File "/usr/local/share/pip-global/numpy/__init__.py", line 213, in __getattr__
    import numpy.testing as testing
  File "/usr/local/share/pip-global/numpy/__init__.py", line 213, in __getattr__
    import numpy.testing as testing
  [Previous line repeated 871 more times]
  File "<frozen importlib._bootstrap>", line 200, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 163, in _get_module_lock
RecursionError: maximum recursion depth exceeded while calling a Python object
```

#### Output of ``pd.show_versions()``
'1.0.3'

**Comment by MarcoGorelli** [comment]
If you type
```bash
/workdir$ python
```
and then
```python
import pandas as pd

pd.show_versions()
```

does that work? If so, can you include the full output?

**Comment by MarcoGorelli** [comment]
Also, do you have a file called `logging.py` inside the `src` directory? If so, can you try renaming it?

**Comment by RH-bB** [comment]
Ohh, 
```logging.py``` in src directory.

I renamed this, it works fine.
Thanks!!
