### ISSUE TITLE
BUG: eval not working with fillna

### ISSUE THREAD

**Issue by meakbiyik** [pandas-dev/pandas#34045]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

```python
import pandas as pd
d = pd.DataFrame([1, 2], columns=['a'])
d.eval('((a-1)/(a-1)).fillna(0)')
```

#### Problem description
With eval, fillna function raises an obscure error

```python
>>> d.eval('(a-1)/(a-1)')
0    NaN
1    1.0
Name: a, dtype: float64
>>> d.eval('((a-1)/(a-1)).fillna(0)')
Traceback (most recent call last):
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\frame.py", line 3346, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\eval.py", line 332, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 764, in __init__
    self.terms = self.parse()
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 781, in parse
    return self._visitor.visit(self.expr)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 381, in visit_Module
    return self.visit(expr, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 384, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 622, in visit_Call
    res = self.visit_Attribute(node.func)
  File "C:\Users\ErenAkbiyik\.conda\envs\work\lib\site-packages\pandas\core\computation\expr.py", line 607, in visit_Attribute
    resolved = self.visit(value).value
AttributeError: 'Div' object has no attribute 'value'
```

#### Expected Output

```python
>>> d.eval('(a-1)/(a-1)')
0    0.0
1    1.0
Name: a, dtype: float64
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.3
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by meakbiyik** [comment]
Now I think maybe this is not possible with eval at all. But then, how can I imitate the functionality of fillna while using eval?

**Comment by Shailly26** [comment]
take

**Comment by Shailly26** [comment]
Hi meakbiyik, 
Try this:
d.eval('((a-1)/(a-1))').fillna(0)

Output:
0    0.0
1    1.0
dtype: float64

**Comment by meakbiyik** [comment]
Hi @Shailly26, for some reasons it is not possible for me to perform additional operations to the eval'd string, it should contain all operations by itself. What I found as the solution was to do something like this:

```python
expr = '''b = (a-1)/(a-1)
          c = b.fillna(0)'''
d.eval(expr)
```

This works, but I think it is not optimal from a performance perspective. Since the new approach is functional, I am convinced that this is a bug, Div objects (and other operations) should have the namespace of a pandas dataframe if they include a dataframe themselves, and same with Series.
