### ISSUE TITLE
BUG: blosc:snappy doesn't seem to be supported with blosc=1.19.0

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas#34620]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example
The following example works with blosc=1.18.1 but fails with the latest blosc (1.19.0)

conda install pandas pytables blosc=1.18.1 # works
conda install pandas pytables blosc=1.19.0 # leads to failure

```python
import numpy as np
import pandas as pd

pd.DataFrame(np.random.rand(10, 3)).to_hdf("test.hdf", "df", complib="blosc:snappy")
```

#### Problem description
The error message is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/twoertwe/miniforge3/envs/test/lib/python3.8/site-packages/pandas/core/generic.py", line 2490, in to_hdf
    pytables.to_hdf(
  File "/home/twoertwe/miniforge3/envs/test/lib/python3.8/site-packages/pandas/io/pytables.py", line 279, in to_hdf
    with HDFStore(
  File "/home/twoertwe/miniforge3/envs/test/lib/python3.8/site-packages/pandas/io/pytables.py", line 521, in __init__
    raise ValueError(
ValueError: complib only supports ['zlib', 'lzo', 'bzip2', 'blosc', 'blosc:blosclz', 'blosc:lz4', 'blosc:lz4hc', 'blosc:zlib', 'blosc:zstd'] compression.
```

The change log of blosc doesn't mentioned snappy: https://github.com/Blosc/c-blosc/releases

#### Expected Output

The compression should either work or `to_hdf` should mention that `blosc:snappy` doesn't work with `blosc=1.19.0`.

#### Output of ``pd.show_versions()``

<details>

I installed the latest blosc as above but for some reason  ``pd.show_versions()`` doesn't find it.

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.5.2.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.1.post20200529
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by twoertwein** [comment]
@akvail found that pytables prefers an external installation of blosc (https://github.com/conda-forge/pytables-feedstock/pull/30) but the conda-forge build of blosc seems to be built with the default configuration that does not provide support for snappy. The anaconda package of blosc supports snappy :)

`conda config --env --add pinned_packages anaconda::blosc`

If blosc is already installed:
`conda install --force-reinstall blosc -c anaconda`
