### ISSUE TITLE
ERR: could pandas suggest to use bitwise operators to filter instead of `and` and `or`, as on Kaggle?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#35037]
Currently, if one writes
```python
>>> import pandas as pd
>>> df = pd.DataFrame([1,2,3])
>>> df
   0
0  1
1  2
2  3
```
then the traceback shows
```python-traceback
>>> df[df[0].ge(0) and df[0].lt(0)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/pandas-dev/pandas/core/generic.py", line 1326, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I've noticed that [Kaggle]() add their own warning when someone tries to do this:
```
To combine filtering conditions in Pandas, use bitwise operators ('&' and '|') not pure Python ones ('and' and 'or')
```

See below:

![image](https://user-images.githubusercontent.com/33491632/85942450-4facb780-b921-11ea-968d-3b1453ff200d.png)

----

Sure, there's no way of reading users' minds - perhaps they reached this error by some other means - but would the error message be clearer if there was an extra line reading
```
If you were trying to combine filtering conditions in Pandas, use bitwise operators ('&' and '|') instead of pure Python ones ('and' and 'or')
```
?

**Comment by erfannariman** [comment]
This would be a good improvement to the API, as someone being quite active on SO, I see this questions quite often.

**Comment by erfannariman** [comment]
It is also marked as an "highly active question": [link](https://stackoverflow.com/questions/36921951/truth-value-of-a-series-is-ambiguous-use-a-empty-a-bool-a-item-a-any-o)

**Comment by WillAyd** [comment]
I don't know the entire history of this but I think more of a numpy question than a pandas one

My guess is there is ambiguity as to what `and` would mean when comparing say an array to an array versus an array to a scalar, etc... but someone else probably knows more of the reasoning
