### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'compare' 

### ISSUE THREAD

**Issue by RandyBetancourt** [pandas-dev/pandas#35145]
pandas .compare() from the [documentation ](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.compare.html)returns:

```AttributeError: 'DataFrame' object has no attribute 'compare'```

```
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>>
>>> print(pd.__name__, pd.__version__)
pandas 1.0.3
>>>
>>> df = pd.DataFrame(
...     {
...         "col1": ["a", "a", "b", "b", "a"],
...         "col2": [1.0, 2.0, 3.0, np.nan, 5.0],
...         "col3": [1.0, 2.0, 3.0, 4.0, 5.0]
...     },
...     columns=["col1", "col2", "col3"],
... )
>>> df
  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0
>>>
>>> df2 = df.copy()
>>> df2.loc[0, 'col1'] = 'c'
>>> df2.loc[2, 'col3'] = 4.0
>>> df2
  col1  col2  col3
0    c   1.0   1.0
1    a   2.0   2.0
2    b   3.0   4.0
3    b   NaN   4.0
4    a   5.0   5.0
>>>
>>> df.compare(df2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\randy\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'compare'
```

**Comment by jreback** [comment]
this is in 1.1 which is not yet released

**Comment by jreback** [comment]
you are looking at the dev docs
