### ISSUE TITLE
Python3.6 FreeBSD pip3 install pandas fails with error 1

### ISSUE THREAD

**Issue by andibb** [pandas-dev/pandas#35193]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by andibb** [comment]
Hi, I am trying to install pandas on a freeBSD jail. I am able to install other packages, except pandas. I copied the error I get.
If you need any further information just leave me a reply


  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip                                                    install --ignore-installed --no-user --prefix /tmp/pip-build-env-dv0titcu/overla                                                   y --no-warn-script-location --no-binary :none: --only-binary :none: -i https://p                                                   ypi.org/simple -- setuptools wheel 'Cython>=0.29.13' 'numpy==1.13.3; python_vers                                                   ion=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_ve                                                   rsion=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_                                                   version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; pytho                                                   n_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; pyt                                                   hon_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; p                                                   ython_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (142 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"'                                                    don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"'                                                    don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"'                                                    don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"'                                                    don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"'                                                    don't match your environment
  Collecting setuptools
    Using cached setuptools-49.1.0-py3-none-any.whl (789 kB)
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting Cython>=0.29.13
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
  Collecting numpy==1.13.3
    Using cached numpy-1.13.3.zip (5.0 MB)
  Using legacy setup.py install for numpy, since package 'wheel' is not installe                                                   d.
  Installing collected packages: setuptools, wheel, Cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize                                                   ; sys.argv[0] = '"'"'/tmp/pip-install-u4n1u5ot/numpy/setup.py'"'"'; __file__='"'                                                   "'/tmp/pip-install-u4n1u5ot/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'                                                   "', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close(                                                   );exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-recor                                                   d-3p8cocvy/install-record.txt --single-version-externally-managed --prefix /tmp/                                                   pip-build-env-dv0titcu/overlay --compile --install-headers /tmp/pip-build-env-dv                                                   0titcu/overlay/include/python3.6m/numpy
           cwd: /tmp/pip-install-u4n1u5ot/numpy/
      Complete output (119 lines):
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      blas_opt_info:
      blas_mkl_info:
        libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_info:
        FOUND:
          libraries = ['openblas', 'openblas']
          library_dirs = ['/usr/local/lib']
          language = c
          define_macros = [('HAVE_CBLAS', None)]

        FOUND:
          libraries = ['openblas', 'openblas']
          library_dirs = ['/usr/local/lib']
          language = c
          define_macros = [('HAVE_CBLAS', None)]

      /bin/sh: svnversion: not found
      non-existing path in 'numpy/distutils': 'site.cfg'
      /bin/sh: svnversion: not found
      F2PY Version 2
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_lapack_info:
      customize UnixCCompiler
      C compiler: cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-co                                                   de -DNDEBUG -g -fwrapv -O3 -Wall -fPIC

      creating /tmp/tmpvrtkn97t/tmp
      creating /tmp/tmpvrtkn97t/tmp/tmpvrtkn97t
      compile options: '-MMD -MF /tmp/tmpvrtkn97t/file.c.d -c'
      cc: /tmp/tmpvrtkn97t/file.c

      C compiler: cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-co                                                   de -DNDEBUG -g -fwrapv -O3 -Wall -fPIC

      creating /tmp/tmpmmlnmzfe/tmp
      creating /tmp/tmpmmlnmzfe/tmp/tmpmmlnmzfe
      compile options: '-c'
      cc: /tmp/tmpmmlnmzfe/source.c

      Traceback (most recent call last):
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/unixccompiler.py",                                                    line 58, in UnixCCompiler__compile
          extra_postargs, display = display)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 152, in CCompiler_spawn
          raise DistutilsExecError('Command "%s" failed with exit status %d%s' %                                                    (cmd, s, msg))
      distutils.errors.DistutilsExecError: Command "cc -pthread -Wno-unused-resu                                                   lt -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -c /tmp                                                   /tmpmmlnmzfe/source.c -o /tmp/tmpmmlnmzfe/tmp/tmpmmlnmzfe/source.o" failed with                                                    exit status 127

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-u4n1u5ot/numpy/setup.py", line 392, in <module>
          setup_package()
        File "/tmp/pip-install-u4n1u5ot/numpy/setup.py", line 384, in setup_pack                                                   age
          setup(**metadata)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/core.py", line 135                                                   , in setup
          config = configuration()
        File "/tmp/pip-install-u4n1u5ot/numpy/setup.py", line 166, in configurat                                                   ion
          config.add_subpackage('numpy')
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 1029, in add_subpackage
          caller_level = 2)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 998, in get_subpackage
          caller_level = caller_level + 1)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 935, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 16, in configuration
          config.add_subpackage('linalg')
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 1029, in add_subpackage
          caller_level = 2)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 998, in get_subpackage
          caller_level = caller_level + 1)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/misc_util.py", lin                                                   e 935, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/linalg/setup.py", line 29, in configuration
          lapack_info = get_info('lapack_opt', 0)  # and {}
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 380, in get_info
          return cl().get_info(notfound_action)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 572, in get_info
          self.calc_info()
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 1478, in calc_info
          openblas_info = get_info('openblas_lapack')
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 380, in get_info
          return cl().get_info(notfound_action)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 572, in get_info
          self.calc_info()
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 1755, in calc_info
          if not self.check_embedded_lapack(info):
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/system_info.py", l                                                   ine 1790, in check_embedded_lapack
          obj = c.compile([src], output_dir=tmpdir)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 343, in CCompiler_compile
          single_compile(o)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 303, in single_compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/ccompiler.py", lin                                                   e 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/tmp/pip-install-u4n1u5ot/numpy/numpy/distutils/unixccompiler.py",                                                    line 61, in UnixCCompiler__compile
          raise CompileError(msg)
      distutils.errors.CompileError: Command "cc -pthread -Wno-unused-result -Ws                                                   ign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -c /tmp/tmpmm                                                   lnmzfe/source.c -o /tmp/tmpmmlnmzfe/tmp/tmpmmlnmzfe/source.o" failed with exit s                                                   tatus 127
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 -u -c                                                    'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u4n1u5ot/                                                   numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u4n1u5ot/numpy/setup.py'"'"'                                                   ;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'                                                   \r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))                                                   ' install --record /tmp/pip-record-3p8cocvy/install-record.txt --single-version-                                                   externally-managed --prefix /tmp/pip-build-env-dv0titcu/overlay --compile --inst                                                   all-headers /tmp/pip-build-env-dv0titcu/overlay/include/python3.6m/numpy Check t                                                   he logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 /usr/loc                                                   al/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix                                                    /tmp/pip-build-env-dv0titcu/overlay --no-warn-script-location --no-binary :none                                                   : --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0                                                   .29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'                                                   AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'                                                   "'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='                                                   "'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=                                                   ='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_syste                                                   m=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_sys                                                   tem=='"'"'AIX'"'"'' Check the logs for full command output.

**Comment by WillAyd** [comment]
Unless I am misreading the traceback it looks like your issue is installing numpy from source. With that the case you should probably check StackOverflow for that and if no luck try opening an issue on their Github

**Comment by andibb** [comment]
Thank you for helping me out. I will give it a try next week.

William Ayd <notifications@github.com> schrieb am Sa., 11. Juli 2020, 17:54:
