### ISSUE TITLE
Non-intuitive behavior when multi-indexing a Series

### ISSUE THREAD

**Issue by konstantinmiller** [pandas-dev/pandas#35349]
Most likely that is not a bug but intended behavior but I find it quite confusing.

Consider the following example
```
idx = pd.IndexSlice
s = pd.Series(index=pd.MultiIndex.from_tuples([('A', '0'), ('A', '1'), ('B', '0')]), 
              data=[21, 22, 23])
s.loc[idx['A', :], :]
```
which gives
```
A  0    21
   1    22
B  0    23
dtype: int64
```
while intuitively, one would expect
```
A  0    21
   1    22
dtype: int64
```
I would expect the latter because that's what you would get with a `pd.DataFrame` where the second `:` is referring to the column index. Not paying attention that the object is a series, gives you a completely different result than if you would have a data frame.

**Comment by simonjayhawkins** [comment]
Thanks @konstantinmiller for the report.

on master this now raises an Exception instead of producing the unexpected behaviour. What version of pandas are you using.

```
>>> import pandas as pd
>>>
>>> pd.__version__
'1.1.0rc0'
>>>
>>> idx = pd.IndexSlice
>>> s = pd.Series(
...     index=pd.MultiIndex.from_tuples([("A", "0"), ("A", "1"), ("B", "0")]),
...     data=[21, 22, 23],
... )
>>> s
A  0    21
   1    22
B  0    23
dtype: int64
>>>
>>> s.loc[idx["A", :], :]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\pandas\pandas\core\indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\simon\pandas\pandas\core\indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\simon\pandas\pandas\core\indexing.py", line 766, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "C:\Users\simon\pandas\pandas\core\indexing.py", line 834, in _getitem_nested_tuple
    return self._getitem_axis(tup, axis=axis)
  File "C:\Users\simon\pandas\pandas\core\indexing.py", line 1103, in _getitem_axis
    locs = labels.get_locs(key)
  File "C:\Users\simon\pandas\pandas\core\indexes\multi.py", line 3108, in get_locs
    indexer = self._reorder_indexer(seq, indexer)
  File "C:\Users\simon\pandas\pandas\core\indexes\multi.py", line 3137, in _reorder_indexer
    k_codes = self.levels[i].get_indexer(k)
  File "C:\Users\simon\pandas\pandas\core\indexes\base.py", line 3000, in get_indexer
    indexer = self._engine.get_indexer(target._get_engine_target())
  File "pandas\_libs\index.pyx", line 254, in pandas._libs.index.IndexEngine.get_indexer
    return self.mapping.lookup(values)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1724, in pandas._libs.hashtable.PyObjectHashTable.lookup
    hash(val)
TypeError: unhashable type: 'slice'
>>>
```

I would say that maybe this is still incorrect and I think that the error should reflect that too many indexers are involved.

**Comment by konstantinmiller** [comment]
I'm using 1.0.5. Sorry for not checking the behavior on the mater branch, I should have done that. So, great that it's now raising an exception.

Of course, if possible, it would be helpful to have a more expressive error message pointing clearer to the actual error :)
