### ISSUE TITLE
QST:module 'pandas.core.indexing' has no attribute 'get_indexers_list'

### ISSUE THREAD

**Issue by ziwang-com** [pandas-dev/pandas#35404]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```
n [1]: runfile('D:/zwPython/demo/zw005xver.py', wdir='D:/zwPython/demo')
Traceback (most recent call last):

  File "D:\zwPython\demo\zw005xver.py", line 29, in <module>
    import zipline

  File "D:\zwPython\py3\python-3.8.3.amd64\lib\site-packages\zipline\__init__.py", line 24, in <module>
    from . import finance

  File "D:\zwPython\py3\python-3.8.3.amd64\lib\site-packages\zipline\finance\__init__.py", line 16, in <module>
    from . import execution, trading

  File "D:\zwPython\py3\python-3.8.3.amd64\lib\site-packages\zipline\finance\trading.py", line 20, in <module>
    from zipline.utils.pandas_utils import normalize_date

  File "D:\zwPython\py3\python-3.8.3.amd64\lib\site-packages\zipline\utils\pandas_utils.py", line 223, in <module>
    '_' + name for (name, _) in pd.core.indexing.get_indexers_list()

AttributeError: module 'pandas.core.indexing' has no attribute 'get_indexers_list'

**Comment by jreback** [comment]
you would have to bring this up to ziplime - this is a private method
