### ISSUE TITLE
Attribute "dtype" are different error with testing.assert_frame_equal

### ISSUE THREAD

**Issue by openskullbox** [pandas-dev/pandas#35715]
Hi,
When trying testing.assert_frame_equal, I get an assert error.
E           Attribute "dtype" are different
E           [left]:  Int64
E           [right]: Int16

However, for assert_frame_equal, I do set the argument `check_dtype=False`.

From traceback, I can see that `assert_extension_array_equal` is being called with `check_dtype=True` which is causing the issue.

I do not have a sample at hand and I will update when I can.

Affected version: 1.1.0
The test cases were / are running fine with 1.0.5

**Comment by MarcoGorelli** [comment]
Thanks for the report - the following fails for me on 1.0.5 as well:

```python-traceback
>>> import pandas as pd
>>> a = pd.DataFrame({'a': [1]}, dtype='Int64')
>>> b = pd.DataFrame({'a': [1]}, dtype='Int16')
>>> pd.testing.assert_frame_equal(a, b, check_dtype=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgorelli/miniconda3/envs/old-pandas/lib/python3.7/site-packages/pandas/_testing.py", line 1382, in assert_frame_equal
    obj=f'{obj}.iloc[:, {i}] (column name="{col}")',
  File "/home/mgorelli/miniconda3/envs/old-pandas/lib/python3.7/site-packages/pandas/_testing.py", line 1184, in assert_series_equal
    assert_extension_array_equal(left.array, right.array)
  File "/home/mgorelli/miniconda3/envs/old-pandas/lib/python3.7/site-packages/pandas/_testing.py", line 1022, in assert_extension_array_equal
    assert_attr_equal("dtype", left, right, obj="ExtensionArray")
  File "/home/mgorelli/miniconda3/envs/old-pandas/lib/python3.7/site-packages/pandas/_testing.py", line 772, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/home/mgorelli/miniconda3/envs/old-pandas/lib/python3.7/site-packages/pandas/_testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: ExtensionArray are different

Attribute "dtype" are different
[left]:  Int64
[right]: Int16
>>> pd.__version__
'1.0.5'
```

**Comment by simonjayhawkins** [comment]
> The test cases were / are running fine with 1.0.5

@openskullbox Thanks for the report. labelled as a bug for now. If you show an case where this worked in 1.0.5, that'll be great.
