### ISSUE TITLE
CI: Travis failing with INTERNALERROR

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#35737]
I'm seeing this on every recent Travis 37-coverage build:

```
============================= test session starts ==============================
platform linux -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/travis/build/pandas-dev/pandas, configfile: setup.cfg, testpaths: pandas
plugins: xdist-2.0.0, cov-2.10.0, forked-1.2.0, hypothesis-5.24.0
gw0 I
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/_pytest/main.py", line 238, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/xdist/dsession.py", line 78, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/xdist/workermanage.py", line 65, in setup_nodes
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/xdist/workermanage.py", line 65, in <listcomp>
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/xdist/workermanage.py", line 73, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/xdist/workermanage.py", line 260, in setup
INTERNALERROR>     self.config.hook.pytest_configure_node(node=self)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pytest_cov/plugin.py", line 239, in pytest_configure_node
INTERNALERROR>     self.cov_controller.configure_node(node)
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pytest_cov/engine.py", line 274, in configure_node
INTERNALERROR>     workerinput(node).update({
INTERNALERROR>   File "/home/travis/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/pytest_cov/compat.py", line 42, in fn
INTERNALERROR>     return getattr(obj, attr, *args)
INTERNALERROR> AttributeError: 'WorkerController' object has no attribute 'slaveinput'
The command "ci/run_tests.sh" exited with 3.

```

**Comment by rhshadrach** [comment]
I think this is related to the removal of (slave from pytest-xdist)[https://github.com/pytest-dev/pytest-cov/issues/411]; this should be fixed in pytest-cov version 2.10.1 ((ref)[https://pytest-cov.readthedocs.io/en/latest/changelog.html] which was published about a day ago, but Travis doesn't seem to be pulling it in just yet.

**Comment by alimcmaster1** [comment]
Lets try: https://github.com/pandas-dev/pandas/pull/35754

**Comment by alimcmaster1** [comment]
```
Current thread 0x00001110 (most recent call first):
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\psutil\_pswindows.py", line 993 in open_files
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\psutil\_pswindows.py", line 679 in wrapper
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\psutil\__init__.py", line 1154 in open_files
  File "D:\a\1\s\pandas\util\_test_decorators.py", line 256 in file_leak_context
  File "C:\Miniconda\envs\pandas-dev\lib\contextlib.py", line 112 in __enter__
  File "D:\a\1\s\pandas\util\_test_decorators.py", line 242 in check_file_leaks
  File "D:\a\1\s\pandas\tests\io\parser\test_common.py", line 2150 in test_file_descriptor_leak
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\_pytest\python.py", line 180 in pytest_pyfunc_call
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\_pytest\python.py", line 1567 in runtest
  File "C:\Miniconda\envs\pandas-dev\lib\site-packages\_pytest\runner.py", line 153 in pytest_runtest_call
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>
[gw2] node down: Not properly terminated
F
replacing crashed worker gw2
```
Also seeing this with the latest pytest-xdist release 2.0.0. We should maybe just pin to <2.0.0 similar to Scipy:
https://github.com/scipy/scipy/pull/12730

**Comment by jreback** [comment]
yep let's ping it (and create an issue to unpin once a stable release lands)
