### ISSUE TITLE
Pandas fails to build in AIX with Python 3.7

### ISSUE THREAD

**Issue by ayappanec** [pandas-dev/pandas#36070]
Building Pandas master branch in AIX fails with the below error

ERROR: Command errored out with exit status 1:
   command: /opt/freeware/bin/python3 /opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3r6qx0fj
       cwd: /tmp/pip-req-build-_gzfu3c7
  Complete output (30 lines):
  Traceback (most recent call last):
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 25, in <module>
      cmdclass = versioneer.get_cmdclass()
    File "/tmp/pip-req-build-_gzfu3c7/versioneer.py", line 1543, in get_cmdclass
      from setuptools.command.sdist import sdist as _sdist
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/command/__init__.py", line 8, in <module>
      from distutils.command.bdist import bdist
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/bdist.py", line 24, in <module>
      class bdist(Command):
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/bdist.py", line 32, in bdist
      "(default: %s)" % get_platform()),
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 107, in get_platform
      return get_host_platform()
    File "/tmp/pip-build-env-s1psbl1s/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 82, in get_host_platform
      from _aix_support import aix_platform
  ModuleNotFoundError: No module named '_aix_support'

Same issue which affects the scipy build as well --> https://github.com/scipy/scipy/issues/12797

**Comment by jreback** [comment]
note that we don't support AIX explicitly (eg test) but will take patches

**Comment by ayappanec** [comment]
The issue is fixed in setuptools 50.0.1 onwards. Now the pandas build succeeds.
