### ISSUE TITLE
TYP: typing errors for mypy==0.790

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#37104]
```
mypy pandas
pandas/core/computation/parsing.py:41: error: unused 'type: ignore' comment
pandas/io/common.py:452: error: Unsupported operand types for + ("List[Optional[str]]" and "List[str]")  [operator]
pandas/core/aggregation.py:483: error: Value of type variable "_LT" of "sorted" cannot be "Optional[Hashable]"  [type-var]
pandas/core/aggregation.py:606: error: Value of type variable "_LT" of "sorted" cannot be "Optional[Hashable]"  [type-var]
pandas/core/groupby/ops.py:270: error: Incompatible types in assignment (expression has type "Index", variable has type "Iterator[Any]")  [assignment]
pandas/core/groupby/ops.py:270: note: 'Index' is missing following 'Iterator' protocol member:
pandas/core/groupby/ops.py:270: note:     __next__
Found 5 errors in 4 files (checked 1057 source files)
```

**Comment by dsaxton** [comment]
Is the error for L452 in common.py right? Seems fine to add a list of strings and None to a list of strings.

**Comment by simonjayhawkins** [comment]
This seems a common issue in expressions with concatinating strings. Mypy inference determines the type from the first sequence.

when assigning the result, then it is the type of the result that is important, so these errors could be considered false positives.

It is quite messy to add casts to resolve these, so ignores are probably OK.

It is possible to refactor, using unpacking, so that mypy doesn't complain, but I don't think this method gets universal approval. i.e.

["foo", None] + [1, 2, 3] -> ["foo", None, *[1, 2, 3]]

**Comment by simonjayhawkins** [comment]
```
pandas/core/aggregation.py:483: error: Value of type variable "_LT" of "sorted" cannot be "Optional[Hashable]"  [type-var]
pandas/core/aggregation.py:606: error: Value of type variable "_LT" of "sorted" cannot be "Optional[Hashable]"  [type-var]
```

These are not false positives...

```
>>> sorted([None,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'int' and 'NoneType'
>>> sorted([1, "foo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'str' and 'int'
>>> 
```

opened #39025 for one of the cases

**Comment by simonjayhawkins** [comment]
due to recent changes we have an additional mypy error

```
pandas/io/common.py:182: error: Only @runtime_checkable protocols can be used with instance and class checks  [misc]
```

may need to revert #38018. further investigation (and code sample) on whether there was a regression
