### ISSUE TITLE
BUG: Groupby any/all raises TypeError for pd.NA 

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#37501]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

df = pd.DataFrame({"a": [1, 1, 2, 2, 3, 3, 4], "b": [1, pd.NA, 2, 3, 4, 5, 6]})
grouped = df.groupby("a")
print(grouped.all())
print(grouped.any())

```

#### Problem description

Both raise a ``TypeError``

Traceback:

```
Traceback (most recent call last):
  File "/home/developer/.config/JetBrains/PyCharm2020.2/scratches/scratch_4.py", line 10, in <module>
    print(grouped.all())
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/groupby.py", line 1424, in all
    return self._bool_agg("all", skipna)
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/groupby.py", line 1375, in _bool_agg
    return self._get_cythonized_result(
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/groupby.py", line 2631, in _get_cythonized_result
    raise TypeError(error_msg)
TypeError: boolean value of NA is ambiguous
```

Maybe using mask like in ``print(df.all(axis=1))``?

#### Expected Output

Should work like with ``np.nan`` and return

```
      b
a      
1  True
2  True
3  True
4  True
      b
a      
1  True
2  True
3  True
4  True
```

#### Output of ``pd.show_versions()``

<details>
master

</details>

**Comment by phofl** [comment]
Similar:

```
df = pd.DataFrame({"a": [1, 1, 2, 2, 3, 3, 4], "b": [1, pd.NA, 2, 3, 4, 5, 6]})
grouped = df.groupby("a")
print(grouped.mean())
```

raises a ``DataError``

Traceback:

```
Traceback (most recent call last):
  File "/home/developer/.config/JetBrains/PyCharm2020.2/scratches/scratch_4.py", line 10, in <module>
    print(grouped.mean())
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/groupby.py", line 1490, in mean
    return self._cython_agg_general(
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/generic.py", line 1021, in _cython_agg_general
    agg_mgr = self._cython_agg_blocks(
  File "/home/developer/PycharmProjects/pandas/pandas/core/groupby/generic.py", line 1123, in _cython_agg_blocks
    raise DataError("No numeric types to aggregate")
pandas.core.base.DataError: No numeric types to aggregate
```

while

``print(grouped.sum())`` works.

**Comment by arw2019** [comment]
I think this falls under the umbrella of #37494

**Comment by arw2019** [comment]
> I think this falls under the umbrella of #37494

On a second look I think this is an independent issue

**Comment by GYHHAHA** [comment]
The `groupby.all` or `groupby.any` problem comes from `bool(pd.NA)` is ambiguous.
https://github.com/pandas-dev/pandas/blob/d3788525ee368db0b6565b72ab4eeba9140fd1d4/pandas/core/groupby/groupby.py#L1367
