### ISSUE TITLE
New Pandas Assertion Error 

### ISSUE THREAD

**Issue by andrewswimm3395** [pandas-dev/pandas#38474]
I am running into an assertion error when using group_by.min() which was never a problem when I was using the older version of pandas

**Comment by andrewswimm3395** [comment]
df_min_enroll = df.groupby('F101_StudentNumber').min()['Enrollment Date minus Open Date'].reset_index()
Traceback (most recent call last):

  File "<ipython-input-11-000ba374164a>", line 1, in <module>
    df_min_enroll = df.groupby('F101_StudentNumber').min()['Enrollment Date minus Open Date'].reset_index()

  File "C:\Users\aswimm\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 1551, in min
    return self._agg_general(

  File "C:\Users\aswimm\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 999, in _agg_general
    return self._cython_agg_general(

  File "C:\Users\aswimm\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 1021, in _cython_agg_general
    agg_blocks, agg_items = self._cython_agg_blocks(

  File "C:\Users\aswimm\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 1135, in _cython_agg_blocks
    assert len(locs) == result.shape[1]

AssertionError

That is the specific error and this only happens when using min or max

**Comment by mroeschke** [comment]
Could you post a minimal, reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
closing, feel free to ping if you have a reproducible example
