### ISSUE TITLE
ValueError: Only callable can be used as callback

### ISSUE THREAD

**Issue by SaraJ52** [pandas-dev/pandas#38635]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing Dataset
dataset = pd.read_csv("dataset.csv") 

```
When I'm running the last line which imports m dataset it gives me error and I do not know how to resolve that. 
ERROR:

dataset = pd.read_csv("C:/Users/saraj/OneDrive/Desktop/AI/dataset.csv")
Traceback (most recent call last):

  File "<ipython-input-33-9a3340a25db3>", line 1, in <module>
    dataset = pd.read_csv("C:/Users/saraj/OneDrive/Desktop/AI/dataset.csv")

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\io\parsers.py", line 460, in _read
    data = parser.read(nrows)

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\io\parsers.py", line 1213, in read
    df = DataFrame(col_dict, columns=columns, index=index)

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\core\frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\core\internals\construction.py", line 259, in init_dict
    if missing.any() and not is_integer_dtype(dtype):

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\core\generic.py", line 11580, in logical_func
    return self._reduce(

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\pandas\core\series.py", line 4248, in _reduce
    with np.errstate(all="ignore"):

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\numpy\core\_ufunc_config.py", line 436, in __enter__
    self.oldcall = seterrcall(self.call)

  File "C:\Users\saraj\anaconda3\envs\AI project\lib\site-packages\numpy\core\_ufunc_config.py", line 308, in seterrcall
    raise ValueError("Only callable can be used as callback")

ValueError: Only callable can be used as callback

**Comment by SaraJ52** [comment]
I have selected the correct directory of my file .

**Comment by rhshadrach** [comment]
Can you produce the error with a small example file (e.g. 10 records)? If so, it would be helpful to post the data as well.

**Comment by MarcoGorelli** [comment]
closing as we don't have the necessary info to reproduce, feel free to ping if you have a reproducible example

**Comment by ddelange** [comment]
For me, restarting my python session did the trick. After that, my previously failing example started working.

fwiw:
```pycon
>>> import pandas as pd
>>> pd.read_json('https://github.com/pandas-dev/pandas/files/6547754/bad_df.json.gz')
```

**Comment by ShutterZor** [comment]
Restarting your Python, I just met the same question, and it worked.
