### ISSUE TITLE
BUILD: openSUSE: Can't import IncompatibleFrequency in Pandas

### ISSUE THREAD

**Issue by lukaszpiwowarek** [pandas-dev/pandas#39113]
Hi, I am trying to install Pandas for a project for our Devs. After installing Pandas with pip3 and trying to run the project, we get this stack trace:

```Traceback (most recent call last):
  File "src/bin/app.py", line 17, in <module>
    from bin.generator_dispatcher import GeneratorDispatcher
  File "/opt/yana/python/report-engine-dev/src/bin/generator_dispatcher.py", line 13, in <module>
    from athlete_baseline_report.bin.athlete_baseline_report import (
  File "/opt/yana/python/report-engine-dev/src/athlete_baseline_report/bin/athlete_baseline_report.py", line 3, in <module>
    from athlete_baseline_report.data_builder.data_builder import DataBuilder
  File "/opt/yana/python/report-engine-dev/src/athlete_baseline_report/data_builder/data_builder.py", line 12, in <module>
    from shared.algorithm.cc.cc_calculation import CcCalculation
  File "/opt/yana/python/report-engine-dev/src/shared/algorithm/cc/cc_calculation.py", line 9, in <module>
    from shared.algorithm.cc.CalculateCC import calculateCC_list
  File "/opt/yana/python/report-engine-dev/src/shared/algorithm/cc/CalculateCC.py", line 16, in <module>
    import pandas as pd
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 4, in <module>
    from pandas.core.indexes.base import (Index,
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 53, in <module>
    from pandas.core import ops
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 21, in <module>
    from pandas.core.construction import extract_array
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/construction.py", line 15, in <module>
    from pandas._libs.tslibs import IncompatibleFrequency, OutOfBoundsDatetime
ImportError: cannot import name 'IncompatibleFrequency'
```
Does Pandas require something else to be installed? The project uses Pandas 0.23.4. I get the same error if I install latest version.

Pandas was installed with pip3 like this:

`sudo -H pip3 install pandas==0.23.4`

The host is Ubuntu 18.04.5 LTS with all installed packages completely up to date.

**Comment by phofl** [comment]
Please show a reproducible example and show versions

**Comment by lukaszpiwowarek** [comment]
Hi there,

I attempted to use the original deployment method which is Anaconda3. I performed the following steps:

- Install latest Anaconda3 for the user running project
- Created new environment with python3.6 called test36
- Installed required version of Pandas (0.23.4) using Anaconda3 into test36 environment
- Activated test36 environment and launched python3 within it
- Attempted to import pandas, with same result as above

All steps except Anaconda install are in detail are below:

```
(base) hzhang@yana-reportengine-new:~$ conda create -n test36 python=3.6
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/hzhang/anaconda3/envs/test36

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-51.1.2          |   py36h06a4308_4         730 KB
    ------------------------------------------------------------
                                           Total:         730 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.12.8-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py36h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1i-h27cfd23_0
  pip                pkgs/main/linux-64::pip-20.3.3-py36h06a4308_0
  python             pkgs/main/linux-64::python-3.6.12-hcff3b4d_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-51.1.2-py36h06a4308_4
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-51.1.2    | 730 KB    | ################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test36
#
# To deactivate an active environment, use
#
#     $ conda deactivate
(base) hzhang@yana-reportengine-new:~$ conda install -n test36 pandas==0.23.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/hzhang/anaconda3/envs/test36

  added / updated specs:
    - pandas==0.23.4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-dateutil-2.8.1      |             py_0         215 KB
    ------------------------------------------------------------
                                           Total:         215 KB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.2-254
  mkl                pkgs/main/linux-64::mkl-2020.2-256
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he8ac12f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.2.0-py36h23d657b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.1-py36h0573a6f_0
  numpy              pkgs/main/linux-64::numpy-1.19.2-py36h54aff64_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.19.2-py36hfa32c7d_0
  pandas             pkgs/main/linux-64::pandas-0.23.4-py36h04863e7_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pytz               pkgs/main/noarch::pytz-2020.5-pyhd3eb1b0_0
  six                pkgs/main/linux-64::six-1.15.0-py36h06a4308_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-dateutil-2.8. | 215 KB    | ################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) hzhang@yana-reportengine-new:~$ conda activate test36
(test36) hzhang@yana-reportengine-new:~$ python3
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 4, in <module>
    from pandas.core.indexes.base import (Index,
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 53, in <module>
    from pandas.core import ops
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 21, in <module>
    from pandas.core.construction import extract_array
  File "/home/hzhang/.local/lib/python3.6/site-packages/pandas/core/construction.py", line 15, in <module>
    from pandas._libs.tslibs import IncompatibleFrequency, OutOfBoundsDatetime
ImportError: cannot import name 'IncompatibleFrequency'
>>> 
```

**Comment by Ceaus** [comment]
Same here. Default openSUSE Leap 15.2. All Python packages are default from the openSUSE repo.

**Comment by alepapadop** [comment]
Same problem here with openSUSE Lead 15.2 by using pip for installing pandas

**Comment by mroeschke** [comment]
Thanks for the report but this appears to be an issue with an older version of pandas for a python version we no longer support. Additionally we don't actively manage package distribution for opensuse so closing. Can reopen if this is an issue with a newer version of pandas
