### ISSUE TITLE
BUG:import pandas AttributeError: module 'numpy' has no attribute 'ndarray'

### ISSUE THREAD

**Issue by emilianosantin** [pandas-dev/pandas#39251]
---

Hi
I am not sure what caused the problem, but when I try to import pandas I get a numpy attribute error. I am Mac user on Jupyter when I try to import pandas this is the error I get. I previously posted this as a question but I did not provide all the necessary info so I closed the QST#39243 
```

import pandas as pd

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-7dd3504c366f> in <module>
----> 1 import pandas as pd

~/opt/anaconda3/lib/python3.7/site-packages/pandas/__init__.py in <module>
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import (
     23     np_version_under1p17 as _np_version_under1p17,
     24     np_version_under1p18 as _np_version_under1p18,

~/opt/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py in <module>
     12 import warnings
     13 
---> 14 from pandas._typing import F
     15 
     16 PY38 = sys.version_info >= (3, 8)

~/opt/anaconda3/lib/python3.7/site-packages/pandas/_typing.py in <module>
     52 # array-like
     53 
---> 54 AnyArrayLike = TypeVar("AnyArrayLike", "ExtensionArray", "Index", "Series", np.ndarray)
     55 ArrayLike = TypeVar("ArrayLike", "ExtensionArray", np.ndarray)
     56 

AttributeError: module 'numpy' has no attribute 'ndarray'
below are my python and jupyter versions

```
Here are some relevant packages versions:

numpy     :1.19.5
pandas.   : 1.2.0
geopandas :0.63
python :3.7.9
anaconda :client 1.7.2
anaconda :0.0.1.1
setuptools 49.6.0
jupyter core     : 4.7.0
jupyter-notebook : 6.2.0
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.11
jupyter lab      : 3.0.5
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5
(base) __________-MacBook-Air:~ ____________$ 

 I tried pip install although I use anaconda and did not work
```
pip uninstall -y numpy
pip uninstall -y setuptools
pip install setuptools
pip install numpy
```

**Comment by MarcoGorelli** [comment]
do you have a folder called `numpy` in your working directory?

**Comment by emilianosantin** [comment]
Hi thanks for getting back to me. I have several of them with different versions.

 

/Users/_________________/opt/anaconda3/pkgs/numpy-1.19.5-py37hec87de9_1

 

/Users/_________________/opt/anaconda3/pkgs/numpy-1.19.5-py37hec87de9_1/lib/python3.7/site-packages

 

/Users/_________________/opt/anaconda3/pkgs/numpy-base-1.18.5-py37hc72aeb7_0

 

/Users/_________________/opt/anaconda3/pkgs/numpy-1.19.5-py37hec87de9_1/lib/python3.7/site-packages/numpy-1.19.5.dist-info

**Comment by MarcoGorelli** [comment]
What about in your current directory (the one in which you're running Python)

**Comment by MarcoGorelli** [comment]
> I tried pip install although I use anaconda and did not work

What didn't work? Can you show what you did and your output?

**Comment by emilianosantin** [comment]
here is what I get, but pandas does not import

```
pip install setuptools
Collecting setuptools
  Downloading setuptools-51.3.3-py3-none-any.whl (786 kB)
     |████████████████████████████████| 786 kB 848 kB/s 
Installing collected packages: setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray 0.16.0 requires numpy>=1.15, which is not installed.
wradlib 1.7.4 requires numpy, which is not installed.
tensorboard 2.2.2 requires numpy>=1.12.0, which is not installed.
spyder 4.2.1 requires pyqt5<5.13, which is not installed.
spyder 4.2.1 requires pyqtwebengine<5.13, which is not installed.
orange3 3.26.0 requires numpy>=1.16.0, which is not installed.
orange3-text 0.8.0 requires lxml, which is not installed.
orange3-text 0.8.0 requires nltk>=3.0.5, which is not installed.
orange3-text 0.8.0 requires numpy, which is not installed.
orange3-imageanalytics 0.5.0 requires numpy>=1.16.*, which is not installed.
orange3-educational 0.3.0 requires numpy, which is not installed.
metpy 0.12.2 requires numpy>=1.16.0, which is not installed.
lttl 2.0.9 requires numpy, which is not installed.
eo-learn-core 0.8.0 requires numpy>=1.19.0, which is not installed.
cartopy 0.17.0 requires numpy>=1.10, which is not installed.
altair 4.1.0 requires numpy, which is not installed.
orange3-text 0.8.0 requires docutils<0.16, but you have docutils 0.16 which is incompatible.
orange3-text 0.8.0 requires python-dateutil<2.8.1, but you have python-dateutil 2.8.1 which is incompatible.
eo-learn-core 0.8.0 requires geopandas!=0.8.0,>=0.5.0, but you have geopandas 0.8.0+56.g9fdeb14 which is incompatible.
Successfully installed setuptools-51.3.3
```
```
pip install numpy
Collecting numpy
  Downloading numpy-1.19.5-cp37-cp37m-macosx_10_9_x86_64.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 185 kB/s 
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
quantecon 0.4.8 requires numba>=0.38, which is not installed.
quantecon 0.4.8 requires sympy, which is not installed.
orange3-text 0.8.0 requires lxml, which is not installed.
orange3-text 0.8.0 requires nltk>=3.0.5, which is not installed.
u8darts 0.5.0 requires ipython==7.15.0, but you have ipython 7.19.0 which is incompatible.
u8darts 0.5.0 requires matplotlib==3.2.2, but you have matplotlib 3.3.3 which is incompatible.
u8darts 0.5.0 requires numpy==1.19.0, but you have numpy 1.19.5 which is incompatible.
u8darts 0.5.0 requires pandas==1.1.0, but you have pandas 1.2.0 which is incompatible.
u8darts 0.5.0 requires scikit-learn==0.23.2, but you have scikit-learn 0.24.0 which is incompatible.
u8darts 0.5.0 requires scipy==1.5.0, but you have scipy 1.5.3 which is incompatible.
u8darts 0.5.0 requires statsmodels==0.11.1, but you have statsmodels 0.12.1 which is incompatible.
u8darts 0.5.0 requires tqdm==4.46.1, but you have tqdm 4.56.0 which is incompatible.
tensorflow 2.1.0 requires scipy==1.4.1; python_version >= "3", but you have scipy 1.5.3 which is incompatible.
tensorflow 2.1.0 requires tensorboard<2.2.0,>=2.1.0, but you have tensorboard 2.2.2 which is incompatible.
pysal 2.2.0 requires python-dateutil<=2.8.0, but you have python-dateutil 2.8.1 which is incompatible.
pysal 2.2.0 requires urllib3<1.25, but you have urllib3 1.26.2 which is incompatible.
orange3-text 0.8.0 requires docutils<0.16, but you have docutils 0.16 which is incompatible.
orange3-text 0.8.0 requires python-dateutil<2.8.1, but you have python-dateutil 2.8.1 which is incompatible.
eo-learn-core 0.8.0 requires geopandas!=0.8.0,>=0.5.0, but you have geopandas 0.8.0+56.g9fdeb14 which is incompatible.
Successfully installed numpy-1.19.5
```

**Comment by MarcoGorelli** [comment]
Please show the output of `pip install pandas` too

**Comment by emilianosantin** [comment]
thanks it worked!!! Now geopandas does not work but that is no here. I appreciate your help

**Comment by MarcoGorelli** [comment]
no worries!

**Comment by shrikant02** [comment]
> thanks it worked!!! Now geopandas does not work but that is no here. I appreciate your help

I don't understand what's solved the issue ? I am facing similar error

`AttributeError: module 'numpy' has no attribute 'bool_'`

**Comment by MarcoGorelli** [comment]
please show your full output

**Comment by shrikant02** [comment]
> please show your full output

```
 import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 13, in <module>
    __import__(dependency)
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/__init__.py", line 146, in <module>
    from . import add_newdocs
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 72, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/unittest/main.py", line 4, in <module>
    import argparse
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/argparse.py", line 87, in <module>
    import copy as _copy
  File "/home/conoprs/Workspace/computation/copy.py", line 3, in <module>
    from openpyxl import load_workbook
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/openpyxl/__init__.py", line 26, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/openpyxl/compat/strings.py", line 9, in <module>
    from .numbers import NUMERIC_TYPES
  File "/opt/app/control/software/tools/Anaconda3/lib/python3.6/site-packages/openpyxl/compat/numbers.py", line 24, in <module>
    NUMERIC_TYPES = NUMERIC_TYPES + (numpy.bool_, numpy.floating, numpy.integer)
AttributeError: module 'numpy' has no attribute 'bool_'
```

I don't get this error when I run the same command in `/Anaconda3/lib/python3.6/site-packages/numpy/compat` folder

**Comment by MarcoGorelli** [comment]
`/home/conoprs/Workspace/computation/copy.py`

looks like you're importing a local file called `copy`, you'll need to rename it

**Comment by shrikant02** [comment]
Thanks, error gone
