### ISSUE TITLE
DataFrame.from_records fails when the argument is Series with non-default index

### ISSUE THREAD

**Issue by bgbg** [pandas-dev/pandas#40429]
Summary: if `from_records` is called upon a `Series` with index that doesn't start with `0`, it fails.

```python
import pandas as pd
print(f'Pandas version is {pd.__version__}')
data = pd.Series([{'a': 1, 'b': 2}, {'a': 11, 'b': 22}], index=[10, 20])
pd.DataFrame.from_records(data.values) # works
pd.DataFrame.from_records(data)  # fails
```

Output

```text
Pandas version is 1.2.1
Traceback (most recent call last):
  File "/Users/boris/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1625, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1632, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
....
```

**Comment by bgbg** [comment]
Update: it is sufficient that the first element in the `Series` has the index 0. The rest of the indices are ignored:

```
data = pd.Series([{'a': 1, 'b': 2}, {'a': 11, 'b': 22}], index=[0, 20])
pd.DataFrame.from_records(data)
Out[16]: 
    a   b
0   1   2
1  11  22
```

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.from_records.html?highlight=from_records#pandas.DataFrame.from_records

doesn't support Series at all as it's not a structured array

**Comment by bgbg** [comment]
@jreback In this case, shouldn't the constructor raise a `TypeError` or `ValueError` exception on *any* `Series` argument? Potentially with a short explanation?

**Comment by mzeitlin11** [comment]
Raising a more helpful error here would be great, contributions welcome!

**Comment by hasan-yaman** [comment]
take
