### ISSUE TITLE
BUG: pandas uses numexpr if it exists, numexpr is buggy and enters infinite loop on .query('col.isna()'), Anaconda ships with numexpr installed by default, numexpr isn't listed as a requirement of pandas

### ISSUE THREAD

**Issue by gabiteodoru** [pandas-dev/pandas#40848]
- [ ] I have checked that this issue has not already been reported.

- [ X ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by phofl** [comment]
Numexpr is an optional dependency and Listed here: https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#recommended-dependencies

**Comment by gabiteodoru** [comment]
Thanks a lot for the reply! I was just looking at pip show pandas for
dependencies, was not aware they are listed there.

I guess the main point I wanted to raise was -- is it a good idea to use a
non-compulsory dependency library without notifying the user that it's
being used? It makes bugs introduced by optional dependencies really hard
to track, especially when the user hasn't manually installed the
pandas-optional dependency because it was a required dependency of another
library.

But if you guys think it's the best way to go :) Thanks again for all your
work!

**Comment by phofl** [comment]
I am not quite sure what you would expect here? How should we notify users that a dependency is used apart from documenting this?

**Comment by phofl** [comment]
Could you provide something reproducible for the infinite loop?

**Comment by mzeitlin11** [comment]
#34044, #27639 maybe related

**Comment by gabiteodoru** [comment]
OK, so after further investigating the issue, here is reproducing code.
Note that the issue will disappear by pip uninstall numexpr

import sys, pandas as pd, numpy as np
np.set_printoptions(threshold = sys.maxsize)

x = pd.DataFrame({'a':np.array([0,np.nan,None])})
def f(n):
    try:
        x2 = x.sample(n,replace = True)
        x2.query('a.isnull() == False')
    except:
        pass
%time f(100000)
Wall time: 341 ms
%time f(200000)
Wall time: 3.25 s
%time f(300000)
Wall time: 11.1 s

So it's actually not an *infinite* loop, but our table had 3 million rows,
and it scales over-linearly

The suppressed error is:


  File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py",
line 3469, in query
    res = self.eval(expr, **kwargs)

  File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py",
line 3599, in eval
    return _eval(expr, inplace=inplace, **kwargs)

  File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\eval.py",
line 347, in eval
    ret = eng_inst.evaluate()

  File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 73, in evaluate
    res = self._evaluate()

  File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 113, in _evaluate
    _check_ne_builtin_clash(self.expr)

  File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 29, in _check_ne_builtin_clash
    names = expr.names

  File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\expr.py",
line 826, in names
    return frozenset(term.name for term in com.flatten(self.terms))

TypeError: unhashable type: 'numpy.ndarray'


Appears to be related to:

https://stackoverflow.com/questions/51878316/pandas-python-series-objects-are-mutable-thus-they-cannot-be-hashed-in-query-me

Hope this helps! :)

**Comment by gabiteodoru** [comment]
Forgot to add -- error on CTRL+C

Traceback (most recent call last):


File "<ipython-input-15-371eac7162d6>", line 1, in <module>

f(1000000)


File "<ipython-input-9-8dd07e2969e1>", line 3, in f

x2.query('a.isnull() == False')


File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py", line
3469, in query

res = self.eval(expr, **kwargs)


File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py", line
3599, in eval

return _eval(expr, inplace=inplace, **kwargs)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\eval.py",
line 347, in eval

ret = eng_inst.evaluate()


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 73, in evaluate

res = self._evaluate()


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 109, in _evaluate

s = self.convert()


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\engines.py",
line 55, in convert

return printing.pprint_thing(self.expr)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 235, in pprint_thing

result = as_escaped_string(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 211, in as_escaped_string

result = str(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\expr.py",
line 808, in __repr__

return printing.pprint_thing(self.terms)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 235, in pprint_thing

result = as_escaped_string(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 211, in as_escaped_string

result = str(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\ops.py",
line 220, in __repr__

return pprint_thing(f" {self.op} ".join(parened))


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\ops.py",
line 219, in <genexpr>

parened = (f"({pprint_thing(opr)})" for opr in self.operands)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 235, in pprint_thing

result = as_escaped_string(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\io\formats\printing.py",
line 211, in as_escaped_string

result = str(thing)


File
"C:\Users\user\anaconda3\lib\site-packages\pandas\core\computation\ops.py",
line 193, in __repr__

return repr(self.name)


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 1413, in _array_repr_implementation

lst = array2string(arr, max_line_width, precision, suppress_small,


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 692, in array2string

return _array2string(a, options, separator, prefix)


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 468, in wrapper

return f(self, *args, **kwargs)


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 501, in _array2string

lst = _formatArray(a, format_function, options['linewidth'],


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 845, in _formatArray

return recurser(index=(),


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 802, in recurser

s, line = _extendLine_pretty(


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 715, in _extendLine_pretty

return _extendLine(s, line, word, line_width, next_line_prefix, legacy)


File "C:\Users\user\anaconda3\lib\site-packages\numpy\core\arrayprint.py",
line 705, in _extendLine

line += word

**Comment by gabiteodoru** [comment]
As potential solutions: could you make numexpr appear in pip show pandas?
Or if not, what would you think about printing "using numexpr" on import like tensorflow prints stuff when importing.

Just thinking ways of making people's lives easier, as it's a tricky bug

**Comment by rhshadrach** [comment]
> OK, so after further investigating the issue, here is reproducing code.
Note that the issue will disappear by pip uninstall numexpr

> %time f(300000)
> Wall time: 11.1 s

> So it's actually not an *infinite* loop, but our table had 3 million rows,
> and it scales over-linearly

On my machine, running with `10_000_000` takes 0.58s, I'd be curious to understand why it's 11.1s on yours for `300_000`. If you remove the query line, what is the execution time for you then?

I'd agree the error message and the stack isn't so helpful here, is that what you mean when you say "tricky bug"? I don't think we can reliably tell when it's not helpful. If that is true, the intercepting and modifying the message may do more harm than good.

`pip show` is showing requirements, and numexpr is not a requirement, right? Not sure I understand what the suggestion is here.

Related: #32556

**Comment by rhshadrach** [comment]
Also - I don't think the long output is necessarily helpful for this issue, would you mind removing it?

**Comment by gabiteodoru** [comment]
Do you have numexpr installed in the env that takes 0.58s for 10m rows?

**Comment by rhshadrach** [comment]
Yes - 2.7.3

**Comment by gabiteodoru** [comment]
Hmm.... OK, so I create a new conda environment, install numpy and pandas only, and run a .py file containing the code I showed above for 300,000 rows

`(myenv) C:\Users\user>conda list
# packages in environment at C:\Users\user\anaconda3\envs\myenv:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py38haa95532_0
intel-openmp              2020.2                      254
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
openssl                   1.1.1k               h2bbff1b_0
pandas                    1.2.3            py38hf11a4ad_0
pip                       21.0.1           py38haa95532_0
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
setuptools                52.0.0           py38haa95532_0
six                       1.15.0           py38haa95532_0
sqlite                    3.35.4               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0

(myenv) C:\Users\user>python d:\temp\pandabug.py
0.04986834526062012
`

Then I just install numexpr and run it again

`(myenv) C:\Users\user>conda list
# packages in environment at C:\Users\user\anaconda3\envs\myenv:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py38haa95532_0
intel-openmp              2020.2                      254
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
numexpr                   2.7.3            py38hcbcaa1e_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
openssl                   1.1.1k               h2bbff1b_0
pandas                    1.2.3            py38hf11a4ad_0
pip                       21.0.1           py38haa95532_0
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
setuptools                52.0.0           py38haa95532_0
six                       1.15.0           py38haa95532_0
sqlite                    3.35.4               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0

(myenv) C:\Users\user>python d:\temp\pandabug.py
11.516265153884888`

I'm on Windows 10, but I tried doing the same thing on ubuntu, and I get the same result. If you still can't reproduce, well, I guess I can give up :)

**Comment by gabiteodoru** [comment]
> Also - I don't think the long output is necessarily helpful for this issue, would you mind removing it?

Exactly which output? I have two comments with long error messages :)

**Comment by gabiteodoru** [comment]
pandabug.py for completeness

```import sys, pandas as pd, numpy as np, time
np.set_printoptions(threshold = np.inf)
x = pd.DataFrame({'a':np.array([0,np.nan,None])})
def f(n):
    try:
        x2 = x.sample(n,replace = True)
        x2.query('a.isnull() == False')
    except:
        pass
t = time.time()
f(300000)
print(time.time()-t)```

**Comment by rhshadrach** [comment]
Odd, I do not think it should not take that much time for the query to fail. If you're able to profile and find out where this time in query is being spent, it would be helpful, but I understand if that's too much effort. Perhaps someone else can reproduce.

**Comment by jorisvandenbossche** [comment]
For me, the function is actually raising an error (but it's catched in `f(n)`, so you don't directly see it). Is that correct? 
If so, there might be going something wrong with raising the error (it might be trying to print the values in the error message, which can blow up).

**Comment by jorisvandenbossche** [comment]
cc @simonjayhawkins in case you can reproduce this on Windows (in an env with numexpr installed)

**Comment by phofl** [comment]
Can reproduce on win10. machine: 4 cores 40gb ram

Takes 16 seconds to run through.

profile:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   300000    9.662    0.000    9.721    0.000 arrayprint.py:695(_extendLine)
 300001/1    2.074    0.000   11.845   11.845 arrayprint.py:718(recurser)
1500278/1500234    0.070    0.000    0.070    0.000 {built-in method builtins.len}
   300000    0.033    0.000    0.033    0.000 arrayprint.py:1142(__call__)
        1    0.011    0.011    0.011    0.011 {built-in method pandas._libs.missing.isnaobj}
    33334    0.005    0.000    0.005    0.000 {method 'rstrip' of 'str' objects}
        1    0.003    0.003    0.004    0.004 {method 'choice' of 'numpy.random.mtrand.RandomState' objects}
        4    0.003    0.001    0.003    0.001 {method 'copy' of 'numpy.ndarray' objects}
        1    0.002    0.002    0.002    0.002 {method 'take' of 'numpy.ndarray' objects}
        1    0.002    0.002    0.002    0.002 {pandas._libs.algos.take_2d_axis0_object_object}
        7    0.001    0.000    0.001    0.000 {built-in method numpy.empty}
        1    0.001    0.001    0.001    0.001 indexers.py:225(maybe_convert_indices)
       20    0.001    0.000    0.001    0.000 {built-in method numpy.array}
        1    0.001    0.001    0.012    0.012 missing.py:244(_isna_string_dtype)
        3    0.001    0.000   11.847    3.949 ops.py:219(<genexpr>)
        1    0.001    0.001   11.846   11.846 arrayprint.py:1365(_array_repr_implementation)
        1    0.001    0.001   11.882   11.882 <ipython-input-4-7727d8aaa8d6>:4(f)
       16    0.001    0.000   11.847    0.740 {method 'join' of 'str' objects}
        1    0.001    0.001   11.883   11.883 <string>:1(<module>)
        1    0.001    0.001    0.008    0.008 managers.py:1426(take)
```

everything else is more or less not relevant.

<details>

INSTALLED VERSIONS
------------------
commit           : 963cf2b5abf4e1ee99a7f6b9031ad485804c5dff
python           : 3.7.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.0.dev0+4095.g963cf2b5a
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 49.6.0.post20210108
Cython           : 0.29.21
pytest           : 6.2.1
hypothesis       : 6.0.2
sphinx           : 3.4.3
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.5
fastparquet      : 0.5.0
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.1
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.2
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.52.0

</details>

**Comment by rhshadrach** [comment]
Thanks @jorisvandenbossche @phofl. Previously I made the mistake of not including `np.set_printoptions(threshold = np.inf)`; with this included I can reproduce the long runtime.

**Comment by gabiteodoru** [comment]
Yep, it's getting stuck in formatting the error message, it's bouncing
between those top three functions in the profiling. And it looks like the
number of calls scale linearly with the number of rows; and I bet the
object being acted is also proportional in size with the number of rows, so
each function call takes more than constant time. Meaning the whole thing
scales super-linearly. Call it for 3,000,000 rows now, and it should take
forever.

It's not a big deal, but it's just a *really* hard bug to find, and can be
triggered by something as easy as another package installing numexpr

**Comment by rhshadrach** [comment]
It's not formatting the error message, it's formatting the expression; in convert:

```
    def convert(self) -> str:
        """
        Convert an expression for evaluation.

        Defaults to return the expression as a string.
        """
        return printing.pprint_thing(self.expr)
```

When I run with the default NumPy print threshold, the string is

    (array([False, False,  True, ...,  True, False, False])) == (False)

**Comment by gabiteodoru** [comment]
Ah OK, I just assumed that since np.set_printoptions is necessary to make
it slow, it might have to do with what it's printing, and the only thing it
prints in the end is an error; but I guess I was wrong :)

**Comment by rhshadrach** [comment]
For this example, the `a.isnull()` gets parsed as an instance of `pandas.core.computation.ops.Constant`. Is it true that when using numexpr, any instance of Constant must be hashable? We could catch that here, which occurs before any conversion to string.

**Comment by rhshadrach** [comment]
Also, are there hashable python objects that would have long string reps that we can do something about?

**Comment by jbrockmendel** [comment]
closed by #43301
