### ISSUE TITLE
BUG: map nested dict on categorical Series prints a TypeError and ignores it

### ISSUE THREAD

**Issue by adrien-berchet** [pandas-dev/pandas#40892]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
tested = pd.Series(["key_1", "key_2"], dtype="category")
tested.map({"key_1": {"a": 1}, "key_2": {"a": 2}})
```

#### Problem description

The given code raises an exception but actually ignores it and returns the expected result. I think it would be better to ignore it silently. Note that it seems to happen only with categorical Series.

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.map_locations()

TypeError: unhashable type: 'dict'
Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'dict'
Out[10]: 
0    {'a': 1}
1    {'a': 2}
dtype: object
```

#### Expected Output

```python
Out[10]: 
0    {'a': 1}
1    {'a': 2}
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-70-generic
Version          : #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.2.3
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 49.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.7
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
the same also occurs on master.

**Comment by phofl** [comment]
If I execute this in the debugger the code exits

```
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5185, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'dict'

Process finished with exit code 1
```

**Comment by narukaze132** [comment]
Tested the given code on the current stable version and got a TypeError, but nothing returned. If that's the intended behavior, I think this issue can be closed out.
