### ISSUE TITLE
BUG: max()/min() don't work on DataFrames  constructed from scipy sparse matrix

### ISSUE THREAD

**Issue by melkonyan** [pandas-dev/pandas#40921]
Example:
```python
import pandas as pd
from scipy import sparse as sc
import numpy as np

np.random.seed(42)
a = np.random.randint(0, 10, size=(200, 5))
a_sp = sc.coo_matrix(a)
a_sp_pd = pd.DataFrame.sparse.from_spmatrix(a_sp)
a_sp_pd.max()
```
Expected output:
```
0    9
1    9
2    9
3    9
4    9
dtype: int64

```

Actual output:
```
Series([], dtype: float64)
```

System info: 
```
  - numpy [required: >=1.17, installed: 1.20.2]
  - scipy [required: >=0.19.1, installed: 1.6.2]
  - pandas [required: >=1.0.0,<=1.1.4, installed: 1.2.4]
```

**Comment by phofl** [comment]
This raises 
```
Traceback (most recent call last):
  File "/home/developer/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/developer/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/developer/.config/JetBrains/PyCharm2021.1/scratches/scratch_4.py", line 527, in <module>
    a_sp = sc.sparse.coo_matrix(a)
AttributeError: module 'scipy' has no attribute 'sparse'

Process finished with exit code 1
```

for me. Could you check your example?

**Comment by melkonyan** [comment]
My bad, updated

**Comment by phofl** [comment]
This is not implemented. The error is caught in the call stack and an empty result is returned.

**Comment by taytzehao** [comment]
I will be adding a max & min method pandas\core\arrays\sparse\array.py in the sparsearray class

**Comment by taytzehao** [comment]
Take
