### ISSUE TITLE
QST: Unable to solve read_excel and *kwargs error

### ISSUE THREAD

**Issue by rdancy01** [pandas-dev/pandas#41088]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```
Hello all,

I'm new to Pandas and I can't solve these errors I'm getting. Any assistance would be appreciated.

Traceback (most recent call last):
File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 515, in
main()
File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 471, in main
[all_data,suite_list] = openSpreadsheet()
File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 91, in openSpreadsheet
all_data = pd.read_excel(workbook_name, 1 ,usecols=['Name','Test Stand','Status',
File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\util_decorators.py", line 299, in wrapper
return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'

C:\Users\HA_Report_Generation\Report Generator Legacy>python3 report_generator_1_5_3.py
Opening spreadsheet from .\Regression\CVB Logix Firmware-Test Run-20210411.xls...

Traceback (most recent call last):
File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 515, in
main()
File "C:\Users\HA_Report_Generation\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 471, in main
[all_data,suite_list] = openSpreadsheet()
File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 91, in openSpreadsheet
all_data = pd.read_excel(workbook_name, 1 ,usecols=['Name','Test Stand','Status',
File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\util_decorators.py", line 299, in wrapper
return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'

**Comment by phofl** [comment]
Hi, please provide a minimal and reproducible example (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) if you think this is a bug in pandas. If this is simply a usage question please ask them on stackoverflow

**Comment by attack68** [comment]
The answer is described by the error message.
There is no keyword argument called 'index' in read_excel. It is called 'index_col' and accepts an integer or list of such.
See here: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html.
