### ISSUE TITLE
BUG: Getting import error on master "Cannot import IS64"

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#41340]
I might be doing something wrong here, but when executing

```python
import pandas as pd
```

I get an import error after pulling f40e58cc50abcd03efae372df0586467a957f695. The commit before is fine. Can someone reproduce?

```
Traceback (most recent call last):
  File "/home/developer/.config/JetBrains/PyCharm2021.1/scratches/scratch_4.py", line 566, in <module>
    import pandas as pd
  File "/home/developer/PycharmProjects/pandas/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/developer/PycharmProjects/pandas/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/developer/PycharmProjects/pandas/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/developer/PycharmProjects/pandas/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/developer/PycharmProjects/pandas/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/developer/PycharmProjects/pandas/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 30, in init pandas._libs.missing
ImportError: cannot import name IS64

Process finished with exit code 1
```

The show versions is from the last working commit

cc @fangchenli 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : a43c42c32d4f161679974e403b11784c824714bc
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-50-generic
Version          : #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0.dev0+1544.ga43c42c32d
numpy            : 1.20.0
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 49.6.0.post20210108
Cython           : 0.29.21
pytest           : 6.2.1
hypothesis       : 6.0.2
sphinx           : 3.4.3
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.5
fastparquet      : 0.5.0
gcsfs            : 0.7.1
matplotlib       : 3.3.3
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 1.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.52.0
None

</details>

**Comment by jbrockmendel** [comment]
have you rebuilt recently?

**Comment by phofl** [comment]
Yes, did not fix it.

But just setup my complete conda env from scratch , this fixed the error

**Comment by abmyii** [comment]
For me the solution (after ensuring my environment was setup correctly) was to run:
```
make clean   # Optional
make build
```
