### ISSUE TITLE
QST: build offline?

### ISSUE THREAD

**Issue by themaddoctor** [pandas-dev/pandas#41383]
- [x ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ n/a] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

[40/40] Cythonizing pandas/io/sas/sas.pyx
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/setuptools/ssl_support.py", line 174, in connect
    (self.host, self.port), getattr(self, 'source_address', None)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 764, in open_url
    return open_with_auth(url, self.opener)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 951, in _socket_timeout
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 1070, in open_with_auth
    fp = opener(request)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/site-packages/setuptools/ssl_support.py", line 161, in https_open
    lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 761, in <module>
    setup_package()
  File "setup.py", line 754, in setup_package
    **setuptools_kwargs,
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
    not self.always_copy, self.local_index
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 653, in fetch_distribution
    dist = find(requirement)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 633, in find
    loc = self.download(dist.location, tmpdir)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 577, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 822, in _download_url
    return self._attempt_download(url, filename)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 828, in _attempt_download
    headers = self._download_to(url, filename)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 727, in _download_to
    fp = self.open_url(url)
  File "/usr/lib/python3.7/site-packages/setuptools/package_index.py", line 778, in open_url
    % (url, v.reason))
distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/a9/03/5b216f6a55ffc6bdac3ad3a896c58d4f17d99e18ff82fc68363df7d6a7b3/numpy-1.20.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=9cab23439eb1ebfed1aaec9cd42b7dc50fc96d5cd3147da348d9161f0501ada5: [Errno -2] Name or service not known

```
I am building on a machine that CANNOT access the internet. I already have numpy etc., yet setup.py will not
allow me to build pandas.

Q: how to build offline?

**Comment by jorisvandenbossche** [comment]
It seems it is trying to download numpy, which is a required dependency for pandas. If you are building offline, you will need to ensure numpy is already installed or downloaded in advance. 

Can you indicate how you are building pandas? (which command did you use?) Using pip? (see eg https://stackoverflow.com/a/14447068/653364 for ensuring pip can use downloaded requirements)
