### ISSUE TITLE
QST: Subclassed lists are not allowed as indexers of dfs in v1.3.0

### ISSUE THREAD

**Issue by pwwang** [pandas-dev/pandas#42431]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
>>> from pandas import DataFrame
>>> df = DataFrame(dict(x=[1,2,3]))
>>> class MyList(list): 
...     ...
...
>>> 
>>> 
>>> key = MyList(['x'])
>>> key
['x']
>>> 
>>> df[key]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    df[key]
  File "/.../python3.7/site-packages/pandas/core/frame.py", line 3445, in __getitem__
    if com.is_bool_indexer(key):
  File "/...python3.7/site-packages/pandas/core/common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got MyList)
```
This works in `v1.2.*`.

It is mentioned in the docstring of `is_bool_indexer` that 

> with ``_is_boolean`` set are considered boolean indexers.

But I had no luck with that property being set with `MyList`.

Not sure if this is an intended change or not. I did find any documentation for this.

**Comment by pwwang** [comment]
Now I think this is a bug.

#42433
