### ISSUE TITLE
BUG: AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py'>

### ISSUE THREAD

**Issue by 874061490** [pandas-dev/pandas#43543]
### 

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py'>

### Question about pandas

Traceback (most recent call last):
[27]   File "/ganling_ms/yiaijun/ConWea-master/train.py", line 325, in <module>
[28]     main(dataset_path=args.dataset_path)
[29]   File "/ganling_ms/yiaijun/ConWea-master/train.py", line 291, in main
[30]     df = pickle.load(open(dataset_path+ 'df_contextualized.pkl', "rb"))
[31] AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py'>

**Comment by mroeschke** [comment]
Thanks for the issue. It appears you have filled out the incorrect template. We suggest following the `Bug Report` template so the team has an better change diagnosing the issue. Closing but we anticipate your issue with that template.
