### ISSUE TITLE
BUG: Modifying values of a dataframe using lower level MultiIndex columns causes silently casting them to float64

### ISSUE THREAD

**Issue by ozars** [pandas-dev/pandas#43719]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

DTYPE = np.float32
#  DTYPE = np.int32

def rand():
    return (np.random.rand(5) * 10).astype(DTYPE)

def assert_dtype(d):
    assert (d.dtypes == DTYPE).all(), f"\n{d.dtypes}"


df1 = pd.DataFrame({"x": rand(), "y": rand()})
assert_dtype(df1)

df1.loc[:, ["x", "y"]] = 2 * df1.loc[:, ["x", "y"]] - 1
assert_dtype(df1)


df2 = pd.DataFrame({("a", "x"): rand()})
assert_dtype(df2)

df2.loc[:, ("a", "x")] = 2 * df2.loc[:, ("a", "x")] - 1
assert_dtype(df2)

assert_dtype(df2.loc[:, "a"])
assert_dtype(2 * df2.loc[:, "a"] - 1)
df2.loc[:, "a"] = 2 * df2.loc[:, "a"] - 1
assert_dtype(df2) # FAILS


Output:
```Traceback (most recent call last):
  File "/home/omer/tmp/pd_err.py", line 30, in <module>
    assert_dtype(df2) # FAILS
  File "/home/omer/tmp/pd_err.py", line 11, in assert_dtype
    assert (d.dtypes == DTYPE).all(), f"\n{d.dtypes}"
AssertionError:
a  x    float64
dtype: object
```
```


### Issue Description

When lower level MultiIndex columns are used for modifying a dataframe, they are cast to float64 even when destination and source have same types.

### Expected Behavior

dtype(s) of such assignments aren't cast if not needed.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-8-amd64
Version          : #1 SMP Debian 5.10.46-4 (2021-08-03)
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 20.3.4
setuptools       : 44.1.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by ozars** [comment]
Using empty slices works as expected as a workaround:

```py
df2.loc[:, ("a", slice(None))] = 2 * df2.loc[:, ("a", slice(None))] - 1
assert_dtype(df2) # OK
```
