### ISSUE TITLE
BUILD: upgrade asv to cython 0.29.24

### ISSUE THREAD

**Issue by alexhlim** [pandas-dev/pandas#44069]
### 

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-10.16-x86_64-i386-64bit

### Installation Method

conda install

### pandas Version

1.3.3 (upstream/master)

### Python Version

3.8.12

### Installation Logs

<details>

asv continuous -f 1.1 upstream/master HEAD
· Creating environments.......
· Discovering benchmarks.
·· Uninstalling from conda-py3.8-Cython0.29.21-jinja2-matplotlib-numba-numexpr-numpy-odfpy-openpyxl-pyarrow-pytables-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt..
·· Building 3eeef2ab <asv-upgrade-cython> for conda-py3.8-Cython0.29.21-jinja2-matplotlib-numba-numexpr-numpy-odfpy-openpyxl-pyarrow-pytables-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.
·· Error running /Users/xanderhlim/Documents/dev/pandas-alexhlim/asv_bench/env/46dec818773cf9720d7354158b888d0d/bin/python setup.py build -j4 (exit status 1)
   STDOUT -------->
   
   STDERR -------->
   Traceback (most recent call last):
     File "setup.py", line 650, in <module>
       ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
     File "setup.py", line 410, in maybe_cythonize
       raise RuntimeError(
   RuntimeError: Cannot cythonize with old Cython version (0.29.21 installed, needs 0.29.24)

·· Failed to build the project and import the benchmark suite.

</details>

**Comment by alexhlim** [comment]
duplicate of #44067
