### ISSUE TITLE
BUG: Exception while loading XML with XPath

### ISSUE THREAD

**Issue by olvinroght** [pandas-dev/pandas#44403]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

xml = '''<RootNode>
  <Child1>Text1</Child1>
  <Child2>Text2</Child2>
  <Node1 name="Child3" value="Text3" />
  <Node2 customname="Child4" some-attr="blah blah" value="Text4" />
</RootNode>'''
xpath = ".//Child1/text() | .//Child2/text() | " \
        ".//Node1[@name='Child3']/@value | " \
        ".//Node2[@customname='Child4']/@value"

df = pd.read_xml(xml, xpath=xpath)
```

### Issue Description

Last line `pd.read_xml()` throws next exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 927, in read_xml
    return _parse(
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 728, in _parse
    data_dicts = p.parse_data()
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 400, in parse_data
    return self._parse_nodes()
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 455, in _parse_nodes
    dicts = [
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 457, in <listcomp>
    **el.attrib,
AttributeError: 'lxml.etree._ElementUnicodeResult' object has no attribute 'attrib'
```
Same XPath expression works in `lxml` which is used as default xml parser. For some reasons `pandas` fails to get attribute value `/@value`, if I remove this from expression it doesn't throw any exceptions.

With simpler XPath (`.//Node1[@name='Child3']/@value`) it throws another exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 927, in read_xml
    return _parse(
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 728, in _parse
    data_dicts = p.parse_data()
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 397, in parse_data
    self._validate_path()
  File "C:\Users\[USER]\AppData\Roaming\Python\Python39\site-packages\pandas\io\xml.py", line 505, in _validate_path
    raise ValueError(msg)
ValueError: xpath does not return any nodes. Be sure row level nodes are in xpath. If document uses namespaces denoted with xmlns, be sure to define namespaces and use them in xpath.
```
### Expected Behavior

```python
from lxml import etree

xml = '''<RootNode>
  <Child1>Text1</Child1>
  <Child2>Text2</Child2>
  <Node1 name="Child3" value="Text3" />
  <Node2 customname="Child4" some-attr="blah blah" value="Text4" />
</RootNode>'''
xpath = ".//Child1/text() | .//Child2/text() | " \
        ".//Node1[@name='Child3']/@value | " \
        ".//Node2[@customname='Child4']/@value"

root = etree.fromstring(xml)
result = root.xpath(xpath)
# returns ['Text1', 'Text2', 'Text3', 'Text4']
```

### Installed Versions

```
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : 
pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

**Comment by ParfaitG** [comment]
What is your desired result? From your `lxml` output you receive a list of text values, `['Text1', 'Text2', 'Text3', 'Text4']`, but no corresponding node or attribute names. Is this intended to be a data frame of one column and four rows? Or four columns and one row?

Two important things to note about `read_xml`:

1. **Node Collection**: `read_xml` is designed to build a data frame from a _collection_ of _repeated_ XML nodes and not single node text or single attribute value (or concatenation of individual values as you attempt). This is also why this IO method is best used on flatter XML files and not heavily nested ones. Fundamentally, `read_xml` parses elements themselves, nodes (which become columns) and text/attribute values (which become rows) together, and not only text/attribute values.

2. **Immediate Descendants**: As I mentioned on a recent StackOverflow [response](https://stackoverflow.com/a/69859621/1422451), `read_xml` parses all the _immediate_ descendants of a set of nodes including its child nodes and attributes. So always think of the parent level to parse in xpath expressions where its children and attributes are migrated to a data frame. The parent does not show up in final data frame. Likewise, grandchildren will not appear in final data frame.

For your specific two attempts, consider simply running from root or node:

```python
xpath = "/RootNode"
        
child_df = pd.read_xml(xml, xpath=xpath)
child_df
  Child1 Child2  Node1  Node2
0  Text1  Text2    NaN    NaN


xpath = "//Node1[@name='Child3']"

node1_df = pd.read_xml(xml, xpath=xpath)
node1_df
     name  value
0  Child3  Text3
```

If you need all three levels together, consider calling `read_xml` three times for each level and then concatenate with a horizontal merge and even add prefixes for distinct column names:

```python
df = pd.concat(
    [
        pd.read_xml(xml, xpath="/RootNode"),
        pd.read_xml(xml, xpath="//Node1[@name='Child3']").add_prefix("Node1_"),
        pd.read_xml(xml, xpath="//Node2[@customname='Child4']").add_prefix("Node2_")
    ],
    axis = "columns"
)

df
  Child1 Child2  Node1  Node2 Node1_name Node1_value Node2_customname Node2_some_attr Node2_value
0  Text1  Text2    NaN    NaN     Child3       Text3           Child4       blah blah       Text4
```

Alternatively, you can run XSLT to modify your XML to build the collection of nodes you require and then instead of `xpath` you can use the `stylesheet` argument and call `read_xml` once. Notice insertion of `<row>` to show one row to be parsed.

```python
xslt = '''\
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output indent="yes"/>
  <xsl:strip-space elements="*"/>
  
  <xsl:template match="/RootNode">
    <xsl:copy>
      <row>
        <xsl:copy-of select="Child1|Child2"/>
        <Child3><xsl:value-of select="Node1[@name='Child3']/@value"/></Child3>
        <Child4><xsl:value-of select="Node2[@customname='Child4']/@value"/></Child4>
      </row>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>'''

df = pd.read_xml(xml, stylesheet=xslt)

df
  Child1 Child2 Child3 Child4
0  Text1  Text2  Text3  Text4
```

**Comment by ParfaitG** [comment]
Unless you have further information on desired data frame result, I am closing for now.
