### ISSUE TITLE
QST: resampling with origin='end_day' raises ValueError: Values falls before first bin

### ISSUE THREAD

**Issue by mkp-gebensleben** [pandas-dev/pandas#44957]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

idx = pd.date_range(
    start='2021-04-22 01:00:00+00:00',
    end='2021-04-28 01:00:00+00:00',
    freq='1d'
)

df = pd.DataFrame(index=idx, data=range(len(idx)))

result = df.resample(rule='7d', origin='end_day').min()
```

### Issue Description

Using `origin='end_day'` when resampling raises a ValueError. I don't understand the error message.

Traceback

```
Traceback (most recent call last):
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-b959ed20b9fd>", line 11, in <module>
    result = df.resample(rule='7d', origin='end_day').min()
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\frame.py", line 10350, in resample
    return super().resample(
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\generic.py", line 8126, in resample
    return get_resampler(
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 1382, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 1552, in _get_resampler
    return DatetimeIndexResampler(obj, groupby=self, kind=kind, axis=self.axis)
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 158, in __init__
    self.binner, self.grouper = self._get_binner()
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 241, in _get_binner
    binner, bins, binlabels = self._get_binner_for_time()
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 1113, in _get_binner_for_time
    return self.groupby._get_time_bins(self.ax)
  File "C:\Users\User.Name\.virtualenvs\MyEnv-SwK0JD0-\lib\site-packages\pandas\core\resample.py", line 1609, in _get_time_bins
    bins = lib.generate_bins_dt64(
  File "pandas\_libs\lib.pyx", line 809, in pandas._libs.lib.generate_bins_dt64
ValueError: Values falls before first bin
```

### Expected Behavior

The resample docs say

> ‘end_day’: origin is the ceiling midnight of the last day

so I expected `origin='end_day'` to behave like `origin=df.index.max().ceil('1d')`.
However, only the first approach raises an error.
```
>>> df.resample(rule='7d', origin=df.index.max().ceil('1d')).min() 
                           0
2021-04-22 00:00:00+00:00  0
```

### Installed Versions

<details>
INSTALLED VERSIONS<br>
------------------<br>
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d<br>
python           : 3.8.7.final.0<br>
python-bits      : 64<br>
OS               : Windows<br>
OS-release       : 10<br>
Version          : 10.0.19041<br>
machine          : AMD64<br>
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD<br>
byteorder        : little<br>
LC_ALL           : None<br>
LANG             : None<br>
LOCALE           : de_DE.cp1252<br>
pandas           : 1.3.5<br>
numpy            : 1.21.4<br>
pytz             : 2021.3<br>
dateutil         : 2.8.2<br>
pip              : 21.0.1<br>
setuptools       : 53.0.0<br>
Cython           : None<br>
pytest           : 6.2.3<br>
hypothesis       : None<br>
sphinx           : None<br>
blosc            : None<br>
feather          : None<br>
xlsxwriter       : None<br>
lxml.etree       : None<br>
html5lib         : None<br>
pymysql          : None<br>
psycopg2         : 2.9.2 (dt dec pq3 ext lo64)<br>
jinja2           : 3.0.3<br>
IPython          : 7.30.1<br>
pandas_datareader: None<br>
bs4              : None<br>
bottleneck       : None<br>
fsspec           : None<br>
fastparquet      : None<br>
gcsfs            : None<br>
matplotlib       : 3.4.1<br>
numexpr          : None<br>
odfpy            : None<br>
openpyxl         : None<br>
pandas_gbq       : None<br>
pyarrow          : None<br>
pyxlsb           : None<br>
s3fs             : None<br>
scipy            : 1.7.3<br>
sqlalchemy       : 1.4.28<br>
tables           : None<br>
tabulate         : 0.8.9<br>
xarray           : None<br>
xlrd             : 2.0.1<br>
xlwt             : None<br>
numba            : None<br>

</details>

**Comment by mkp-gebensleben** [comment]
The actual equivalent of

    df.resample(rule='7d', origin='end_day').min()

is

    df.resample(rule='7d', origin=df.index.max().ceil('1d'), closed='right', label='right').min()

for which the same `ValueError` is raised.

So there are two issues

1. The docs should mention that `'end'` and `'end_day'` override `closed` and `label` (if they are None).
2. I still don't get the ValueError. Why does `resample` not add bins as needed until all timestamps of the index fall into a bin?

**Comment by mkp-gebensleben** [comment]
Related stackoverflow questions

https://stackoverflow.com/questions/70436226/resampling-raises-valueerror-values-falls-before-first-bin

https://stackoverflow.com/questions/70436514/timestamp-binning-mechanics-when-resampling

**Comment by vasil-pashov** [comment]
Another edge case for this. When the value matches the bin but is not inside it because is on the opened interval there no groups in the resampler.
```python
df = pd.DataFrame({"col_0": [0]}, index=pd.DatetimeIndex([pd.Timestamp("1969-06-01 00:01:00")]))
len(df.resample("1h", closed="right", label="left", offset="1min", origin="end_day")) # This is 0
df.resample("1h", closed="right", label="left", offset="1min", origin="end_day").agg(None, col_0_sum=('col_0', 'sum'))
```
Throws:

```
ValueError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 df.resample("1h", closed="right", label="left", offset="1min", origin="end_day").agg(None, col_0_sum=('col_0', 'sum'))

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/resample.py:355, in Resampler.aggregate(self, func, *args, **kwargs)
    353 if result is None:
    354     how = func
--> 355     result = self._groupby_and_aggregate(how, *args, **kwargs)
    357 return result

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/resample.py:453, in Resampler._groupby_and_aggregate(self, how, *args, **kwargs)
    451         result = grouped.aggregate(func)
    452     else:
--> 453         result = grouped.aggregate(how, *args, **kwargs)
    454 except (AttributeError, KeyError):
    455     # we have a non-reducing function; try to evaluate
    456     # alternatively we want to evaluate only a column of the input
   (...)    460     #  on Series, raising AttributeError or KeyError
    461     #  (depending on whether the column lookup uses getattr/__getitem__)
    462     result = _apply(
    463         grouped, how, *args, include_groups=self.include_groups, **kwargs
    464     )

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/generic.py:1432, in DataFrameGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
   1429     kwargs["engine_kwargs"] = engine_kwargs
   1431 op = GroupByApply(self, func, args=args, kwargs=kwargs)
-> 1432 result = op.agg()
   1433 if not is_dict_like(func) and result is not None:
   1434     # GH #52849
   1435     if not self.as_index and is_list_like(func):

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/apply.py:190, in Apply.agg(self)
    187     return self.apply_str()
    189 if is_dict_like(func):
--> 190     return self.agg_dict_like()
    191 elif is_list_like(func):
    192     # we require a list, but not a 'str'
    193     return self.agg_list_like()

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/apply.py:423, in Apply.agg_dict_like(self)
    415 def agg_dict_like(self) -> DataFrame | Series:
    416     """
    417     Compute aggregation in the case of a dict-like argument.
    418 
   (...)    421     Result of aggregation.
    422     """
--> 423     return self.agg_or_apply_dict_like(op_name="agg")

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/apply.py:1603, in GroupByApply.agg_or_apply_dict_like(self, op_name)
   1598     kwargs.update({"engine": engine, "engine_kwargs": engine_kwargs})
   1600 with com.temp_setattr(
   1601     obj, "as_index", True, condition=hasattr(obj, "as_index")
   1602 ):
-> 1603     result_index, result_data = self.compute_dict_like(
   1604         op_name, selected_obj, selection, kwargs
   1605     )
   1606 result = self.wrap_results_dict_like(selected_obj, result_index, result_data)
   1607 return result

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/apply.py:496, in Apply.compute_dict_like(self, op_name, selected_obj, selection, kwargs)
    493         results += key_data
    494 else:
    495     # key used for column selection and output
--> 496     results = [
    497         getattr(obj._gotitem(key, ndim=1), op_name)(how, **kwargs)
    498         for key, how in func.items()
    499     ]
    500     keys = list(func.keys())
    502 return keys, results

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/apply.py:497, in <listcomp>(.0)
    493         results += key_data
    494 else:
    495     # key used for column selection and output
    496     results = [
--> 497         getattr(obj._gotitem(key, ndim=1), op_name)(how, **kwargs)
    498         for key, how in func.items()
    499     ]
    500     keys = list(func.keys())
    502 return keys, results

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/generic.py:257, in SeriesGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
    255 kwargs["engine"] = engine
    256 kwargs["engine_kwargs"] = engine_kwargs
--> 257 ret = self._aggregate_multiple_funcs(func, *args, **kwargs)
    258 if relabeling:
    259     # columns is not narrowed by mypy from relabeling flag
    260     assert columns is not None  # for mypy

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/generic.py:362, in SeriesGroupBy._aggregate_multiple_funcs(self, arg, *args, **kwargs)
    360     for idx, (name, func) in enumerate(arg):
    361         key = base.OutputKey(label=name, position=idx)
--> 362         results[key] = self.aggregate(func, *args, **kwargs)
    364 if any(isinstance(x, DataFrame) for x in results.values()):
    365     from pandas import concat

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/generic.py:249, in SeriesGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
    247     if engine_kwargs is not None:
    248         kwargs["engine_kwargs"] = engine_kwargs
--> 249     return getattr(self, func)(*args, **kwargs)
    251 elif isinstance(func, abc.Iterable):
    252     # Catch instances of lists / tuples
    253     # but not the class list / tuple itself.
    254     func = maybe_mangle_lambdas(func)

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:3152, in GroupBy.sum(self, numeric_only, min_count, engine, engine_kwargs)
   3147 else:
   3148     # If we are grouping on categoricals we want unobserved categories to
   3149     # return zero, rather than the default of NaN which the reindexing in
   3150     # _agg_general() returns. GH #31422
   3151     with com.temp_setattr(self, "observed", True):
-> 3152         result = self._agg_general(
   3153             numeric_only=numeric_only,
   3154             min_count=min_count,
   3155             alias="sum",
   3156             npfunc=np.sum,
   3157         )
   3159     return self._reindex_output(result, fill_value=0)

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1907, in GroupBy._agg_general(self, numeric_only, min_count, alias, npfunc, **kwargs)
   1897 @final
   1898 def _agg_general(
   1899     self,
   (...)   1905     **kwargs,
   1906 ):
-> 1907     result = self._cython_agg_general(
   1908         how=alias,
   1909         alt=npfunc,
   1910         numeric_only=numeric_only,
   1911         min_count=min_count,
   1912         **kwargs,
   1913     )
   1914     return result.__finalize__(self.obj, method="groupby")

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:2004, in GroupBy._cython_agg_general(self, how, alt, numeric_only, min_count, **kwargs)
   2001     result = self._agg_py_fallback(how, values, ndim=data.ndim, alt=alt)
   2002     return result
-> 2004 new_mgr = data.grouped_reduce(array_func)
   2005 res = self._wrap_agged_manager(new_mgr)
   2006 if how in ["idxmin", "idxmax"]:

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/internals/base.py:367, in SingleDataManager.grouped_reduce(self, func)
    365 def grouped_reduce(self, func):
    366     arr = self.array
--> 367     res = func(arr)
    368     index = default_index(len(res))
    370     mgr = type(self).from_array(res, index)

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1979, in GroupBy._cython_agg_general.<locals>.array_func(values)
   1977 def array_func(values: ArrayLike) -> ArrayLike:
   1978     try:
-> 1979         result = self._grouper._cython_operation(
   1980             "aggregate",
   1981             values,
   1982             how,
   1983             axis=data.ndim - 1,
   1984             min_count=min_count,
   1985             **kwargs,
   1986         )
   1987     except NotImplementedError:
   1988         # generally if we have numeric_only=False
   1989         # and non-applicable functions
   1990         # try to python agg
   1991         # TODO: shouldn't min_count matter?
   1992         # TODO: avoid special casing SparseArray here
   1993         if how in ["any", "all"] and isinstance(values, SparseArray):

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/ops.py:831, in BaseGrouper._cython_operation(self, kind, values, how, axis, min_count, **kwargs)
    829 ids, _, _ = self.group_info
    830 ngroups = self.ngroups
--> 831 return cy_op.cython_operation(
    832     values=values,
    833     axis=axis,
    834     min_count=min_count,
    835     comp_ids=ids,
    836     ngroups=ngroups,
    837     **kwargs,
    838 )

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/ops.py:550, in WrappedCythonOp.cython_operation(self, values, axis, min_count, comp_ids, ngroups, **kwargs)
    539 if not isinstance(values, np.ndarray):
    540     # i.e. ExtensionArray
    541     return values._groupby_op(
    542         how=self.how,
    543         has_dropped_na=self.has_dropped_na,
   (...)    547         **kwargs,
    548     )
--> 550 return self._cython_op_ndim_compat(
    551     values,
    552     min_count=min_count,
    553     ngroups=ngroups,
    554     comp_ids=comp_ids,
    555     mask=None,
    556     **kwargs,
    557 )

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/ops.py:329, in WrappedCythonOp._cython_op_ndim_compat(self, values, min_count, ngroups, comp_ids, mask, result_mask, **kwargs)
    327 if result_mask is not None:
    328     result_mask = result_mask[None, :]
--> 329 res = self._call_cython_op(
    330     values2d,
    331     min_count=min_count,
    332     ngroups=ngroups,
    333     comp_ids=comp_ids,
    334     mask=mask,
    335     result_mask=result_mask,
    336     **kwargs,
    337 )
    338 if res.shape[0] == 1:
    339     return res[0]

File ~/venvs/311/lib/python3.11/site-packages/pandas/core/groupby/ops.py:418, in WrappedCythonOp._call_cython_op(self, values, min_count, ngroups, comp_ids, mask, result_mask, **kwargs)
    407 counts = np.zeros(ngroups, dtype=np.int64)
    408 if self.how in [
    409     "idxmin",
    410     "idxmax",
   (...)    416     "sum",
    417 ]:
--> 418     func(
    419         out=result,
    420         counts=counts,
    421         values=values,
    422         labels=comp_ids,
    423         min_count=min_count,
    424         mask=mask,
    425         result_mask=result_mask,
    426         is_datetimelike=is_datetimelike,
    427         **kwargs,
    428     )
    429 elif self.how in ["sem", "std", "var", "ohlc", "prod", "median"]:
    430     if self.how in ["std", "sem"]:

File pandas/_libs/groupby.pyx:689, in pandas._libs.groupby.group_sum()

ValueError: len(index) != len(labels)
```
