### ISSUE TITLE
BUG: Unexpected behavioral change, NaN support dropped with `dispatch_ufunc_with_out`

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [pandas-dev/pandas#45249]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
from pandas.core import arraylike
import numpy as np

bool_array = pd.array([True, False, None], dtype="boolean")
# BooleanArray>
# [True, False, <NA>]
# Length: 3, dtype: boolean

ufunc = np.logical_and
method = '__call__'
inputs = (bool_array, np.asarray([True] * len(bool_array)))
kwargs = {"out": np.asarray([True] * len(bool_array))}

# The `__array_ufunc__` calls the `dispatch` function below which fails
#bool_array.__array_ufunc__(ufunc, method, *inputs, **kwargs)

arraylike.dispatch_ufunc_with_out(bool_array, ufunc, method, *inputs, **kwargs)
# ValueError: cannot convert to 'bool'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.
```
```


### Issue Description

Prior to commit b2d54d9c16990bd8eaeacd4de24fc33cfdbfb43b, applying a `ufunc` in pandas such as `np.logical_and` treated NA values as False. The commit b2d54d9c16990bd8eaeacd4de24fc33cfdbfb43b introduced a helper function`dispatch_ufunc_with_out` which refactored some code, but crucially removed code which performed that NA type inference. Now, applying a `ufunc` on NA values fails.

### Expected Behavior

```
import pandas as pd
from pandas.core import arraylike
import numpy as np

bool_array = pd.array([True, False, None], dtype="boolean")
# BooleanArray>
# [True, False, <NA>]
# Length: 3, dtype: boolean

ufunc = np.logical_and
method = '__call__'
inputs = (bool_array, np.asarray([True] * len(bool_array)))
kwargs = {"out": np.asarray([True] * len(bool_array))}

bool_array.__array_ufunc__(ufunc, method, *inputs, **kwargs)
# Passes
```

### Installed Versions

<details>

There is some sort of error when running `pd.show_versions()`. This bug exists as a result of commit b2d54d9c16990bd8eaeacd4de24fc33cfdbfb43b. It does not fail before that commit.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/damianbarabonkov/Documents/QuantCo/pandas/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/Users/damianbarabonkov/Documents/QuantCo/pandas/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/Users/damianbarabonkov/Documents/QuantCo/pandas/pandas/compat/_optional.py", line 116, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/miniconda3/envs/nightly/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/miniconda3/envs/nightly/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/opt/miniconda3/envs/nightly/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/opt/miniconda3/envs/nightly/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 73, in do_override
    ensure_local_distutils()
  File "/opt/miniconda3/envs/nightly/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 61, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /opt/miniconda3/envs/nightly/lib/python3.10/distutils/core.py

</details>

**Comment by jbrockmendel** [comment]
This behavior is correct.  The old behavior was ignoring the `out` kwarg.

**Comment by mroeschke** [comment]
Closing as this is appears to a bug fix from a prior version
