### ISSUE TITLE
BUG: ReadTheDocs is unable to install pandas 1.4.0

### ISSUE THREAD

**Issue by Davide-sd** [pandas-dev/pandas#45657]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
Installed /home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/pyviz_comms-2.1.0-py3.7.egg
Searching for pandas>=0.20.0
Reading https://pypi.org/simple/pandas/
Downloading https://files.pythonhosted.org/packages/4d/aa/e7078569d20f45e8cf6512a24bf2945698f13a7975650773c01366ea96dc/pandas-1.4.0.tar.gz#sha256=cdd76254c7f0a1583bd4e4781fb450d0ebf392e10d3f12e92c95575942e37df5
Best match: pandas 1.4.0
Processing pandas-1.4.0.tar.gz
Writing /tmp/easy_install-2cnujap1/pandas-1.4.0/setup.cfg
Running pandas-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2cnujap1/pandas-1.4.0/egg-dist-tmp-4b9oe7ft
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-2cnujap1/pandas-1.4.0/setup.py", line 651, in <module>
  File "/tmp/easy_install-2cnujap1/pandas-1.4.0/setup.py", line 415, in maybe_cythonize
RuntimeError: Cannot cythonize without Cython installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup.py", line 57, in <module>
    "adaptive==0.13.1"
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
    replace_conflicting=replace_conflicting
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-2cnujap1/pandas-1.4.0/setup.py", line 651, in <module>
  File "/tmp/easy_install-2cnujap1/pandas-1.4.0/setup.py", line 415, in maybe_cythonize
RuntimeError: Cannot cythonize without Cython installed.
```

### Issue Description

I'm not sure if this is a bug...

I'm building a module which requires [adaptive](https://github.com/python-adaptive/adaptive/). adaptive requires pandas. Everything works fine locally, but once I push the commits, ReadTheDocs fails to build the documentation. I have posted the traceback above. So far, I have "solved" my issue by adding a previous version of Pandas to my dependencies.

### Expected Behavior

ReadTheDocs should be able to install pandas 1.4.0.

### Installed Versions

<details>

1.4.0

</details>

**Comment by jreback** [comment]
3.7 support has been dropped
