### ISSUE TITLE
BUG: Float Nullable dtypes not being returned when `use_nullable_dtypes=True` in `pd.read_parquet`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#45694]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> df = pd.DataFrame({'a':[1, 2, 3], 'b':[1.0, 2.0, 3]})
>>> df['c'] = pd.Series([1, 2, 3], dtype='uint8')
>>> df.to_parquet('a')
>>> pd.read_parquet('a').dtypes
a      int64
b    float64
c      uint8
dtype: object
>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    float64
c      UInt8
dtype: object
>>> pd.__version__
'1.4.0'
```

### Issue Description

When `use_nullable_dtypes=True` in parquet reader the floating column is being read as `float64` instead of `Float64`(A nullable dtype)

### Expected Behavior

>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    Float64
c      UInt8
dtype: object

### Installed Versions

<details>

pd.show_versions()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/pgali/opt/anaconda3/envs/del/lib/python3.9/distutils/core.py

</details>

**Comment by Jaafarben2** [comment]
Pandas primarily uses NaN to represent missing data. Because NaN is a float, this forces an array of integers with any missing values to become floating point.So pandas introduce a extension types for (int64 -> Int64, ... ), but there isn't a need to extend float64 to Float64 because float64 is nullable (NaN is a float).

```
>>> pd.Series([1, 2, np.nan], dtype="Float64").dtype
dtype('float64')
```

**Comment by galipremsagar** [comment]
> Pandas primarily uses NaN to represent missing data. Because NaN is a float, this forces an array of integers with any missing values to become floating point.So pandas introduce a extension types for (int64 -> Int64, ... ), but there isn't a need to extend float64 to Float64 because float64 is nullable (NaN is a float).
> 
> ```
> >>> pd.Series([1, 2, np.nan], dtype="Float64").dtype
> dtype('float64')
> ```

I don't understand. Is this documented somewhere? What I'm expecting interms of nullable dtype equivalent is `pd.Float64Dtype`, the one currently being returned is of `numpy.dtype`:

```python
>>> df['b']
0    1.0
1    2.0
2    3.0
Name: b, dtype: float64
>>> df['b'].dtype
dtype('float64')
>>> type(df['b'].dtype)
<class 'numpy.dtype[float64]'>
>>> type(df['b'].astype(pd.Float64Dtype()).dtype)
<class 'pandas.core.arrays.floating.Float64Dtype'>
>>> df['b'].astype(pd.Float64Dtype())
0    1.0
1    2.0
2    3.0
Name: b, dtype: Float64
```

**Comment by Jaafarben2** [comment]
Yes, I'm sorry for using an earlier version of pandas.
Otherwise the float mapping is missing in the "mapping" dictionary on pandas\io\parquet.py
I add these two lines in the "mapping" dictionary of parquet.py and it works:
```
mapping = {
.
.
.
self.api.float32(): pd.Float32Dtype(),
self.api.float64(): pd.Float64Dtype(),
}
```
I will make a pull request about this
