### ISSUE TITLE
BUG: ExcelWriter with openpyxl, engine_kwargs doesn't work anymore

### ISSUE THREAD

**Issue by dnzila** [pandas-dev/pandas#45734]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

This bug exist using the example from pandas documentation:

```python
pd.ExcelWriter("path_to_file.xlsx",
               engine="openpyxl",
               mode="a",
               engine_kwargs={"keep_vba": True})
```

```python-traceback
File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\pandas\io\excel\_openpyxl.py", line 72, in __init__
    self.book = Workbook(**engine_kwargs)
__init__() got an unexpected keyword argument 'keep_vba'
```

### Issue Description

Hi, 
since i update to **pandas** *1.4.0*,  **pd.ExcelWriter()** with **openpyxl** and **engine_kwargs** doesn't have the same behavior as the *1.3.x*
The **openpyxl** version use in accordance is *3.0.9*

From the few things that i saw, the way openpyxl is called, there are much less **engine_kwargs** available than the previous version of **pandas** (*1.3.x*)
in **pandas**:
```python
else:
    # Create workbook object with default optimized_write=True.
    self.book = Workbook(**engine_kwargs)
```

In **openpyxl**:
```python
class Workbook(object):
    """Workbook is the container for all other parts of the document."""

    _read_only = False
    _data_only = False
    template = False
    path = "/xl/workbook.xml"

    def __init__(self,
                 write_only=False,
                 iso_dates=False,
                 ):
```
The init called for workbook only allow two arguments: **write_only** and **iso_dates**
Whereas in the pandas documentation, it called the **engine_kwargs** -> **keep_vba**

### Expected Behavior

Should use the engine_kwargs or raise an error for invalid ones.

### Installed Versions

<details>

I use pandas 1.4.0, 

but when i run pd.show_versions() i got this:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\pandas\util\_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\pandas\util\_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\pandas\compat\_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\setuptools\__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\_distutils_hack\__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "C:\Users\dnzila\.conda\envs\aorpy\lib\site-packages\_distutils_hack\__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: C:\Users\dnzila\.conda\envs\aorpy\lib\distutils\core.py
```

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! When the mode is append, we should be calling load_workbook instead of Workbook. A PR to fix would be most welcome!

**Comment by phofl** [comment]
I can neither reproduce this on main nor on 1.4.0. Could you try @rhshadrach ?

**Comment by rhshadrach** [comment]
Thanks @phofl  - I can not reproduce this either. Assuming the versions are correct, I've only been able to come up with one theory. @dnzilla - might you have copied this code from a web page? I've run into issues where code copied off a web page uses non-ascii character set causing odd behavior. In particular, what is the value of `ord("a")` where `a` is from the mode you set. If you are able to get the value of `mode` after the call to `super().__init__` within the openpyxl file within pandas, that would also be helpful.

**Comment by phofl** [comment]
@dnzila Closing, please ping to reopen if you can adress comments
