### ISSUE TITLE
BUG: df created with `columns` takes exceedingly long time for `sum()`

### ISSUE THREAD

**Issue by nirandaperera** [pandas-dev/pandas#45816]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd 
import numpy as np
from numpy.random import default_rng
import time

rng = default_rng()

r = 1000000000
data = rng.integers(0, r, size=(r, 2))
df = pd.DataFrame(data).add_prefix("col")

t1 = time.time()
df.sum()
t2 = time.time()
print((t2-t1)*1000)

df = pd.DataFrame(data, columns=["col0", "col1"])
t1 = time.time()
df.sum()
t2 = time.time()
print((t2-t1)*1000)
```

### Issue Description

Ref: example. 
I'm creating a df from a numpy array (10^9, 2) and then call `df.sum()`.
When I create df from, `df = pd.DataFrame(data).add_prefix("col")` it takes **1502ms** for the `df.sum()`
But, 
When I create df from, `df = pd.DataFrame(data, columns=["col0", "col1"])` it takes **11979ms** for the `df.sum()`! :astonished: 

Why would there be such a drastic timing difference?

### Expected Behavior

Both cases should take similar times

### Installed Versions

<details>
> pd.show_versions() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "******/.conda/envs/cylon_dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "******/.conda/envs/cylon_dev/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: ******/.conda/envs/cylon_dev/lib/python3.8/distutils/core.py

> pd.__version__
'1.4.0'

</details>

**Comment by jbrockmendel** [comment]
> Why would there be such a drastic timing difference?

Tentatively looks like the `.add_prefix("col")` is making a copy, which is changing the layout of the data in a way that makes .sum faster.

**Comment by nirandaperera** [comment]
> > Why would there be such a drastic timing difference?
> 
> Tentatively looks like the `.add_prefix("col")` is making a copy, which is changing the layout of the data in a way that makes .sum faster.

But could that cause an 8x performance difference?

**Comment by nirandaperera** [comment]
I checked `np.sum(data, axis=0)`, and it also seem to take a similar amount of time (~12s).
And when I changed `data` to fortran-order, `np.asfortranarray(rng.integers(0, r, size=(r, 2)))`, the timings are consistent araound 1.5s. 
 So, I'm guessing this is expected behavior?

**Comment by jbrockmendel** [comment]
> So, I'm guessing this is expected behavior?

Yah, I don't see what we could do differently.  Open to ideas.

**Comment by jbrockmendel** [comment]
closed by #44562
