### ISSUE TITLE
can't pass min_count to sum()

### ISSUE THREAD

**Issue by czka** [pandas-dev/pandas#45970]
Not sure whether this is a bug report, usage question or a request for docs. Sorry! I searched through StackOverflow and pandas-dev GH tickets carefully not finding a reply matching my issue. So here it goes.

My setup:

```
import pandas as pd
pd.__version__
'1.4.0'

import sys
sys.version
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
```

I want to aggregate daily values to weekly by their sum, producing a weekly `NaN` rather than `0` where there were only `NaN`s in the daily input. My real-life case is on [1], and here's a dummy reproducible example:

```
import pandas as pd
import numpy as np

d={'date': pd.date_range(start='2020-01-01', end='2020-01-31', freq='D'), 'value': [np.nan]*16 + [1]*15}
df=pd.DataFrame(d)
```

```
df.resample(rule='W', on='date').agg({'value': sum})
            value
date             
2020-01-05    0.0
2020-01-12    0.0
2020-01-19    3.0
2020-01-26    7.0
2020-02-02    5.0
```

Now how do I tell the `sum()` method above I want a weekly `NaN` rather than `0` where there were only `NaN`s in the daily input? Ie. how do I pass it the `min_count=1` parameter? I tried as suggested on [3], but that refuses to work as follows:

1. `lambda x: sum(x, min_count=1)` triggers `'min_count' is an invalid keyword argument for sum()`:

```
df.resample(rule='W', on='date').agg({'value': lambda x: sum(x, min_count=1)})

<input>:1: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pandas/core/resample.py", line 347, in aggregate
    result = ResamplerWindowApply(self, func, args=args, kwargs=kwargs).agg()
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 168, in agg
    return self.agg_dict_like()
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 475, in agg_dict_like
    results = {
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 476, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 287, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1490, in _python_agg_general
    return self._python_apply_general(f, self._selected_obj)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1455, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 761, in apply
    res = f(group)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1467, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "<input>", line 1, in <lambda>
TypeError: 'min_count' is an invalid keyword argument for sum()
```

2. `lambda x: np.sum(x, min_count=1` triggers `_sum_dispatcher() got an unexpected keyword argument 'min_count'`:

```
df.resample(rule='W', on='date').agg({'value': lambda x: np.sum(x, min_count=1)})

<input>:1: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pandas/core/resample.py", line 347, in aggregate
    result = ResamplerWindowApply(self, func, args=args, kwargs=kwargs).agg()
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 168, in agg
    return self.agg_dict_like()
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 475, in agg_dict_like
    results = {
  File "/usr/lib/python3.10/site-packages/pandas/core/apply.py", line 476, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 287, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1490, in _python_agg_general
    return self._python_apply_general(f, self._selected_obj)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1455, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 761, in apply
    res = f(group)
  File "/usr/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1467, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "<input>", line 1, in <lambda>
  File "<__array_function__ internals>", line 179, in sum
TypeError: _sum_dispatcher() got an unexpected keyword argument 'min_count'
```

I'm aiming for an output as produced right below, but being able to apply different functions to those 12 columns of mine in 1 batch in my real-life case [1]:

```
df.resample(rule='W', on='date').sum(min_count=1)
            value
date             
2020-01-05    NaN
2020-01-12    NaN
2020-01-19    3.0
2020-01-26    7.0
2020-02-02    5.0
```

Interesingly the closest thing I managed to obtain is:

```
df.resample(rule='W', on='date').agg({'value': lambda x: sum(x)})
            value
date             
2020-01-05    NaN
2020-01-12    NaN
2020-01-19    NaN
2020-01-26    7.0
2020-02-02    5.0
```

But this has 1 extra `NaN` compared to `df.resample(rule='W', on='date').sum(min_count=1)`, and as you see I'm not passing `min_count` there at all...

Any comments/advice please?

[1]https://github.com/czka/covid_toll_tool/blob/main/covid_toll_tool.py#L248
[2]https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.sum.html
[3]https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#applying-different-functions-to-dataframe-columns

**Comment by phofl** [comment]
I think what you are looking for is

```
df.resample(rule='W', on='date').agg({'value': lambda x: x.sum(min_count=1)})
```

Please confirm if I am correct

**Comment by czka** [comment]
> I think what you are looking for is
> 
> ```
> df.resample(rule='W', on='date').agg({'value': lambda x: x.sum(min_count=1)})
> ```
> 
> Please confirm if I am correct

@phofl Your solution works like a charm. Thank you very much! I owe you big time.

Would you happen to know if there's any other way to pass a parameter to sum() or mean() than with `lambda`, in my use case [1]? I mean also if that takes rewriting that piece of code. Asking because, as this ticket clearly shows, I'm not well-versed with `lambda`, so I'll rather use it my last resort ;).

[1]https://github.com/czka/covid_toll_tool/blob/main/covid_toll_tool.py#L248

**Comment by phofl** [comment]
I don't think so, in general x.sum() and sum(x) are two different functions. Please ask usage questions on stackoverflow
