### ISSUE TITLE
BUG:  Unable to install Pandas in Mac M1 and Python 3.6.15 and MacOs Monterey

### ISSUE THREAD

**Issue by iammujtaba** [pandas-dev/pandas#46169]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
python3 --version
o/p - 3.6.15
pip3 install pandas==0.23.4
```

### Issue Description

Collecting pandas==0.23.4 (from -r requirements.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/e9/ad/5e92ba493eff96055a23b0a1323a9a803af71ec859ae3243ced86fcbd0a4/pandas-0.23.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/0g/7mj8xtf91tn2m_snvqb55kg00000gn/T/easy_install-r4o7q75d/numpy-1.22.2/setup.py", line 34, in <module>
    
    RuntimeError: Python version >= 3.8 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0g/7mj8xtf91tn2m_snvqb55kg00000gn/T/pip-install-mqpk_3vn/pandas/setup.py", line 749, in <module>
        **setuptools_kwargs)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/Users/programmer/.pyenv/versions/3.6.15/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/programmer/.pyenv/versions/3.6.15/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/programmer/wealthy/taxy/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/0g/7mj8xtf91tn2m_snvqb55kg00000gn/T/easy_install-r4o7q75d/numpy-1.22.2/setup.py", line 34, in <module>
    
    RuntimeError: Python version >= 3.8 required.

### Expected Behavior

It should install as it is working in Intel based chip

### Installed Versions

<details>

0.23.4

</details>

**Comment by mroeschke** [comment]
Thanks for the report. It appears your version of numpy is too new. You will probably need to downgrade it to a version that still supports 3.6

Generally, the team only has the bandwidth to support the latest release of pandas. If you need version 0.23.x and discover other issues, we recommend to fork the branch: https://github.com/pandas-dev/pandas/tree/0.23.x
