### ISSUE TITLE
QST: Strange unconsistent error ValueError: Unknown format code 'd' for object of type 'float' when using pandas.read_csv()

### ISSUE THREAD

**Issue by MR-T77** [pandas-dev/pandas#46184]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/71299420/valueerror-unknown-format-code-d-for-object-of-type-float-when-using-pandas/71299567#71299567

### Question about pandas

I'm pursuing a bug in my code, and right now I find that in a part of the code (a module) I can read a *csv* into a pandas DataFrame with no issues (e.g. in the end I can do `df` in the debug console or I can do `print(df)`), and on the other part (another module) I can read a *csv* into a pandas Dataframe, but when I try to print it I get the following error: `ValueError: Unknown format code 'd' for object of type 'float'` (in this case when I do `df` in the debug console I get `<pandas.core.frame.DataFrame object at 0x172dcad60>` instead of the print).

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/core/frame.py", line 995, in __repr__
        self.to_string(
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/core/frame.py", line 1131, in to_string
        return fmt.DataFrameRenderer(formatter).to_string(
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1053, in to_string
        string = string_formatter.to_string()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/string.py", line 25, in to_string
        text = self._get_string_representation()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/string.py", line 40, in _get_string_representation
        strcols = self._get_strcols()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/string.py", line 31, in _get_strcols
        strcols = self.fmt.get_strcols()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 540, in get_strcols
        strcols = self._get_strcols_without_index()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 804, in _get_strcols_without_index
        fmt_values = self.format_col(i)
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 818, in format_col
        return format_array(
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1240, in format_array
        return fmt_obj.get_result()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1271, in get_result
        fmt_values = self._format_strings()
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1518, in _format_strings
        return list(self.get_result_as_array())
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1435, in get_result_as_array
        return format_with_na_rep(self.values, self.formatter, self.na_rep)
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1427, in format_with_na_rep
        [
      File "/machine/miniforge3/envs/py39deps26-source/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1428, in <listcomp>
        formatter(val) if not m else na_rep
    ValueError: Unknown format code 'd' for object of type 'float'

The precise instruction to read is equal on both modules(!), but I'm getting  

    df = pd.read_csv(results_path / f'{results}.csv')

I can't reproduce this, unless I run it through the existing code (through the existing modules). If I use a new program that simply reads the csv with the `pd.read_csv()` function the problem does not happen.
I can't really make sense of this, so I'm leaving this here hoping that someone figures what I may be doing wrong. It seems that depending on the module where I am, pandas loads the csv in a different way.

**Comment by MR-T77** [comment]
I found it, in one of the modules I had introduced an error `pd.options.display.float_format = '{:,.0d}'.format`, which manifested only when I print the DataFrame.
