### ISSUE TITLE
BUG: Cannot install pandas in docker via setup.py with python 3.10

### ISSUE THREAD

**Issue by distortedsignal** [pandas-dev/pandas#46363]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

Dockerfile:
```Dockerfile
ARG VERSION

FROM python:$VERSION-buster

RUN mkdir /workdir

ADD setup.py /workdir

RUN cd /workdir && python setup.py install

```

setup.py:
```py
#!/usr/bin/env python

from setuptools import setup

setup(
    install_requires=[
        'pandas'
    ]
)

```

Run the following command:
```sh
> docker build --no-cache --build-arg VERSION="3.9.10" . && echo && echo "Done building on 3.9.10" && echo && docker build --no-cache --build-arg VERSION="3.10.2" .
```

When I run the command, I get the following output:

```
[+] Building 14.1s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 172B                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3.9.10-buster                                                          0.6s
 => CACHED [1/4] FROM docker.io/library/python:3.9.10-buster@sha256:794b620641185e126ce2408f31086b61a0c866d1aa66dccdfa6fccf59ac  0.0s
 => [internal] load build context                                                                                                0.0s
 => => transferring context: 29B                                                                                                 0.0s
 => [2/4] RUN mkdir /workdir                                                                                                     0.3s
 => [3/4] ADD setup.py /workdir                                                                                                  0.0s
 => [4/4] RUN cd /workdir && python setup.py install                                                                            12.3s
 => exporting to image                                                                                                           0.9s
 => => exporting layers                                                                                                          0.8s
 => => writing image sha256:1bc4a382f0ff188e6b2787572668bf2e39a818b3f289b6effe95cc49bee3b4a9                                     0.0s

Done building on 3.9.10

[+] Building 5.7s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 37B                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3.10.2-buster                                                          0.5s
 => [internal] load build context                                                                                                0.0s
 => => transferring context: 29B                                                                                                 0.0s
 => CACHED [1/4] FROM docker.io/library/python:3.10.2-buster@sha256:b1f25ddc334ed6d44b707e42c0263d17ac4222cedf0a36496d5af8a185d  0.0s
 => [2/4] RUN mkdir /workdir                                                                                                     0.3s
 => [3/4] ADD setup.py /workdir                                                                                                  0.0s
 => ERROR [4/4] RUN cd /workdir && python setup.py install                                                                       4.6s
------
 > [4/4] RUN cd /workdir && python setup.py install:
#8 1.013 running install
#8 1.188 running bdist_egg
#8 1.189 running egg_info
#8 1.189 creating UNKNOWN.egg-info
#8 1.190 writing UNKNOWN.egg-info/PKG-INFO
#8 1.190 writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
#8 1.190 writing requirements to UNKNOWN.egg-info/requires.txt
#8 1.190 writing top-level names to UNKNOWN.egg-info/top_level.txt
#8 1.191 writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
#8 1.192 reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
#8 1.192 writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
#8 1.193 installing library code to build/bdist.linux-x86_64/egg
#8 1.193 running install_lib
#8 1.193 warning: install_lib: 'build/lib' does not exist -- no Python modules to install
#8 1.193
#8 1.193 creating build
#8 1.193 creating build/bdist.linux-x86_64
#8 1.194 creating build/bdist.linux-x86_64/egg
#8 1.194 creating build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.194 copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.194 copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.195 copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.195 copying UNKNOWN.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.196 zip_safe flag not set; analyzing archive contents...
#8 1.196 copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#8 1.197 creating dist
#8 1.197 creating 'dist/UNKNOWN-0.0.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
#8 1.198 removing 'build/bdist.linux-x86_64/egg' (and everything under it)
#8 1.201 Processing UNKNOWN-0.0.0-py3.10.egg
#8 1.205 Copying UNKNOWN-0.0.0-py3.10.egg to /usr/local/lib/python3.10/site-packages
#8 1.206 Adding UNKNOWN 0.0.0 to easy-install.pth file
#8 1.208
#8 1.208 Installed /usr/local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10.egg
#8 1.209 Processing dependencies for UNKNOWN==0.0.0
#8 1.210 Searching for pandas
#8 1.210 Reading https://pypi.org/simple/pandas/
#8 2.019 Downloading https://files.pythonhosted.org/packages/c4/eb/cfa96ba42695b3c28d4864a796d492f188471dd536df7e5e5e0c54b629a6/pandas-1.4.1.tar.gz#sha256=8db93ec98ac7cb5f8ac1420c10f5e3c43533153f253fe7fb6d891cf5aa2b80d2
#8 3.215 Best match: pandas 1.4.1
#8 3.215 Processing pandas-1.4.1.tar.gz
#8 4.403 Writing /tmp/easy_install-vz39z6ho/pandas-1.4.1/setup.cfg
#8 4.403 Running pandas-1.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vz39z6ho/pandas-1.4.1/egg-dist-tmp-8_lc34u5
#8 4.524 Traceback (most recent call last):
#8 4.524   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
#8 4.524     yield saved
#8 4.524   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
#8 4.524     yield
#8 4.524   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
#8 4.525     _execfile(setup_script, ns)
#8 4.525   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
#8 4.525     exec(code, globals, locals)
#8 4.525   File "/tmp/easy_install-vz39z6ho/pandas-1.4.1/setup.py", line 18, in <module>
#8 4.525 ModuleNotFoundError: No module named 'numpy'
#8 4.525
#8 4.525 During handling of the above exception, another exception occurred:
#8 4.525
#8 4.525 Traceback (most recent call last):
#8 4.525   File "/workdir/setup.py", line 5, in <module>
#8 4.525     setup(
#8 4.525   File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
#8 4.525     return distutils.core.setup(**attrs)
#8 4.525   File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
#8 4.525     dist.run_commands()
#8 4.525   File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
#8 4.526     self.run_command(cmd)
#8 4.526   File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
#8 4.526     cmd_obj.run()
#8 4.526   File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 67, in run
#8 4.526     self.do_egg_install()
#8 4.526   File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 117, in do_egg_install
#8 4.526     cmd.run(show_deprecation=False)
#8 4.526   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 408, in run
#8 4.526     self.easy_install(spec, not self.no_deps)
#8 4.526   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
#8 4.527     return self.install_item(None, spec, tmpdir, deps, True)
#8 4.527   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 697, in install_item
#8 4.527     self.process_distribution(spec, dist, deps)
#8 4.527   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 744, in process_distribution
#8 4.527     distros = WorkingSet([]).resolve(
#8 4.527   File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
#8 4.528     dist = best[req.key] = env.best_match(
#8 4.528   File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
#8 4.528     return self.obtain(req, installer)
#8 4.529   File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
#8 4.529     return installer(requirement)
#8 4.529   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
#8 4.529     return self.install_item(spec, dist.location, tmpdir, deps)
#8 4.529   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 695, in install_item
#8 4.530     dists = self.install_eggs(spec, download, tmpdir)
#8 4.530   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
#8 4.530     return self.build_and_install(setup_script, setup_base)
#8 4.530   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
#8 4.530     self.run_setup(setup_script, setup_base, args)
#8 4.530   File "/usr/local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
#8 4.531     run_setup(setup_script, args)
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 249, in run_setup
#8 4.531     with setup_context(setup_dir):
#8 4.531   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
#8 4.531     self.gen.throw(typ, value, traceback)
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 190, in setup_context
#8 4.531     with save_modules():
#8 4.531   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
#8 4.531     self.gen.throw(typ, value, traceback)
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 169, in save_modules
#8 4.531     saved_exc.resume()
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 143, in resume
#8 4.531     raise exc.with_traceback(self._tb)
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
#8 4.531     yield saved
#8 4.531   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
#8 4.532     yield
#8 4.532   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
#8 4.532     _execfile(setup_script, ns)
#8 4.532   File "/usr/local/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
#8 4.532     exec(code, globals, locals)
#8 4.532   File "/tmp/easy_install-vz39z6ho/pandas-1.4.1/setup.py", line 18, in <module>
#8 4.532 ModuleNotFoundError: No module named 'numpy'
------
executor failed running [/bin/sh -c cd /workdir && python setup.py install]: exit code: 1
```

This fails similarly on 3.10.0 and 3.10.1.

### Issue Description

When attempting to install pandas on python 3.10 versions as a dependency to another module, the install fails with a "ModuleNotFoundError." This is curious as attempting the install with the same files on python 3.9 succeeds (as in the repro steps). After the repro steps, I attempted the install several times using the following script:

```sh
> DISTROS=("bullseye" "slim-bullseye" "buster" "slim-buster" "alpine3.15" "alpine3.14") ; \
for d in $DISTROS ; do \
    echo ; \
    echo "Build on $d" ; \
    echo ; \
    docker build --no-cache --build-arg VERSION="3.10.2" --build-arg DISTRO="$d" . ; \
done
```

Each install failed.

### Expected Behavior

Pandas should be installed successfully.

### Installed Versions

None - the installer broke.

**Comment by distortedsignal** [comment]
This _might_ be because I'm running on MacOS? I'm not 100% on that, though.

**Comment by distortedsignal** [comment]
PS: The form that you guys use doesn't really capture this kind of issue well. I understand this is mostly a python project, but it's possible to have bugs in and around python code that cannot be captured by a "Minimal Example" _purely_ in python.

**Comment by distortedsignal** [comment]
Interestingly, installing `pandas` with pip works in python 3.10.2:

```Dockerfile
FROM python:3.10.2-buster

RUN mkdir /workdir

RUN pip install pandas
```

```sh
> docker build --no-cache .
[+] Building 14.6s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/python:3.10.2-buster                                                                                  0.5s
 => CACHED [1/3] FROM docker.io/library/python:3.10.2-buster@sha256:b1f25ddc334ed6d44b707e42c0263d17ac4222cedf0a36496d5af8a185dcf072                     0.0s
 => [2/3] RUN mkdir /workdir                                                                                                                             0.3s
 => [3/3] RUN pip install pandas                                                                                                                        12.5s
 => exporting to image                                                                                                                                   1.2s
 => => exporting layers                                                                                                                                  1.2s
 => => writing image sha256:f6c6c2dfb6cad372f601afc0c2e534ca5062d3146afa75abf7df8897f3b78b39                                                             0.0s
```

**Comment by rhshadrach** [comment]
pandas' setup.py has

```
    numpy>=1.18.5; platform_machine!='aarch64' and platform_machine!='arm64' and python_version<'3.10'
    numpy>=1.19.2; platform_machine=='aarch64' and python_version<'3.10'
    numpy>=1.20.0; platform_machine=='arm64' and python_version<'3.10'
    numpy>=1.21.0; python_version>='3.10'
```

Is it possible that you aren't able to get numpy >= 1.21.0, which would explain why it works on Python 3.9 but not 3.10?

**Comment by rhshadrach** [comment]
Please respond here if you're still experiencing issues and can reopen.
