### ISSUE TITLE
BUG: specific strings, that are converted to datetime, cannot be written to parquet files

### ISSUE THREAD

**Issue by mplatzer** [pandas-dev/pandas#46508]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'x': ['2021-10-05 16:06:38.995523400']})
df['x'] = pd.to_datetime(df['x'])
df.to_parquet('test.parquet')
```

### Issue Description

Despite a successful conversion from string to datetime, the serialization to parquet crashes with the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pandas/core/frame.py", line 2835, in to_parquet
    return to_parquet(
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pandas/io/parquet.py", line 420, in to_parquet
    impl.write(
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pandas/io/parquet.py", line 195, in write
    self.api.parquet.write_table(
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pyarrow/parquet.py", line 2092, in write_table
    writer.write_table(table, row_group_size=row_group_size)
  File "/Users/mplatzer/miniconda3/envs/mostly-engine-v2/lib/python3.9/site-packages/pyarrow/parquet.py", line 754, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow/_parquet.pyx", line 1506, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Casting from timestamp[ns] to timestamp[us] would lose data: 1633449998995523400
```

If we trim the string first, then the bug doesn't occur:
```
import pandas as pd
df = pd.DataFrame({'x': ['2021-10-05 16:06:38.995523400']})
df['x'] = pd.to_datetime(df['x'].str[0:26])
df.to_parquet('test.parquet')
```

### Expected Behavior

It would be expected that either the datetime conversion crashes, or that the serialization doesn't crash.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 7.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.02.0
scipy            : 1.8.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mplatzer** [comment]
ok, it seems this is already a known issue: https://stackoverflow.com/questions/53893554/transfer-and-write-parquet-with-python-and-pandas-got-timestamp-error
