### ISSUE TITLE
BUG: inconsistent behavior of `pd.Series.astype("datetime64")` for concatenated 2 heterogenous `pd.Series` with equal `pd.Timestamp` and `datetime.date` values and more than 50 elements

### ISSUE THREAD

**Issue by lycantropos** [pandas-dev/pandas#46579]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import datetime
import pandas as pd

# runs fine with 50 elements
(pd.concat([pd.Series([pd.Timestamp('2022-03-17 00:00:00')]), pd.Series([datetime.date(2022, 3, 17)] * 49)],
           join='outer')
 .astype('datetime64'))
# fails with 51 elements
(pd.concat([pd.Series([pd.Timestamp('2022-03-17 00:00:00')]), pd.Series([datetime.date(2022, 3, 17)] * 50)],
           join='outer')
 .astype('datetime64'))
```

### Issue Description

If we `pd.concat` 2 non-empty `pd.Series` one having `pd.Timestamp` and other having `datetime.date` equal values (representing the same date) such that sum of their sizes is more than 50 then we will have
```bash
Traceback (most recent call last):
  File "/path/to/python3.9.10/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 5, in <module>
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/generic.py", line 5920, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 419, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 580, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1292, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1237, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1163, in astype_nansafe
    to_datetime(arr).values,
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1074, in to_datetime
    result = _convert_and_box_cache(arg, cache_array)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 256, in _convert_and_box_cache
    result = Series(arg).map(cache_array)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/series.py", line 4237, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/base.py", line 852, in _map_values
    indexer = mapper.index.get_indexer(values)
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3764, in get_indexer
    return pself.get_indexer(
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```
but if we do the same for 50 values or less than no exception is raised.

### Expected Behavior

both should fail or both should succeed independent on the number of values

### Installed Versions

`pd.show_versions()` fails with
```bash
>>> import pandas as pd
>>> pd.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/path/to/python3.9.10/lib/python3.9/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/path/to/python3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/path/to/python3.9.10/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /path/to/python3.9.10/lib/python3.9/distutils/core.py
```

so my environment is
- macOs 12.3 (21E230), Apple M1 Pro (but it reproduces inside `python:3.9.10` Docker container)
- Python3.9.10
- `pandas==1.4.1`

Inside Docker
```python
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.104-linuxkit
Version          : #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
```

**Comment by mroeschke** [comment]
Thanks for the report. This is fixed on main, but raises a warning. This is related to `to_datetime` using `cache=True`, so there will probably need to be a fix in there converting the dates to datetime objects beforehand

```
In [8]: (pd.concat([pd.Series([pd.Timestamp('2022-03-17 00:00:00')]), pd.Series([datetime.date(2022, 3, 17)] * 50)],
   ...:            join='outer')
   ...:  .astype('datetime64'))
pandas/core/indexes/base.py:2361: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  return self._engine.is_unique
pandas/core/algorithms.py:1002: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  return htable.duplicated(values, keep=keep)
Out[8]:
0    2022-03-17
0    2022-03-17
1    2022-03-17
2    2022-03-17
3    2022-03-17
4    2022-03-17
5    2022-03-17
6    2022-03-17
7    2022-03-17
8    2022-03-17
9    2022-03-17
10   2022-03-17
11   2022-03-17
12   2022-03-17
13   2022-03-17
14   2022-03-17
15   2022-03-17
16   2022-03-17
17   2022-03-17
18   2022-03-17
19   2022-03-17
20   2022-03-17
21   2022-03-17
22   2022-03-17
23   2022-03-17
24   2022-03-17
25   2022-03-17
26   2022-03-17
27   2022-03-17
28   2022-03-17
29   2022-03-17
30   2022-03-17
31   2022-03-17
32   2022-03-17
33   2022-03-17
34   2022-03-17
35   2022-03-17
36   2022-03-17
37   2022-03-17
38   2022-03-17
39   2022-03-17
40   2022-03-17
41   2022-03-17
42   2022-03-17
43   2022-03-17
44   2022-03-17
45   2022-03-17
46   2022-03-17
47   2022-03-17
48   2022-03-17
49   2022-03-17
dtype: datetime64[ns]
```

**Comment by jbrockmendel** [comment]
This no longer produces a warning. May be closeable.
