### ISSUE TITLE
BUG: read_xml iterparse doesn't handle multiple toplevel elements with lxml parser

### ISSUE THREAD

**Issue by bailsman** [pandas-dev/pandas#47422]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
from tempfile import NamedTemporaryFile
import pandas as pd

XML = '''
<!-- it will choke on this comment -->
<issue>
  <type>BUG</type>
</issue>
'''.encode('utf-8')

with NamedTemporaryFile() as tempfile:
    tempfile.write(XML)
    tempfile.flush()
    df = pd.read_xml(tempfile.name, iterparse={'issue': ['type']})
```

### Issue Description

```
Traceback (most recent call last):
  File "k.py", line 14, in <module>
    df = pd.read_xml(tempfile.name, iterparse={'issue': ['type']})
  File "/home/erietveld/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/erietveld/.local/lib/python3.8/site-packages/pandas/io/xml.py", line 1208, in read_xml
    return _parse(
  File "/home/erietveld/.local/lib/python3.8/site-packages/pandas/io/xml.py", line 946, in _parse
    data_dicts = p.parse_data()
  File "/home/erietveld/.local/lib/python3.8/site-packages/pandas/io/xml.py", line 538, in parse_data
    self._parse_nodes() if self.iterparse is None else self._iterparse_nodes()
  File "/home/erietveld/.local/lib/python3.8/site-packages/pandas/io/xml.py", line 677, in _iterparse_nodes
    del elem.getparent()[0]
TypeError: 'NoneType' object does not support item deletion
```

Note this feature is not yet released and planned for 1.5.0: https://github.com/pandas-dev/pandas/pull/45724#issuecomment-1154200083

### Expected Behavior

No exception is thrown and the document is parsed successfully. Perhaps don't try to delete if the element has no parent?

```diff
diff --git a/pandas/io/xml.py b/pandas/io/xml.py
index 181b0fe..c026a00 100644
--- a/pandas/io/xml.py
+++ b/pandas/io/xml.py
@@ -674,6 +674,8 @@ class _LxmlFrameParser(_XMLFrameParser):

                 elem.clear()
                 while elem.getprevious() is not None:
+                    if elem.getparent() is None:
+                        break
                     del elem.getparent()[0]

         if dicts == []:
```

### Installed Versions

5465f54f7640cbb4be9b223846823d4935142431

**Comment by ParfaitG** [comment]
I cannot reproduce this issue with your exact code. What version of `lxml` do you have installed? Check with following:

```python
import lxml
print(lxml.__version__)
```

The pandas' [minimum recommended version](https://pandas.pydata.org/docs/getting_started/install.html) for optional dependency for `lxml` is 4.5.0.

**Comment by bailsman** [comment]
4.9.0

**Comment by ParfaitG** [comment]
Thanks. Oddly now, I do reproduce issue with 4.5.2. I may have been using a development code version. Thinking more, this may not be a pandas issue but an an lxml issue especially since we follow the same setup as lxml docs. I will raise an issue on their [mailing list](https://mail.python.org/archives/list/lxml@python.org/) with an iterparse reprex. 

It may be the unusual case of a comment _before_ root element. They may even provide guidance since the [iterparse / modifying the tree docs](https://lxml.de/4.5/parsing.html#modifying-the-tree) includes a note on the `while` loop usage.
