### ISSUE TITLE
BUG: to_datetime ParserError on incorrect element

### ISSUE THREAD

**Issue by mousey92** [pandas-dev/pandas#47495]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
pd.to_datetime(["today", "yesterday"])
```

### Issue Description

The error message indicates the error on the wrong item to convert.

Converting the string "today" to a datetime is no problem:
`pd.to_datetime("today")` gives the same result as `pd.to_datetime("now")`
`pd.to_datetime("yesterday")` gives 
`ParserError: Unknown string format: yesterday`

But combining the two into
`pd.to_datetime(["today", "yesterday"])`
gives an error indicating that the "today" string is unknown:
```
Traceback (most recent call last):
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2236, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas\_libs\tslibs\conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\tools\datetimes.py", line 1076, in to_datetime
    result = convert_listlike(arg, format)
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\tools\datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2242, in objects_to_datetime64ns
    raise err
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2224, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas\_libs\tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslibs\parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\dateutil\parser\_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: today
```

Obviously the "today" string is not the problem, it's the "yesterday" string

Switching the two strings around does gives the proper error:
`pd.to_datetime(["yesterday", "today"])`
gives
```
Traceback (most recent call last):
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2236, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas\_libs\tslibs\conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\tools\datetimes.py", line 1076, in to_datetime
    result = convert_listlike(arg, format)
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\tools\datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2242, in objects_to_datetime64ns
    raise err
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\pandas\core\arrays\datetimes.py", line 2224, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas\_libs\tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas\_libs\tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas\_libs\tslibs\parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Matthijs.Kramer\Anaconda3\envs\test\lib\site-packages\dateutil\parser\_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: yesterday
```

It seems whenever any of the input strings cannot be parsed, an error is thrown on the first item in the input.

### Expected Behavior

When providing an number of datetime strings to `pd.to_datetime`, not all of which can be parsed, the error message should indicate on which string the error occurred, rather than the first string in the list.

In the above example, the error message should read
`Unknown string format: yesterday` instead of `Unknown string format: today`, regardless of the order of the two input strings

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Netherlands.1252

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.6.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by sidshrivastav** [comment]
@simonjayhawkins hey I've tried to debug this issue, this message is coming from dateutil parser, I believe we handle cases for `now` and `today` in tslib, maybe we need to add check if there in parser if data contain anything other than `now` and `today`, throw an error instead of letting it go to dateutil.parser
