### ISSUE TITLE
BUG: pd.cut(df, bins=N) current behavior is incorrect, returns float where int is the limit

### ISSUE THREAD

**Issue by FlorinAndrei** [pandas-dev/pandas#47996]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
hd = pd.read_csv("HeartDisease.csv")
pd.cut(hd["Age"], bins=3, include_lowest=True)
```

### Issue Description

The lowest of the three bins created is: `(28.951, 45.0]`. This is incorrect in several ways.

First off, I expect a left-inclusive bin there. That bin is not left-inclusive.

Secondly, the minimum value in that column is 29. It is not 28.951 - that float is an artifact of the library and does not exist in the data.

One workaround you can find online is this:

```
_, edges = pd.cut(hd["Age"], bins=3, include_lowest=True, retbins=True)
edges_r = [round(x) for x in edges]
pd.cut(hd["Age"], bins=edges_r)
```

But this is pointless and annoying. The library should simply return the true minimum value.

### Expected Behavior

The bin I expect is `[29.0, 45.0]`. I would also settle for `[29, 45]`.

### Installed Versions

<details>

>>> pd.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\pandas\util\_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\pandas\util\_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\_distutils_hack\__init__.py", line 79, in find_spec
    return method()
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\_distutils_hack\__init__.py", line 100, in spec_for_pip
    if self.pip_imported_during_build():
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\_distutils_hack\__init__.py", line 111, in pip_imported_during_build
    return any(
  File "C:\Users\flori\AppData\Roaming\Python\Python310\site-packages\_distutils_hack\__init__.py", line 112, in <genexpr>
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'
</details>

**Comment by GYHHAHA** [comment]
For each item, the same interval close form is expected. So now we set the lowest edge as 0.1% * (max - min) when close is right to envelop the mininal value.

**Comment by attack68** [comment]
I agree with you. Although the docs suggest the following for bins:

>int : Defines the number of equal-width bins in the range of x. The range of x is extended by .1% on each side to include the minimum and maximum values of x.

I think this is unnecessary and, as you put it, annoying.

Also I think this function is probably quite useful (for categorising continuous data in an ML context) and possibly likely to increase in usage. It could do with revamp. It was also added to #40245 without yet being addressed.

For `numpy.histogram` I think the behaviour is much better, i.e. they get `[1,2), [2,3), [3,4]`

> All but the last (righthand-most) bin is half-open.

Additionally `numpy.histogram` has a very usful arg `density`, which allows for a different algo to calculate bins, included with `weights`.

For example

```python
>>> s = np.random.rand(100)
>>> s[0], s[99] = 0, 1
>>> df = pd.DataFrame({"samples": s})
>>> pd.cut(df["samples"], bins=10, retbins=True)
... 
Categories (10, interval[float64, right]): [(-0.001, 0.1] < (0.1, 0.2] < (0.2, 0.3] < (0.3, 0.4] ... (0.6, 0.7] < (0.7, 0.8] < (0.8, 0.9] < (0.9, 1.0]]

>>> np.histogram(df["samples"])
(array([ 7,  4, 11, 14, 11,  9,  8, 14, 11, 11]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
```

If doing: `pd.cut(df["samples"], bins=np.histogram(df["samples"])[1], retbins=True)`, then the first datapoint at `0` is excluded. If `include_lowest` is set to True it just reduces the leftmost specified bin by an arbitrary 0.1% (instead of actually making it inclusive), which is horrible, IMO.

**Comment by FlorinAndrei** [comment]
> For numpy.histogram I think the behaviour is much better, i.e. they get [1,2), [2,3), [3,4]

Indeed, `numpy.histogram()` does the right thing if you request that both ends are included. The R function `discretize()` has the same behavior as Numpy. This is what people expect when they use a function like this.

> If include_lowest is set to True it just reduces the leftmost specified bin by an arbitrary 0.1% (instead of actually making it inclusive), which is horrible, IMO.

That is precisely my main objection. The current behavior of this function makes stuff up. It's just a very, very poor hack.

**Comment by andrey-orderby** [comment]
I am facing the same issue right now of ```pd.cut()``` creating intervals with left bound excluded and right bound included. Totally  support @FlorinAndrei. The default behavior should be that the left bound is included and the right one is excluded. I did not expect any other variant. And to make it worse there are no arguments to the function to set this manually. The issue was reported more than 1.5 years ago and still no solution. (I am using pandas 2.0.3)

**Comment by attack68** [comment]
PRs are welcome. It is always encouraged to support a software that is free and is built by unpaid volunteers.
