### ISSUE TITLE
BUG: to_datetime raises when errors=coerce and infer_datetime_format

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#48633]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
pd.to_datetime(["200622-12-31", "111111-24-11"], errors='coerce', infer_datetime_format=True)
```

### Issue Description

```
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    pd.to_datetime(["200622-12-31", "111111-24-11"], errors='coerce', infer_datetime_format=True)
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 1124, in to_datetime
    result = convert_listlike(argc, format)
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 418, in _convert_listlike_datetimes
    format = _guess_datetime_format_for_array(arg, dayfirst=dayfirst)
  File "/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py", line 132, in _guess_datetime_format_for_array
    return guess_datetime_format(arr[non_nan_elements[0]], dayfirst=dayfirst)
  File "pandas/_libs/tslibs/parsing.pyx", line 1029, in pandas._libs.tslibs.parsing.guess_datetime_format
    tokens[offset_index] = parsed_datetime.strftime("%z")
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
```

Note that this is different from https://github.com/pandas-dev/pandas/issues/46071, because here the error happens when pandas is still guessing the format

### Expected Behavior

```
DatetimeIndex(['NaT', 'NaT'], dtype='datetime64[ns]', freq=None)
```

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : bf856a85a3b769821809ff456e288542af16310c
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.6.0.dev0+145.gbf856a85a3
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : 6.54.5
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.3
numba            : 0.55.2
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.8
pyarrow          : 9.0.0
pyreadstat       : 1.1.9
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.9.1
snappy           : 
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : 0.18.0
tzdata           : None
None

</details>

**Comment by MarcoGorelli** [comment]
Related to https://github.com/pandas-dev/pandas/issues/28299

**Comment by MarcoGorelli** [comment]
likewise, with `errors='ignore'`
