### ISSUE TITLE
BUILD: Getting Syntax error for pandas library import in python If not using virtual env

### ISSUE THREAD

**Issue by gmmkmtgk** [pandas-dev/pandas#48658]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

pip install

### pandas Version

latest

### Python Version

3.10.6

### Installation Logs

If I use virtual env then everything is fine But if I run simply then getting syntax error for any kind of library import

Consider a simple pandas library import program

```
import pandas as pd




C:\Users\Keshav\Desktop\GAN_Assignment>python main.py
Traceback (most recent call last):
  File "C:\Users\Keshav\Desktop\GAN_Assignment\main.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\compat\__init__.py", line 15, in <module>      
    from pandas.compat.numpy import (
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module> 
    from pandas.util.version import Version
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>     
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>       
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\tslibs\__init__.py", line 30, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas\_libs\tslibs\timezones.pyx", line 14, in init pandas._libs.tslibs.timezones
  File "C:\Users\Keshav\AppData\Local\Programs\Python\Python310\lib\site-packages\dateutil\tz.py", line 78
    `self._name`,
    ^
SyntaxError: invalid syntax
```

![16b8583075ed5ab039e26ab7c6f49777160b4f53](https://user-images.githubusercontent.com/51493190/191273640-6f105e3a-bc29-495e-80b1-029e28ce607a.png)

**Comment by phofl** [comment]
Closing for now. Please ping to reopen, when you can answer questions
