### ISSUE TITLE
BUG: `pd.core.algorithms.duplicated` fails with float-based `SparseArray`

### ISSUE THREAD

**Issue by tehunter** [pandas-dev/pandas#48788]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> import numpy as np
>>> arr = pd.arrays.SparseArray([0,1,np.nan,1])
>>> pd.core.algorithms.duplicated(arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pandas/pandas/core/algorithms.py", line 1063, in duplicated
    values = _ensure_data(values)
  File "/home/pandas/pandas/core/algorithms.py", line 177, in _ensure_data
    if values.dtype.itemsize in [2, 12, 16]:  # type: ignore[union-attr]
AttributeError: 'SparseDtype' object has no attribute 'itemsize'
```

### Issue Description

`_ensure_data` tries to access `dtype.itemsize` for float types. `SparseArray` can be considered a float type, but doesn't implement an `itemsize` attribute. Addressing #48424 may solve this, but the `itemsize` attribute is also causing an issue in #42070

### Expected Behavior

Returns without error

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 24da5be949b8e0a9299af915c6e9731c373c9dda
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.6.0.dev0+203.g24da5be949.dirty
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : 6.54.6
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           :
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.0
numba            : 0.55.2
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.8
pyarrow          : 9.0.0
pyreadstat       : 1.1.9
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.9.1
snappy           :
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : 0.18.0
tzdata           : None

</details>

**Comment by EarsAndEggs** [comment]
Greetings, I'm also having the same issue where it says that AttributeError: 'SparseDtype' object has no attribute 'itemsize'

This is how I'm currently generating the dataframe, and trying to use HDFStore obviously won't work with the error
```
mat = pd.DataFrame.sparse.from_spmatrix(sparse_matrix, columns=column_names)
store = pd.HDFStore('sparse_matrix.h5')
store.put('mutation_matrix', mat, format='table', data_columns=True)
store.close()
```

Are there any updates on fixes?

**Comment by topper-123** [comment]
I can confirm this bug. A PR would be welcome.
