### ISSUE TITLE
BUG: .unstack() with recarray column raises TypeError since 1.4.0

### ISSUE THREAD

**Issue by stefan-jansen** [pandas-dev/pandas#49388]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

c = np.array([2] * 20, dtype='f8')
r = np.rec.fromarrays([c], names=['c'])

df = pd.DataFrame({'a': np.arange(20) // 5, 'b': list('ABCDE') * 4, 'c': r})
# df.info() => see GH48526
df.set_index(['a', 'b']).c.unstack()
```

### Issue Description

Starting with 1.4.0, Including a column of dtype `np.record`(related to [#48526](https://github.com/pandas-dev/pandas/issues/48526)) as follows:

```
c = np.array([2] * 9, dtype='f8')
r = np.rec.fromarrays([c], names=['c'])
df = pd.DataFrame({'a': np.arange(9) // 3,
                   'b': list('ABC') * 3,
                   'c': r})
print(df.dtypes)

a                             int64
b                            object
c    (numpy.record, [('c', '<f8')])
```
raises a TypeError:
```
   df.set_index(['a', 'b']).unstack()
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/frame.py", line 9060, in unstack
    result = unstack(self, level, fill_value)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 479, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 508, in _unstack_frame
    return unstacker.get_result(
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 215, in get_result
    values, _ = self.get_new_values(values, fill_value)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 228, in get_new_values
    sorted_values = self._make_sorted_values(values)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 167, in _make_sorted_values
    sorted_values = algos.take_nd(values, indexer, axis=0)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/array_algos/take.py", line 118, in take_nd
    return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/array_algos/take.py", line 135, in _take_nd_ndarray
    dtype, fill_value, mask_info = _take_preprocess_indexer_and_fill_value(
  File "/home/stefan/.pyenv/versions/pd_bug/lib/python3.9/site-packages/pandas/core/array_algos/take.py", line 587, in _take_preprocess_indexer_and_fill_value
    dtype, fill_value = arr.dtype, arr.dtype.type()
TypeError: void() takes exactly 1 positional argument (0 given)
```

### Expected Behavior

Before 1.4.0, the output of the same code shows that the `recarray` has `dtype` `object` and the `unstack` does not throw an error:

```
a     int64
b    object
c    object
dtype: object
        c                
b       A       B       C
a                        
0  (2.0,)  (2.0,)  (2.0,)
1  (2.0,)  (2.0,)  (2.0,)
2  (2.0,)  (2.0,)  (2.0,)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.9.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-52-generic
Version          : #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3
Cython           : 0.29.32
pytest           : 6.2.5
hypothesis       : None
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.1
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : 1.4.42
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by topper-123** [comment]
Yes. I can confirm this error.

Also, just printing you original dataframe gives an error also:

```python
import numpy as np
import pandas as pd

c = np.array([2] * 20, dtype='f8')
r = np.rec.fromarrays([c], names=['c'])

df = pd.DataFrame({'a': np.arange(20) // 5, 'b': list('ABCDE') * 4, 'c': r})
print(df)
```

gives error:

```
TypeError                                 Traceback (most recent call last)
/opt/homebrew/Caskroom/miniconda/base/envs/pandas/lib/python3.9/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/homebrew/Caskroom/miniconda/base/envs/pandas/lib/python3.9/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)

/opt/homebrew/Caskroom/miniconda/base/envs/pandas/lib/python3.9/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/python/pandas-dev/pandas/pandas/core/frame.py in __repr__(self)
   1084
   1085         repr_params = fmt.get_dataframe_repr_params()
-> 1086         return self.to_string(**repr_params)
   1087
   1088     def _repr_html_(self) -> str | None:

~/python/pandas-dev/pandas/pandas/core/frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, max_rows, max_cols, show_dimensions, decimal, line_width, min_rows, max_colwidth, encoding)
   1265                 decimal=decimal,
   1266             )
-> 1267             return fmt.DataFrameRenderer(formatter).to_string(
   1268                 buf=buf,
   1269                 encoding=encoding,

~/python/pandas-dev/pandas/pandas/io/formats/format.py in to_string(self, buf, encoding, line_width)
   1134
   1135         string_formatter = StringFormatter(self.fmt, line_width=line_width)
-> 1136         string = string_formatter.to_string()
   1137         return save_to_buffer(string, buf=buf, encoding=encoding)
   1138

~/python/pandas-dev/pandas/pandas/io/formats/string.py in to_string(self)
     28
     29     def to_string(self) -> str:
---> 30         text = self._get_string_representation()
     31         if self.fmt.should_show_dimensions:
     32             text = "".join([text, self.fmt.dimensions_info])

~/python/pandas-dev/pandas/pandas/io/formats/string.py in _get_string_representation(self)
     43             return self._empty_info_line
     44
---> 45         strcols = self._get_strcols()
     46
     47         if self.line_width is None:

~/python/pandas-dev/pandas/pandas/io/formats/string.py in _get_strcols(self)
     34
     35     def _get_strcols(self) -> list[list[str]]:
---> 36         strcols = self.fmt.get_strcols()
     37         if self.fmt.is_truncated:
     38             strcols = self._insert_dot_separators(strcols)

~/python/pandas-dev/pandas/pandas/io/formats/format.py in get_strcols(self)
    615         Render a DataFrame to a list of columns (as lists of strings).
    616         """
--> 617         strcols = self._get_strcols_without_index()
    618
    619         if self.index:

~/python/pandas-dev/pandas/pandas/io/formats/format.py in _get_strcols_without_index(self)
    881                 int(self.col_space.get(c, 0)), *(self.adj.len(x) for x in cheader)
    882             )
--> 883             fmt_values = self.format_col(i)
    884             fmt_values = _make_fixed_width(
    885                 fmt_values, self.justify, minimum=header_colwidth, adj=self.adj

~/python/pandas-dev/pandas/pandas/io/formats/format.py in format_col(self, i)
    895         frame = self.tr_frame
    896         formatter = self._get_formatter(i)
--> 897         return format_array(
    898             frame.iloc[:, i]._values,
    899             formatter,

~/python/pandas-dev/pandas/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal, leading_space, quoting)
   1326     )
   1327
-> 1328     return fmt_obj.get_result()
   1329
   1330

~/python/pandas-dev/pandas/pandas/io/formats/format.py in get_result(self)
   1357
   1358     def get_result(self) -> list[str]:
-> 1359         fmt_values = self._format_strings()
   1360         return _make_fixed_width(fmt_values, self.justify)
   1361

~/python/pandas-dev/pandas/pandas/io/formats/format.py in _format_strings(self)
   1411             inferred
   1412             # vals may have 2 or more dimensions
-> 1413             & np.all(notna(vals), axis=tuple(range(1, len(vals.shape))))
   1414         )
   1415         leading_space = self.leading_space

~/python/pandas-dev/pandas/pandas/core/dtypes/missing.py in notna(obj)
    432     Name: 1, dtype: bool
    433     """
--> 434     res = isna(obj)
    435     if isinstance(res, bool):
    436         return not res

~/python/pandas-dev/pandas/pandas/core/dtypes/missing.py in isna(obj)
    183     Name: 1, dtype: bool
    184     """
--> 185     return _isna(obj)
    186
    187

~/python/pandas-dev/pandas/pandas/core/dtypes/missing.py in _isna(obj, inf_as_na)
    212         return False
    213     elif isinstance(obj, (np.ndarray, ABCExtensionArray)):
--> 214         return _isna_array(obj, inf_as_na=inf_as_na)
    215     elif isinstance(obj, ABCIndex):
    216         # Try to use cached isna, which also short-circuits for integer dtypes

~/python/pandas-dev/pandas/pandas/core/dtypes/missing.py in _isna_array(values, inf_as_na)
    302             result = ~np.isfinite(values)
    303         else:
--> 304             result = np.isnan(values)
    305
    306     return result

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Want to take a stab at this, @stefan-jansen?

**Comment by jbrockmendel** [comment]
i dont think we support record-dtypes.  these should be cast somewhere along the way

**Comment by topper-123** [comment]
Ok, thanks, makes sense several errors pop up then, when using them:-).

I see instantiating Series using recarrays gives an error:

```ipython
In [1]:  r = np.rec.fromarrays([c], names=['c'])
In [2]: pd.Series(r)
ValueError: Cannot construct a Series from an ndarray with compound dtype.  Use DataFrame instead.
```

The case with `pd.DataFrame({'c': r})` should logically give a similar error, so I say OP's example should have raised in the DataFrame construction.

**Comment by topper-123** [comment]
Close temporarily.

**Comment by topper-123** [comment]
Looking further, we can't use dataframes (a multidim object) as single columns in a dataframe:

```python
In [1]: df = pd.DataFrame({"a": "a b a b".split(), "b": range(4)})
In [2]: pd.DataFrame({"a": df}, index=df.index)
ValueError: Data must be 1-dimensional
``` 

IMO we should disallow single columns being constructed from multidim object like recarrays and DataFrames, in order to keep things consistent.

@jbrockmendel, do you agree?
