### ISSUE TITLE
BUG: dictionary groupby aggregation fails in case duplicated MultiIndex values are in columns

### ISSUE THREAD

**Issue by dchigarev** [pandas-dev/pandas#50402]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas

df = pandas.DataFrame(
    [[1, 2, 3], [4, 5, 6]],
    columns=pandas.MultiIndex.from_tuples([("a", 0), ("b", 0), ("b", 1)]),
)

res = df.groupby(by=[1, 2]).agg({("a", 0): "sum"})  # works fine
print(res)

df.columns = pandas.MultiIndex.from_tuples([("a", 0), ("b", 0), ("b", 0)])
res = df.groupby(by=[1, 2]).agg(
    {("a", 0): "sum"}
)  # AttributeError: 'Series' object has no attribute 'columns'
print(res)
```

### Issue Description

<details><summary>Reproducer's traceback</summary>

```python-traceback
Traceback (most recent call last):
  File "t2.py", line 12, in <module>
    res = df.groupby(by=[1, 2]).agg({("a", 0): "sum"}) # AttributeError: 'Series' object has no attribute 'columns'
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 894, in aggregate
    result = op.agg()
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/apply.py", line 169, in agg
    return self.agg_dict_like()
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/apply.py", line 486, in agg_dict_like
    results = {
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/apply.py", line 487, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 275, in aggregate
    return getattr(self, func)(*args, **kwargs)
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 2425, in sum
    result = self._agg_general(
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1683, in _agg_general
    result = self._cython_agg_general(
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1743, in _cython_agg_general
    numeric_only_bool = self._resolve_numeric_only(how, numeric_only, axis=0)
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1347, in _resolve_numeric_only
    if len(obj.columns) and not len(check.columns) and not obj.empty:
  File "/localdisk/dchigare/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'columns'
```

</details>

### Expected Behavior

Groupby on a frame with duplicated non-MultiIndex values works fine, I would expect the MultiIndex case to work the same.
```python
import pandas

df = pandas.DataFrame(
    [[1, 2, 3], [4, 5, 6]],
    columns=pandas.Index(["a", "b", "b"]),
)

res = df.groupby(by=[1, 2]).agg({"a": "sum"})  # works fine
print(res)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-124-generic
Version          : #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.4.1
pip              : 22.2.2
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : 5.3.0
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           :
fastparquet      : 0.8.3
fsspec           : 2022.8.2
gcsfs            : None
matplotlib       : 3.3.0
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.8.2
scipy            : 1.9.1
snappy           : None
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : None
xarray           : 2022.9.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! Likely this is due to differences in results when a MultiIndex has duplicates in DataFrame:

```
df = pd.DataFrame({'a': [1, 1, 2, 2], 'b': [3, 4, 5, 5], 'c': range(4)}).set_index(['a', 'b'])
print(df.loc[1, 3])
#      c
# a b   
# 1 3  0

df = pd.DataFrame({'a': [1, 1, 2, 2], 'b': [3, 4, 5, 6], 'c': range(4)}).set_index(['a', 'b'])
print(df.loc[1, 3])
# c    0
# Name: (1, 3), dtype: int64
```

Agreed this behavior should be handled internally. Further investigations and PRs to fix are welcome!

**Comment by jrdunson2** [comment]
Hey - can anyone help? I have a dataframe where all the columns are objects... (except one a object that I converted to a datetime): 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   jobid              96 non-null     object        
 1   emailname          96 non-null     object        
 2   dataextensionname  96 non-null     object        
 3   mwemailname        96 non-null     object        
 4   subjectline        96 non-null     object        
 5   campaignids        96 non-null     object        
 6   campaignid1        96 non-null     object        
 7   campaignid2        96 non-null     object        
 8   campaignid3        96 non-null     object        
 9   campaignid4        96 non-null     object        
 10  campaignid5        96 non-null     object        
 11  department         96 non-null     object        
 12  emailtype          96 non-null     object        
 13  sentdate           96 non-null     datetime64[ns]
 14  src                96 non-null     object  

... I have no floats64 columns... 

and yet, I still get the message: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first. 
  df.fillna('', inplace=True) #-- Removes 'NaN' values 

I have already run the command: f.fillna('', inplace=True) #-- Removes 'NaN' values (and this doesn't help)

and still get the warning.   I have spent several hours just trying to get around this... and can find no help on google ... 

Thanks
 Jarrell
