### ISSUE TITLE
BUG: resample don't work with non-nanosecond reso

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50656]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
dti = DatetimeIndex([np.datetime64('1750-01-01', 'ns'), np.datetime64('1750-01-03', 'ns')])
ser = Series([1, 2], index=dti)
print(ser.resample('D').sum())

dti = DatetimeIndex([np.datetime64('1750-01-01', 's'), np.datetime64('1750-01-03', 's')])
ser = Series([1, 2], index=dti)
print(ser.resample('D').sum())
```

### Issue Description

The non-nano one throws 
```
Traceback (most recent call last):
  File "/home/marcogorelli/pandas-dev/t.py", line 19, in <module>
    print(ser.resample('D').sum())
          ^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/series.py", line 5608, in resample
    return super().resample(
           ^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/generic.py", line 8687, in resample
    return get_resampler(
           ^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 1503, in get_resampler
    return tg._get_resampler(obj, kind=kind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 1661, in _get_resampler
    return DatetimeIndexResampler(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 168, in __init__
    self.binner, self.grouper = self._get_binner()
                                ^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 255, in _get_binner
    binner, bins, binlabels = self._get_binner_for_time()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 1235, in _get_binner_for_time
    return self.groupby._get_time_bins(self.ax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/pandas-dev/pandas/core/resample.py", line 1724, in _get_time_bins
    bins = lib.generate_bins_dt64(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 848, in pandas._libs.lib.generate_bins_dt64
    raise ValueError("Values falls after last bin")
ValueError: Values falls after last bin
```

### Expected Behavior

```
1750-01-01    1
1750-01-02    0
1750-01-03    2
Freq: D, dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 1d634743215b3eba4f15d458267b8f0ba4571e47
python           : 3.11.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+1132.g1d63474321.dirty
numpy            : 1.25.0.dev0+319.g46142454e
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.2.0
hypothesis       : 6.52.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
None

</details>

**Comment by MarcoGorelli** [comment]
I think is just a matter of adding `as_unit` here

https://github.com/pandas-dev/pandas/blob/6b10bb875add0030e95b33869e974150dec78670/pandas/core/resample.py#L1710-L1718

? I'll make a PR soon-ish
