### ISSUE TITLE
BUG: to_datetime with mixed iso-str and ints

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#50721]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
objs = ["2016-01-01 01:02:03+05:00", "2016-01-01 01:02:03+06:00", 0]

pd.to_datetime(objs)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/tools/datetimes.py", line 1077, in to_datetime
    result = convert_listlike(argc, format)
  File "pandas/core/tools/datetimes.py", line 449, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File "pandas/core/tools/datetimes.py", line 480, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "pandas/_libs/tslibs/strptime.pyx", line 513, in pandas._libs.tslibs.strptime.array_strptime
    raise
  File "pandas/_libs/tslibs/strptime.pyx", line 342, in pandas._libs.tslibs.strptime.array_strptime
    raise ValueError(f"time data \"{val}\" doesn't "
ValueError: time data "0" doesn't match format "%Y-%m-%d %H:%M:%S%z", at position 2
```

### Issue Description

cc @MarcoGorelli 

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by MarcoGorelli** [comment]
thanks! will address

**Comment by jbrockmendel** [comment]
If it isn't addressed before then, this will be closeable in 3.0 when the deprecated _array_to_datetime_object path is removed.

**Comment by mroeschke** [comment]
Looks like `_array_to_datetime_object` has been removed so I suppose we can close this
