### ISSUE TITLE
BUG:  Various pandas.api.types.is_*_dtype functions fail with ExtensionDtype as an argument

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#50923]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas.api.types import (
    is_object_dtype,
    is_datetime64_dtype,
    is_datetime64tz_dtype,
    is_timedelta64_dtype,
    is_period_dtype,
    is_interval_dtype,
    is_categorical_dtype,
    is_string_dtype,
    is_integer_dtype,
    is_signed_integer_dtype,
    is_unsigned_integer_dtype,
    is_int64_dtype,
    is_datetime64_any_dtype,
    is_datetime64_ns_dtype,
    is_timedelta64_ns_dtype,
    is_numeric_dtype,
    is_float_dtype,
    is_bool_dtype,
    is_extension_array_dtype,
    is_complex_dtype,
)

from pandas.core.dtypes.dtypes import ExtensionDtype

trylist = [
    is_object_dtype,
    is_datetime64_dtype,
    is_datetime64tz_dtype,
    is_timedelta64_dtype,
    is_period_dtype,
    is_interval_dtype,
    is_categorical_dtype,
    is_string_dtype,
    is_integer_dtype,
    is_signed_integer_dtype,
    is_unsigned_integer_dtype,
    is_int64_dtype,
    is_datetime64_any_dtype,
    is_datetime64_ns_dtype,
    is_timedelta64_ns_dtype,
    is_numeric_dtype,
    is_float_dtype,
    is_bool_dtype,
    is_extension_array_dtype,
    is_complex_dtype,
]

for isfunc in trylist:
    name = isfunc.__name__

    try:
        isfunc(ExtensionDtype)
        print("   OK ", name)
    except Exception:
        print("FAILS ", name)
```

### Issue Description

There is an inconsistency in whether the `is_*_dtype()` methods accept `ExtensionDtype` as a parameter.

Results of above code:
```text
FAILS  is_object_dtype
FAILS  is_datetime64_dtype
   OK  is_datetime64tz_dtype
FAILS  is_timedelta64_dtype
   OK  is_period_dtype
   OK  is_interval_dtype
   OK  is_categorical_dtype
   OK  is_string_dtype
FAILS  is_integer_dtype
FAILS  is_signed_integer_dtype
FAILS  is_unsigned_integer_dtype
FAILS  is_int64_dtype
FAILS  is_datetime64_any_dtype
   OK  is_datetime64_ns_dtype
   OK  is_timedelta64_ns_dtype
FAILS  is_numeric_dtype
FAILS  is_float_dtype
   OK  is_bool_dtype
   OK  is_extension_array_dtype
FAILS  is_complex_dtype
```

Discovered as a result of trying to fix a reported pandas-stubs issue https://github.com/pandas-dev/pandas-stubs/issues/514

### Expected Behavior

All of those methods should accept `ExtensionDtype` (and any subclasses of that type) as a parameter

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.1.0
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.7
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : 1.2.0
pyxlsb           : 1.0.10
s3fs             : None
scipy            : 1.10.0
snappy           : None
sqlalchemy       : 1.4.45
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.1.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by JustinAmstadt** [comment]
take

**Comment by JustinAmstadt** [comment]
Update:

This is the error and stack I'm getting when I call one of the broken functions:

```
Traceback (most recent call last):
  File "/home/justin/VSCode/pandas/justin_test/issue50923.py", line 58, in <module>
    print(is_float_dtype(ExtensionDtype))
  File "/home/justin/.local/lib/python3.10/site-packages/pandas/core/dtypes/common.py", line 1271, in is_float_dtype
    return _is_dtype_type(arr_or_dtype, classes(np.floating))
  File "/home/justin/.local/lib/python3.10/site-packages/pandas/core/dtypes/common.py", line 1610, in _is_dtype_type
    return condition(np.dtype(arr_or_dtype).type)
TypeError: Cannot interpret '<property object at 0x7fa5bc35b3d0>' as a data type
```

It seems like some if not all functions are calling 
```
def _is_dtype_type(arr_or_dtype, condition) -> bool:
```

and it is breaking at these four lines:
```
    elif isinstance(arr_or_dtype, type):
        if issubclass(arr_or_dtype, ExtensionDtype):
            arr_or_dtype = arr_or_dtype.type
        return condition(np.dtype(arr_or_dtype).type)
```

When the arr_or_dtype = arr_or_dtype.type is called, the type changes from 
```
<class 'pandas.core.dtypes.base.ExtensionDtype'>
```
to
```
<property object at 0x7fa3caf9f1f0>
```

When that line is not called, the type stays the same and the function returns
```
<class 'numpy.object_'>
```
instead

I frankly do not really understand what is going on here and what these functions do. I would be extremely grateful if you have more information on these functions.

**Comment by Dr-Irv** [comment]
> if issubclass(arr_or_dtype, ExtensionDtype):
>             arr_or_dtype = arr_or_dtype.type

I think the issue is as follows.  `ExtensionDtype` is an abstract class.  As such, the value of `ExtensionDtype.type` is a property.  But if you have a subclass of `ExtensionDtype`, e.g., `CategoricalDtype`, then `type` will be an actual type.

So I think the test should be:
```python
if isinstance(arr_or_dtype, ExtensionDtype):
    return False
elif  issubclass(arr_or_dtype, ExtensionDtype):
    arr_or_dtype = arr_or_dtype.type
return condition(np.dtype(arr_or_dtype).type)
```

I'm not 100% sure that will work, but give that a try, and create appropriate tests for each of the `is_*_dtype()` methods where you test `ExtensionDtype`, `CategoricalDtype` and `BoolDtype` .  The latter two are subclasses of `ExtensionDtype` .

**Comment by Dr-Irv** [comment]
By the way, if you really want to be complete with a fix for this, adding tests for all of the following types for each of the `is_*_dtype()` methods would be helpful (and probably will uncover some related issues):
```python
ArrowDtype
BooleanDtype
FloatingDtype
Float32Dtype
Float64Dtype
IntegerDtype
Int8Dtype
Int16Dtype
Int32Dtype
Int64Dtype
UInt8Dtype
UInt16Dtype
UInt32Dtype
UInt64Dtype
NumericDtype
SparseDtype
StringDtype
ExtensionDtype:
StorageExtensionDtype
CategoricalDtype
DatetimeTZDtype
PeriodDtype
IntervalDtype
```
For example, I tested `is_float_dtype(FloatingDtype)` and that also fails, so that method needs some logic similar to what is in `is_bool_dtype()`.

**Comment by JustinAmstadt** [comment]
I fell pretty ill today, so I'm going to keep tabs on this issue, but open it up for someone else to work on it. If nobody has worked on it after I feel well enough to sit at my computer, I'll start up again.

**Comment by oayala65** [comment]
Something is wrong..!!
When an array has string, int, float, NaN, etc it is called "object".
The expression pandas.api.types.is_string_dtype(arr_or_dtype) , check whether the provided array or dtype is of the string dtype.
"If an array is passed with an object dtype, the elements must be inferred as strings."

From the pandas manual.

Currently if an array has different data types and trying to check them with pandas.api.types.is_string_dtype( ) it will give the message "False".
That is, it does not work according to the pandas manual.

I hope it is resolved soon.!!!!
