### ISSUE TITLE
BUILD: 

### ISSUE THREAD

**Issue by boxblox** [pandas-dev/pandas#51673]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-10.16-x86_64-i386-64bit

### Installation Method

pip install

### pandas Version

2.0.0rc0

### Python Version

3.10.9

### Installation Logs

`pip` process seems successful....

```
(test)[adam: pandas](main)$ python -m pip install --upgrade --pre pandas==2.0.0rc0 --no-cache
Collecting pandas==2.0.0rc0
  Downloading pandas-2.0.0rc0-cp310-cp310-macosx_10_9_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 8.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/adam/miniconda3/envs/test/lib/python3.10/site-packages (from pandas==2.0.0rc0) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Users/adam/miniconda3/envs/test/lib/python3.10/site-packages (from pandas==2.0.0rc0) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in /Users/adam/miniconda3/envs/test/lib/python3.10/site-packages (from pandas==2.0.0rc0) (2022.7.1)
Requirement already satisfied: six>=1.5 in /Users/adam/miniconda3/envs/test/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas==2.0.0rc0) (1.16.0)
Installing collected packages: pandas
Successfully installed pandas-2.0.0rc0
```

... but cannot `import pandas as pd` without a `ModuleNotFoundError`

```
(test)[adam: pandas](main)$ python -c "import pandas as pd"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/adam/Projects/pandas/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/Users/adam/Projects/pandas/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/Users/adam/Projects/pandas/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/Users/adam/Projects/pandas/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/Users/adam/Projects/pandas/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/Users/adam/Projects/pandas/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
ModuleNotFoundError: No module named 'pandas._libs.interval'
```

**Comment by boxblox** [comment]
lame-o mistake on my end.

**Comment by MarcoGorelli** [comment]
> lame-o mistake on my end.

could you share your mistake so it helps other who end up here please?

**Comment by boxblox** [comment]
my current directory was `pandas` (my clone of the repo) so I was importing locally... instead of from my environment.  needed to step out of the directory and do the import.  all good now.
