### ISSUE TITLE
DOC:fix EX02 plot.line and parallel_coordinates

### ISSUE THREAD

**Issue by zgdjcls** [pandas-dev/pandas#51696]
Hi I'm going to work on:
`pandas.plotting.parallel_coordinates`
and
`pandas.DataFrame.plot.line`

_Originally posted by @zgdjcls in https://github.com/pandas-dev/pandas/issues/51236#issuecomment-1444250238_
But when I run the docstrings I got this error:
Partially validate docstrings (EX02)
<doctest pandas.Series.xs[5]>:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.xs(('mammal', 'dog'))
Traceback (most recent call last):
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 494, in <module>
    main(
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 429, in main
    return print_validate_all_results(
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 373, in print_validate_all_results
    result = validate_all(prefix, ignore_deprecated, ignore_functions)
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 329, in validate_all
    for func_name, _, section, subsection in get_all_api_items():
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 360, in get_all_api_items
    yield from get_api_items(f)
  File "/Users/zhengyiming/Desktop/pandas/./ci/../scripts/validate_docstrings.py", line 137, in get_api_items
    func = getattr(func, part)
AttributeError: type object 'CombinedDatetimelikeProperties' has no attribute 'unit'
Partially validate docstrings (EX02) DONE

I'm not sure why it says 'CombinedDatetimelikeProperties' has no attribute 'unit', is this my environment issue? How should I fix this

**Comment by MarcoGorelli** [comment]
Hi - my guess is that you didn't follow everything in https://pandas.pydata.org/docs/dev/development/contributing_environment.html ?

**Comment by MarcoGorelli** [comment]
closing as per https://github.com/pandas-dev/pandas/issues/51236#issuecomment-1448961676
