### ISSUE TITLE
BUG: Overflow behavior differs between numpy types and arrow dtypes

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#52024]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
a_pa = pd.Series([127], dtype="int8[pyarrow]")
b_pa = pd.Series([127], dtype="int8[pyarrow]")

a_pa + b_pa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ps_0310_is\lib\site-packages\pandas\core\ops\common.py", line 81, in new_method
    return method(self, other)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\series.py", line 6071, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\base.py", line 1345, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\ops\array_ops.py", line 217, in arithmetic_op
    res_values = op(left, right)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\ops\common.py", line 81, in new_method
    return method(self, other)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\arrays\arrow\array.py", line 505, in _arith_method
    return self._evaluate_op_method(other, op, ARROW_ARITHMETIC_FUNCS)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\arrays\arrow\array.py", line 490, in _evaluate_op_method
    result = pc_func(self._data, other._data)
  File "C:\ps_0310_is\lib\site-packages\pyarrow\compute.py", line 239, in wrapper
    return func.call(args, None, memory_pool)
  File "pyarrow\_compute.pyx", line 355, in pyarrow._compute.Function.call
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: overflow
```

### Issue Description

Using arrow types, this operation overflows, when using numpy, the bits that do not fit in the resulting dtype are dropped (by default). Is this difference in default behavior between numpy types and arrow types intentional? Is there a flag to control this behavior.

### Expected Behavior

I expect same behavior as numpy, where the higher order bits are discarded instead of an overflow:

a_np = pd.Series([127], dtype="int8")
b_np = pd.Series([127], dtype="int8")
>>> a_np + b_np
0   -2
dtype: int8

### Installed Versions

<details>

>>> pd.show_versions()
C:\ps_0310_is\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 1a2e300170efc08cb509a0b4ff6248f8d55ae777
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.0rc0
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.2.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
</details>

**Comment by jbrockmendel** [comment]
> Is this difference in default behavior between numpy types and arrow types intentional? 

Yes

> Is there a flag to control this behavior.

No

**Comment by rohanjain101** [comment]
Sounds like this can just be closed then as there's no issue. Is there a plan to add a flag to control overflow behavior with an arrow backend? As I believe numpy exposes that as a setting.

**Comment by jbrockmendel** [comment]
Let's keep the issue open, as I expect something similar to come up frequently for a while

**Comment by jbrockmendel** [comment]
My hypothesis that this would come up frequently didn't pan out.  Closing.
