### ISSUE TITLE
BUG: Can't compute cummin/cummax on ordered categorical

### ISSUE THREAD

**Issue by alexklapheke** [pandas-dev/pandas#52335]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> s = pd.Series(list("ababca"), dtype=pd.CategoricalDtype(list("abc"), ordered=True))
>>> s
0    a
1    b
2    a
3    b
4    c
5    a
dtype: category
Categories (3, object): ['a' < 'b' < 'c']

Independently:

>>> s.max()
'c'
>>> s.cummax()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 11673, in cummax
    return NDFrame.cummax(self, axis, skipna, *args, **kwargs)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 11253, in cummax
    return self._accum_func(
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 11248, in _accum_func
    result = self._mgr.apply(block_accum_func)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 350, inapply
    applied = b.apply(f, **kwargs)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 328, in apply
    result = func(self.values, **kwargs)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 11241, in block_accum_func
    result = values._accumulate(name, skipna=skipna, **kwargs)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/arrays/base.py", line 1406, in _accumulate
    raise NotImplementedError(f"cannot perform {name} with type {self.dtype}")
NotImplementedError: cannot perform cummax with type category

Within a groupby:

>>> t = pd.Series([1, 2, 1, 2, 1, 2])
>>> s.groupby(t).max()
1    c
2    b
dtype: category
Categories (3, object): ['a' < 'b' < 'c']
>>> s.groupby(t).cummax()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 3665, in cummax
    return self._cython_transform(
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 497, in _cython_transform
    result = self.grouper._cython_operation(
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 1005, in _cython_operation
    return cy_op.cython_operation(
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 718, in cython_operation
    self._disallow_invalid_ops(values.dtype)
  File "/home/alex/Downloads/pandas/venv/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 264, in _disallow_invalid_ops
    raise TypeError(f"{dtype} type does not support {how} operations")
TypeError: category type does not support cummax operations
```

### Issue Description

Calling `.min()`/`.max()` on an ordered categorical works as expected, but calling `.cummin()`/`.cummax()` raises `NotImplementedError`. Would expect output similar to that of `pd.Categorical.from_codes(s.cat.codes.cummax(), categories=s.cat.categories)`.

### Expected Behavior

Independently:

```
0    a
1    b
2    b
3    b
4    c
5    c
dtype: category
Categories (3, object): ['a' < 'b' < 'c']
```

Within a groupby:

```
0    a
1    b
2    a
3    b
4    c
5    b
dtype: category
Categories (3, object): ['a' < 'b' < 'c']
```

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit           : ceef0da443a7bbb608fb0e251f06ae43a809b472
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.2.8-arch1-1
Version          : #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+368.gceef0da443
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
```

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. The error raise is `NotImplementedError`, so I think this is an enhancement rather than a bug. +1 on supporting.

**Comment by rmhowe425** [comment]
take

**Comment by bdwzhangumich** [comment]
take
