### ISSUE TITLE
BUILD: Failed to install on MacOS M2 Chip

### ISSUE THREAD

**Issue by newTypeGeek** [pandas-dev/pandas#52643]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Darwin-22.3.0-arm64-arm-64bit

### Installation Method

pip install

### pandas Version

1.2.5

### Python Version

3.7

### Installation Logs

2023-04-13T12:53:59,712 Collecting pandas~=1.2.5
2023-04-13T12:53:59,712   Created temporary directory: /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-unpack-lgp490wz
2023-04-13T12:53:59,732   Using cached pandas-1.2.5.tar.gz (5.5 MB)
2023-04-13T12:54:00,046   Added pandas~=1.2.5 from https://files.pythonhosted.org/packages/ab/5c/b38226740306fd73d0fea979d10ef0eda2c7956f4b59ada8675ec62edba7/pandas-1.2.5.tar.gz to build tracker '/private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-tracker-m_6778gl'
2023-04-13T12:54:00,049   Created temporary directory: /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2
2023-04-13T12:54:00,050   Running command pip subprocess to install build dependencies
2023-04-13T12:54:00,181   Using pip 23.0.1 from /Users/bennytam/.pyenv/versions/test-3.7/lib/python3.11/site-packages/pip (python 3.11)
2023-04-13T12:54:00,192   Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
2023-04-13T12:54:00,192   Ignoring numpy: markers 'python_version == "3.8" and platform_system != "AIX"' don't match your environment
2023-04-13T12:54:00,193   Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
2023-04-13T12:54:00,193   Ignoring numpy: markers 'python_version == "3.8" and platform_system == "AIX"' don't match your environment
2023-04-13T12:54:00,420   Collecting setuptools
2023-04-13T12:54:00,422     Using cached setuptools-67.6.1-py3-none-any.whl (1.1 MB)
2023-04-13T12:54:00,464   Collecting wheel
2023-04-13T12:54:00,466     Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
2023-04-13T12:54:00,689   Collecting Cython<3,>=0.29.21
2023-04-13T12:54:00,692     Using cached Cython-0.29.34-py2.py3-none-any.whl (988 kB)
2023-04-13T12:54:00,773     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,774     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/5f/d6/ad58ded26556eaeaa8c971e08b6466f17c4ac4d786cd3d800e26ce59cc01/numpy-1.21.3.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,774     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,775     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,776     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,881     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,882     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/5f/d6/ad58ded26556eaeaa8c971e08b6466f17c4ac4d786cd3d800e26ce59cc01/numpy-1.21.3.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,883     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,884     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,884     Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
2023-04-13T12:54:00,898   Collecting numpy
2023-04-13T12:54:00,907     Using cached numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
2023-04-13T12:54:00,980   Installing collected packages: wheel, setuptools, numpy, Cython
2023-04-13T12:54:01,002     Creating /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin
2023-04-13T12:54:01,002     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/wheel to 755
2023-04-13T12:54:02,118     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/f2py to 755
2023-04-13T12:54:02,119     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/f2py3 to 755
2023-04-13T12:54:02,119     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/f2py3.11 to 755
2023-04-13T12:54:02,383     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/cygdb to 755
2023-04-13T12:54:02,383     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/cython to 755
2023-04-13T12:54:02,383     changing mode of /private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-build-env-5r273mf2/overlay/bin/cythonize to 755
2023-04-13T12:54:02,387   Successfully installed Cython-0.29.34 numpy-1.24.2 setuptools-67.6.1 wheel-0.40.0
2023-04-13T12:54:02,546   Running command Getting requirements to build wheel

// ... skip .... 

2023-04-13T13:03:43,253     Running setup.py install for numpy: finished with status 'error'
2023-04-13T13:03:43,254   error: legacy-install-failure

2023-04-13T13:03:43,254   × Encountered error while trying to install package.
2023-04-13T13:03:43,254   ╰─> numpy

2023-04-13T13:03:43,254   note: This is an issue with the package mentioned above, not pip.
2023-04-13T13:03:43,254   hint: See above for output from the failure.
2023-04-13T13:03:43,258   WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
2023-04-13T13:03:43,258   You should consider upgrading via the '/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/bin/python3.7 -m pip install --upgrade pip' command.
2023-04-13T13:03:43,377   ERROR: [present-diagnostic] pip subprocess to install build dependencies exited with 1
// ... skip ...
2023-04-13T13:03:43,380 ERROR: [present-diagnostic] pip subprocess to install build dependencies exited with 1
2023-04-13T13:03:43,381 Exception information:
2023-04-13T13:03:43,381 Traceback (most recent call last):
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
2023-04-13T13:03:43,381     status = run_func(*args)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
2023-04-13T13:03:43,381     return func(self, options, args)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 340, in run
2023-04-13T13:03:43,381     reqs, check_supported_wheels=not options.target_dir
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
2023-04-13T13:03:43,381     collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
2023-04-13T13:03:43,381     state = resolution.resolve(requirements, max_rounds=max_rounds)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
2023-04-13T13:03:43,381     self._add_to_criteria(self.state.criteria, r, parent=None)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
2023-04-13T13:03:43,381     if not criterion.candidates:
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
2023-04-13T13:03:43,381     return bool(self._sequence)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
2023-04-13T13:03:43,381     return any(self)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
2023-04-13T13:03:43,381     return (c for c in iterator if id(c) not in self._incompatible_ids)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
2023-04-13T13:03:43,381     candidate = func()
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 220, in _make_candidate_from_link
2023-04-13T13:03:43,381     version=version,
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 294, in __init__
2023-04-13T13:03:43,381     version=version,
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
2023-04-13T13:03:43,381     self.dist = self._prepare()
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
2023-04-13T13:03:43,381     dist = self._prepare_distribution()
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
2023-04-13T13:03:43,381     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
2023-04-13T13:03:43,381     return self._prepare_linked_requirement(req, parallel_builds)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 560, in _prepare_linked_requirement
2023-04-13T13:03:43,381     self.build_isolation,
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
2023-04-13T13:03:43,381     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 35, in prepare_distribution_metadata
2023-04-13T13:03:43,381     self._prepare_build_backend(finder)
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 57, in _prepare_build_backend
2023-04-13T13:03:43,381     finder, pyproject_requires, "overlay", kind="build dependencies"
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/build_env.py", line 207, in install_requirements
2023-04-13T13:03:43,381     kind=kind,
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/build_env.py", line 264, in _install_requirements
2023-04-13T13:03:43,381     extra_environ=extra_environ,
2023-04-13T13:03:43,381   File "/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
2023-04-13T13:03:43,381     raise error
2023-04-13T13:03:43,381 pip._internal.exceptions.InstallationSubprocessError: pip subprocess to install build dependencies exited with 1
2023-04-13T13:03:43,384 WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
2023-04-13T13:03:43,384 You should consider upgrading via the '/Users/bennytam/.pyenv/versions/3.7.16/envs/test-3.7/bin/python3.7 -m pip install --upgrade pip' command.
2023-04-13T13:03:43,384 Removed pandas~=1.2.5 from https://files.pythonhosted.org/packages/ab/5c/b38226740306fd73d0fea979d10ef0eda2c7956f4b59ada8675ec62edba7/pandas-1.2.5.tar.gz#sha256=14abb8ea73fce8aebbb1fb44bec809163f1c55241bcc1db91c2c780e97265033 from build tracker '/private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-req-tracker-i0_jzo88'
2023-04-13T13:03:43,384 Removed build tracker: '/private/var/folders/f5/xsvjkjj94pvffy49nk5wm5qsrqq7f6/T/pip-req-tracker-i0_jzo88'

**Comment by phofl** [comment]
Hi, we don't have wheels before 1.3 for Apple silicone.

We don't support these versions anymore, so only suggestion I can give is upgrading or fixing the errors yourself
