### ISSUE TITLE
User-facing AssertionError with groupby on list of empty list.

### ISSUE THREAD

**Issue by jtratner** [pandas-dev/pandas#5289]
I hesitate to post this, but grouping on a list of empty list yields an AssertionError. It's so edge case I'm not sure it's worth bring up though:

``` python
df = pd.DataFrame(zip(range(10), range(10)), columns=['apple', 'b'])
df.groupby([[]])
# Long traceback yields: AssertionError: Grouper and axis must be same length
```

Came from this SO issue (but it's really only related because of the error message) - http://stackoverflow.com/questions/19483991/how-to-make-grouper-and-axis-the-same-length

**Comment by simonjayhawkins** [comment]
this issue can be closed.

original code sample raises `ValueError` on 0.25.0.dev0+208.g74a9ae309

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\generic.py", line 7672, in groupby
    observed=observed, **kwargs)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\groupby\groupby.py", line 2206, in groupby
    return klass(obj, by, **kwds)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\groupby\groupby.py", line 363, in __init__
    mutated=self.mutated)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\groupby\grouper.py", line 605, in _get_grouper
    if not isinstance(gpr, Grouping) else gpr)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\groupby\grouper.py", line 242, in __init__
    self.grouper = _convert_grouper(index, grouper)
  File "C:\Users\simon\OneDrive\code\pandas-simonjayhawkins\pandas\core\groupby\grouper.py", line 632, in _convert_grouper
    raise ValueError('Grouper and axis must be same length')
ValueError: Grouper and axis must be same length
```

**Comment by simonjayhawkins** [comment]
> this issue can be closed.

although there is no coverage. maybe we should add a test first.
