### ISSUE TITLE
BUG: Assigning Categorical to parts of column hangs indefinitely

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#52927]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame({"a": [1, 1, 1, 1, 1], "b": ["a", "a", "a", "a", "a"]})
df.loc[1:2, "a"] = pd.Categorical([2, 2], categories=[1, 2])
```

### Issue Description

It hangs forever. Or at least, longer than I'm patient enough to wait

### Expected Behavior

Based on https://github.com/pandas-dev/pandas/blob/272b73585fc8523fe18bc0ee05ca1f2c2e5bf33a/doc/source/user_guide/categorical.rst#L779

```python
In [8]: df
Out[8]: 
   a  b
0  1  a
1  2  a
2  2  a
3  1  a
4  1  a
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.8.16.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.6.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : 2023.1.0
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2022.7
None

</details>

**Comment by phofl** [comment]
I am getting a RecursionError at least

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 1047, in setitem
    casted = np_can_hold_element(values.dtype, value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/dtypes/cast.py", line 1739, in np_can_hold_element
    raise LossySetitemError
pandas.errors.LossySetitemError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrick/Library/Application Support/JetBrains/PyCharm2023.1/scratches/scratch.py", line 473, in <module>
    df.loc[1:2, "a"] = pd.Categorical([2, 2], categories=[1, 2])
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexing.py", line 834, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexing.py", line 1813, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexing.py", line 1857, in _setitem_with_indexer_split_path
    self._setitem_single_column(ilocs[0], value, pi)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexing.py", line 2012, in _setitem_single_column
    self.obj._mgr.column_setitem(loc, plane_indexer, value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/managers.py", line 1378, in column_setitem
    new_mgr = col_mgr.setitem((idx,), value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/managers.py", line 399, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/managers.py", line 357, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 1051, in setitem
    return nb.setitem(indexer, value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 1051, in setitem
    return nb.setitem(indexer, value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 1051, in setitem
    return nb.setitem(indexer, value)
  [Previous line repeated 980 more times]
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 1050, in setitem
    nb = self.coerce_to_target_dtype(value)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 425, in coerce_to_target_dtype
    return self.astype(new_dtype, copy=False)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/internals/blocks.py", line 513, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/dtypes/astype.py", line 239, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/dtypes/astype.py", line 174, in astype_array
    if is_dtype_equal(values.dtype, dtype):
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/dtypes/common.py", line 609, in is_dtype_equal
    source = _get_dtype(source)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/dtypes/common.py", line 1417, in _get_dtype
    if isinstance(arr_or_dtype, np.dtype):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jbrockmendel** [comment]
Haven't looked at the underlying issue, but RecursionErrors in this chunk of code have come up a few times.  Might be worth adding a check in coerce_to_target_dtype

```
if self.dtype == new_dtype:
    raise AssertionError("Something has gone wrong. Please report a bug")
```

**Comment by Raphencoder** [comment]
I have the same behavior, this bug is really annoying because it doesn't keep a trace of the problematic line of code that need to be change.
Is there any recommandation or tips in order to debug this kind of behavior ?

**Comment by jbrockmendel** [comment]
@Raphencoder short-term i'd suggest patching Block.coerce_to_target_dtype as suggested [here](https://github.com/pandas-dev/pandas/issues/52927#issuecomment-1526468451).  Longer-term this is something we'll have to fix.
