### ISSUE TITLE
BUG: Series.str.get with arrow String Dtype allows index to be floating point value

### ISSUE THREAD

**Issue by wirable23** [pandas-dev/pandas#53024]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> a = pd.Series(["ab"], dtype=pd.ArrowDtype(pa.string()))
>>> a.str.get(1.2)
0    b
dtype: string[pyarrow]
>>>
```

### Issue Description

According to the documentation, the index is required to be an int, so this should fail. When using the pandas StringDtype() an error is raised.

### Expected Behavior

```
>>> a2 = pd.Series(["ab"], dtype=pd.StringDtype())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\pd_201_0425\lib\site-packages\pandas\core\strings\accessor.py", line 1059, in get
    result = self._data.array._str_get(i)
  File "C:\pd_201_0425\lib\site-packages\pandas\core\strings\object_array.py", line 269, in _str_get
    return self._str_map(f)
  File "C:\pd_201_0425\lib\site-packages\pandas\core\arrays\string_.py", line 599, in _str_map
    result = lib.map_infer_mask(
  File "pandas\_libs\lib.pyx", line 2786, in pandas._libs.lib.map_infer_mask
  File "C:\pd_201_0425\lib\site-packages\pandas\core\strings\object_array.py", line 266, in f
    return x[i]
TypeError: string indices must be integers
>>>
```

I expect an error to be raised, as the method is documented to require an integral index.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>
</details>

**Comment by mroeschke** [comment]
Thanks for the report. I suppose we could raise an error in pandas but this appears to also happen in pyarrow: https://github.com/apache/arrow/issues/35385

**Comment by mroeschke** [comment]
Closing as an upstream bug in https://github.com/apache/arrow/issues/35385
