### ISSUE TITLE
BUG: Unable to run test suite

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#53225]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
On Windows


pip install -e . -vv
pytest pandas/tests/io/test_stata.py
```

### Issue Description

I am getting a hard to decipher error when attempting to run part of the test suite on Windows.  The above commands produces

```
ImportError while loading conftest 'C:\git\pandas\pandas\conftest.py'.
C:\Anaconda\lib\site-packages\_pandas_editable_loader.py:268: in find_spec
    tree = self.rebuild()
C:\Anaconda\lib\site-packages\_pandas_editable_loader.py:309: in rebuild
    subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=stdout, check=True)
C:\Anaconda\lib\subprocess.py:528: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1
```

which makes it look like it is trying to compile.  Not sure why it is trying to compile.  I have installed

```
pip install -r requirements-dev.txt
```

in the virtual environment.

### Expected Behavior

Should run the requested part of the test suite.

### Installed Versions

I am unable to show versions, same error:

```
python -c "import pandas; pandas.show_versions()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "C:\Anaconda\lib\site-packages\_pandas_editable_loader.py", line 268, in find_spec
    tree = self.rebuild()
  File "C:\Anaconda\lib\site-packages\_pandas_editable_loader.py", line 309, in rebuild
    subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=stdout, check=True)
  File "C:\Anaconda\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
```

**Comment by bashtage** [comment]
I read teh dev docs and it seem that my usual compile method doesn't work.  Not quite sure why. When I used

```bash
python -m pip install -ve . --no-build-isolation
```

it worked as expected.
