### ISSUE TITLE
BLD: 1 zillion build failures since meson switch

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53480]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
NA
```

### Issue Description

I use git worktree to work on multiple branches at once, have been having a terrible time since the meson switchover.  @lithomas1 has been helping me troubleshoot.  This issue is 1) to see if anyone else is having meson-related headaches and 2) to document fixes as they are found.

Problem 1)
```
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Desktop/pd/depr-to_pickle-48402/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "~/Desktop/pd/depr-to_pickle-48402/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "~/Desktop/pd/depr-to_pickle-48402/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: F401,E501 # isort: skip # type: ignore[reportUnusedImport]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
````

Problem 2)
(while trying to troubleshoot problem 1)
```
% python3 -m pip install -ve . --no-build-isolation 

Using pip 23.1.2 from ~/Desktop/pd/depr-to_pickle-48402/env-depr-to_pickle-48402/lib/python3.11/site-packages/pip (python 3.11)
Obtaining file:///~/Desktop/pd/depr-to_pickle-48402
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Preparing editable metadata (pyproject.toml)
  + meson setup --reconfigure ~/Desktop/pd/depr-to_pickle-48402 /~/Desktop/pd/depr-to_pickle-48402/build/cp311 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=~/Desktop/pd/depr-to_pickle-48402/build/cp311/meson-python-native-file.ini
  WARNING: Regenerating configuration from scratch.
  Reason: Coredata file '~/Desktop/pd/depr-to_pickle-48402/build/cp311/meson-private/coredata.dat' references functions or classes that don't exist. This probably means that it was generated with an old version of meson. Try running from the source directory meson setup ~/Desktop/pd/depr-to_pickle-48402/build/cp311 --wipe
  The Meson build system
  Version: 1.0.1
  Source dir: ~/Desktop/pd/depr-to_pickle-48402
  Build dir: ~/Desktop/pd/depr-to_pickle-48402/build/cp311
  Build type: native build

  ../../meson.build:2:0: ERROR: Unknown options: "vsenv"

  A full log can be found at ~/Desktop/pd/depr-to_pickle-48402/build/cp311/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: ~/Desktop/pd/depr-to_pickle-48402/env-depr-to_pickle-48402/bin/python3 ~/Desktop/pd/depr-to_pickle-48402/env-depr-to_pickle-48402/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /var/folders/vm/666lh09n50l3jcd7v34vrs880000gn/T/tmpl7ll091z
  cwd: ~/Desktop/pd/depr-to_pickle-48402
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Problem 3)
```
% pytest pandas/tests -m "not slow and not db"
[...]
ImportError while loading conftest ~/Desktop/pd/depr-combine/pandas/conftest.py'.
_pytest.pathlib.ImportPathMismatchError: ('pandas.conftest', '~/Desktop/pd/depr-period-b/pandas/conftest.py', PosixPath('~/Desktop/pd/depr-combine/pandas/conftest.py'))
```

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by lithomas1** [comment]
Problem 1 just looks like you tried to import pandas without the extension modules built in place, or imported pandas without running the pip install command for meson build.

```
Reason: Coredata file '~/Desktop/pd/depr-to_pickle-48402/build/cp311/meson-private/coredata.dat' references functions or classes that don't exist. This probably means that it was generated with an old version of meson. Try running from the source directory meson setup ~/Desktop/pd/depr-to_pickle-48402/build/cp311 --wipe
```
This looks relevant for problem 2. CI runs fine with meson 1.0.1, so I guess the error message is suggesting you had an older version of meson installed that didn't support the ``--vsenv`` keyword?

Can you try deleting the ``build`` folder(``~/Desktop/pd/depr-to_pickle-48402/build``) in that worktree directory?

Problem 3 looks like meson-python is loading pandas from another branch.
(It is mixing your ``depr-period-b`` and ``depr-combine`` branches, I think)

You'll just have to uninstall pandas and reinstall pandas everytime you change worktrees with
```
pip uninstall pandas
pip install -ve . --no-build-isolation
```
(Shouldn't take long since each worktree should have its own build directory. Main issue here is that you get a confusing error message if you forget to uninstall/reinstall.)

**Comment by jbrockmendel** [comment]
> You'll just have to uninstall pandas and reinstall pandas everytime you change worktrees with

```
% pip uninstall pandas && pip install -ve . --no-build-isolation

WARNING: Skipping pandas as it is not installed.
Using pip 23.1.2 from /~/Desktop/pd/depr-value_counts-47862/env-depr-value_counts-47862/lib/python3.11/site-packages/pip (python 3.11)
Obtaining file:///~/Desktop/pd/depr-value_counts-47862
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Preparing editable metadata (pyproject.toml)
  + meson setup --reconfigure ~/Desktop/pd/depr-value_counts-47862 ~/Desktop/pd/depr-value_counts-47862/build/cp311 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=~/Desktop/pd/depr-value_counts-47862/build/cp311/meson-python-native-file.ini
  The Meson build system
  Version: 1.1.1
  Source dir: ~/Desktop/pd/depr-value_counts-47862
  Build dir: ~/Desktop/pd/depr-value_counts-47862/build/cp311
  Build type: native build
  Project name: pandas
  Project version: 2.1.0.dev0+877.g2f9d16f8fd.dirty
  C compiler for the host machine: ccache cc (clang 14.0.3 "Apple clang version 14.0.3 (clang-1403.0.22.14.1)")
  C linker for the host machine: cc ld64 857.1
  C++ compiler for the host machine: ccache c++ (clang 14.0.3 "Apple clang version 14.0.3 (clang-1403.0.22.14.1)")
  C++ linker for the host machine: c++ ld64 857.1
  Cython compiler for the host machine: cython (cython 0.29.33)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (~/Desktop/pd/depr-value_counts-47862/env-depr-value_counts-47862/bin/python)
  Found pkg-config: /usr/local/bin/pkg-config (0.29.2)

  ../../pandas/meson.build:9:9: ERROR: Tried to form an absolute path to a dir in the source tree.
  You should not do that but use relative paths instead, for
  directories that are part of your project.

  To get include path to any directory relative to the current dir do

  incdir = include_directories(dirname)

  After this incdir will contain both the current source dir as well as the
  corresponding build dir. It can then be used in any subdirectory and
  Meson will take care of all the busywork to make paths work.

  Dirname can even be '.' to mark the current directory. Though you should
  remember that the current source and build directories are always
  put in the include directories by default so you only need to do
  include_directories('.') if you intend to use the result in a
  different subdirectory.

  Note that this error message can also be triggered by
  external dependencies being installed within your source
  tree - it's not recommended to do this.


  A full log can be found at ~/Desktop/pd/depr-value_counts-47862/build/cp311/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: ~/Desktop/pd/depr-value_counts-47862/env-depr-value_counts-47862/bin/python ~/Desktop/pd/depr-value_counts-47862/env-depr-value_counts-47862/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /var/folders/vm/666lh09n50l3jcd7v34vrs880000gn/T/tmpm3_rsc50
  cwd: ~/Desktop/pd/depr-value_counts-47862
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(env-depr-value_counts-47862) (base) brock@EnterpriseB depr-value_counts-47862 % 
```

**Comment by lithomas1** [comment]
You're using a venv, right?

If so, I think I know whats happening. Can probably can send a patch in for this pretty soon.

**Comment by jbrockmendel** [comment]
> You're using a venv (located inside pandas), right?

My usual workflow doesn't use a venv.  I've tried using them to troubleshoot the issues here without success.

**Comment by jbrockmendel** [comment]
Closing.  If more problems should up will reopen.
