### ISSUE TITLE
BUG: MultiIndex.levels returns extra values after filtering rows

### ISSUE THREAD

**Issue by davidgilbertson** [pandas-dev/pandas#53733]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    dict(
        A=range(20),
        B=range(20, 40),
    ),
    index=pd.date_range("2000-01-01", "2000-01-20"),
)

df1 = df.set_index("A", append=True).head(10)

print("df1 dates (wrong):", df1.index.levels[0])  # Contains all dates, not just 10!
print("df1 dates (right):", df1.index.get_level_values(0))  # just 10 dates
```

### Issue Description

I have a dataframe with a multi index. I filter rows somehow (in the example just using `.head()`). Now when I check what dates I have in my index, I get back values that aren't in my dataset!

Perhaps this is by design (I see that there is a second way to get at the values), but it's certainly not intuitive and the help page for `MultiIndex.levels` is blank: https://pandas.pydata.org/pandas-docs/version/1.5.0/reference/api/pandas.MultiIndex.levels.html.

### Expected Behavior

I think the index should only contain values that I see when I look at the whole DF, regardless of what method I use to access the values.

Or to put it another way, `df.set_index("A", append=True).head(10)` should behave the same as `df.head(10).set_index("A", append=True)`

### Installed Versions

`pd.show_versions()` appears to be broken. My version is `'2.0.1'`

<details>

Traceback (most recent call last):
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/qtpy/__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/home/davidg/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PySide6'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/davidg/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/davidg/.virtualenvs/learning/lib/python3.10/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

</details>

**Comment by samukweku** [comment]
https://pandas.pydata.org/docs/user_guide/advanced.html#defined-levels talks about it more. It is more of a performance thing to leave the levels as is. You can remove the unused levels with the remove_unused_levels() method

**Comment by phofl** [comment]
Yep exactly, closing as duplicate

**Comment by davidgilbertson** [comment]
You know, I think I read that part of the docs once but the info had since fallen out of my brain. Thanks!
