### ISSUE TITLE
BUG: df.compare fails for pyarrow backed dataframes

### ISSUE THREAD

**Issue by hgjn-cowi** [pandas-dev/pandas#53997]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd  # assert pd.__version__ == '2.0.3'
import pyarrow as pa # assert pa.__version__ == '12.0.1'
import numpy as np   # assert np.__version__ == '1.25.0'

df_int64 = pd.DataFrame(data=dict(seed=[]), dtype="int64")
    
# Compare works fine for "old" int64
assert df_int64.compare(df_int64.copy()).empty

df_pyarrow = df_int64.astype("int64[pyarrow]")
# But fails for pyarrow encoded columns, in many type combinations:
assert df_pyarrow.compare(df_pyarrow.copy()).empty
assert df_int64.compare(df_pyarrow).empty
assert df_pyarrow.compare(df_int64).empty
```

### Issue Description

Using df.compare on dataframes with pyarrow backed int64 fails with:
```
NotImplementedError: <class 'pandas.core.arrays.arrow.array.ArrowExtensionArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.
```

This happens even for *empty* dataframes (as seen in the example)

The full stack trace is here:
```
(.venv) hgjn@PC01708:~/src/cowind-data-classes$ /home/hgjn/src/cowind-data-classes/.venv/bin/python /home/hgjn/src/cowind-data-classes/tests/foo.py
Traceback (most recent call last):
  File "/home/hgjn/src/cowind-data-classes/tests/foo.py", line 16, in <module>
    assert df_pyarrow.compare(df_pyarrow.copy()).empty
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 7713, in compare
    return super().compare(
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/generic.py", line 9212, in compare
    mask = ~((self == other) | (self.isna() & other.isna()))
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/arraylike.py", line 78, in __or__
    return self._logical_method(other, operator.or_)
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 7457, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 7496, in _dispatch_frame_op
    bm = self._mgr.operate_blockwise(
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1545, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/internals/ops.py", line 65, in operate_blockwise
    res_values = res_values.reshape(1, -1)
  File "/home/hgjn/src/cowind-data-classes/.venv/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 898, in reshape
    raise NotImplementedError(
NotImplementedError: <class 'pandas.core.arrays.arrow.array.ArrowExtensionArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.
````

### Expected Behavior

Expected `DataFrame` with `"int64[pyarrow]"` to support `.compare`.

So, the tests in the example should not raise errors.

### Installed Versions

pandas  '2.0.3'
pyarrow '12.0.1'
numpy '1.25.0'

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.90.1-microsoft-standard-WSL2
Version          : #1 SMP Fri Jan 27 02:56:13 UTC 2023
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.25.0
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 44.1.1
pip              : 23.1.2
Cython           : None
pytest           : 7.3.1
hypothesis       : 6.79.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.3
psycopg2         : None
jinja2           : None
IPython          : 8.14.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 2.0.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
None
</details>

**Comment by vigneshRamanathan3105** [comment]
I am interested in contributing. Please assign this to me

**Comment by jbrockmendel** [comment]
Can you check on main?  All the assertions in the OP work for me

**Comment by hgjn-cowi** [comment]
Verified this is solved in main, 

```
(.venv) hgjn@PC01708:~/src/pandas$ git diff
diff --git a/pandas/tests/frame/methods/test_compare.py b/pandas/tests/frame/methods/test_compare.py
index a4d0a7068a..fcd52dea0a 100644
--- a/pandas/tests/frame/methods/test_compare.py
+++ b/pandas/tests/frame/methods/test_compare.py
@@ -7,6 +7,25 @@ import pandas as pd
 import pandas._testing as tm
 
 
+#@pytest.mark.xfail(reason = "Reported as https://github.com/pandas-dev/pandas/issues/53997", raises=NotImplementedError)
+def test_pyarrow_not_compareable():
+    df_int64 = pd.DataFrame(data=dict(seed=[1, 2]), dtype="int64")
+    
+    # Compare works fine for "old" int64
+    assert df_int64.compare(df_int64.copy()).empty
+
+    # But fails for pyarrow encoded columns, in many type combinations:
+    
+    # NotImplementedError: <class 'pandas.core.arrays.arrow.array.ArrowExtensionArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.
+    df_pyarrow = df_int64.astype("int64[pyarrow]")
+
+    assert df_pyarrow.compare(df_pyarrow.copy()).empty
+    assert df_int64.compare(df_pyarrow).empty
+    assert df_pyarrow.compare(df_int64).empty
+
+if __name__ == "__main__":
+    test_pyarrow_not_compareable()
+
 @pytest.mark.parametrize("align_axis", [0, 1, "index", "columns"])
 def test_compare_axis(align_axis):
     # GH#30429
```

``` python
#@pytest.mark.xfail(reason = "Reported as https://github.com/pandas-dev/pandas/issues/53997", raises=NotImplementedError)
def test_pyarrow_not_compareable():
    df_int64 = pd.DataFrame(data=dict(seed=[1, 2]), dtype="int64")
    
    # Compare works fine for "old" int64
    assert df_int64.compare(df_int64.copy()).empty

    # But fails for pyarrow encoded columns, in many type combinations:
    
    # NotImplementedError: <class 'pandas.core.arrays.arrow.array.ArrowExtensionArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.
    df_pyarrow = df_int64.astype("int64[pyarrow]")

    assert df_pyarrow.compare(df_pyarrow.copy()).empty
    assert df_int64.compare(df_pyarrow).empty
    assert df_pyarrow.compare(df_int64).empty

```

``` sh
(.venv) hgjn@PC01708:~/src/pandas$ pytest pandas/tests/frame/methods/test_compare.py -k not_compareable
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.9.2, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/hgjn/src/pandas
configfile: pyproject.toml
plugins: hypothesis-6.80.0, xdist-3.3.1, asyncio-0.21.0, anyio-3.7.0, localserver-0.7.1, cov-4.1.0, cython-0.2.1
asyncio: mode=strict
collected 26 items / 25 deselected / 1 selected                                                                                                                                                                    

pandas/tests/frame/methods/test_compare.py .

----------------------------------------------------------------------------- generated xml file: /home/hgjn/src/pandas/test-data.xml ------------------------------------------------------------------------------
=============================================================================================== slowest 30 durations ===============================================================================================
0.02s call     pandas/tests/frame/methods/test_compare.py::test_pyarrow_not_compareable

(2 durations < 0.005s hidden.  Use -vv to show these durations.)
========================================================================================= 1 passed, 25 deselected in 0.04s =========================================================================================
```
