### ISSUE TITLE
BUG: No module named 'pandas._libs.properties' when using Python 3.11.2 and pandas=2.0.3

### ISSUE THREAD

**Issue by hrsma2i** [pandas-dev/pandas#54092]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
$ python 

>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user.name/my-library/.venv/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user.name/my-library/.venv/lib/python3.11/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/Users/user.name/my-library/.venv/lib/python3.11/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/Users/user.name/my-library/.venv/lib/python3.11/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/Users/user.name/my-library/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
ModuleNotFoundError: No module named 'pandas._libs.properties'
```

### Issue Description

I'm using Python 3.11.2 and pandas==2.0.3

### Expected Behavior

I can import pandas without the error.

### Installed Versions

<details>

I can't execute `pd.show_versions()`.

</details>

**Comment by lithomas1** [comment]
How did you install pandas?

Can you provide output of the install step?

Can you also provide your platform (e.g. Windows/macOS/Linux and what CPU architecture)?

**Comment by hrsma2i** [comment]
@lithomas1 

> Can you also provide your platform (e.g. Windows/macOS/Linux and what CPU architecture)?

macOS Ventura 13.3.1(a)

```bash
$ uname -m
x86_64
```

> How did you install pandas?

```
$ brew install pyenv
$ brew install pipx
$ pipx install poetry
$ cd my-library
$ pyenv local 3.11.2
$ poetry add pandas
```

**Comment by rhshadrach** [comment]
Can you also share the output from these commands.

**Comment by hrsma2i** [comment]
@lithomas1 @rhshadrach 

The output from `poetry add -vvv pandas` is:

```
Loading configuration file /Users/user.name/Library/Application Support/pypoetry/config.toml
Trying to detect current active python executable as specified in the config.
Found: /Users/user.name/parent-directory/logics/my-library/.venv/bin/python
Using virtualenv: /Users/user.name/parent-directory/logics/my-library/.venv
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/pandas/ HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4404394768 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/6/6/e/c/7/66ec76a7b6ed4081044f5c7821af293b63c17bc2ac523ff93d5ca7d5.lock
[filelock] Lock 4404394768 acquired on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/6/6/e/c/7/66ec76a7b6ed4081044f5c7821af293b63c17bc2ac523ff93d5ca7d5.lock
[filelock] Attempting to release lock 4404394768 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/6/6/e/c/7/66ec76a7b6ed4081044f5c7821af293b63c17bc2ac523ff93d5ca7d5.lock
[filelock] Lock 4404394768 released on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/6/6/e/c/7/66ec76a7b6ed4081044f5c7821af293b63c17bc2ac523ff93d5ca7d5.lock
Source (PyPI): 1 packages found for pandas 2.0.3

Updating dependencies
Resolving dependencies...
   1: fact: my-library is 0.1.0
   1: derived: my-library
   1: fact: my-library depends on typer (^0.9.0)
   1: fact: my-library depends on scipy (^1.11.1)
   1: fact: my-library depends on scikit-learn (^1.3.0)
   1: fact: my-library depends on tqdm (^4.65.0)
   1: fact: my-library depends on batchutil (*)
   1: fact: my-library depends on fastparquet (^2023.7.0)
   1: fact: my-library depends on pyarrow (^12.0.1)
   1: fact: my-library depends on pandas (2.0.3)
   1: fact: my-library depends on black (^23.7.0)
   1: fact: my-library depends on ruff (^0.0.277)
   1: selecting my-library (0.1.0)
   1: derived: ruff (>=0.0.277,<0.0.278)
   1: derived: black (>=23.7.0,<24.0.0)
   1: derived: pandas (==2.0.3)
   1: derived: pyarrow (>=12.0.1,<13.0.0)
   1: derived: fastparquet (>=2023.7.0,<2024.0.0)
   1: derived: batchutil (*) @ file:///Users/user.name/parent-directory/batchutil
   1: derived: tqdm (>=4.65.0,<5.0.0)
   1: derived: scikit-learn (>=1.3.0,<2.0.0)
   1: derived: scipy (>=1.11.1,<2.0.0)
   1: derived: typer (>=0.9.0,<0.10.0)
Source (PyPI): 1 packages found for pandas 2.0.3
   1: fact: batchutil (0.1.0) depends on python-json-logger (^2.0.2)
   1: selecting batchutil (0.1.0 /Users/user.name/parent-directory/batchutil)
   1: derived: python-json-logger (>=2.0.2,<3.0.0)
   0: Duplicate dependencies for numpy
   0: Different requirements found for numpy (>=1.21.0) with markers python_version >= "3.10" and numpy (>=1.23.2) with markers python_version >= "3.11".
   1: Version solving took 0.041 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({Package('pandas', '2.0.3'): {'numpy': <Dependency numpy (>=1.21.0)>}}).
   1: fact: my-library is 0.1.0
   1: derived: my-library
   1: fact: my-library depends on typer (^0.9.0)
   1: fact: my-library depends on scipy (^1.11.1)
   1: fact: my-library depends on scikit-learn (^1.3.0)
   1: fact: my-library depends on tqdm (^4.65.0)
   1: fact: my-library depends on batchutil (*)
   1: fact: my-library depends on fastparquet (^2023.7.0)
   1: fact: my-library depends on pyarrow (^12.0.1)
   1: fact: my-library depends on pandas (2.0.3)
   1: fact: my-library depends on black (^23.7.0)
   1: fact: my-library depends on ruff (^0.0.277)
   1: selecting my-library (0.1.0)
   1: derived: ruff (>=0.0.277,<0.0.278)
   1: derived: black (>=23.7.0,<24.0.0)
   1: derived: pandas (==2.0.3)
   1: derived: pyarrow (>=12.0.1,<13.0.0)
   1: derived: fastparquet (>=2023.7.0,<2024.0.0)
   1: derived: batchutil (*) @ file:///Users/user.name/parent-directory/batchutil
   1: derived: tqdm (>=4.65.0,<5.0.0)
   1: derived: scikit-learn (>=1.3.0,<2.0.0)
   1: derived: scipy (>=1.11.1,<2.0.0)
   1: derived: typer (>=0.9.0,<0.10.0)
Source (PyPI): 1 packages found for pandas 2.0.3
   1: fact: batchutil (0.1.0) depends on python-json-logger (^2.0.2)
   1: selecting batchutil (0.1.0 /Users/user.name/parent-directory/batchutil)
   1: derived: python-json-logger (>=2.0.2,<3.0.0)
   1: fact: pandas (2.0.3) depends on python-dateutil (>=2.8.2)
   1: fact: pandas (2.0.3) depends on pytz (>=2020.1)
   1: fact: pandas (2.0.3) depends on tzdata (>=2022.1)
   1: fact: pandas (2.0.3) depends on numpy (>=1.21.0)
   1: selecting pandas (2.0.3)
   1: derived: numpy (>=1.21.0)
   1: derived: tzdata (>=2022.1)
   1: derived: pytz (>=2020.1)
   1: derived: python-dateutil (>=2.8.2)
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/tzdata/ HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4408522000 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/c/f/6/e/0cf6e817e2c5554000c735ecab0f3cf492f7d33b50d5a474a801ba24.lock
[filelock] Lock 4408522000 acquired on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/c/f/6/e/0cf6e817e2c5554000c735ecab0f3cf492f7d33b50d5a474a801ba24.lock
[filelock] Attempting to release lock 4408522000 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/c/f/6/e/0cf6e817e2c5554000c735ecab0f3cf492f7d33b50d5a474a801ba24.lock
[filelock] Lock 4408522000 released on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/c/f/6/e/0cf6e817e2c5554000c735ecab0f3cf492f7d33b50d5a474a801ba24.lock
Source (PyPI): 10 packages found for tzdata >=2022.1
   1: selecting ruff (0.0.277)
   1: fact: black (23.7.0) depends on click (>=8.0.0)
   1: fact: black (23.7.0) depends on mypy-extensions (>=0.4.3)
   1: fact: black (23.7.0) depends on packaging (>=22.0)
   1: fact: black (23.7.0) depends on pathspec (>=0.9.0)
   1: fact: black (23.7.0) depends on platformdirs (>=2)
   1: selecting black (23.7.0)
   1: derived: platformdirs (>=2)
   1: derived: pathspec (>=0.9.0)
   1: derived: packaging (>=22.0)
   1: derived: mypy-extensions (>=0.4.3)
   1: derived: click (>=8.0.0)
   1: fact: pyarrow (12.0.1) depends on numpy (>=1.16.6)
   1: selecting pyarrow (12.0.1)
   1: fact: fastparquet (2023.7.0) depends on pandas (>=1.5.0)
   1: fact: fastparquet (2023.7.0) depends on numpy (>=1.20.3)
   1: fact: fastparquet (2023.7.0) depends on cramjam (>=2.3)
   1: fact: fastparquet (2023.7.0) depends on fsspec (*)
   1: fact: fastparquet (2023.7.0) depends on packaging (*)
   1: selecting fastparquet (2023.7.0)
   1: derived: fsspec
   1: derived: cramjam (>=2.3)
   1: fact: tqdm (4.65.0) depends on colorama (*)
   1: selecting tqdm (4.65.0)
   1: derived: colorama
   1: fact: scikit-learn (1.3.0) depends on numpy (>=1.17.3)
   1: fact: scikit-learn (1.3.0) depends on scipy (>=1.5.0)
   1: fact: scikit-learn (1.3.0) depends on joblib (>=1.1.1)
   1: fact: scikit-learn (1.3.0) depends on threadpoolctl (>=2.0.0)
   1: selecting scikit-learn (1.3.0)
   1: derived: threadpoolctl (>=2.0.0)
   1: derived: joblib (>=1.1.1)
   1: fact: scipy (1.11.1) depends on numpy (>=1.21.6,<1.28.0)
   1: selecting scipy (1.11.1)
   1: derived: numpy (>=1.21.6,<1.28.0)
   1: fact: typer (0.9.0) depends on click (>=7.1.1,<9.0.0)
   1: fact: typer (0.9.0) depends on typing-extensions (>=3.7.4.3)
   1: selecting typer (0.9.0)
   1: derived: typing-extensions (>=3.7.4.3)
   1: derived: click (>=7.1.1,<9.0.0)
   1: selecting python-json-logger (2.0.7)
   1: selecting pytz (2023.3)
   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)
   1: selecting python-dateutil (2.8.2)
   1: derived: six (>=1.5)
   1: selecting platformdirs (3.8.1)
   1: selecting pathspec (0.11.1)
   1: selecting packaging (23.1)
   1: selecting mypy-extensions (1.0.0)
   1: fact: click (8.1.4) depends on colorama (*)
   1: selecting click (8.1.4)
   1: selecting fsspec (2023.6.0)
   1: selecting cramjam (2.6.2)
   1: selecting threadpoolctl (3.1.0)
   1: selecting joblib (1.3.1)
   1: selecting typing-extensions (4.7.1)
   1: selecting six (1.16.0)
   1: selecting tzdata (2023.3)
   1: selecting numpy (1.25.1)
   1: selecting colorama (0.4.6)
   1: Version solving took 0.254 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({Package('pandas', '2.0.3'): {'numpy': <Dependency numpy (>=1.23.2)>}}).
   1: fact: my-library is 0.1.0
   1: derived: my-library
   1: fact: my-library depends on typer (^0.9.0)
   1: fact: my-library depends on scipy (^1.11.1)
   1: fact: my-library depends on scikit-learn (^1.3.0)
   1: fact: my-library depends on tqdm (^4.65.0)
   1: fact: my-library depends on batchutil (*)
   1: fact: my-library depends on fastparquet (^2023.7.0)
   1: fact: my-library depends on pyarrow (^12.0.1)
   1: fact: my-library depends on pandas (2.0.3)
   1: fact: my-library depends on black (^23.7.0)
   1: fact: my-library depends on ruff (^0.0.277)
   1: selecting my-library (0.1.0)
   1: derived: ruff (>=0.0.277,<0.0.278)
   1: derived: black (>=23.7.0,<24.0.0)
   1: derived: pandas (==2.0.3)
   1: derived: pyarrow (>=12.0.1,<13.0.0)
   1: derived: fastparquet (>=2023.7.0,<2024.0.0)
   1: derived: batchutil (*) @ file:///Users/user.name/parent-directory/batchutil
   1: derived: tqdm (>=4.65.0,<5.0.0)
   1: derived: scikit-learn (>=1.3.0,<2.0.0)
   1: derived: scipy (>=1.11.1,<2.0.0)
   1: derived: typer (>=0.9.0,<0.10.0)
Source (PyPI): 1 packages found for pandas 2.0.3
   1: fact: batchutil (0.1.0) depends on python-json-logger (^2.0.2)
   1: selecting batchutil (0.1.0 /Users/user.name/parent-directory/batchutil)
   1: derived: python-json-logger (>=2.0.2,<3.0.0)
   1: fact: pandas (2.0.3) depends on python-dateutil (>=2.8.2)
   1: fact: pandas (2.0.3) depends on pytz (>=2020.1)
   1: fact: pandas (2.0.3) depends on tzdata (>=2022.1)
   1: fact: pandas (2.0.3) depends on numpy (>=1.23.2)
   1: selecting pandas (2.0.3)
   1: derived: numpy (>=1.23.2)
   1: derived: tzdata (>=2022.1)
   1: derived: pytz (>=2020.1)
   1: derived: python-dateutil (>=2.8.2)
Source (PyPI): 10 packages found for tzdata >=2022.1
   1: selecting ruff (0.0.277)
   1: fact: black (23.7.0) depends on click (>=8.0.0)
   1: fact: black (23.7.0) depends on mypy-extensions (>=0.4.3)
   1: fact: black (23.7.0) depends on packaging (>=22.0)
   1: fact: black (23.7.0) depends on pathspec (>=0.9.0)
   1: fact: black (23.7.0) depends on platformdirs (>=2)
   1: selecting black (23.7.0)
   1: derived: platformdirs (>=2)
   1: derived: pathspec (>=0.9.0)
   1: derived: packaging (>=22.0)
   1: derived: mypy-extensions (>=0.4.3)
   1: derived: click (>=8.0.0)
   1: fact: pyarrow (12.0.1) depends on numpy (>=1.16.6)
   1: selecting pyarrow (12.0.1)
   1: fact: fastparquet (2023.7.0) depends on pandas (>=1.5.0)
   1: fact: fastparquet (2023.7.0) depends on numpy (>=1.20.3)
   1: fact: fastparquet (2023.7.0) depends on cramjam (>=2.3)
   1: fact: fastparquet (2023.7.0) depends on fsspec (*)
   1: fact: fastparquet (2023.7.0) depends on packaging (*)
   1: selecting fastparquet (2023.7.0)
   1: derived: fsspec
   1: derived: cramjam (>=2.3)
   1: fact: tqdm (4.65.0) depends on colorama (*)
   1: selecting tqdm (4.65.0)
   1: derived: colorama
   1: fact: scikit-learn (1.3.0) depends on numpy (>=1.17.3)
   1: fact: scikit-learn (1.3.0) depends on scipy (>=1.5.0)
   1: fact: scikit-learn (1.3.0) depends on joblib (>=1.1.1)
   1: fact: scikit-learn (1.3.0) depends on threadpoolctl (>=2.0.0)
   1: selecting scikit-learn (1.3.0)
   1: derived: threadpoolctl (>=2.0.0)
   1: derived: joblib (>=1.1.1)
   1: fact: scipy (1.11.1) depends on numpy (>=1.21.6,<1.28.0)
   1: selecting scipy (1.11.1)
   1: derived: numpy (>=1.21.6,<1.28.0)
   1: fact: typer (0.9.0) depends on click (>=7.1.1,<9.0.0)
   1: fact: typer (0.9.0) depends on typing-extensions (>=3.7.4.3)
   1: selecting typer (0.9.0)
   1: derived: typing-extensions (>=3.7.4.3)
   1: derived: click (>=7.1.1,<9.0.0)
   1: selecting python-json-logger (2.0.7)
   1: selecting pytz (2023.3)
   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)
   1: selecting python-dateutil (2.8.2)
   1: derived: six (>=1.5)
   1: selecting platformdirs (3.8.1)
   1: selecting pathspec (0.11.1)
   1: selecting packaging (23.1)
   1: selecting mypy-extensions (1.0.0)
   1: fact: click (8.1.4) depends on colorama (*)
   1: selecting click (8.1.4)
   1: selecting fsspec (2023.6.0)
   1: selecting cramjam (2.6.2)
   1: selecting threadpoolctl (3.1.0)
   1: selecting joblib (1.3.1)
   1: selecting typing-extensions (4.7.1)
   1: selecting six (1.16.0)
   1: selecting tzdata (2023.3)
   1: selecting numpy (1.25.1)
   1: selecting colorama (0.4.6)
   1: Version solving took 0.132 seconds.
   1: Tried 1 solutions.
   0: Complete version solving took 0.431 seconds with 2 overrides
   0: Resolved with overrides: ({Package('pandas', '2.0.3'): {'numpy': <Dependency numpy (>=1.21.0)>}}), ({Package('pandas', '2.0.3'): {'numpy': <Dependency numpy (>=1.23.2)>}})

Finding the necessary packages for the current system
Source (poetry-repo): 1 packages found for pandas 2.0.3
Source (poetry-repo): 1 packages found for pandas 2.0.3
Source (poetry-repo): 1 packages found for tzdata >=2022.1
Source (poetry-repo): 1 packages found for pandas 2.0.3
Source (poetry-repo): 1 packages found for tzdata >=2022.1

Package operations: 1 install, 1 update, 0 removals, 24 skipped

  • Installing tzdata (2023.3)
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/tzdata/2023.3/json HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4409254416 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/b/a/c/0/abac0abea2d200e498c2a16bc192d4135e3b75d2199542e62fb4c3c3.lock
[filelock] Lock 4409254416 acquired on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/b/a/c/0/abac0abea2d200e498c2a16bc192d4135e3b75d2199542e62fb4c3c3.lock
[filelock] Attempting to release lock 4409254416 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/b/a/c/0/abac0abea2d200e498c2a16bc192d4135e3b75d2199542e62fb4c3c3.lock
[filelock] Lock 4409254416 released on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/b/a/c/0/abac0abea2d200e498c2a16bc192d4135e3b75d2199542e62fb4c3c3.lock
  • Updating pandas (1.5.3 -> 2.0.3)
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/pandas/2.0.3/json HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4412543568 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/f/d/9/f/7/fd9f7889aab554a9400d154456b37a31475b94d9105bd8c5b9f52e5e.lock
[filelock] Lock 4412543568 acquired on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/f/d/9/f/7/fd9f7889aab554a9400d154456b37a31475b94d9105bd8c5b9f52e5e.lock
[filelock] Attempting to release lock 4412543568 on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/f/d/9/f/7/fd9f7889aab554a9400d154456b37a31475b94d9105bd8c5b9f52e5e.lock
[filelock] Lock 4412543568 released on /Users/user.name/Library/Caches/pypoetry/cache/repositories/PyPI/_http/f/d/9/f/7/fd9f7889aab554a9400d154456b37a31475b94d9105bd8c5b9f52e5e.lock
Skipping wheel pandas-2.0.3-cp310-cp310-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp310-cp310-win32.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp310-cp310-win_amd64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp311-cp311-win32.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp311-cp311-win_amd64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-macosx_11_0_arm64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-win32.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp38-cp38-win_amd64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-macosx_11_0_arm64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-win32.whl as this is not supported by the current environment
Skipping wheel pandas-2.0.3-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing batchutil (0.1.0 /Users/user.name/parent-directory/batchutil): Skipped for the following reason: Already installed
  • Installing black (23.7.0): Skipped for the following reason: Already installed
  • Installing click (8.1.4): Skipped for the following reason: Already installed
  • Installing cramjam (2.6.2): Skipped for the following reason: Already installed
  • Installing fsspec (2023.6.0): Skipped for the following reason: Already installed
  • Installing mypy-extensions (1.0.0): Skipped for the following reason: Already installed
  • Installing numpy (1.25.1): Skipped for the following reason: Already installed
  • Installing packaging (23.1): Skipped for the following reason: Already installed
  • Installing fastparquet (2023.7.0): Skipped for the following reason: Already installed
  • Installing pyarrow (12.0.1): Skipped for the following reason: Already installed
  • Installing python-dateutil (2.8.2): Skipped for the following reason: Already installed
  • Installing pathspec (0.11.1): Skipped for the following reason: Already installed
  • Installing ruff (0.0.277): Skipped for the following reason: Already installed
  • Installing scipy (1.11.1): Skipped for the following reason: Already installed
  • Installing six (1.16.0): Skipped for the following reason: Already installed
  • Installing threadpoolctl (3.1.0): Skipped for the following reason: Already installed
  • Installing python-json-logger (2.0.7): Skipped for the following reason: Already installed
  • Installing pytz (2023.3): Skipped for the following reason: Already installed
  • Installing scikit-learn (1.3.0): Skipped for the following reason: Already installed
  • Installing joblib (1.3.1): Skipped for the following reason: Already installed
  • Installing typer (0.9.0): Skipped for the following reason: Already installed
  • Installing platformdirs (3.8.1): Skipped for the following reason: Already installed
  • Installing typing-extensions (4.7.1): Skipped for the following reason: Already installed
  • Installing tqdm (4.65.0): Skipped for the following reason: Already installed

Writing lock file
```

**Comment by lithomas1** [comment]
[This](https://files.pythonhosted.org/packages/b3/92/a5e5133421b49e901a12e02a6a7ef3a0130e10d13db8cb657fdd0cba3b90/pandas-2.0.3-cp311-cp311-macosx_10_9_x86_64.whl) is the wheel that should have been downloaded
(pandas-2.0.3-cp311-cp311-macosx_10_9_x86_64.whl)

Can you try installing with pip or clearing your poetry cache and trying again?

(You can also try installing the wheel I linked manually)

**Comment by mroeschke** [comment]
Closing as this issue needs more information
