### ISSUE TITLE
BUG: Docs does not build on macos, due to EOFError

### ISSUE THREAD

**Issue by Tialo** [pandas-dev/pandas#54231]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```
Follow steps from contributing guide
https://pandas.pydata.org/docs/dev/development/contributing_environment.html

1. Clone git repository
2. Create mamba environment
3. Install pandas with meson, using command `python -m pip install -ve . --no-build-isolation --config-settings editable-verbose=true`
4. Build documentation `python make.py html`
```

### Issue Description

I am trying to build documentation on macos and getting this weird exception 

Exception occurred:
```
File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
raise EOFError
```

Full build logs:
<details>
+ /Users/y.korobko/mambaforge/envs/pandas-dev/bin/ninja

[17/91] Linking target pandas/_libs/tslibs/np_datetime.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[19/91] Linking target pandas/_libs/tslibs/dtypes.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[21/91] Linking target pandas/_libs/tslibs/nattype.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[24/91] Linking target pandas/_libs/tslibs/conversion.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[25/91] Linking target pandas/_libs/tslibs/vectorized.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[28/91] Linking target pandas/_libs/tslibs/timezones.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[30/91] Linking target pandas/_libs/tslibs/fields.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[32/91] Linking target pandas/_libs/tslibs/tzconversion.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[35/91] Linking target pandas/_libs/tslibs/parsing.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[37/91] Linking target pandas/_libs/tslibs/strptime.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[39/91] Linking target pandas/_libs/hashing.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[42/91] Linking target pandas/_libs/tslibs/period.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[46/91] Linking target pandas/_libs/tslibs/timestamps.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[50/91] Linking target pandas/_libs/tslibs/timedeltas.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[56/91] Linking target pandas/_libs/missing.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[62/91] Linking target pandas/_libs/internals.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[64/91] Linking target pandas/_libs/ops.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[66/91] Linking target pandas/_libs/testing.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[69/91] Linking target pandas/_libs/reshape.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[71/91] Linking target pandas/_libs/tslib.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[73/91] Linking target pandas/_libs/tslibs/offsets.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[75/91] Linking target pandas/_libs/parsers.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[77/91] Linking target pandas/_libs/lib.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[79/91] Linking target pandas/_libs/index.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[81/91] Linking target pandas/_libs/window/aggregations.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[83/91] Linking target pandas/_libs/interval.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[85/91] Linking target pandas/_libs/hashtable.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[87/91] Linking target pandas/_libs/algos.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[89/91] Linking target pandas/_libs/groupby.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[91/91] Linking target pandas/_libs/join.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Running Sphinx v6.2.1
+ /Users/y.korobko/mambaforge/envs/pandas-dev/bin/ninja
[1/1] Generating write_version_file with a custom command
making output directory... готово
[autosummary] generating autosummary for: development/community.rst, development/contributing.rst, development/contributing_codebase.rst, development/contributing_docstring.rst, development/contributing_documentation.rst, development/contributing_environment.rst, development/contributing_gitpod.rst, development/copy_on_write.rst, development/debugging_extensions.rst, development/developer.rst, ..., whatsnew/v1.5.0.rst, whatsnew/v1.5.1.rst, whatsnew/v1.5.2.rst, whatsnew/v1.5.3.rst, whatsnew/v2.0.0.rst, whatsnew/v2.0.1.rst, whatsnew/v2.0.2.rst, whatsnew/v2.0.3.rst, whatsnew/v2.0.4.rst, whatsnew/v2.1.0.rst
[autosummary] generating autosummary for: /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.ArrowDtype.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.BooleanDtype.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.__array__.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.categories.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.codes.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.dtype.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.from_codes.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.ordered.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.Categorical.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.CategoricalDtype.categories.rst, ..., /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.n.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.name.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.nanos.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.normalize.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.rule_code.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.unique.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.util.hash_array.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.util.hash_pandas_object.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.wide_to_long.rst
[autosummary] generating autosummary for: /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.divide.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.flags.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.isetitem.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.multiply.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.subtract.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.DataFrame.to_numpy.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.ExcelFile.close.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.ExcelWriter.book.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.ExcelWriter.check_extension.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.ExcelWriter.close.rst, ..., /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.Week.rollforward.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.WeekOfMonth.base.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.WeekOfMonth.rollback.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.WeekOfMonth.rollforward.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearBegin.base.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearBegin.rollback.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearBegin.rollforward.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.base.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.rollback.rst, /Users/y.korobko/Desktop/pandas/doc/source/reference/api/pandas.tseries.offsets.YearEnd.rollforward.rst
loading intersphinx inventory from https://dateutil.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://pandas-gbq.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://pylib.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/objects.inv...
loading intersphinx inventory from https://arrow.apache.org/docs/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 174 source files that are out of date
updating environment: [новая конфигурация] 2471 added, 0 changed, 0 removed
reading sources... [  3%] reference/api/pandas.Categorical.from_codes .. reference/api/pandas.DataF
reading sources... [  5%] reference/api/pandas.DataFrame.bfill .. reference/api/pandas.DataFrame.from_records

```
Exception occurred:
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

The full traceback has been saved in /var/folders/y7/cy5bf8md4c13f184hpts4yqw0000gq/T/sphinx-err-_np_7vi_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
</details>

Content of log file:
<details>

 Platform:         darwin; (macOS-13.4.1-x86_64-i386-64bit)
 Sphinx version:   6.2.1
 Python version:   3.10.12 (CPython)
 Docutils version: 0.19
 Jinja2 version:   3.1.2
 Pygments version: 2.15.1

 Last messages:
   building [mo]: targets for 0 po files that are out of date
   writing output...
   
   building [html]: targets for 174 source files that are out of date
   updating environment:
   [новая конфигурация]
   2471 added, 0 changed, 0 removed
   reading sources... [  1%] development/community .. reference/api/pandas.Categorical.dtype
   reading sources... [  3%] reference/api/pandas.Categorical.from_codes .. reference/api/pandas.DataFrame.between_time
   reading sources... [  5%] reference/api/pandas.DataFrame.bfill .. reference/api/pandas.DataFrame.from_records

 Loaded extensions:
   sphinx.ext.mathjax (6.2.1)
   alabaster (0.7.13)
   sphinxcontrib.applehelp (1.0.4)
   sphinxcontrib.devhelp (1.0.2)
   sphinxcontrib.htmlhelp (2.0.1)
   sphinxcontrib.serializinghtml (1.1.5)
   sphinxcontrib.qthelp (1.0.3)
   contributors (0.1)
   IPython.sphinxext.ipython_directive (unknown version)
   IPython.sphinxext.ipython_console_highlighting (unknown version)
   matplotlib.sphinxext.plot_directive (3.7.2)
   sphinx.ext.autodoc.preserve_defaults (6.2.1)
   sphinx.ext.autodoc.type_comment (6.2.1)
   sphinx.ext.autodoc.typehints (6.2.1)
   sphinx.ext.autodoc (6.2.1)
   sphinx.ext.autosummary (6.2.1)
   numpydoc (1.5.0)
   sphinx_copybutton (0.5.2)
   sphinx_design (0.4.1)
   sphinx_toggleprompt (0.4.0)
   sphinx.ext.coverage (6.2.1)
   sphinx.ext.doctest (6.2.1)
   sphinx.ext.extlinks (6.2.1)
   sphinx.ext.ifconfig (6.2.1)
   sphinx.ext.intersphinx (6.2.1)
   sphinx.ext.linkcode (6.2.1)
   sphinx.ext.todo (6.2.1)
   nbsphinx (0.9.2)
   pydata_sphinx_theme (unknown version)

```
 Traceback:
Traceback (most recent call last):
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 328, in build
    updated_docnames = set(self.read())
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_parallel(docnames, nproc=self.app.parallel)
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 489, in _read_parallel
    tasks.join()
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/util/parallel.py", line 99, in join
    if not self._join_one():
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/site-packages/sphinx/util/parallel.py", line 117, in _join_one
    exc, logs, result = pipe.recv()
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/y.korobko/mambaforge/envs/pandas-dev/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
</details>

First of all I am struggling understanding is it pandas bug, somehow connected to environment or versions of sphinx extensions, or it is fault of sphinx itself. Some people have encountered similar bug, but unfortunately their solution didn't help to my problem, so I couldn't find way to resolve issue in sphinx github.
Also I wonder if build warnings matter to this case `ld: warning: -pie being ignored. It is only used when linking a main executable`.

If you are missing some information I would be glad to add it to comments.

### Expected Behavior

Docs would build.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 3c01ce2af5099a8a830195b2050d3a4036d14ff3
python           : 3.10.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.5.0
Version          : Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : ru_RU.UTF-8
LOCALE           : ru_RU.UTF-8

pandas           : 2.1.0.dev0+1273.g3c01ce2af5
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.2.1
Cython           : 0.29.33
pytest           : 7.4.0
hypothesis       : 6.82.0
sphinx           : 6.2.1
blosc            : None
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : 1.4.6
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.7
brotli           : 
fastparquet      : 2023.7.0
fsspec           : 2023.6.0
gcsfs            : 2023.6.0
matplotlib       : 3.7.2
numba            : 0.57.1
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : 1.2.2
pyxlsb           : 1.0.10
s3fs             : 2023.6.0
scipy            : 1.11.1
snappy           : 
sqlalchemy       : 2.0.19
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.7.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
</details>

**Comment by UmbertoFasci** [comment]
In previous contributions I have done with Mac, I used the following procedure which worked for me:

```bash
cd web
./python_web.py pandas
cd build
python -m http.server
```

This should build out all the web docs, where you can test if your change breaks it or not. Let me know if this works!

**Comment by Tialo** [comment]
It worked, but it builds only main part of website without docs. After starting server on localhost I go to "Documentation" page and get 404, because I haven't built the documentation.
```
::1 - - [23/Jul/2023 20:07:06] code 404, message File not found
::1 - - [23/Jul/2023 20:07:06] "GET /docs/ HTTP/1.1" 404 -
```

**Comment by Tialo** [comment]
I am sorry for closing. Misclick

**Comment by UmbertoFasci** [comment]
Understood, my solution is focused on building the web portion. I will investigate building the docs directly in my system no problem.

**Comment by Moisan** [comment]
I can reproduce this. It seems to be linked to parallel jobs since the  following command works:
```
python make.py --num-jobs 1 html
```

**Comment by jbrockmendel** [comment]
#62015 added the tip to use `--num-jobs 1`.  AFAICT this is an upstream problem and nothing else we can do here. Closing.
