### ISSUE TITLE
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by anmyachev** [pandas-dev/pandas#54848]
Reproducer:
```python
import pandas as pd

df1 = pd.DataFrame(["a"]).convert_dtypes()
df2 = pd.DataFrame([1]).convert_dtypes()
pd.concat([df1, df2])  # <= numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
```

Traceback:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Miniconda3\envs\modin\lib\site-packages\pandas\core\reshape\concat.py", line 393, in concat
    return op.get_result()
  File "Miniconda3\envs\modin\lib\site-packages\pandas\core\reshape\concat.py", line 680, in get_result
    new_data = concatenate_managers(
  File "Miniconda3\envs\modin\lib\site-packages\pandas\core\internals\concat.py", line 180, in concatenate_managers
    values = concat_compat(vals, axis=1, ea_compat_axis=True)
  File "Miniconda3\envs\modin\lib\site-packages\pandas\core\dtypes\concat.py", line 135, in concat_compat
    result = np.concatenate(to_concat_arrs, axis=axis)
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
```

pandas 2.1.0rc0

**Comment by lithomas1** [comment]
Hi,
Thanks for reporting this issue. I can confirm this is a regression from 2.0.3. Marking for 2.1.1.

Not sure if #53260 caused this (the erroring line is from there),
but cc @jbrockmendel just in case.

**Comment by jbrockmendel** [comment]
haven't looked closely, but 53260 is entirely plausible as being responsible.
