### ISSUE TITLE
BUG: sort_values raises error about Categorical categories must be unique when no categorical types used

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#54911]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> s1 = pd.Series([-0.0, 0.0], dtype="float[pyarrow]")
>>> s2 = pd.Series([False, False], dtype="bool[pyarrow]")
>>> df = pd.DataFrame({"A": s1, "B": s2})
>>> df.sort_values(list(df.columns))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\frame.py", line 6751, in sort_values
    indexer = lexsort_indexer(
              ^^^^^^^^^^^^^^^^
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\sorting.py", line 341, in lexsort_indexer
    cat = Categorical(k, ordered=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\arrays\categorical.py", line 438, in __init__
    dtype = CategoricalDtype(categories, dtype.ordered)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 187, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 344, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ps_311_0722\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 540, in validate_categories
    raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique
>>>
```

### Issue Description

There's no categorical types used in the above example, so error is unexpected.

### Expected Behavior

df is already sorted, so I expect it to be returned without raising an error.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.2.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.0
numpy               : 1.25.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
>>>

</details>

**Comment by lukemanley** [comment]
Thanks for the report. It looks like this is raising in `Categorical`:

```
import pandas as pd

ser = pd.Series([-0.0, 0.0], dtype="float[pyarrow]")
pd.Categorical(ser)
```

**Comment by lukemanley** [comment]
More specifically, this looks like the disconnect:

```
In [1]: import pandas as pd

In [2]: arr = pd.array([-0.0, 0.0], dtype="float[pyarrow]")

In [3]: pd.Series(arr).is_unique
Out[3]: True

In [4]: pd.Index(arr).is_unique
Out[4]: False
```

**Comment by lukemanley** [comment]
xref: https://github.com/apache/arrow/issues/26214
