### ISSUE TITLE
BUG: Unexpected behavior when a DataFrame has MultiIndex columns and non-unique index

### ISSUE THREAD

**Issue by jonmooser** [pandas-dev/pandas#55126]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd


df = pd.DataFrame(
    np.random.random((5, 3)),
    index=[1, 2, 2, 3, 4],
    columns=pd.MultiIndex.from_product([np.arange(3), ["x"]]),
)

print(df)

"""
import numpy as np
import pandas as pd


df = pd.DataFrame(
    np.random.random((5, 3)),
    index=[1, 2, 2, 3, 4],
    columns=pd.MultiIndex.from_product([np.arange(3), ["x"]]),
)

"""
This works, but is arguably a bug.
It returns a Series of two values, but the contract of the
DataFrame.at, as I understand, is to return a single value
"""
print(df.at[2, 1])
print()

"""
This works and returns a scalar value as expected
"""
print(df.loc[1, (1, "x")])
print()

"""
Fails with 
ValueError: Invalid call for scalar access (getting)!
"""
print(df.at[1, (1, "x")])
```

### Issue Description

When a DataFrame has one axis with non-unique values, and one axis with a multi-index, the DataFrame.at method throws a confusing error.
Even if this is strictly expected, the error should be more clear (And maybe KeyError instead of ValueError)

It feels like a bug because
1. Calling loc with the same parameters works and
2. There is no ambiguity in the values passed 
(there is only one row with index=1) 

```python-traceback
Traceback (most recent call last):
  File "/Users/jonathan/Dropbox/py/debug_tests/pandas_mi_bug.py", line 33, in <module>
    print(df.at[1, (1, "x")])
          ~~~~~^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/indexing.py", line 2485, in __getitem__
    raise ValueError("Invalid call for scalar access (getting)!")
ValueError: Invalid call for scalar access (getting)!
```

### Expected Behavior

In the example above, 
```python
print(df.at[1, (1, "x")])
```
Should return a single value at that location

If it *should* throw an Error, make it clear that the duplicates in the index is the problem (concat() does this)
Also note:
* If the index contains unique values, it will work as expected
* It the columns are not a MultiIndex, it will work as expected
In other words *both* axes need to have these properties for the bug to appear

### Installed Versions

<details>
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.0.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 21.4.0
Version             : Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.0
numpy               : 1.23.4
pytz                : 2022.5
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.2.0
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.12.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

**Comment by Matheus-Ribeiro-ITA** [comment]
I faced a similar issue using `.at`. It works with `.loc`, but not` .at`. I'm using pandas 2.2.3.

Unfortunately, I wasn't able to reproduce it on a separate file. When I tried copying the values to test it, it simply worked 😅 

This is the code snippet I tried to reproduce the bug, but failed to reproduce it.

```
import pandas as pd

print(pd.__version__)

data = [
    {
        'date': pd.Timestamp('2024-10-23 23:59:59-0300', tz='Etc/GMT+3'),
        'asset_id': 77,
        'financial_institution_id': 3066.0,
        'dividend_cash_value': 0.0,
    }
]

df = pd.DataFrame(data)


df.set_index(['date', 'asset_id', 'financial_institution_id'], inplace=True)

p_key = (
    pd.Timestamp('2024-10-23 23:59:59-0300', tz='Etc/GMT+3'),
    float(77),
    float(3066.0),
)
if p_key in df.index:
    df.at[p_key, 'dividend_cash_value'] += 100

print(df)
```

**Comment by jonmooser** [comment]
Hard to know what is different in your production code, but the code you pasted above won't trigger the bug I reported. 
You need to have a DataFrame where either the columns or index has a redundancy. In your case there is only a single column, so you can't have two columns with the same name.
