### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'mesonpy'

### ISSUE THREAD

**Issue by LukeLIN-web** [pandas-dev/pandas#55146]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
I am packaging pandas to RPM packages.


+ /usr/bin/python3 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
Processing /root/rpmbuild/BUILD/pandas-2.1.0
  Running command /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpdrw8720i
  Preparing metadata (pyproject.toml) ... done
```

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
 ...
  File "/usr/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 557, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/usr/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 28, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'
```
```


### Issue Description

It may have some problem in `pyproject.toml`

I can `pip install pandas` successfully.


### Expected Behavior

It should not show `ModuleNotFoundError: No module named 'mesonpy'`

### Installed Versions

<details>

/root/miniconda3/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.4.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 4.15.0-167-generic
Version             : #175-Ubuntu SMP Wed Jan 5 01:56:07 UTC 2022
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.0
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 67.8.0
pip                 : 23.1.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by lithomas1** [comment]
You need to install ``meson-python`` for this to work.

**Comment by LukeLIN-web** [comment]
> meson-python

I have installed it. 
```
(base) [root@b09a96c7cc6a pyporter]# pip install meson-python
Requirement already satisfied: meson-python in /root/miniconda3/lib/python3.11/site-packages (0.14.0)
Requirement already satisfied: meson>=0.63.3 in /root/miniconda3/lib/python3.11/site-packages (from meson-python) (1.2.1)
Requirement already satisfied: pyproject-metadata>=0.7.1 in /root/miniconda3/lib/python3.11/site-packages (from meson-python) (0.7.1)
Requirement already satisfied: packaging>=19.0 in /root/miniconda3/lib/python3.11/site-packages (from pyproject-metadata>=0.7.1->meson-python) (23.0)
```

**Comment by lithomas1** [comment]
I think we have a hard pin on 0.13.1.

Can you try removing ``--no-deps``?

**Comment by AbhinavGor** [comment]
I am having the same issue. I have meson-python installed.
![2024-02-05-183959_1920x1080_scrot](https://github.com/pandas-dev/pandas/assets/56104674/44eeecaa-5a28-4287-8f83-03381781917d)

**Comment by HenriWahl** [comment]
Same here.

**Comment by lithomas1** [comment]
Can you open a new issue?
(Glancing really quickly I suspect the issue is that you need *exactly* meson-python version 0.13.1)

I think the original issue is resolved.

(@LukeLIN-web please correct me if I'm wrong)

**Comment by LukeLIN-web** [comment]
You could open a new issue if it still troubles you. @AbhinavGor
