### ISSUE TITLE
BUILD: pandas build failing on Gitpod due to Meson

### ISSUE THREAD

**Issue by rsm-23** [pandas-dev/pandas#55214]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-6.1.44-060144-generic-x86_64-with-glibc2.31

### Installation Method

Other

### pandas Version

dev

### Python Version

3.10.8

### Installation Logs

Getting this error after my Gitpod env is setup and I try to execute `python make.py clean`
<details>
Traceback (most recent call last):
  File "/workspace/pandas/doc/make.py", line 382, in <module>
    sys.exit(main())
  File "/workspace/pandas/doc/make.py", line 364, in main
    globals()["pandas"] = importlib.import_module("pandas")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/pandas/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/workspace/pandas/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/workspace/pandas/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
</details>

**Comment by rsm-23** [comment]
When I try to build pandas again, I get the following error.
```python
The Meson build system
  Version: 1.0.1
  Source dir: /workspace/pandas
  Build dir: /workspace/pandas/build/cp310
  Build type: native build

  ../../meson.build:2:0: ERROR: Meson version is 1.0.1 but project requires >=1.2.1

  A full log can be found at /workspace/pandas/build/cp310/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/bin/python /usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmp1rllz7pn
  cwd: /workspace/pandas
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
``` 
When I `pip install meson==1.2.1`, I get some other error like this:
```python
The Meson build system
  Version: 1.2.1
  Source dir: /workspace/pandas
  Build dir: /workspace/pandas/build/cp310
  Build type: native build

  ../../meson.build:2:0: ERROR: Tried modify read only option 'vsenv'

  A full log can be found at /workspace/pandas/build/cp310/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/bin/python /usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpejj2mnkz
  cwd: /workspace/pandas
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by rsm-23** [comment]
AFAIK, we shouldn't need to build Pandas on Gitpod, it builds automatically. And on top of that the issues are raising because Gitpod doesn't allow tinkering with the env. Overall the Gitpod development env is broken :/

**Comment by theuerc** [comment]
The build instructions for gitpod are essentially an automated version of the dockerfile installation flow on https://pandas.pydata.org/docs/development/contributing_environment.html

The issue is that the installation instructions have changed recently. It's just a one-liner fix, so I'll submit a pull request right now.
