### ISSUE TITLE
BUG: `DataFrame.astype` does not suppress exceptions when dtype is ExtensionDtype and `errors="ignore"`

### ISSUE THREAD

**Issue by yuanx749** [pandas-dev/pandas#56218]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

ser = pd.Series(["a", "b", "c"])
print(ser.astype("Float64", errors="ignore"))  # not raise

df = pd.DataFrame(["a", "b", "c"])
print(df.astype("float64", errors="ignore"))  # not raise

print(df.astype("Float64", errors="ignore"))  # this raises
```

### Issue Description

When a dataframe contains columns that can not be converted to an ExtensionDtype (such as Float64, Int64), `DataFrame.astype` raises an exception, though `errors="ignore"`. However, casting to a normal dtype or casting the column as a seris do not raise, as expected.

### Expected Behavior

I would expect no exception is raised when `errors="ignore"`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 4c520e35f95429ceaf91ea67cd2ced5aabba9619
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.10.16.3-microsoft-standard-WSL2
Version               : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0dev0+743.g4c520e35f9
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : 3.0.5
pytest                : 7.4.3
hypothesis            : 6.91.0
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : 0.58.1
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
</details>

**Comment by yuanx749** [comment]
take

**Comment by yuanx749** [comment]
From the traceback below, looks like adding the argument `errors` line 6588 in ser.astype could fix it. I would like to submit a PR it this fix is OK.

<details>

```
Traceback (most recent call last):
  File "/home/xiao/pandas/example.py", line 9, in <module>
    print(df.astype("Float64", errors="ignore"))  # this raises
  File "/home/xiao/pandas/pandas/core/generic.py", line 6588, in astype
    results = [ser.astype(dtype, copy=copy) for _, ser in self.items()]
  File "/home/xiao/pandas/pandas/core/generic.py", line 6588, in <listcomp>
    results = [ser.astype(dtype, copy=copy) for _, ser in self.items()]
  File "/home/xiao/pandas/pandas/core/generic.py", line 6592, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/xiao/pandas/pandas/core/internals/managers.py", line 448, in astype
    return self.apply(
  File "/home/xiao/pandas/pandas/core/internals/managers.py", line 381, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/xiao/pandas/pandas/core/internals/blocks.py", line 730, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/xiao/pandas/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/xiao/pandas/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/xiao/pandas/pandas/core/dtypes/astype.py", line 80, in _astype_nansafe
    return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
  File "/home/xiao/pandas/pandas/core/arrays/masked.py", line 150, in _from_sequence
    values, mask = cls._coerce_to_array(scalars, dtype=dtype, copy=copy)
  File "/home/xiao/pandas/pandas/core/arrays/numeric.py", line 264, in _coerce_to_array
    values, mask, _, _ = _coerce_to_data_and_mask(
  File "/home/xiao/pandas/pandas/core/arrays/numeric.py", line 218, in _coerce_to_data_and_mask
    values = values.astype(dtype, copy=copy)
ValueError: could not convert string to float: 'a'
```

</details>
