### ISSUE TITLE
Binary operations don't broadcast across multiindex

### ISSUE THREAD

**Issue by roblevy** [pandas-dev/pandas#5645]
related #6360

Based on [this SO question](http://stackoverflow.com/questions/20383972/binary-operation-broadcasting-across-multiindex?noredirect=1#comment30444368_20383972)

Consider the following two Series:

``` python
x = pd.DataFrame({'year':[1,1,1,1,2,2,2,2],
                  'country':['A','A','B','B','A','A','B','B'],
                  'prod':[1,2,1,2,1,2,1,2],
                  'val':[10,20,15,25,20,30,25,35]})
x = x.set_index(['year','country','prod']).squeeze()

y = pd.DataFrame({'year':[1,1,2,2],'prod':[1,2,1,2],
                  'mul':[10,0.1,20,0.2]})
y = y.set_index(['year','prod']).squeeze()
```

which look like:

``` python
    year  country  prod
    1     A        1       10
                   2       20
          B        1       15
                   2       25
    2     A        1       20
                   2       30
          B        1       25
                   2       35

year  prod
1     1       10.0
      2        0.1
2     1       20.0
      2        0.2
```

I find it to be an _extremely_ common task, to perform binary operations by distributing the values of `y` over a particular level of `x`. For example, I'd like to multiply all values of product 1 in year 1 by 10.0, regardless of `country`.

The required result is therefore as follows:

``` python
    year  country  prod
    1     A        1       100.0
                   2       2.0
          B        1       150.0
                   2       2.5
    2     A        1       400.0
                   2       6.0
          B        1       500.0
                   2       7.0
```

The binary operation .mul() doesn't work as expected:

``` python
>>> x.mul(y, level=['year','prod'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 334, in f
    return self._binop(other, op, level=level, fill_value=fill_value)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2075, in _binop
    this, other = self.align(other, level=level, join='outer')
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2570, in align
    return_indexers=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/index.py", line 954, in join
    return_indexers=return_indexers)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/index.py", line 1058, in _join_level
    raise Exception('Join on level between two MultiIndex objects '
Exception: Join on level between two MultiIndex objects is ambiguous
```

To create the required result, the user currently has to do this:

``` python
x = x.reset_index('country').sort_index()
x.val = x.val * y
x = x.reset_index().set_index(['year',
                               'country',
                               'prod']).sortlevel()
```

**Comment by roblevy** [comment]
This may or may not be relevant, but I've found a comparatively neat workaround for this problem: `unstack` the index level(s) which doesn't (don't) appear in the other `Series`.

    In [81]: x.unstack('country').mul(y, axis=0).stack()
    Out[81]: 
    year  prod  country
    1     1     A          100.0
                B          150.0
          2     A            2.0
                B            2.5
    2     1     A          400.0
                B          500.0
          2     A            6.0
                B            7.0
    dtype: float64

This is not the best possible solution since it changes the order of the index of `x` which is unexpected, but it should be pretty efficient.

**Comment by jreback** [comment]
yes this would be quite efficient

```
In [31]: x.unstack('country').mul(y, axis=0).stack().reorder_levels(x.index.names)
Out[31]: 
year  country  prod
1     A        1       100.0
      B        1       150.0
      A        2         2.0
      B        2         2.5
2     A        1       400.0
      B        1       500.0
      A        2         6.0
      B        2         7.0
dtype: float64
```

**Comment by roblevy** [comment]
Looks to me like you might (*sometimes* at least) need a `.sortlevel()` on the end of that command. At least when I did it once "in real life" I needed to.

**Comment by znicholls** [comment]
This appears to have been fixed somewhere, in the latest master you can do

```python
import pandas as pd                                                                                                                                     

x = pd.DataFrame({'year':[1,1,1,1,2,2,2,2],
                  'country':['A','A','B','B','A','A','B','B'],
                  'prod':[1,2,1,2,1,2,1,2],
                  'val':[10,20,15,25,20,30,25,35]})
x = x.set_index(['year','country','prod']).squeeze()

y = pd.DataFrame({'year':[1,1,2,2],'prod':[1,2,1,2],
                  'mul':[10,0.1,20,0.2]})
y = y.set_index(['year','prod']).squeeze()

x.mul(y, axis=0)

# result below
year  prod  country
1     1     A          100.0
            B          150.0
      2     A            2.0
            B            2.5
2     1     A          400.0
            B          500.0
      2     A            6.0
            B            7.0
dtype: float64
```

**Comment by mroeschke** [comment]
Closing as this seems addressed
