### ISSUE TITLE
BUG: mod and divmod raise NotImplementedError with pyarrow types

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#56693]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> a = pd.Series([-7], dtype="int64[pyarrow]")
>>> a % 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pd_22_env\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\arraylike.py", line 226, in __mod__
    return self._arith_method(other, operator.mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\series.py", line 5995, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\base.py", line 1382, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\ops\array_ops.py", line 273, in arithmetic_op
    res_values = op(left, right)
                 ^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\arraylike.py", line 226, in __mod__
    return self._arith_method(other, operator.mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 757, in _arith_method
    return self._evaluate_op_method(other, op, ARROW_ARITHMETIC_FUNCS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_22_env\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 743, in _evaluate_op_method
    raise NotImplementedError(f"{op.__name__} not implemented.")
NotImplementedError: mod not implemented.
>>>
```

### Issue Description

A NotImplementedError is raised.

### Expected Behavior

Behavior with numpy types:

```
>>> a = pd.Series([-7])
>>> a % 3
0    2
dtype: int64
>>>
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d4c8d82b52045f49a0bb1d762968918a06886ae9
python                : 3.11.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.2.0rc0
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.2
pip                   : 23.3.1
Cython                : None
pytest                : 7.0.1
hypothesis            : None
sphinx                : 4.2.0
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.19.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
>>>

</details>

**Comment by rohanjain101** [comment]
No arrow compute method.

**Comment by seanslma** [comment]
This error still exists in pandas 2.2.2.

Both
```py
a = pd.Series([-7], dtype="int64[pyarrow]")
a % 3
```
and
```py
d = pd.DataFrame({'x': [1,2,3]}, dtype='int64[pyarrow]')
(d['x'] + 2).mod(2)
```
failed with the error pointing to the same code:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[4], line 2
      1 a = pd.Series([-7], dtype="int64[pyarrow]")
----> 2 a % 3

File ~\conda-envs\test-env\lib\site-packages\pandas\core\ops\common.py:76, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     72             return NotImplemented
     74 other = item_from_zerodim(other)
---> 76 return method(self, other)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\arraylike.py:226, in OpsMixin.__mod__(self, other)
    224 @unpack_zerodim_and_defer("__mod__")
    225 def __mod__(self, other):
--> 226     return self._arith_method(other, operator.mod)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\series.py:6135, in Series._arith_method(self, other, op)
   6133 def _arith_method(self, other, op):
   6134     self, other = self._align_for_op(other)
-> 6135     return base.IndexOpsMixin._arith_method(self, other, op)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\base.py:1382, in IndexOpsMixin._arith_method(self, other, op)
   1379     rvalues = np.arange(rvalues.start, rvalues.stop, rvalues.step)
   1381 with np.errstate(all="ignore"):
-> 1382     result = ops.arithmetic_op(lvalues, rvalues, op)
   1384 return self._construct_result(result, name=res_name)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\ops\array_ops.py:273, in arithmetic_op(left, right, op)
    260 # NB: We assume that extract_array and ensure_wrapped_if_datetimelike
    261 #  have already been called on `left` and `right`,
    262 #  and `maybe_prepare_scalar_for_op` has already been called on `right`
    263 # We need to special-case datetime64/timedelta64 dtypes (e.g. because numpy
    264 # casts integer dtypes to timedelta64 when operating with timedelta64 - GH#22390)
    266 if (
    267     should_extension_dispatch(left, right)
    268     or isinstance(right, (Timedelta, BaseOffset, Timestamp))
   (...)
    271     # Timedelta/Timestamp and other custom scalars are included in the check
    272     # because numexpr will fail on it, see GH#31457
--> 273     res_values = op(left, right)
    274 else:
    275     # TODO we should handle EAs consistently and move this check before the if/else
    276     # (https://github.com/pandas-dev/pandas/issues/41165)
    277     # error: Argument 2 to "_bool_arith_check" has incompatible type
    278     # "Union[ExtensionArray, ndarray[Any, Any]]"; expected "ndarray[Any, Any]"
    279     _bool_arith_check(op, left, right)  # type: ignore[arg-type]

File ~\conda-envs\test-env\lib\site-packages\pandas\core\ops\common.py:76, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     72             return NotImplemented
     74 other = item_from_zerodim(other)
---> 76 return method(self, other)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\arraylike.py:226, in OpsMixin.__mod__(self, other)
    224 @unpack_zerodim_and_defer("__mod__")
    225 def __mod__(self, other):
--> 226     return self._arith_method(other, operator.mod)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\arrays\arrow\array.py:787, in ArrowExtensionArray._arith_method(self, other, op)
    786 def _arith_method(self, other, op):
--> 787     return self._evaluate_op_method(other, op, ARROW_ARITHMETIC_FUNCS)

File ~\conda-envs\test-env\lib\site-packages\pandas\core\arrays\arrow\array.py:773, in ArrowExtensionArray._evaluate_op_method(self, other, op, arrow_funcs)
    771 pc_func = arrow_funcs[op.__name__]
    772 if pc_func is NotImplemented:
--> 773     raise NotImplementedError(f"{op.__name__} not implemented.")
    775 result = pc_func(self._pa_array, other)
    776 return type(self)(result)

NotImplementedError: mod not implemented.
```
