### ISSUE TITLE
BUG: Interchange with PyArrow types does not match PyArrow behavior

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#56801]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import datetime
>>> import pandas as pd
>>> df = pd.DataFrame([[datetime.date(2023, 1, 1)]], dtype=pd.ArrowDtype(pa.date32()))
>>> df.dtypes
0    date32[day][pyarrow]
dtype: object

>>> df.__dataframe__().get_column(0).get_buffers()
{'data': (PandasBuffer({'bufsize': 8, 'ptr': 103818415071840, 'device': 'CPU'}), (<DtypeKind.DATETIME: 22>, 64, 'tdD', '=')), 'validity': None, 'offsets': None}

>>> pa.Table.from_pandas(df).__dataframe__().get_column(0).get_buffers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/willayd/mambaforge/envs/pantab-dev/lib/python3.12/site-packages/pyarrow/interchange/dataframe.py", line 139, in get_column
    return _PyArrowColumn(self._df.column(i),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willayd/mambaforge/envs/pantab-dev/lib/python3.12/site-packages/pyarrow/interchange/column.py", line 239, in __init__
    self._dtype = self._dtype_from_arrowdtype(dtype, bit_width)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willayd/mambaforge/envs/pantab-dev/lib/python3.12/site-packages/pyarrow/interchange/column.py", line 322, in _dtype_from_arrowdtype
    raise ValueError(
ValueError: Data type date32[day] not supported by interchange protocol
```

### Issue Description

I find it surprising that pandas provides a different value to the interchange protocol for an Arrow dtype than Arrow itself would (side note, I am also surprised Arrow fails here)

cc @MarcoGorelli 

### Expected Behavior

Should match arrow

### Installed Versions

main

**Comment by jorisvandenbossche** [comment]
> I find it surprising that pandas provides a different value to the interchange protocol for an Arrow dtype than Arrow itself

Essentially the current implementation of the interchange protocol in pandas is based on numpy, so it converts whatever other type (our own nullable, or Arrow dtypes) to numpy. Which is the root cause of the various issues you opened, I think

**Comment by WillAyd** [comment]
I assume there is historical reasoning to that, but is there any reason you think it should remain that way going forward?

**Comment by jorisvandenbossche** [comment]
No, there is definitely no good reason to not support it going forward, it was just to limit the scope of the initial PR I assume.

**Comment by mroeschke** [comment]
`__dataframe__` has been deprecated in https://github.com/pandas-dev/pandas/pull/62920 so closing as won't fix
