### ISSUE TITLE
BUG: Inconsistent handling of `converters=...` in `read_csv` C parser and other IO functions

### ISSUE THREAD

**Issue by oliverbeagley-pgg** [pandas-dev/pandas#56848]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import io

import pandas as pd

csv_text = 'field\n"1.23,4.56"\n'


def convert(val: str) -> list[float]:
    return [float(x) for x in val.split(",")]


converters = {"field": convert}

# Works
pd.read_csv(io.StringIO(csv_text), converters=converters, engine="c")

# Doesn't work
pd.read_csv(io.StringIO(csv_text), converters=converters, engine="python")

# Doesn't work (openpyxl)
with io.BytesIO() as xlsx_buffer:
    pd.read_csv(io.StringIO(csv_text)).to_excel(xlsx_buffer, index=False)
    xlsx_buffer.seek(0)

    pd.read_excel(xlsx_buffer, converters=converters)


# Doesn't work (lxml)
with io.BytesIO() as xml_buffer:
    pd.read_csv(io.StringIO(csv_text)).to_xml(xml_buffer, index=False)
    xml_buffer.seek(0)

    pd.read_xml(xml_buffer, converters=converters)
```

### Issue Description

Unsure if bug or just a lack of documentation, but depending on the method converters is handled differently for different methods, and for csvs it is dependent on the engine.

It appears the python parser will not handle unhashable types for the converted values, but the `C` parser for `read_csv` will.

### Expected Behavior

Each IO method with converter handles the argument the same.

I can see merits for either way, ie converters should only convert to a specific scalar value and transformation is otherwise done after read, or given pandas supports complex types as values you can use converters for any arbitrary conversion.

In either case I would expect the use of the argument to be the same for any IO method for which it is present, or for it to be at least documented more clearly.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.133.1-microsoft-standard-WSL2
Version             : #1 SMP Thu Oct 5 21:02:42 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 5.1.0
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.2
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : None
pyqt5               : None

</details>

**Comment by ParfaitG** [comment]
Thank you for your interesting post! I see your example attempts to convert a string value to a `list` type within a column. The intended use of `converters` is more for scalar, atomic values and not embedded iterables. Hence, why the failed attempts raise:

> TypeError: unhashable type: 'list'

Arguably, you can use a different data structure to store such embedded lists than the DataFrame which is intended to store byte-size data of primitive types (`boolean`, `str`, `int`, `float`) included their extensions in a two-dimensional array.

Also, unlike `read_excel` and `read_xml` that interface to external packages, `read_csv` uses pandas specific Cython and Python libraries simply given that the delimited text file is the most popular, defacto industry data format. Hence, more custom features are available to read CSV text files and handling of this special need to convert string to list differ between the IO methods. 

Users can always run [`Series.str.split`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html) after parsing the data: `df["field"] = df["field"].str.split(',')`. Really, `converters` may serve as a convenience feature not meant to handle complex cases, requiring ad-hoc data wrangling.

**Comment by oliverbeagley-pgg** [comment]
The documentation is not clear on the intended of converters if that is the case I don't think.

The docs say:
> Dict of functions for converting values in certain columns. Keys can either be integers or column labels.

It is a little more descriptive for read_excel but still does not specifiy it is intended to return scalars, and nor does the user guide on I/O.

**Comment by ParfaitG** [comment]
Understood. The term _values_ is likely intended to generalize for the base case for data analytics that interact with scalars in cells and not complex types like embedded iterables and objects. Docs would need to expound on all unhashable types and class objects in Python of which is open-ended in number: lists, dicts, sets, numpy arrays, pandas Series/DataFrames, ...

But `converters` mainly depends on the method used. In fact, had you used a hashable type like `tuple` in method, `converters` works across the IO methods in your example! And all scalar types (`bool`, `integer`, `float`, `str`, `None`) are hashable.

```python
def convert(val: str) -> dict[float]:
    return tuple(float(x) for x in val.split(","))
```

Maybe docs can indicate that methods of `converters` should return hashable types if not using the c engine in `read_csv`? But then this may get deep under the hood since data analysts and scientists, principal users of pandas, would need to know what are hashable types which arguably fall in the domain of computer programming.

**Comment by oliverbeagley-pgg** [comment]
Understood on hashable types, but the current error message when converters returns a hashable type when using the python parser is just `TypeError: unhashable type: 'list'` (full traceback below), so a user is forced to know about hashable types to understand the error message. Probably an argument there that the error needs to be reemitted with a bit more detail too.

Could the docs just link to the page on data types ([here](https://pandas.pydata.org/docs/reference/arrays.html) or [here](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes)) and highlight that a converter function is intended to be used to return one of the concrete types there, with a note that something that would be classified as an object dtype isn't guaranteed to have support? (reality may be that it needs to be a numpy type based on the source code for the function that errors out expects an ndarray)


<details>
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "<snip>/python3.10/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
  File "<snip>/python3.10/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "<snip>/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 289, in read
    conv_data = self._convert_data(data)
  File "<snip>/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 360, in _convert_data
    return self._convert_to_ndarrays(
  File "<snip>/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 565, in _convert_to_ndarrays
    cvals, na_count = self._infer_types(
  File "<snip>/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 743, in _infer_types
    na_count = parsers.sanitize_objects(values, na_values)
  File "parsers.pyx", line 2148, in pandas._libs.parsers.sanitize_objects
TypeError: unhashable type: 'list'
```

**Comment by ParfaitG** [comment]
What docs do you recommend the change and what specific wording change? Usually, we want to keep pandas docs brief and not expound to cover every possible use case.  Also, we would need to test each of those concrete types to find what `converters` can support. 

Since the `converters` argument is not central for the IO read functions but serves more as a convenience function to handle `dtypes`, I wonder if extended doc notes would cause more confusion than not. But if you insist it is worthwhile, I can defer to others on the team.

**Comment by rhshadrach** [comment]
It seems to me support for unhashable results was explicitly added in #68689 (`test_converter_unhashable_output_with_na_values`), and from a cursory investigation that supporting in the Python engine won't be difficult. Assuming that is the case, I'm positive on supporting them here.
