### ISSUE TITLE
BUG: `to_datetime` raises `OutOfBoundsDatetime` rather than falling back to `datetime.datetime`

### ISSUE THREAD

**Issue by kroche98** [pandas-dev/pandas#57017]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.to_datetime("2998-01-01")


```python-traceback
Traceback (most recent call last):
  File "conversion.pyx", line 326, in pandas._libs.tslibs.conversion._TSObject.ensure_reso
  File "np_datetime.pyx", line 683, in pandas._libs.tslibs.np_datetime.convert_reso
OverflowError: result would overflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/path/to/file.py", line 2, in <module>
    pd.to_datetime("2998-01-01")
  File "~/path/to/python/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1101, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "~/path/to/python/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 435, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64(
  File "~/path/to/python/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 2398, in objects_to_datetime64
    result, tz_parsed = tslib.array_to_datetime(
  File "tslib.pyx", line 414, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 596, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 571, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 332, in pandas._libs.tslibs.conversion._TSObject.ensure_reso
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2998-01-01, at position 0

```

### Issue Description

According to the documentation for `to_datetime`, the return type falls back to `datetime.datetime` in case of out-of-range timestamp parsing. However, trying to parse any date greater than `pandas.Timestamp.max` raises `OutOfBoundsDatetime`.

### Expected Behavior

The code should return a `datetime.datetime` object.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.9.6.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.2.0
Version               : Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 58.0.4
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by Aloqeely** [comment]
in `pandas/_libs/tslib.pyx`: lines 582-589:
```pyx
except (TypeError, OverflowError, ValueError) as ex:
    ex.args = (f"{ex}, at position {i}",)
    if is_coerce:
        iresult[i] = NPY_NAT
        continue
    elif is_raise:
        raise
    return values, None
```

The error is raised here but as far as I'm concerned there are no fallback attempts, I think this at least calls for a documentation change until fallback functionality is implemented (or fixed?)

**Comment by jbrockmendel** [comment]
With non-nano, this now returns a Timestamp with "s" unit.  Closing.
