### ISSUE TITLE
BUG: Casting dtype of large datetime values raises an error inconsistent with resolution

### ISSUE THREAD

**Issue by amanlai** [pandas-dev/pandas#58147]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from datetime import datetime, UTC
lst = [datetime(3000,1,1, tzinfo=UTC), datetime(939,12,31, tzinfo=UTC)]
s = pd.Series(lst, dtype='datetime64[s]')
```
```


### Issue Description

The above code raises the following error:
```none
Traceback (most recent call last):
  File "<pyshell#75>", line 1, in <module>
    pd.Series(lst, dtype='datetime64[ns]')
  File "C:\Python\Python312\Lib\site-packages\pandas\core\series.py", line 512, in __init__
    data = sanitize_array(data, index, dtype, copy)
  File "C:\Python\Python312\Lib\site-packages\pandas\core\construction.py", line 628, in sanitize_array
    subarr = _try_cast(data, dtype, copy)
  File "C:\Python\Python312\Lib\site-packages\pandas\core\construction.py", line 785, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
  File "C:\Python\Python312\Lib\site-packages\pandas\core\dtypes\cast.py", line 1216, in maybe_cast_to_datetime
    dta = DatetimeArray._from_sequence(value, dtype=dtype)
  File "C:\Python\Python312\Lib\site-packages\pandas\core\arrays\datetimes.py", line 297, in _from_sequence
    return cls._from_sequence_not_strict(scalars, dtype=dtype, copy=copy)
  File "C:\Python\Python312\Lib\site-packages\pandas\core\arrays\datetimes.py", line 339, in _from_sequence_not_strict
    subarr, tz, inferred_freq = _sequence_to_dt64ns(
  File "C:\Python\Python312\Lib\site-packages\pandas\core\arrays\datetimes.py", line 2226, in _sequence_to_dt64ns
    data, inferred_tz = objects_to_datetime64ns(
  File "C:\Python\Python312\Lib\site-packages\pandas\core\arrays\datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 487, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 767, in pandas._libs.tslibs.conversion.parse_pydatetime
  File "np_datetime.pyx", line 231, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 3000-01-01 00:00:00, at position 0
```
The above code attempts to cast to `datetime[s]`, not `datetime[ns]`, so the error seems inconsistent.

Weirdly, if I cast each datetime into a POSIX timestamp and try again, the casting works without errors.
```python
lst1 = [x.timestamp() for x in lst]
s = pd.Series(lst1, dtype='datetime64[s]')    # <--- OK
```

### Expected Behavior

Since the POSIX timestamp casting works fine, the expected behavior is the produce the following output:
```none
0   3000-01-01
1    939-12-31
dtype: datetime64[s]
```

At the minimum, the error message should not say `Out of bounds nanosecond timestamp: ` because the casting resolution is not nanosecond.

### Installed Versions

<details>

Python 3.12.0
pandas==2.1.1
numpy==1.26.0
Windows 10 64-bit
</details>

**Comment by asishm** [comment]
on main this raises as `ValueError: Cannot convert timezone-aware data to timezone-naive dtype. Use pd.Series(values).dt.tz_localize(None) instead.` which makes sense

`s = pd.Series(lst, dtype='datetime64[s, UTC]')` this works on main

**Comment by amanlai** [comment]
@asishm `s = pd.Series(lst, dtype='datetime64[s, UTC]')` throws an `OverflowError: value too large` error but it works fine on main, so I guess it's a non-issue. Thanks for clarification.

**Comment by asishm** [comment]
Not sure when it was fixed, but `s = pd.Series(lst, dtype='datetime64[s, UTC]')` also works in 2.2.1
