### ISSUE TITLE
BUG: Whether using pip or whl, i am unable to install pandas on my pc.

### ISSUE THREAD

**Issue by GaoRP** [pandas-dev/pandas#58191]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Microsoft Windows [版本 10.0.19042.631]
(c) 2020 Microsoft Corporation. 保留所有权利。

C:\Users\T>pip install pandas
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pandas
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/59/2afa81b9fb300c90531803c0fd43ff4548074fa3e8d0f747ef63b3b5e77a/pandas-2.2.1.tar.gz (4.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [27 lines of output]
      + meson setup C:\Users\T\AppData\Local\Temp\pip-install-zmuiyeag\pandas_2222b59c0f8e4b79a46756caf4d840e2 C:\Users\T\AppData\Local\Temp\pip-install-zmuiyeag\pandas_2222b59c0f8e4b79a46756caf4d840e2\.mesonpy-vpzjukf0\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\T\AppData\Local\Temp\pip-install-zmuiyeag\pandas_2222b59c0f8e4b79a46756caf4d840e2\.mesonpy-vpzjukf0\build\meson-python-native-file.ini
      Traceback (most recent call last):
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\msetup.py", line 178, in generate
          env = environment.Environment(self.source_dir, self.build_dir, self.options)
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\environment.py", line 552, in __init__
          config = coredata.parse_machine_files(self.coredata.config_files)
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\coredata.py", line 1030, in parse_machine_files
          parser = MachineFileParser(filenames)
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\coredata.py", line 972, in __init__
          self.parser.read(filenames)
        File "C:\Users\T\AppData\Local\Temp\pip-build-env-f_2n0qyb\overlay\Lib\site-packages\mesonbuild\coredata.py", line 959, in read
          return super().read(filenames, encoding)
        File "C:\软件之家\Python 3.10.11\lib\configparser.py", line 699, in read
          self._read(fp, filename)
        File "C:\软件之家\Python 3.10.11\lib\configparser.py", line 1022, in _read
          for lineno, line in enumerate(fp, start=1):
        File "C:\软件之家\Python 3.10.11\lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 27: invalid continuation byte

      ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Issue Description

Whether using pip or whl, i am unable to install pandas on my pc.
Please fix it as soon as possible，thank u very much.

### Expected Behavior

Whether using pip or whl, i am unable to install pandas on my pc.

### Installed Versions

<details>

'pd.show_versions' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

</details>

**Comment by lithomas1** [comment]
> https://pypi.tuna.tsinghua.edu.cn/packages/3d/59/2afa81b9fb300c90531803c0fd43ff4548074fa3e8d0f747ef63b3b5e77a/pandas-2.2.1.tar.gz (4.4 MB)


This looks like a source distribution, and is not an official wheel/source distribution provided by us.

Are you able to install wheels from pypi.org?

**Comment by mroeschke** [comment]
This doesn't look like a issue with pandas' distributed packages so closing
