### ISSUE TITLE
BUILD: Pandas 2.1.1 DLL load failed

### ISSUE THREAD

**Issue by EmmaIKirk** [pandas-dev/pandas#58405]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.22000-SP0

### Installation Method

pip install

### pandas Version

2.1.1

### Python Version

3.10.11

### Installation Logs

<details>

When install pandas 2.1.1, after import pandas, the below error occurred.
But when install pandas 2.0.3, import pandas is ok.

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\__init__.py", line 59, in <module>
    from pandas.core.api import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\groupby\generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\generic.py", line 187, in <module>
    from pandas.core.window import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "E:\CODE\venv\MetaGPT-310\lib\site-packages\pandas\core\window\ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed while importing aggregations: The specified module could not be found.

</details>

**Comment by EmmaIKirk** [comment]
> Can you please share the output of the `pip install` command that you used to install pandas 2.1.1?

Collecting pandas==2.1.1
  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.22.4 in e:\code\venv\metagpt-310\lib\site-packages (from pandas==2.1.1) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\code\venv\metagpt-310\lib\site-packages (from pandas==2.1.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\code\venv\metagpt-310\lib\site-packages (from pandas==2.1.1) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in e:\code\venv\metagpt-310\lib\site-packages (from pandas==2.1.1) (2024.1)
Requirement already satisfied: six>=1.5 in e:\code\venv\metagpt-310\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.1.1) (1.16.0)
Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)
Installing collected packages: pandas
Successfully installed pandas-2.1.1

**Comment by jbrockmendel** [comment]
Does newer pandas (on newer python) work for you?
