### ISSUE TITLE
BUG: can't support numpy2.2,how to deal with it

### ISSUE THREAD

**Issue by Franklyn1987** [pandas-dev/pandas#59023]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\Franklyn-Article\2.工具箱\源码\Python\qiguaheji.py", line 14, in 
import qimendunjia as qi
File "D:\Franklyn-Article\2.工具箱\源码\Python\qimendunjia.py", line 14, in 
import pandas as pd
File "C:\Python312\Lib\site-packages\pandas_init_.py", line 62, in 
from pandas.core.api import (
File "C:\Python312\Lib\site-packages\pandas\core\api.py", line 28, in 
from pandas.core.arrays import Categorical
File "C:\Python312\Lib\site-packages\pandas\core\arrays_init_.py", line 1, in 
from pandas.core.arrays.arrow import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow_init_.py", line 5, in 
from pandas.core.arrays.arrow.array import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in 
from pandas.core.arrays.masked import BaseMaskedArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in 
from pandas.core import (
File "C:\Python312\Lib\site-packages\pandas\core\nanops.py", line 52, in 
bn = import_optional_dependency("bottleneck", errors="warn")
File "C:\Python312\Lib\site-packages\pandas\compat_optional.py", line 135, in import_optional_dependency
module = importlib.import_module(name)
File "C:\Python312\Lib\importlib_init_.py", line 90, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Python312\Lib\site-packages\bottleneck_init.py", line 7, in 
from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
Traceback (most recent call last):
File "C:\Users\cuili\AppData\Roaming\Python\Python312\site-packages\numpy\core_multiarray_umath.py", line 44, in getattr
raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

### Issue Description

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\Franklyn-Article\2.工具箱\源码\Python\qiguaheji.py", line 14, in 
import qimendunjia as qi
File "D:\Franklyn-Article\2.工具箱\源码\Python\qimendunjia.py", line 14, in 
import pandas as pd
File "C:\Python312\Lib\site-packages\pandas_init_.py", line 62, in 
from pandas.core.api import (
File "C:\Python312\Lib\site-packages\pandas\core\api.py", line 28, in 
from pandas.core.arrays import Categorical
File "C:\Python312\Lib\site-packages\pandas\core\arrays_init_.py", line 1, in 
from pandas.core.arrays.arrow import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow_init_.py", line 5, in 
from pandas.core.arrays.arrow.array import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in 
from pandas.core.arrays.masked import BaseMaskedArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in 
from pandas.core import (
File "C:\Python312\Lib\site-packages\pandas\core\nanops.py", line 52, in 
bn = import_optional_dependency("bottleneck", errors="warn")
File "C:\Python312\Lib\site-packages\pandas\compat_optional.py", line 135, in import_optional_dependency
module = importlib.import_module(name)
File "C:\Python312\Lib\importlib_init_.py", line 90, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Python312\Lib\site-packages\bottleneck_init.py", line 7, in 
from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
Traceback (most recent call last):
File "C:\Users\cuili\AppData\Roaming\Python\Python312\site-packages\numpy\core_multiarray_umath.py", line 44, in getattr
raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

### Expected Behavior

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\Franklyn-Article\2.工具箱\源码\Python\qiguaheji.py", line 14, in 
import qimendunjia as qi
File "D:\Franklyn-Article\2.工具箱\源码\Python\qimendunjia.py", line 14, in 
import pandas as pd
File "C:\Python312\Lib\site-packages\pandas_init_.py", line 62, in 
from pandas.core.api import (
File "C:\Python312\Lib\site-packages\pandas\core\api.py", line 28, in 
from pandas.core.arrays import Categorical
File "C:\Python312\Lib\site-packages\pandas\core\arrays_init_.py", line 1, in 
from pandas.core.arrays.arrow import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow_init_.py", line 5, in 
from pandas.core.arrays.arrow.array import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in 
from pandas.core.arrays.masked import BaseMaskedArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in 
from pandas.core import (
File "C:\Python312\Lib\site-packages\pandas\core\nanops.py", line 52, in 
bn = import_optional_dependency("bottleneck", errors="warn")
File "C:\Python312\Lib\site-packages\pandas\compat_optional.py", line 135, in import_optional_dependency
module = importlib.import_module(name)
File "C:\Python312\Lib\importlib_init_.py", line 90, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Python312\Lib\site-packages\bottleneck_init.py", line 7, in 
from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
Traceback (most recent call last):
File "C:\Users\cuili\AppData\Roaming\Python\Python312\site-packages\numpy\core_multiarray_umath.py", line 44, in getattr
raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

### Installed Versions

<details>

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\Franklyn-Article\2.工具箱\源码\Python\qiguaheji.py", line 14, in 
import qimendunjia as qi
File "D:\Franklyn-Article\2.工具箱\源码\Python\qimendunjia.py", line 14, in 
import pandas as pd
File "C:\Python312\Lib\site-packages\pandas_init_.py", line 62, in 
from pandas.core.api import (
File "C:\Python312\Lib\site-packages\pandas\core\api.py", line 28, in 
from pandas.core.arrays import Categorical
File "C:\Python312\Lib\site-packages\pandas\core\arrays_init_.py", line 1, in 
from pandas.core.arrays.arrow import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow_init_.py", line 5, in 
from pandas.core.arrays.arrow.array import ArrowExtensionArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in 
from pandas.core.arrays.masked import BaseMaskedArray
File "C:\Python312\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in 
from pandas.core import (
File "C:\Python312\Lib\site-packages\pandas\core\nanops.py", line 52, in 
bn = import_optional_dependency("bottleneck", errors="warn")
File "C:\Python312\Lib\site-packages\pandas\compat_optional.py", line 135, in import_optional_dependency
module = importlib.import_module(name)
File "C:\Python312\Lib\importlib_init_.py", line 90, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Python312\Lib\site-packages\bottleneck_init.py", line 7, in 
from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
Traceback (most recent call last):
File "C:\Users\cuili\AppData\Roaming\Python\Python312\site-packages\numpy\core_multiarray_umath.py", line 44, in getattr
raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
</details>

**Comment by mbroton** [comment]
This may be because a new major version of numpy was [released](https://pypi.org/project/numpy/#history) on June 16, and in pandas pyproject.toml (version 2.2.2) there is:
```
"numpy>=1.22.4; python_version<'3.11'",
"numpy>=1.23.2; python_version=='3.11'",
"numpy>=1.26.0; python_version>='3.12'",
```
which was causing problems in my case - I had to pin version of numpy to <2 to fix it.

**Comment by OliverHKU** [comment]
> This may be because a new major version of numpy was [released](https://pypi.org/project/numpy/#history) on June 16, and in pandas pyproject.toml (version 2.2.2) there is:
> 
> ```
> "numpy>=1.22.4; python_version<'3.11'",
> "numpy>=1.23.2; python_version=='3.11'",
> "numpy>=1.26.0; python_version>='3.12'",
> ```
> 
> which was causing problems in my case - I had to pin version of numpy to <2 to fix it.

Wondering what the reason was for not setting an upper limit. It doesn't make sense to assume that any newest version of `numpy` will still be compatible with `pandas`. I know that `numpy` hadn't been releasing a new major version for ages before yesterday but other dependencies are also treated this way: https://github.com/pandas-dev/pandas/blob/888295988e8cb8545a7f8b649e275255ffad7b9c/pyproject.toml#L33-L35

**Comment by seberg** [comment]
Just to clarify, this is a `bottleneck` issue, not a pandas one.  Need to avoid `bottleneck`, install the pre-release version `'bottleneck>= 1.4.0rc5'`, or downgrade NumPy for now.
(I assume `bottleneck` will do a release very soon, but there should be nothing to do in pandas.)

**Comment by OliverHKU** [comment]
> Just to clarify, this is a `bottleneck` issue, not a pandas one. Need to avoid `bottleneck`, install the pre-release version `'bottleneck>= 1.4.0rc5'`, or downgrade NumPy for now. (I assume `bottleneck` will do a release very soon, but there should be nothing to do in pandas.)

It is still not a good practice to define dependencies the way it is, unless there's a reason for it, right?

**Comment by seberg** [comment]
Yes, just to say the version bounds are correct here to the degree possible.  Not saying it is may not be good to do it for other dependencies, but you can't do much for depdencies using calver anyway (they somewhat promise to not do major releases).

For larger projects (like pandas), there is also the idea to pin to a version ~1 year in the future as allowing sufficient flexibility while preventing this type of thing and if someone uses semver things are fine.

But, sloppy versioning has its advantages and opinions on best practices differ.

**Comment by seberg** [comment]
Bottleneck has done its release, if you update it, things may just work for you now (assuming there is no other thing missing).

**Comment by Handique-lab** [comment]
I had this same issue while working with OpenCV, you can give the solutions a try for Pandas instead.

Save your files(if needed) and follow the drill

**First try**
downgrading NumPy as newer versions sometimes creates the problem
if it does not solve your issue then go for the second try

**Second try**
Uninstall Anaconda (if you are using it)
and install an older version of the same

*as you have to install OpenCV then NumPy gets installed along with it (may happen with other packages too) and if by any chance you have NumPy already installed in the environment then remove **or** downgrade it and check if it works* 

or else go for the ***third try***

**Third try**
If it still shows the issue then repeat the *Second try* and this time install Pandas without any dependency

use the command below:
**pip install pandas --no-deps** for your case

the command is to be executed in the conda terminal

The second and third tries worked for me, I did not create a new environment instead, I installed it in the **base environment**

I would suggest you create a new environment and install Pandas without dependency
