### ISSUE TITLE
BUG (string dtype): logical operation with bool and string failing

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#60234]
We do allow using logical operators like `|` to be used with non-boolean data (at which point the non-bool series would be cast to bool, I assume). For example:

```python
>>> ser1 = pd.Series([False, False])
>>> ser2 = pd.Series([0.0, 0.1])
>>> ser1 | ser2
0    False
1     True
dtype: bool
```

This also worked with strings in object dtype:

```python
>>> ser2 = pd.Series(["", "b"], dtype=object)
>>>  ser1 | ser2
0    False
1     True
dtype: bool
```

but currently fails with the pyarrow-backed string dtype:

```python
>>> pd.options.future.infer_string = True
>>> ser2 = pd.Series(["", "b"])
>>> ser1 | ser2
...

File ~/scipy/repos/pandas/pandas/core/arrays/arrow/array.py:833, in ArrowExtensionArray._logical_method(self, other, op)
    831     return self._evaluate_op_method(other, op, ARROW_BIT_WISE_FUNCS)
    832 else:
--> 833     return self._evaluate_op_method(other, op, ARROW_LOGICAL_FUNCS)

File ~/scipy/repos/pandas/pandas/core/arrays/arrow/array.py:824, in ArrowExtensionArray._evaluate_op_method(self, other, op, arrow_funcs)
    822     result = pc_func(self._pa_array, other)
    823 except pa.ArrowNotImplementedError as err:
--> 824     raise TypeError(self._op_method_error_message(other_original, op)) from err
    825 return type(self)(result)

TypeError: operation 'ror_' not supported for dtype 'str' with dtype 'bool'
```

**Comment by simonjayhawkins** [comment]
> but currently fails with the pyarrow-backed string dtype:

also fails with the numpy backed string dtype: 

```python
>>> ser2 = pd.Series(["", "b"], dtype="string[python]")
>>> ser2
0     
1    b
dtype: string
>>> 
>>> ser2.dtype.storage
'python'
>>> 
>>> ser1 | ser2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/pandas/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/simon/pandas/pandas/core/arraylike.py", line 79, in __or__
    return self._logical_method(other, operator.or_)
  File "/home/simon/pandas/pandas/core/series.py", line 5881, in _logical_method
    res_values = ops.logical_op(lvalues, rvalues, op)
  File "/home/simon/pandas/pandas/core/ops/array_ops.py", line 439, in logical_op
    res_values = op(lvalues, rvalues)
  File "/home/simon/pandas/pandas/core/arrays/numpy_.py", line 193, in __array_ufunc__
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: unsupported operand type(s) for |: 'bool' and 'str'
>>> 
```

**Comment by ldlin1** [comment]
take

**Comment by ldlin1** [comment]
take

**Comment by ldlin1** [comment]
Hi @jorisvandenbossche, the bot doesn't seem to be working for me, would it possible for you to manually assign this issue to me?

**Comment by ldlin1** [comment]
take

**Comment by jorisvandenbossche** [comment]
It seems to have worked now

**Comment by jbrockmendel** [comment]
ideally we'd have this raise and require users to cast to bool dtype before operating?

**Comment by jorisvandenbossche** [comment]
Yes, but like https://github.com/pandas-dev/pandas/issues/61881 I think we would _ideally_ first deprecate it instead of just changing it?

**Comment by jbrockmendel** [comment]
Sure

**Comment by rhshadrach** [comment]
@jorisvandenbossche - I think this should be enforced in 3.0, is that right?
