### ISSUE TITLE
BUG: setting new items with .loc doesn't work for constant sequences 

### ISSUE THREAD

**Issue by podshumok** [pandas-dev/pandas#7787]
One can construct DataFrame with frozensets in the index:

```
 >>> import pandas
 >>> a = frozenset([1])
 >>> b = frozenset([1, 2])
 >>> c = frozenset([1, 2, 3])
 >>> 
 >>> frame = pandas.DataFrame(index=[a, b], columns=[c])
 >>> frame
        (1, 2, 3)
 (1)          NaN
 (1, 2)       NaN
```

Setting new values for existing items works:

```
 >>> frame.loc[a] = 0
 >>> frame
        (1, 2, 3)
 (1)            0
 (1, 2)       NaN
 >>> frame[c] = 1
 >>> frame
         (1, 2, 3)
 (1)             1
 (1, 2)          1
 >>> frame[frozenset([4])] = 1
 >>> frame
         (1, 2, 3)  (4)
 (1)             1    1
 (1, 2)          1    1
```

But new items cannot be created:

```
 >>> frame.loc[frozenset([3])] = 1
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "venv/lib/python2.7/site-packages/pandas/core/indexing.py", line 118, in __setitem__
     indexer = self._convert_to_indexer(key, is_setter=True)
   File "venv/lib/python2.7/site-packages/pandas/core/indexing.py", line 1085, in _convert_to_indexer
     raise KeyError('%s not in index' % objarr[mask])
 KeyError: '[3] not in index'
```

**Comment by jreback** [comment]
this is a very thorny problem and basically breaks indexing.

**Comment by mroeschke** [comment]
I believe we are moving away from making the indexing code more permissive to indexing types such as `frozenset`. Going to close as a wont fix but happy to reopen if there's more interest from the community
