### ISSUE TITLE
BUG: coercion of non-M8[ns] in datetime ops

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7996]
```
import datetime
s = pd.Series(pd.date_range('20130101',periods=3))
s-pd.Timestamp('20130101')
s-datetime.datetime(2013,1')
```

This fails as the datetime64 is not converted properly (because numpy datetime ops suck)

```
s-np.datetime64('20130101')
```

e.g. `np.datetime64('20130101').astype('M8[ns]')` is a bug, no?

**Comment by jbrockmendel** [comment]
For copy/pasting, the OP has a typo in line `s-datetime.datetime(2013,1')`.

AFAICT the `np.datetime64('20130101')` is unsalvageable and the open issue is `s-np.datetime64('2013-01-01')`.  Is that correct?

**Comment by jbrockmendel** [comment]
Slightly different kind of wrong when using a DatetimeIndex instead of Series:
```
>>> dti = pd.date_range('20130101',periods=3)
>>> dti - np.datetime64('2013-01-01')
DatetimeIndex(['1970-01-01', '1970-01-02', '1970-01-03'], dtype='datetime64[ns]', freq=None)
```

**Comment by jorisvandenbossche** [comment]
> the open issue is s-np.datetime64('2013-01-01'). Is that correct?

Yes, it is:

```
In [2]: import datetime
   ...: s = pd.Series(pd.date_range('20130101',periods=3))
   ...: 

In [3]: s-pd.Timestamp('20130101')
Out[3]: 
0   0 days
1   1 days
2   2 days
dtype: timedelta64[ns]

In [5]: s-datetime.datetime(2013,1,1)
Out[5]: 
0   0 days
1   1 days
2   2 days
dtype: timedelta64[ns]

In [6]: s-np.datetime64('2013-01-01')
Out[6]: 
0   15705 days 23:59:59.999984
1   15706 days 23:59:59.999984
2   15707 days 23:59:59.999984
dtype: timedelta64[ns]
```

**Comment by jbrockmendel** [comment]
I'm about to submit a PR that fixes this.  It works for Series but still fails for DataFrame.

**Comment by sunnychase** [comment]
Hello, I am having issues with the datetime64, can anyone help me here?

`C:\Users\v_ichase\Desktop\Ultimate GEX>PY "C:\Users\v_ichase\Desktop\Ultimate GEX\Gex.py"
Traceback (most recent call last):
  File "C:\Users\v_ichase\Desktop\Ultimate GEX\Gex.py", line 78, in <module>
    dfAgg = df.groupby(['StrikePrice']).sum()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\groupby.py", line 3053, in sum
    result = self._agg_general(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\groupby.py", line 1835, in _agg_general
    result = self._cython_agg_general(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\groupby.py", line 1926, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\internals\managers.py", line 1431, in grouped_reduce
    applied = blk.apply(func)
              ^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\internals\blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\groupby.py", line 1902, in array_func
    result = self.grouper._cython_operation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\ops.py", line 815, in _cython_operation
    return cy_op.cython_operation(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\groupby\ops.py", line 525, in cython_operation
    return values._groupby_op(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_ichase\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\datetimelike.py", line 1637, in _groupby_op
    raise TypeError(f"datetime64 type does not support {how} operations")
TypeError: datetime64 type does not support sum operations`
