### ISSUE TITLE
pandas 0.15.2 is not deployable via cx_freeze with python 

### ISSUE THREAD

**Issue by alexisglr** [pandas-dev/pandas#9199]
I am deploying an application using cx_freeze on Python 2.7.8.final.0 and pandas 0.15.2.
I get the following error with pandas 0.15.2 but no error with 0.15.1. [SO: http://stackoverflow.com/questions/27705163/error-3-on-dateutil-zoneinfo-using-cx-freeze-and-pandas]

I have include the dateutil/zoneinfo files with the include_files function but the problem still occurs.

**hello.py :**

```
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
print 'hello world'
df_dates = pd.date_range(start='01/01/2013', freq='H', periods=100)
df = pd.DataFrame(range(len(df_dates)), index=df_dates)
print df
print df.info()
df.plot()
plt.savefig('test.png')
plt.show(block=False)
```

**setup.py :**

```
includes = ['dateutil.zoneinfo', 'pandas']  # nommer les modules non trouves par cx_freeze
excludes = []
packages = ['os', 'matplotlib.backends.backend_qt4agg', 'dateutil', 'dateutil.zoneinfo', 'pandas']

def include_files():
        path_base = "C:\\Anaconda\\Lib\\site-packages\\dateutil\\zoneinfo\\"
        skip_count = len(path_base) 
        zip_includes = [(path_base, "dateutil/zoneinfo/")]
        for root, sub_folders, files in os.walk(path_base):
            for file_in_root in files:
                zip_includes.append(
                        ("{}".format(os.path.join(root, file_in_root)),
                         "{}".format(os.path.join("dateutil/zoneinfo", root[skip_count:], file_in_root))
                        ) 
                )      
        return zip_includes

includefiles = include_files()
zip_includes = include_files()

optimize = 1
silent = True

options = {   #'path': path,
           'includes': includes,
           'excludes': excludes,
           'packages': packages,
           'include_files': includefiles,
           'zip_includes': zip_includes,
           #'bin_path_includes': binpathincludes,
           'create_shared_zip': True,  # <= ne pas generer de fichier zip
           'include_in_shared_zip': True,  # <= ne pas generer de fichier zip
           'compressed': True,  # <= ne pas generer de fichier zip
           'optimize': optimize,
           'silent': silent
           }


base = None

cible_1 = Executable('hello.py', targetName="hello.exe")
#base=base,
#compress=True,  # <= ne pas generer de fichier zip
#copyDependentFiles=True,
#appendScriptToExe=True,
#appendScriptToLibrary=True,  # <= ne pas generer de fichier zip
#icon=icone
#)

setup(
    name = "salut",
    author = 'XXX',
    version = "0.1",
    description = "Ce programme vous dit bonjour",
    options={"build_exe": options},
    executables = [cible_1],
)
```

**The error is :**

```
[Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: 'C:\\Users\\Utilisateur\\D
esktop\\compilation\\build\\exe.win-amd64-2.7\\library.zip\\dateutil\\zoneinfo/*
.*'
Traceback (most recent call last):
 File "C:\Anaconda\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
   exec(code, m.__dict__)
 File "hello.py", line 2, in <module>
 File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 7, in <module>
   from . import hashtable, tslib, lib
 File "ExtensionLoader_pandas_tslib.py", line 22, in <module>
 File "ExtensionLoader_pandas_tslib.py", line 14, in __bootstrap__
 File "pandas\tslib.pyx", line 44, in init pandas.tslib (pandas\tslib.c:79879)
 File "C:\Anaconda\lib\site-packages\dateutil\zoneinfo\__init__.py", line 32, i
n <module>
   ZONEINFOFILE = getzoneinfofile()
 File "C:\Anaconda\lib\site-packages\dateutil\zoneinfo\__init__.py", line 24, i
n getzoneinfofile
   filenames = os.listdir(os.path.join(os.path.dirname(__file__)))
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: 'C:\\Users\\
Utilisateur\\Desktop\\compilation\\build\\exe.win-amd64-2.7\\library.zip\\dateut
il\\zoneinfo/*.*'
```

**Comment by jreback** [comment]
can you show ``pd.show_versions()`` looks like an encoding issue

**Comment by alexis0587** [comment]
This is the result : 

    >>> pd.show_versions()

    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 2.7.8.final.0
    python-bits: 64
    OS: Windows
    OS-release: 7
    machine: AMD64
    processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    byteorder: little
    LC_ALL: None
    LANG: None

    pandas: 0.15.2
    nose: 1.3.4
    Cython: 0.21
    numpy: 1.9.1
    scipy: 0.14.0
    statsmodels: 0.5.0
    IPython: 2.2.0
    sphinx: 1.2.3
    patsy: 0.3.0
    dateutil: 1.5
    pytz: 2014.9
    bottleneck: None
    tables: 3.1.1
    numexpr: 2.3.1
    matplotlib: 1.4.2
    openpyxl: 1.8.5
    xlrd: 0.9.3
    xlwt: 0.7.5
    xlsxwriter: 0.5.7
    lxml: 3.4.0
    bs4: 4.3.2
    html5lib: None
    httplib2: None
    apiclient: None
    rpy2: None
    sqlalchemy: 0.9.8
    pymysql: None
    psycopg2: None

**Comment by Zenadix** [comment]
+1 to getting this fixed.

**Comment by amardeep-sm** [comment]
I was receiving a similar error and resolved it by upgrading to python-dateutil==2.4.0

**Comment by jbrockmendel** [comment]
@alexisglr @Zenadix can you confirm that the problem still exists in 0.23?

**Comment by jbrockmendel** [comment]
Closing as stale.  @alexisglr ping if this needs re-opening.
