### ISSUE TITLE
TestDataFrameFormatting error when stty columns = 0

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#9228]
When stty columns = 0, I guess this test error.

```
======================================================================
FAIL: test_auto_detect (pandas.tests.test_format.TestDataFrameFormatting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tests/test_format.py", line 315, in test_auto_detect
    self.assertTrue(has_expanded_repr(df))
AssertionError: False is not true
```

To reproduce:

```
stty columns 0
nosetests pandas.tests.test_format
```

**Comment by jreback** [comment]
hmm, auto_detect may not be implemented exactly right.. want to take a look?

**Comment by matthew-brett** [comment]
I'm afraid I don't know the code very well.  If I have time I will try and get to this, but it will likely take a while.

**Comment by gliptak** [comment]
No longer reproducible on current HEAD:

```
$ stty columns 0
$ nosetests pandas.tests.formats.test_format
..................S.............................................SSS...........................................................................................................
----------------------------------------------------------------------
Ran 174 tests in 5.962s

OK (SKIP=4)
```

Please consider closing.

**Comment by jreback** [comment]
happens on macosx for me.

```
[Thu May 26 12:20:06 ~/pandas]$ nosetests pandas.tests.formats.test_format
F.............................S.................................SSS...........................................................................................................
======================================================================
FAIL: test_auto_detect (pandas.tests.formats.test_format.TestDataFrameFormatting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jreback/pandas/pandas/tests/formats/test_format.py", line 361, in test_auto_detect
    self.assertTrue(has_expanded_repr(df))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 174 tests in 4.132s

FAILED (SKIP=4, failures=1)
```

**Comment by mroeschke** [comment]
This looks fixed:

```
(pandas-dev) matthewroeschke:pandas-mroeschke matthewroeschke$ stty columns 0
(pandas-dev) matthewroeschke:pandas-mroeschke matthewroeschke$ pytest pandas/tests/io/formats/test_format.py
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
hypothesis profile 'ci' -> deadline=timedelta(milliseconds=500.0), suppress_health_check=[HealthCheck.too_slow], database=DirectoryBasedExampleDatabase('/Users/matthewroeschke/pandas-mroeschke/.hypothesis/examples')
rootdir: /Users/matthewroeschke/pandas-mroeschke, inifile: setup.cfg
plugins: hypothesis-4.32.2, xdist-1.28.0, cov-2.7.1, mock-1.10.4, forked-1.0.2
collected 174 items

pandas/tests/io/formats/test_format.py ................................. [ 18%]
........................................................................ [ 60%]
.....................................................................    [100%]

========================== 174 passed in 3.87 seconds ==========================
```
